// SUBSYSTEM: zclass_nodes
// Original file: GameZRecoil/zClass/cls_util.c (ledger orig_file; SceneGraph_GetRoot and ZClassNode_CloneModelIfSpecial by RANGE attribution): node utilities and copy handlers. Spec: 04_spec/systems/class_api.md
// Instruction-level ports generated by tools/asm_port/port_batch.py from the Ghidra listings.
#include "GameZRecoil/zClass/cls_util.h"
#include "GameZRecoil/zClass/Class.h"
#include "GameZRecoil/zModel/gmod_const.h"
#include "platform/image/original_data.h"
#include "unattributed/ui_widgets.h"
#include "GameZRecoil/zClass/cls_world.h"
#include "platform/iat_msvcrt.h"
#include "unattributed/zclass_nodes.h"
#include "GameZRecoil/zClass/List.h"
#include "GameZRecoil/zClass/Seq.h"
#include "unattributed/scene_update.h"
#include "GameZRecoil/zClass/Camera.h"
#include "GameZRecoil/zClass/Object3d.h"

namespace recoil {

// 0x004518b0 ClassDb_SetNodeArraySize - if already set [0x00539c90]: error cls_u line 0x210 "Error setting node array size"; else [0x00539c90]=ECX
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ClassDb_SetNodeArraySize(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x5fc90]
        test eax, eax
        jz L_4518d7
        push eax
        push offset g_Data_004da000 + 0x44f8
        push 0x210
        push offset g_Data_004da000 + 0x44d0
        push 0x200
        call Debug_ReportNoop
        add esp, 0x14
        ret
    L_4518d7:
        mov dword ptr [g_Data_004da000 + 0x5fc90], ecx
        ret
    }
}

// 0x004518f0 SceneGraph_GetRoot - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall SceneGraph_GetRoot(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x5fca4]
        ret
    }
}

// 0x00451b20 ZClassNode_CloneModelIfSpecial - bytes ret 8: if +0x3c: (unless 0x004de4cc) 0x00447f00; gwNodeGetModel; Model_NeedsSpecialDraw -> Model_Clone + gwNodeSetModel
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ZClassNode_CloneModelIfSpecial(int, int)
{
    __asm {
        sub esp, 0x8
        xor eax, eax
        push esi
        push edi
        mov edi, edx
        mov edx, dword ptr [ecx + 0x3c]
        test edx, edx
        jz L_451bbe
        mov eax, dword ptr [g_Data_004da000 + 0x44cc]
        test eax, eax
        jz L_451ba6
        lea edx, [esp + 0xc]
        call gwNodeGetModel
        test eax, eax
        jnz L_451bbe
        mov eax, dword ptr [g_Data_004da000 + 0x5fca0]
        mov ecx, dword ptr [esp + 0xc]
        test eax, eax
        mov dword ptr [esp + 0x8], ecx
        mov esi, 0x1
        jz L_451b6b
        call Model_NeedsSpecialDraw
        test eax, eax
        jnz L_451b6b
        xor esi, esi
    L_451b6b:
        test esi, esi
        jz L_451bb3
        mov eax, dword ptr [g_Data_004da000 + 0x5fca0]
        mov edx, dword ptr [g_Data_004da000 + 0x5fc9c]
        mov ecx, dword ptr [esp + 0xc]
        push eax
        call Model_Clone
        test eax, eax
        jnz L_451b93
        mov eax, 0x1
        pop edi
        pop esi
        add esp, 0x8
        ret
    L_451b93:
        mov edx, eax
        mov ecx, edi
        mov dword ptr [esp + 0x8], eax
        call gwNodeSetModel
        pop edi
        pop esi
        add esp, 0x8
        ret
    L_451ba6:
        lea edx, [esp + 0x8]
        call gwNodeGetModel
        test eax, eax
        jnz L_451bbe
    L_451bb3:
        mov edx, dword ptr [esp + 0x8]
        mov ecx, edi
        call gwNodeSetModel
    L_451bbe:
        pop edi
        pop esi
        add esp, 0x8
        ret
    }
}

// 0x004520c0 ClassNode_CopyLight_Unsupported - error cls_u line 0x47d "Can t copy light node"; return 0
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ClassNode_CopyLight_Unsupported(int, int)
{
    __asm {
        push offset g_Data_004da000 + 0x4b14
        push 0x47d
        push offset g_Data_004da000 + 0x44d0
        push 0x800
        call Debug_ReportNoop
        add esp, 0x10
        xor eax, eax
        ret
    }
}

// 0x004520e0 ClassNode_CopySound_Unsupported - error line 0x493 "Can t copy sound node"; return 0
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ClassNode_CopySound_Unsupported(int, int)
{
    __asm {
        push offset g_Data_004da000 + 0x4b48
        push 0x493
        push offset g_Data_004da000 + 0x44d0
        push 0x800
        call Debug_ReportNoop
        add esp, 0x10
        xor eax, eax
        ret
    }
}

// 0x00452230 ClassNode_CopyAnimate_Unsupported - error line 0x518 copying animate node; return 0
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ClassNode_CopyAnimate_Unsupported(int, int)
{
    __asm {
        push offset g_Data_004da000 + 0x4b7c
        push 0x518
        push offset g_Data_004da000 + 0x44d0
        push 0x100
        call Debug_ReportNoop
        add esp, 0x10
        xor eax, eax
        ret
    }
}

// 0x004523c0 ClassNode_CopySequence_Unsupported - error line 0x585 copying sequence node; return 0
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ClassNode_CopySequence_Unsupported(int, int)
{
    __asm {
        push offset g_Data_004da000 + 0x4bb8
        push 0x585
        push offset g_Data_004da000 + 0x44d0
        push 0x100
        call Debug_ReportNoop
        add esp, 0x10
        xor eax, eax
        ret
    }
}

// 0x004523e0 ClassNode_CopySwitch_Unsupported - error line 0x59c copying switch node; return 0
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ClassNode_CopySwitch_Unsupported(int, int)
{
    __asm {
        push offset g_Data_004da000 + 0x4bf4
        push 0x59c
        push offset g_Data_004da000 + 0x44d0
        push 0x100
        call Debug_ReportNoop
        add esp, 0x10
        xor eax, eax
        ret
    }
}

// 0x00451900 World_AllocObjectTable - Capacity [0x00539c90] defaults to 0x203a (8250); malloc cap*0xc4 zeroed at [0x00539c94]; [0x00539c98]=0, [0x004de4c8]=0; builds free list: entry i +0xc0 low 24 bits = i+1, last = 0xffffff. If [0x004de4c4] registers save handler 0x004bffe0(0x00451840, 1000, 0). [0x00539ca4]=1. Returns 0.
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall World_AllocObjectTable(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x5fc90]
        push esi
        test eax, eax
        push edi
        jnz L_451915
        mov eax, 0x203a
        mov dword ptr [g_Data_004da000 + 0x5fc90], eax
    L_451915:
        lea ecx, [eax + eax*0x2]
        shl ecx, 0x4
        add ecx, eax
        shl ecx, 0x2
        push ecx
        call dword ptr [g_Iat_malloc_004cc5dc]
        mov edi, eax
        mov eax, dword ptr [g_Data_004da000 + 0x5fc90]
        mov dword ptr [g_Data_004da000 + 0x5fc94], edi
        add esp, 0x4
        lea ecx, [eax + eax*0x2]
        shl ecx, 0x4
        add ecx, eax
        xor eax, eax
        shl ecx, 0x2
        mov edx, ecx
        shr ecx, 0x2
        rep stosd
        mov ecx, edx
        and ecx, 0x3
        rep stosb
        mov edx, dword ptr [g_Data_004da000 + 0x5fc90]
        mov dword ptr [g_Data_004da000 + 0x5fc98], 0x0
        test edx, edx
        mov dword ptr [g_Data_004da000 + 0x44c8], 0x0
        jle L_4519c4
        lea ecx, [edx - 0x1]
        xor eax, eax
        test ecx, ecx
        jle L_4519ac
        xor ecx, ecx
    L_45197b:
        mov esi, dword ptr [g_Data_004da000 + 0x5fc94]
        inc eax
        mov edx, dword ptr [esi + ecx*0x1 + 0xc0]
        add ecx, 0xc4
        mov edi, edx
        xor edi, eax
        and edi, 0xffffff
        xor edi, edx
        mov dword ptr [esi + ecx*0x1 - 0x4], edi
        mov edx, dword ptr [g_Data_004da000 + 0x5fc90]
        lea esi, [edx - 0x1]
        cmp eax, esi
        jl L_45197b
    L_4519ac:
        mov ecx, dword ptr [g_Data_004da000 + 0x5fc94]
        lea eax, [edx + edx*0x2]
        shl eax, 0x4
        add eax, edx
        lea eax, [ecx + eax*0x4 - 0x4]
        or dword ptr [eax], 0xffffff
    L_4519c4:
        mov eax, dword ptr [g_Data_004da000 + 0x44c4]
        test eax, eax
        jz L_4519e8
        push 0x0
        push 0x3e8
        push offset ZClass_Slot_ApplyNodeParams_00451840
        mov edx, offset GWWorld_BuildSaveRecords
        mov ecx, offset g_Data_004da000 + 0x4530
        call Timer_RegisterIfEnabled
    L_4519e8:
        pop edi
        mov dword ptr [g_Data_004da000 + 0x5fca4], 0x1
        xor eax, eax
        pop esi
        ret
    }
}

// 0x00451a60 gwNode_DestroyTree - ../../04_spec/structs/weapon_two_struct_split.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall gwNode_DestroyTree(int, int)
{
    __asm {
        push esi
        push edi
        mov edi, ecx
        test edi, edi
        jnz L_451a8c
        push offset g_Data_004da000 + 0x39d4
        push 0x2b6
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x10
        mov eax, 0x1
        pop edi
        pop esi
        ret
    L_451a8c:
        mov eax, dword ptr [edi + 0x54]
        test eax, eax
        jle L_451a9b
        mov eax, 0x1
        pop edi
        pop esi
        ret
    L_451a9b:
        mov eax, dword ptr [edi + 0x5c]
        test eax, eax
        jle L_451ae2
        mov eax, dword ptr [edi + 0x60]
        mov ecx, edi
        mov esi, dword ptr [eax]
        mov edx, esi
        call gwNodeDetachChildByClass
        test eax, eax
        jnz L_451b0f
    L_451ab4:
        mov eax, dword ptr [esi + 0x54]
        test eax, eax
        jnz L_451ac6
        mov ecx, esi
        call gwNode_DestroyTree
        test eax, eax
        jnz L_451b0f
    L_451ac6:
        mov eax, dword ptr [edi + 0x5c]
        test eax, eax
        jle L_451ae2
        mov ecx, dword ptr [edi + 0x60]
        mov esi, dword ptr [ecx]
        mov ecx, edi
        mov edx, esi
        call gwNodeDetachChildByClass
        test eax, eax
        jz L_451ab4
        pop edi
        pop esi
        ret
    L_451ae2:
        mov esi, dword ptr [edi + 0x3c]
        test esi, esi
        jz L_451b08
        xor edx, edx
        mov ecx, edi
        call gwNodeSetModel
        test eax, eax
        jnz L_451b0f
        mov eax, dword ptr [esi + 0x8]
        test eax, eax
        jnz L_451b08
        mov ecx, esi
        call Model_Free
        test eax, eax
        jnz L_451b0f
    L_451b08:
        mov ecx, edi
        call gwNodeDestroy
    L_451b0f:
        pop edi
        pop esi
        ret
    }
}

// 0x00451bd0 ZClassNode_CopyProperties - bytes: 0x00447dc0 copy node (error 'ERROR copying node while setting...' line 0x34e via 0x00404e80); gwNodeSetName, gwNodeSetActive(flags +0x24 bit2), gwNodeSetFlag08/10/20/40 from flag bits, each failure logged with line number; 3 callers
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ZClassNode_CopyProperties(int, int)
{
    __asm {
        push ebx
        push esi
        push edi
        mov edi, edx
        mov esi, ecx
        mov edx, esi
        mov ecx, edi
        call gwNodeSetName
        mov ebx, eax
        test ebx, ebx
        jz L_451c0a
        push esi
        push esi
        push offset g_Data_004da000 + 0x4a6c
        push 0x34e
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x18
        mov eax, ebx
        pop edi
        pop esi
        pop ebx
        ret
    L_451c0a:
        mov edx, dword ptr [esi + 0x24]
        mov ecx, edi
        shr edx, 0x2
        and edx, 0x1
        call gwNodeSetActive
        mov ebx, eax
        test ebx, ebx
        jz L_451c44
        push esi
        push esi
        push offset g_Data_004da000 + 0x4a14
        push 0x359
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x18
        mov eax, ebx
        pop edi
        pop esi
        pop ebx
        ret
    L_451c44:
        mov edx, dword ptr [esi + 0x24]
        mov ecx, edi
        shr edx, 0x3
        and edx, 0x1
        call gwNodeSetFlag08
        mov ebx, eax
        test ebx, ebx
        jz L_451c7e
        push esi
        push esi
        push offset g_Data_004da000 + 0x49b0
        push 0x364
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x18
        mov eax, ebx
        pop edi
        pop esi
        pop ebx
        ret
    L_451c7e:
        mov edx, dword ptr [esi + 0x24]
        mov ecx, edi
        shr edx, 0x4
        and edx, 0x1
        call gwNodeSetFlag10
        mov ebx, eax
        test ebx, ebx
        jz L_451cb8
        push esi
        push esi
        push offset g_Data_004da000 + 0x4950
        push 0x36f
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x18
        mov eax, ebx
        pop edi
        pop esi
        pop ebx
        ret
    L_451cb8:
        mov edx, dword ptr [esi + 0x24]
        mov ecx, edi
        shr edx, 0x5
        and edx, 0x1
        call gwNodeSetFlag20
        mov ebx, eax
        test ebx, ebx
        jz L_451cf2
        push esi
        push esi
        push offset g_Data_004da000 + 0x48f0
        push 0x37a
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x18
        mov eax, ebx
        pop edi
        pop esi
        pop ebx
        ret
    L_451cf2:
        mov edx, dword ptr [esi + 0x24]
        mov ecx, edi
        shr edx, 0x6
        and edx, 0x1
        call gwNodeSetFlag40
        mov ebx, eax
        test ebx, ebx
        jz L_451d2c
        push esi
        push esi
        push offset g_Data_004da000 + 0x4898
        push 0x385
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x18
        mov eax, ebx
        pop edi
        pop esi
        pop ebx
        ret
    L_451d2c:
        mov edx, dword ptr [esi + 0x24]
        mov ecx, edi
        shr edx, 0x7
        and edx, 0x1
        call gwNodeSetFlag80
        mov ebx, eax
        test ebx, ebx
        jz L_451d66
        push esi
        push esi
        push offset g_Data_004da000 + 0x4840
        push 0x390
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x18
        mov eax, ebx
        pop edi
        pop esi
        pop ebx
        ret
    L_451d66:
        mov edx, dword ptr [esi + 0x24]
        mov ecx, edi
        shr edx, 0x10
        and edx, 0x1
        call gwNodeSetFlag10000
        mov ebx, eax
        test ebx, ebx
        jz L_451da0
        push esi
        push esi
        push offset g_Data_004da000 + 0x47e4
        push 0x39b
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x18
        mov eax, ebx
        pop edi
        pop esi
        pop ebx
        ret
    L_451da0:
        mov edx, dword ptr [esi + 0x24]
        mov ecx, edi
        shr edx, 0x11
        and edx, 0x1
        call gwNodeSetFlag20000
        mov ebx, eax
        test ebx, ebx
        jz L_451dda
        push esi
        push esi
        push offset g_Data_004da000 + 0x478c
        push 0x3a6
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x18
        mov eax, ebx
        pop edi
        pop esi
        pop ebx
        ret
    L_451dda:
        mov edx, dword ptr [esi + 0x24]
        mov ecx, edi
        shr edx, 0x18
        and edx, 0x1
        call gwNodeClearFlag1000000
        mov ebx, eax
        test ebx, ebx
        jz L_451e14
        push esi
        push esi
        push offset g_Data_004da000 + 0x4730
        push 0x3b1
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x18
        mov eax, ebx
        pop edi
        pop esi
        pop ebx
        ret
    L_451e14:
        mov edx, dword ptr [esi + 0x24]
        mov ecx, edi
        shr edx, 0x17
        and edx, 0x1
        call gwNodeSetFlag800000
        mov ebx, eax
        test ebx, ebx
        jz L_451e4e
        push esi
        push esi
        push offset g_Data_004da000 + 0x46d8
        push 0x3bc
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x18
        mov eax, ebx
        pop edi
        pop esi
        pop ebx
        ret
    L_451e4e:
        mov eax, dword ptr [esi + 0x24]
        mov ecx, dword ptr [edi + 0x24]
        and eax, 0x70000000
        mov edx, edi
        or ecx, eax
        mov dword ptr [edi + 0x24], ecx
        mov ecx, dword ptr [esi + 0x28]
        mov dword ptr [edi + 0x28], ecx
        mov ecx, esi
        call ZClassNode_CloneModelIfSpecial
        mov ebx, eax
        test ebx, ebx
        jz L_451e97
        push esi
        push esi
        push offset g_Data_004da000 + 0x468c
        push 0x3ce
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x18
        mov eax, ebx
        pop edi
        pop esi
        pop ebx
        ret
    L_451e97:
        mov eax, dword ptr [esi + 0x40]
        test eax, eax
        jz L_451ebb
        push esi
        push offset g_Data_004da000 + 0x4658
        push 0x3d8
        push offset g_Data_004da000 + 0x44d0
        push 0x100
        call Debug_ReportNoop
        add esp, 0x14
    L_451ebb:
        mov dword ptr [edi + 0x40], 0x0
        mov edx, dword ptr [esi + 0x44]
        mov ecx, edi
        call gwNodeSetActionList
        mov ebx, eax
        test ebx, ebx
        jz L_451ef6
        push esi
        push esi
        push offset g_Data_004da000 + 0x45ec
        push 0x3e2
        push offset g_Data_004da000 + 0x44d0
        push 0x100
        call Debug_ReportNoop
        add esp, 0x18
        mov eax, ebx
        pop edi
        pop esi
        pop ebx
        ret
    L_451ef6:
        mov edx, dword ptr [esi + 0x48]
        mov ecx, edi
        call gwNodeSetActionCallback
        mov ebx, eax
        test ebx, ebx
        jz L_451f2a
        push esi
        push esi
        push offset g_Data_004da000 + 0x458c
        push 0x3ed
        push offset g_Data_004da000 + 0x44d0
        push 0x100
        call Debug_ReportNoop
        add esp, 0x18
        mov eax, ebx
        pop edi
        pop esi
        pop ebx
        ret
    L_451f2a:
        xor edx, edx
        mov ecx, edi
        mov DL, byte ptr [esi + 0x30]
        call gwNodeSetByte30
        mov edi, eax
        test edi, edi
        jz L_451f60
        push esi
        push esi
        push offset g_Data_004da000 + 0x4538
        push 0x3f8
        push offset g_Data_004da000 + 0x44d0
        push 0x100
        call Debug_ReportNoop
        add esp, 0x18
        mov eax, edi
        pop edi
        pop esi
        pop ebx
        ret
    L_451f60:
        pop edi
        pop esi
        xor eax, eax
        pop ebx
        ret
    }
}

// 0x00451a00 World_ClearAll - 0x0044f120 (ECX=6); 0x0044e6d0; if [0x00539c90] > 0: free [0x00539c94], zero count/ptr/[0x00539c98], [0x004de4c8] = -1; 0x00454360; [0x00539ca4]=0. Returns 0.
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall World_ClearAll(int, int)
{
    __asm {
        push esi
        mov ecx, 0x6
        call ClassList_DeleteAll
        call NodeList_FreeLinkPool
        mov eax, dword ptr [g_Data_004da000 + 0x5fc90]
        xor esi, esi
        cmp eax, esi
        jle L_451a4a
        mov eax, dword ptr [g_Data_004da000 + 0x5fc94]
        cmp eax, esi
        jz L_451a34
        push eax
        call dword ptr [g_Iat_free_004cc5b4]
        add esp, 0x4
        mov dword ptr [g_Data_004da000 + 0x5fc94], esi
    L_451a34:
        mov dword ptr [g_Data_004da000 + 0x5fc90], esi
        mov dword ptr [g_Data_004da000 + 0x5fc98], esi
        mov dword ptr [g_Data_004da000 + 0x44c8], 0xffffffff
    L_451a4a:
        call GameZ_ClearWorldPath
        mov dword ptr [g_Data_004da000 + 0x5fca4], esi
        xor eax, eax
        pop esi
        ret
    }
}

// 0x004518e0 gClsShutdown - World_ClearAll (0x00451a00); return 0
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall gClsShutdown(int, int)
{
    __asm {
        call World_ClearAll
        xor eax, eax
        ret
    }
}

// 0x00451f70 ClassNode_CopyCamera - new camera node 0x00449be0; copy base 0x00451bd0 (error cls_u line 0x422); copy data from src [+0x38]: 0x00449dd0, 0x00449e90, pos 0x0044a0f0(+0x14..), rot 0x00449ea0(+0x20..), 0x0044a2f0(+0xb0,+0xb4), 0x0044a870(+0xd0), Camera_SetFOV (0x0044a610)(+0xe8,+0xec); children: ClassNode_CopyDispatch + att
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ClassNode_CopyCamera(int, int)
{
    __asm {
        push ebx
        push esi
        push edi
        mov ebx, ecx
        call Camera_Create
        mov edi, eax
        test edi, edi
        jnz L_451f84
        pop edi
        pop esi
        pop ebx
        ret
    L_451f84:
        mov edx, edi
        mov ecx, ebx
        call ZClassNode_CopyProperties
        test eax, eax
        jz L_451fba
        push ebx
        push ebx
        push offset g_Data_004da000 + 0x4ae8
        push offset g_Data_004da000 + 0x4ac8
        push 0x422
        push offset g_Data_004da000 + 0x44d0
        push 0x100
        call Debug_ReportNoop
        add esp, 0x1c
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_451fba:
        mov esi, dword ptr [ebx + 0x38]
        mov ecx, edi
        mov edx, dword ptr [esi]
        call Camera_SetWorld
        test eax, eax
        jz L_451fd0
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_451fd0:
        mov edx, dword ptr [esi + 0x4]
        mov ecx, edi
        call Camera_SetData04_NoCheck
        test eax, eax
        jz L_451fe4
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_451fe4:
        mov eax, dword ptr [esi + 0x1c]
        mov ecx, dword ptr [esi + 0x18]
        mov edx, dword ptr [esi + 0x14]
        push eax
        push ecx
        push edx
        mov ecx, edi
        call Camera_SetPosition
        test eax, eax
        jz L_452001
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_452001:
        mov eax, dword ptr [esi + 0x28]
        mov ecx, dword ptr [esi + 0x24]
        mov edx, dword ptr [esi + 0x20]
        push eax
        push ecx
        push edx
        mov ecx, edi
        call Camera_SetLocalAngles
        test eax, eax
        jz L_45201e
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_45201e:
        mov eax, dword ptr [esi + 0xb4]
        mov ecx, dword ptr [esi + 0xb0]
        push eax
        push ecx
        mov ecx, edi
        call Camera_SetNearFar
        test eax, eax
        jz L_45203d
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_45203d:
        mov edx, dword ptr [esi + 0xd0]
        mov ecx, edi
        push edx
        call Camera_SetD0AndInverseSquare
        test eax, eax
        jz L_452055
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_452055:
        mov eax, dword ptr [esi + 0xec]
        mov ecx, dword ptr [esi + 0xe8]
        push eax
        push ecx
        mov ecx, edi
        call Camera_SetFOV
        test eax, eax
        jz L_452074
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_452074:
        mov eax, dword ptr [ebx + 0x5c]
        xor esi, esi
        test eax, eax
        jle L_4520ad
    L_45207d:
        mov edx, dword ptr [ebx + 0x60]
        mov ecx, dword ptr [edx + esi*0x4]
        call ClassNode_CopyDispatch
        test eax, eax
        jz L_4520a7
        mov edx, eax
        mov ecx, edi
        call Camera_AttachChild
        test eax, eax
        jnz L_4520a7
        mov eax, dword ptr [ebx + 0x5c]
        inc esi
        cmp esi, eax
        jl L_45207d
        mov eax, edi
        pop edi
        pop esi
        pop ebx
        ret
    L_4520a7:
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_4520ad:
        mov eax, edi
        pop edi
        pop esi
        pop ebx
        ret
    }
}

// 0x00452100 ClassNode_CopyObject3D - new object node 0x0044daa0; copy base (error line 0x4b9); 0x0044dd90(flags [1]), 0x0044de80; if not flag 8: flag 0x10 -> matrix copy 0x0044e4f0 else SetPosition(+0x54..)/SetRotation(+0x18..)/SetScale(+0x24..); children: CopyDispatch + attach 0x0044db10
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ClassNode_CopyObject3D(int, int)
{
    __asm {
        push ebx
        push esi
        push edi
        mov ebx, ecx
        call Object3D_Create
        mov edi, eax
        test edi, edi
        jnz L_452114
        pop edi
        pop esi
        pop ebx
        ret
    L_452114:
        mov edx, edi
        mov ecx, ebx
        call ZClassNode_CopyProperties
        test eax, eax
        jz L_45214a
        push ebx
        push ebx
        push offset g_Data_004da000 + 0x4ae8
        push offset g_Data_004da000 + 0x4ac8
        push 0x4b9
        push offset g_Data_004da000 + 0x44d0
        push 0x100
        call Debug_ReportNoop
        add esp, 0x1c
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_45214a:
        mov esi, dword ptr [ebx + 0x38]
        mov ecx, edi
        mov eax, dword ptr [esi + 0x4]
        push eax
        call Object3D_SetValue4
        test eax, eax
        jz L_452162
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_452162:
        mov edx, dword ptr [esi]
        mov ecx, edi
        shr edx, 0x1
        and edx, 0x1
        call Object3D_SetFlag2
        test eax, eax
        jz L_45217a
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_45217a:
        mov eax, dword ptr [esi]
        test AL, 0x8
        jnz L_4521ef
        test AL, 0x10
        jz L_452198
        lea edx, [esi + 0x30]
        mov ecx, edi
        call Object3D_SetLocalMatrix
        test eax, eax
        jz L_4521ef
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_452198:
        mov ecx, dword ptr [esi + 0x5c]
        mov edx, dword ptr [esi + 0x58]
        mov eax, dword ptr [esi + 0x54]
        push ecx
        push edx
        push eax
        mov ecx, edi
        call Object3D_SetPosition
        test eax, eax
        jz L_4521b5
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_4521b5:
        mov ecx, dword ptr [esi + 0x20]
        mov edx, dword ptr [esi + 0x1c]
        mov eax, dword ptr [esi + 0x18]
        push ecx
        push edx
        push eax
        mov ecx, edi
        call Object3D_SetRotation
        test eax, eax
        jz L_4521d2
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_4521d2:
        mov ecx, dword ptr [esi + 0x2c]
        mov edx, dword ptr [esi + 0x28]
        mov eax, dword ptr [esi + 0x24]
        push ecx
        push edx
        push eax
        mov ecx, edi
        call Object3D_SetScale
        test eax, eax
        jz L_4521ef
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_4521ef:
        mov eax, dword ptr [ebx + 0x5c]
        xor esi, esi
        test eax, eax
        jle L_452228
    L_4521f8:
        mov ecx, dword ptr [ebx + 0x60]
        mov ecx, dword ptr [ecx + esi*0x4]
        call ClassNode_CopyDispatch
        test eax, eax
        jz L_452214
        mov edx, eax
        mov ecx, edi
        call Object3D_AttachChild
        test eax, eax
        jnz L_452222
    L_452214:
        mov eax, dword ptr [ebx + 0x5c]
        inc esi
        cmp esi, eax
        jl L_4521f8
        mov eax, edi
        pop edi
        pop esi
        pop ebx
        ret
    L_452222:
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_452228:
        mov eax, edi
        pop edi
        pop esi
        pop ebx
        ret
    }
}

// 0x00452250 ClassNode_CopyLOD - new node 0x004542a0; copy base (error line 0x53e); 0x00454330; copy 0x11 dwords data +4..+0x44; 0x00454340(fast sqrt of [+0x4c], 0x1fc00000); children: CopyDispatch + attach 0x00454310
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ClassNode_CopyLOD(int, int)
{
    __asm {
        push ebp
        mov ebp, esp
        sub esp, 0xc
        push ebx
        push esi
        push edi
        mov edi, ecx
        call NodeType6_Create
        mov ebx, eax
        test ebx, ebx
        mov dword ptr [ebp - 0xc], ebx
        jnz L_452270
        pop edi
        pop esi
        pop ebx
        mov esp, ebp
        pop ebp
        ret
    L_452270:
        mov edx, ebx
        mov ecx, edi
        call ZClassNode_CopyProperties
        test eax, eax
        jz L_4522a9
        push edi
        push edi
        push offset g_Data_004da000 + 0x4ae8
        push offset g_Data_004da000 + 0x4ac8
        push 0x53e
        push offset g_Data_004da000 + 0x44d0
        push 0x100
        call Debug_ReportNoop
        add esp, 0x1c
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        mov esp, ebp
        pop ebp
        ret
    L_4522a9:
        mov esi, dword ptr [edi + 0x38]
        mov ecx, ebx
        mov edx, dword ptr [esi]
        call Node_SetClassDataField0_NoCheck
        test eax, eax
        jz L_4522c2
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        mov esp, ebp
        pop ebp
        ret
    L_4522c2:
        mov eax, dword ptr [ebx + 0x38]
        mov ecx, dword ptr [esi + 0x4]
        mov dword ptr [eax + 0x4], ecx
        mov edx, dword ptr [esi + 0x8]
        mov dword ptr [eax + 0x8], edx
        mov ecx, dword ptr [esi + 0xc]
        lea edx, [esi + 0x10]
        mov dword ptr [eax + 0xc], ecx
        lea ecx, [eax + 0x10]
        mov ebx, dword ptr [edx]
        mov dword ptr [ecx], ebx
        mov ebx, dword ptr [edx + 0x4]
        mov dword ptr [ecx + 0x4], ebx
        mov edx, dword ptr [edx + 0x8]
        mov dword ptr [ecx + 0x8], edx
        lea ecx, [esi + 0x1c]
        lea edx, [eax + 0x1c]
        mov ebx, dword ptr [ecx]
        mov dword ptr [edx], ebx
        mov ebx, dword ptr [ecx + 0x4]
        mov dword ptr [edx + 0x4], ebx
        mov ecx, dword ptr [ecx + 0x8]
        mov dword ptr [edx + 0x8], ecx
        lea edx, [esi + 0x28]
        lea ecx, [eax + 0x28]
        mov ebx, dword ptr [edx]
        mov dword ptr [ecx], ebx
        mov ebx, dword ptr [edx + 0x4]
        mov dword ptr [ecx + 0x4], ebx
        mov edx, dword ptr [edx + 0x8]
        mov dword ptr [ecx + 0x8], edx
        mov ecx, dword ptr [esi + 0x34]
        mov dword ptr [eax + 0x34], ecx
        mov edx, dword ptr [esi + 0x38]
        mov dword ptr [eax + 0x38], edx
        mov ecx, dword ptr [esi + 0x3c]
        mov dword ptr [eax + 0x3c], ecx
        mov edx, dword ptr [esi + 0x40]
        mov dword ptr [eax + 0x40], edx
        mov ecx, dword ptr [esi + 0x44]
        mov dword ptr [eax + 0x44], ecx
        mov edx, dword ptr [esi + 0x4c]
        mov dword ptr [ebp - 0x4], edx
        mov eax, dword ptr [ebp - 0x4]
        sar eax, 0x1
        add eax, 0x1fc00000
        mov dword ptr [ebp - 0x8], eax
        fld dword ptr [ebp - 0x8]
        mov ebx, dword ptr [ebp - 0xc]
        mov edx, dword ptr [esi + 0x48]
        push ecx
        mov ecx, ebx
        fstp dword ptr [esp]
        call Node_SetClassDataRangeCheck
        test eax, eax
        jz L_45236b
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        mov esp, ebp
        pop ebp
        ret
    L_45236b:
        mov eax, dword ptr [edi + 0x5c]
        xor esi, esi
        test eax, eax
        jle L_4523aa
    L_452374:
        mov eax, dword ptr [edi + 0x60]
        mov ecx, dword ptr [eax + esi*0x4]
        call ClassNode_CopyDispatch
        test eax, eax
        jz L_4523a1
        mov edx, eax
        mov ecx, ebx
        call gwNodeAttachChild
        test eax, eax
        jnz L_4523a1
        mov eax, dword ptr [edi + 0x5c]
        inc esi
        cmp esi, eax
        jl L_452374
        mov eax, ebx
        pop edi
        pop esi
        pop ebx
        mov esp, ebp
        pop ebp
        ret
    L_4523a1:
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        mov esp, ebp
        pop ebp
        ret
    L_4523aa:
        pop edi
        mov eax, ebx
        pop esi
        pop ebx
        mov esp, ebp
        pop ebp
        ret
    }
}

// 0x00452400 ClassNode_CopyDispatch - null -> error cls_u line 0x5b8; flag +0x24 bit 0x4000000 -> return self; switch type +0x34: 1 0x00451f70, 2 error line 0x5e1 cannot copy world, 5 0x00452100, 6 0x00452250, 7 0x004523c0, 8 0x00452230, others 0x004520c0/0x004520e0/0x004523e0; default error line 0x5e8
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ClassNode_CopyDispatch(int, int)
{
    __asm {
        push esi
        xor esi, esi
        test ecx, ecx
        jnz L_452427
        push offset g_Data_004da000 + 0x39d4
        push 0x5b8
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x10
        xor eax, eax
        pop esi
        ret
    L_452427:
        test dword ptr [ecx + 0x24], 0x4000000
        jz L_452434
        mov eax, ecx
        pop esi
        ret
    L_452434:
        mov eax, dword ptr [ecx + 0x34]
        dec eax
        cmp eax, 0xa
        ja L_4524ac
        cmp eax, 0
        je L_452456
        cmp eax, 1
        je L_45248c
        cmp eax, 2
        je L_4524ac
        cmp eax, 3
        je L_4524ac
        cmp eax, 4
        je L_452444
        cmp eax, 5
        je L_45244d
        cmp eax, 6
        je L_45247a
        cmp eax, 7
        je L_452471
        cmp eax, 8
        je L_45245f
        cmp eax, 9
        je L_452468
        cmp eax, 10
        je L_452483
        int 3  // unreachable: the bounds check above excludes other indices
    L_452444:
        call ClassNode_CopyObject3D
        mov esi, eax
        pop esi
        ret
    L_45244d:
        call ClassNode_CopyLOD
        mov esi, eax
        pop esi
        ret
    L_452456:
        call ClassNode_CopyCamera
        mov esi, eax
        pop esi
        ret
    L_45245f:
        call ClassNode_CopyLight_Unsupported
        mov esi, eax
        pop esi
        ret
    L_452468:
        call ClassNode_CopySound_Unsupported
        mov esi, eax
        pop esi
        ret
    L_452471:
        call ClassNode_CopyAnimate_Unsupported
        mov esi, eax
        pop esi
        ret
    L_45247a:
        call ClassNode_CopySequence_Unsupported
        mov esi, eax
        pop esi
        ret
    L_452483:
        call ClassNode_CopySwitch_Unsupported
        mov esi, eax
        pop esi
        ret
    L_45248c:
        push offset g_Data_004da000 + 0x4c60
        push 0x5e1
        push offset g_Data_004da000 + 0x44d0
        push 0x100
        call Debug_ReportNoop
        add esp, 0x10
        xor eax, eax
        pop esi
        ret
    L_4524ac:
        push ecx
        push offset g_Data_004da000 + 0x4c30
        push 0x5e8
        push offset g_Data_004da000 + 0x44d0
        push 0x100
        call Debug_ReportNoop
        add esp, 0x14
        mov eax, esi
        pop esi
        ret
    }
}

// 0x00452500 gwNode_CloneWithFlag - ../../04_spec/structs/weapon_two_struct_split.md
// Register/stack shape from the listing (ECX, EDX, 4 stack bytes).
__declspec(naked) int __fastcall gwNode_CloneWithFlag(int, int, int)
{
    __asm {
        test ecx, ecx
        jnz L_452525
        push offset g_Data_004da000 + 0x39d4
        push 0x60f
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x10
        xor eax, eax
        ret 0x4
    L_452525:
        mov eax, dword ptr [esp + 0x4]
        push edi
        mov edi, dword ptr [g_Data_004da000 + 0x5fc9c]
        push esi
        mov esi, dword ptr [g_Data_004da000 + 0x44cc]
        mov dword ptr [g_Data_004da000 + 0x44cc], edx
        mov dword ptr [g_Data_004da000 + 0x5fc9c], eax
        call ClassNode_CopyDispatch
        mov dword ptr [g_Data_004da000 + 0x44cc], esi
        mov dword ptr [g_Data_004da000 + 0x5fc9c], edi
        pop esi
        pop edi
        ret 0x4
    }
}

// 0x00452560 Node_FindWithSearchParams - ECX=node. Null -> logs Null node pointer (zClass cls_u line 0x648) and returns 0. Temporarily sets search params [0x00539c9c]/[0x00539ca0] from args, calls 0x00452400, restores previous values, returns result.
// Register/stack shape from the listing (ECX, EDX, 8 stack bytes).
__declspec(naked) int __fastcall Node_FindWithSearchParams(int, int, int, int)
{
    __asm {
        test ecx, ecx
        jnz L_452585
        push offset g_Data_004da000 + 0x39d4
        push 0x648
        push offset g_Data_004da000 + 0x44d0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x10
        xor eax, eax
        ret 0x8
    L_452585:
        mov eax, dword ptr [esp + 0x4]
        push edi
        mov edi, dword ptr [g_Data_004da000 + 0x5fc9c]
        push esi
        mov esi, dword ptr [g_Data_004da000 + 0x44cc]
        mov dword ptr [g_Data_004da000 + 0x44cc], edx
        mov edx, dword ptr [esp + 0x10]
        push ebx
        mov ebx, dword ptr [g_Data_004da000 + 0x5fca0]
        mov dword ptr [g_Data_004da000 + 0x5fc9c], eax
        mov dword ptr [g_Data_004da000 + 0x5fca0], edx
        call ClassNode_CopyDispatch
        mov dword ptr [g_Data_004da000 + 0x5fca0], ebx
        mov dword ptr [g_Data_004da000 + 0x44cc], esi
        pop ebx
        mov dword ptr [g_Data_004da000 + 0x5fc9c], edi
        pop esi
        pop edi
        ret 0x8
    }
}

}  // namespace recoil
