// SUBSYSTEM: asset_io
// Original file: GameZRecoil/zClass/List.c (ledger orig_file): class node lists. Spec: 04_spec/systems/class_api.md
// The jump table 0x0044f0e8 becomes a compare chain; its 12 entries, read from the exe bytes, are
// 0x44f0ac 0x44f012 0x44f05b 0x44f04d 0x44f03f 0x44f0ac 0x44f0ac 0x44f031 0x44f023 0x44f069 0x44f077 0x44f0ac (match).
// Instruction-level ports generated by tools/asm_port/port_batch.py from the Ghidra listings.
#include "GameZRecoil/zClass/List.h"
#include "GameZRecoil/zError/zerr_old.h"
#include "platform/iat_msvcrt.h"
#include "platform/image/original_data.h"
#include "unattributed/scene_update.h"
#include "GameZRecoil/zClass/Animate.h"
#include "GameZRecoil/zClass/Camera.h"
#include "GameZRecoil/zClass/Class.h"
#include "GameZRecoil/zClass/Display.h"
#include "GameZRecoil/zClass/Light.h"
#include "GameZRecoil/zClass/Object3d.h"
#include "GameZRecoil/zClass/Seq.h"
#include "GameZRecoil/zClass/Sound.h"
#include "GameZRecoil/zClass/Switch.h"
#include "GameZRecoil/zClass/Window_nodes.h"
#include "GameZRecoil/zClass/cls_world.h"
#include "GameZRecoil/zModel/gmod_const.h"
#include "unattributed/ui_widgets.h"

namespace recoil {

// 0x0044f000 List_UnregisterNode - ../../04_spec/systems/class_api.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall List_UnregisterNode(int, int)
{
    __asm {
        push esi
        mov esi, ecx
        mov eax, dword ptr [esi + 0x34]
        cmp eax, 0xb
        ja L_44f085
        cmp eax, 0
        je L_44f0ac
        cmp eax, 1
        je L_44f012
        cmp eax, 2
        je L_44f05b
        cmp eax, 3
        je L_44f04d
        cmp eax, 4
        je L_44f03f
        cmp eax, 5
        je L_44f0ac
        cmp eax, 6
        je L_44f0ac
        cmp eax, 7
        je L_44f031
        cmp eax, 8
        je L_44f023
        cmp eax, 9
        je L_44f069
        cmp eax, 10
        je L_44f077
        cmp eax, 11
        je L_44f0ac
        int 3  // unreachable: the bounds check above excludes other indices
    L_44f012:
        mov edx, esi
        mov ecx, 0x8
        call NodeList_MarkNode
        jmp L_44f0ac
    L_44f023:
        mov edx, esi
        mov ecx, 0xc
        call NodeList_MarkNode
        jmp L_44f0ac
    L_44f031:
        mov edx, esi
        mov ecx, 0xb
        call NodeList_MarkNode
        jmp L_44f0ac
    L_44f03f:
        mov edx, esi
        mov ecx, 0xf
        call NodeList_MarkNode
        jmp L_44f0ac
    L_44f04d:
        mov edx, esi
        mov ecx, 0xe
        call NodeList_MarkNode
        jmp L_44f0ac
    L_44f05b:
        mov edx, esi
        mov ecx, 0xd
        call NodeList_MarkNode
        jmp L_44f0ac
    L_44f069:
        mov edx, esi
        mov ecx, 0x9
        call NodeList_MarkNode
        jmp L_44f0ac
    L_44f077:
        mov edx, esi
        mov ecx, 0xa
        call NodeList_MarkNode
        jmp L_44f0ac
    L_44f085:
        push 0x75d
        push offset g_Data_004da000 + 0x3fd0
        push offset g_Data_004da000 + 0x3f8c
        push offset g_Data_004da000 + 0x9bde0
        call dword ptr [g_Iat_sprintf_004cc5c4]
        add esp, 0x10
        mov ecx, 0x3
        call zerr_old_Report
    L_44f0ac:
        test byte ptr [esi + 0x24], 0x1
        jz L_44f0be
        mov edx, esi
        mov ecx, 0x7
        call NodeList_MarkNode
    L_44f0be:
        mov eax, dword ptr [esi + 0x48]
        test eax, eax
        jz L_44f0d8
        mov ecx, dword ptr [esi + 0x44]
        test ecx, ecx
        jl L_44f0d8
        cmp ecx, 0x6
        jge L_44f0d8
        mov edx, esi
        call NodeList_MarkNode
    L_44f0d8:
        mov edx, esi
        mov ecx, 0x6
        call NodeList_MarkNode
        xor eax, eax
        pop esi
        ret
    }
}

// 0x0044f1d0 ZClass_DestroyNodeData - ret 0xc (decomp read in full 2026-09-24, callee names from the ledger; caveat resolved). 0x00447f00 validates (error -> return it). If the node has a model: gwNodeSetModel(0); when that model's ref count (GetField8) is 0, Model_Free (error -> return). Then by class type +0x34, first detaching every 
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ZClass_DestroyNodeData(int, int)
{
    __asm {
        sub esp, 0xc
        lea edx, [esp]
        push ebx
        push ebp
        push esi
        push edi
        mov esi, ecx
        call gwNodeGetModel
        xor ebp, ebp
        cmp eax, ebp
        jnz L_44f5f8
        cmp dword ptr [esp + 0x10], ebp
        jz L_44f219
        xor edx, edx
        mov ecx, esi
        call gwNodeSetModel
        mov ecx, dword ptr [esp + 0x10]
        call GetField8
        test eax, eax
        jnz L_44f219
        mov ecx, dword ptr [esp + 0x10]
        call Model_Free
        cmp eax, ebp
        jnz L_44f5f8
    L_44f219:
        mov eax, dword ptr [esi + 0x34]
        lea ecx, [eax - 0x1]
        cmp ecx, 0xa
        ja L_44f5d4
        cmp ecx, 0
        je L_44f307
        cmp ecx, 1
        je L_44f47b
        cmp ecx, 2
        je L_44f33d
        cmp ecx, 3
        je L_44f373
        cmp ecx, 4
        je L_44f22f
        cmp ecx, 5
        je L_44f29b
        cmp ecx, 6
        je L_44f2d1
        cmp ecx, 7
        je L_44f265
        cmp ecx, 8
        je L_44f3df
        cmp ecx, 9
        je L_44f42d
        cmp ecx, 10
        je L_44f3a9
        int 3  // unreachable: the bounds check above excludes other indices
    L_44f22f:
        cmp dword ptr [esi + 0x5c], ebp
        jle L_44f24d
    L_44f234:
        mov eax, dword ptr [esi + 0x60]
        mov ecx, esi
        mov edx, dword ptr [eax]
        call Object3D_DetachChild
        cmp eax, ebp
        jnz L_44f5f8
        cmp dword ptr [esi + 0x5c], ebp
        jg L_44f234
    L_44f24d:
        cmp dword ptr [esi + 0x54], ebp
        jnz L_44f5c7
        mov ecx, esi
        call gwNodeDelete
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_44f265:
        cmp dword ptr [esi + 0x5c], ebp
        jle L_44f283
    L_44f26a:
        mov ecx, dword ptr [esi + 0x60]
        mov edx, dword ptr [ecx]
        mov ecx, esi
        call Anim_DetachChild
        cmp eax, ebp
        jnz L_44f5f8
        cmp dword ptr [esi + 0x5c], ebp
        jg L_44f26a
    L_44f283:
        cmp dword ptr [esi + 0x54], ebp
        jnz L_44f5c7
        mov ecx, esi
        call Anim_Destroy
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_44f29b:
        cmp dword ptr [esi + 0x5c], ebp
        jle L_44f2b9
    L_44f2a0:
        mov edx, dword ptr [esi + 0x60]
        mov ecx, esi
        mov edx, dword ptr [edx]
        call Class6_DetachChild
        cmp eax, ebp
        jnz L_44f5f8
        cmp dword ptr [esi + 0x5c], ebp
        jg L_44f2a0
    L_44f2b9:
        cmp dword ptr [esi + 0x54], ebp
        jnz L_44f5c7
        mov ecx, esi
        call gwNodeDelete
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_44f2d1:
        cmp dword ptr [esi + 0x5c], ebp
        jle L_44f2ef
    L_44f2d6:
        mov eax, dword ptr [esi + 0x60]
        mov ecx, esi
        mov edx, dword ptr [eax]
        call Seq_DetachChild
        cmp eax, ebp
        jnz L_44f5f8
        cmp dword ptr [esi + 0x5c], ebp
        jg L_44f2d6
    L_44f2ef:
        cmp dword ptr [esi + 0x54], ebp
        jnz L_44f5c7
        mov ecx, esi
        call gwNodeDelete
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_44f307:
        cmp dword ptr [esi + 0x5c], ebp
        jle L_44f325
    L_44f30c:
        mov ecx, dword ptr [esi + 0x60]
        mov edx, dword ptr [ecx]
        mov ecx, esi
        call Camera_DetachChild
        cmp eax, ebp
        jnz L_44f5f8
        cmp dword ptr [esi + 0x5c], ebp
        jg L_44f30c
    L_44f325:
        cmp dword ptr [esi + 0x54], ebp
        jnz L_44f5c7
        mov ecx, esi
        call gwNodeDelete
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_44f33d:
        cmp dword ptr [esi + 0x5c], ebp
        jle L_44f35b
    L_44f342:
        mov edx, dword ptr [esi + 0x60]
        mov ecx, esi
        mov edx, dword ptr [edx]
        call Window_DetachChild
        cmp eax, ebp
        jnz L_44f5f8
        cmp dword ptr [esi + 0x5c], ebp
        jg L_44f342
    L_44f35b:
        cmp dword ptr [esi + 0x54], ebp
        jnz L_44f5c7
        mov ecx, esi
        call gwNodeDelete
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_44f373:
        cmp dword ptr [esi + 0x5c], ebp
        jle L_44f391
    L_44f378:
        mov eax, dword ptr [esi + 0x60]
        mov ecx, esi
        mov edx, dword ptr [eax]
        call Display_DetachChild
        cmp eax, ebp
        jnz L_44f5f8
        cmp dword ptr [esi + 0x5c], ebp
        jg L_44f378
    L_44f391:
        cmp dword ptr [esi + 0x54], ebp
        jnz L_44f5c7
        mov ecx, esi
        call gwNodeDelete
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_44f3a9:
        cmp dword ptr [esi + 0x5c], ebp
        jle L_44f3c7
    L_44f3ae:
        mov ecx, dword ptr [esi + 0x60]
        mov edx, dword ptr [ecx]
        mov ecx, esi
        call Switch_DetachChild
        cmp eax, ebp
        jnz L_44f5f8
        cmp dword ptr [esi + 0x5c], ebp
        jg L_44f3ae
    L_44f3c7:
        cmp dword ptr [esi + 0x54], ebp
        jnz L_44f5c7
        mov ecx, esi
        call gwNodeDelete
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_44f3df:
        cmp dword ptr [esi + 0x5c], ebp
        jle L_44f3fd
    L_44f3e4:
        mov edx, dword ptr [esi + 0x60]
        mov ecx, esi
        mov edx, dword ptr [edx]
        call Light_DetachChild
        cmp eax, ebp
        jnz L_44f5f8
        cmp dword ptr [esi + 0x5c], ebp
        jg L_44f3e4
    L_44f3fd:
        mov eax, dword ptr [esi + 0x38]
        cmp dword ptr [eax + 0xdc], ebp
        jle L_44f415
        mov eax, 0x1
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_44f415:
        cmp dword ptr [esi + 0x54], ebp
        jnz L_44f5c7
        mov ecx, esi
        call Light_Destroy
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_44f42d:
        cmp dword ptr [esi + 0x5c], ebp
        jle L_44f44b
    L_44f432:
        mov ecx, dword ptr [esi + 0x60]
        mov edx, dword ptr [ecx]
        mov ecx, esi
        call Sound_DetachChild
        cmp eax, ebp
        jnz L_44f5f8
        cmp dword ptr [esi + 0x5c], ebp
        jg L_44f432
    L_44f44b:
        mov edx, dword ptr [esi + 0x38]
        cmp dword ptr [edx + 0x8c], ebp
        jle L_44f463
        mov eax, 0x1
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_44f463:
        cmp dword ptr [esi + 0x54], ebp
        jnz L_44f5c7
        mov ecx, esi
        call Sound_Destroy
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_44f47b:
        mov edi, dword ptr [esi + 0x38]
        cmp dword ptr [edi + 0x90], ebp
        jle L_44f4a5
    L_44f486:
        mov eax, dword ptr [edi + 0x94]
        mov ecx, esi
        mov edx, dword ptr [eax]
        call World_RemoveLight
        cmp eax, ebp
        jnz L_44f5f8
        cmp dword ptr [edi + 0x90], ebp
        jg L_44f486
    L_44f4a5:
        mov eax, dword ptr [edi + 0x94]
        cmp eax, ebp
        jz L_44f4d3
        mov ebx, dword ptr [g_Iat_free_004cc5b4]
        push eax
        call ebx
        mov ecx, dword ptr [edi + 0x98]
        add esp, 0x4
        mov dword ptr [edi + 0x94], ebp
        push ecx
        call ebx
        add esp, 0x4
        mov dword ptr [edi + 0x98], ebp
    L_44f4d3:
        mov ebx, dword ptr [esi + 0x38]
        cmp dword ptr [ebx + 0x9c], ebp
        jle L_44f4fd
    L_44f4de:
        mov edx, dword ptr [ebx + 0xa0]
        mov ecx, esi
        mov edx, dword ptr [edx]
        call World_RemoveSound
        cmp eax, ebp
        jnz L_44f5f8
        cmp dword ptr [ebx + 0x9c], ebp
        jg L_44f4de
    L_44f4fd:
        mov eax, dword ptr [ebx + 0xa0]
        cmp eax, ebp
        jz L_44f52b
        mov edi, dword ptr [g_Iat_free_004cc5b4]
        push eax
        call edi
        mov eax, dword ptr [ebx + 0xa4]
        add esp, 0x4
        mov dword ptr [ebx + 0xa0], ebp
        push eax
        call edi
        add esp, 0x4
        mov dword ptr [ebx + 0xa4], ebp
    L_44f52b:
        cmp dword ptr [esi + 0x5c], ebp
        jle L_44f549
    L_44f530:
        mov ecx, dword ptr [esi + 0x60]
        mov edx, dword ptr [ecx]
        mov ecx, esi
        call World_DetachChild
        cmp eax, ebp
        jnz L_44f5f8
        cmp dword ptr [esi + 0x5c], ebp
        jg L_44f530
    L_44f549:
        mov eax, dword ptr [ebx + 0x7c]
        mov edx, dword ptr [ebx + 0x80]
        cmp eax, ebp
        mov dword ptr [esp + 0x14], edx
        mov dword ptr [esp + 0x18], ebp
        jle L_44f5b3
    L_44f55e:
        mov eax, dword ptr [esp + 0x14]
        mov ecx, dword ptr [ebx + 0x78]
        xor ebp, ebp
        mov eax, dword ptr [eax]
        test ecx, ecx
        jle L_44f596
        lea edi, [eax + 0x3a]
    L_44f570:
        cmp word ptr [edi], 0x0
        jle L_44f58b
    L_44f576:
        mov ecx, dword ptr [edi + 0x2]
        mov edx, dword ptr [ecx]
        mov ecx, esi
        call World_DetachChild
        test eax, eax
        jnz L_44f5f8
        cmp word ptr [edi], AX
        jg L_44f576
    L_44f58b:
        mov eax, dword ptr [ebx + 0x78]
        add edi, 0x40
        inc ebp
        cmp ebp, eax
        jl L_44f570
    L_44f596:
        mov edi, dword ptr [esp + 0x14]
        mov eax, dword ptr [esp + 0x18]
        mov ecx, dword ptr [ebx + 0x7c]
        add edi, 0x4
        inc eax
        mov dword ptr [esp + 0x14], edi
        cmp eax, ecx
        mov dword ptr [esp + 0x18], eax
        jl L_44f55e
        xor ebp, ebp
    L_44f5b3:
        cmp dword ptr [esi + 0x54], ebp
        jnz L_44f5c7
        mov ecx, esi
        call World_Destroy
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_44f5c7:
        mov eax, 0x1
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_44f5d4:
        push eax
        push esi
        push esi
        push offset g_Data_004da000 + 0x4064
        push 0x8d4
        push offset g_Data_004da000 + 0x3fd0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x1c
        mov eax, 0x3
    L_44f5f8:
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    }
}

// 0x0044f120 ClassList_DeleteAll - (listType ECX) 0x0044e920; repeatedly delete nodes of list table 0x004ddef8[type] via 0x0044f1d0 until empty (error List line 0x92d if not); 0x0044ec90()==0 -> clear 0x004ddf38[type], return 0; else error line 0x935 return 1
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ClassList_DeleteAll(int, int)
{
    __asm {
        push ebx
        push esi
        push edi
        mov ebx, ecx
        call NodeList_FlushAll
        mov eax, dword ptr [ebx*0x4 + g_Data_004da000 + 0x3ef8]
        mov edi, 0x1
        mov eax, dword ptr [eax]
        test eax, eax
        jz L_44f184
    L_44f13c:
        cmp edi, 0x1
        jnz L_44f174
        xor edi, edi
        mov esi, eax
    L_44f145:
        mov ecx, dword ptr [esi]
        call ZClass_DestroyNodeData
        test eax, eax
        jnz L_44f157
        mov edi, 0x1
        jmp L_44f15a
    L_44f157:
        mov esi, dword ptr [esi + 0x8]
    L_44f15a:
        test esi, esi
        jz L_44f162
        test edi, edi
        jz L_44f145
    L_44f162:
        call NodeList_FlushAll
        mov ecx, dword ptr [ebx*0x4 + g_Data_004da000 + 0x3ef8]
        mov eax, dword ptr [ecx]
        test eax, eax
        jnz L_44f13c
    L_44f174:
        test eax, eax
        jz L_44f184
        push offset g_Data_004da000 + 0x4028
        push 0x92d
        jmp L_44f199
    L_44f184:
        mov ecx, ebx
        call NodeList_Count
        test eax, eax
        jz L_44f1b4
        push offset g_Data_004da000 + 0x3ff4
        push 0x935
    L_44f199:
        push offset g_Data_004da000 + 0x3fd0
        push 0x400
        call Debug_ReportNoop
        add esp, 0x10
        mov eax, 0x1
        pop edi
        pop esi
        pop ebx
        ret
    L_44f1b4:
        mov edx, dword ptr [ebx*0x4 + g_Data_004da000 + 0x3f38]
        pop edi
        pop esi
        xor eax, eax
        mov dword ptr [edx], 0x0
        pop ebx
        ret
    }
}

}  // namespace recoil
