// SUBSYSTEM: zclass_nodes
// Original file: GameZRecoil/zClass/Seq.c (ledger orig_file; from NodeType6_Create 0x004542a0 on by SUBSYS attribution): sequence node class handlers. Spec: 04_spec/systems/class_api.md, 04_spec/systems/scene_update.md
// Instruction-level ports generated by tools/asm_port/port_batch.py from the Ghidra listings.
#include "GameZRecoil/zClass/Seq.h"
#include "GameZRecoil/zClass/Class.h"
#include "platform/iat_msvcrt.h"
#include "platform/image/original_data.h"
#include "unattributed/scene_update.h"
#include "unattributed/ui_widgets.h"

namespace recoil {

// 0x00453ee0 Seq_Create - node = 0x004478c0(); failure -> report (Seq.cpp 0x41) return 0; type [node+0x34]=7; class data calloc(1,0x28) at +0x38 (unchecked), [data+0x10]=1; NodeRegistry_Insert; return node
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Seq_Create(int, int)
{
    __asm {
        push esi
        call gwNodeAlloc
        mov esi, eax
        test esi, esi
        jnz L_453f09
        push offset g_Data_004da000 + 0x39d4
        push 0x41
        push offset g_Data_004da000 + 0x4df8
        push 0x400
        call Debug_ReportNoop
        add esp, 0x10
        xor eax, eax
        pop esi
        ret
    L_453f09:
        push 0x28
        push 0x1
        mov dword ptr [esi + 0x34], 0x7
        call dword ptr [g_Iat_calloc_004cc4ac]
        add esp, 0x8
        mov dword ptr [esi + 0x38], eax
        mov edx, esi
        mov ecx, 0xb
        mov dword ptr [eax + 0x10], 0x1
        call NodeRegistry_Insert
        mov eax, esi
        pop esi
        ret
    }
}

// 0x00453f40 Seq_InsertEntry - (seq ECX, child EDX, index arg1, value arg2): null checks (Seq.cpp 0x94/0x95/0x96, return 5); r = 0x004484d0(); if r != 0 return r; realloc class data to 0x28 + count*8 (count [data+0x1C], realloc unchecked), count++; shifts 8-byte entries up from index (index not bounds-checked); entry[index] at da
// Register/stack shape from the listing (ECX, EDX, 8 stack bytes).
__declspec(naked) int __fastcall Seq_InsertEntry(int, int, int, int)
{
    __asm {
        push ebx
        push esi
        mov esi, ecx
        push edi
        test esi, esi
        mov edi, edx
        jnz L_453f57
        push offset g_Data_004da000 + 0x39d4
        push 0x94
        jmp L_453f78
    L_453f57:
        test edi, edi
        jnz L_453f67
        push offset g_Data_004da000 + 0x39d4
        push 0x95
        jmp L_453f78
    L_453f67:
        mov eax, dword ptr [esi + 0x38]
        test eax, eax
        jnz L_453f95
        push offset g_Data_004da000 + 0x39bc
        push 0x96
    L_453f78:
        push offset g_Data_004da000 + 0x4df8
        push 0x400
        call Debug_ReportNoop
        add esp, 0x10
        mov eax, 0x5
        pop edi
        pop esi
        pop ebx
        ret 0x8
    L_453f95:
        mov edx, edi
        mov ecx, esi
        call gwNodeAttachChild
        test eax, eax
        jnz L_453ff6
        mov eax, dword ptr [esi + 0x38]
        mov ecx, dword ptr [eax + 0x1c]
        lea edx, [ecx*0x8 + 0x28]
        push edx
        push eax
        call dword ptr [g_Iat_realloc_004cc4ec]
        mov dword ptr [esi + 0x38], eax
        mov edx, dword ptr [eax + 0x1c]
        mov esi, dword ptr [esp + 0x18]
        add esp, 0x8
        inc edx
        mov ecx, edx
        mov dword ptr [eax + 0x1c], edx
        lea edx, [ecx - 0x1]
        cmp edx, esi
        jle L_453fe8
        lea ecx, [eax + edx*0x8 + 0x20]
        sub edx, esi
    L_453fd7:
        mov ebx, dword ptr [ecx - 0x8]
        mov dword ptr [ecx], ebx
        mov ebx, dword ptr [ecx - 0x4]
        mov dword ptr [ecx + 0x4], ebx
        sub ecx, 0x8
        dec edx
        jnz L_453fd7
    L_453fe8:
        fld dword ptr [esp + 0x14]
        mov dword ptr [eax + esi*0x8 + 0x20], edi
        fstp dword ptr [eax + esi*0x8 + 0x24]
        xor eax, eax
    L_453ff6:
        pop edi
        pop esi
        pop ebx
        ret 0x8
    }
}

// 0x00454000 Seq_DetachChild - ../../04_spec/systems/class_api.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Seq_DetachChild(int, int)
{
    __asm {
        push ebx
        push esi
        mov esi, ecx
        test esi, esi
        push edi
        mov ebx, edx
        jnz L_454017
        push offset g_Data_004da000 + 0x39d4
        push 0xd3
        jmp L_454038
    L_454017:
        test ebx, ebx
        jnz L_454027
        push offset g_Data_004da000 + 0x39d4
        push 0xd4
        jmp L_454038
    L_454027:
        mov eax, dword ptr [esi + 0x38]
        test eax, eax
        jnz L_454053
        push offset g_Data_004da000 + 0x39bc
        push 0xd5
    L_454038:
        push offset g_Data_004da000 + 0x4df8
        push 0x400
        call Debug_ReportNoop
        add esp, 0x10
        mov eax, 0x5
        pop edi
        pop esi
        pop ebx
        ret
    L_454053:
        mov edx, ebx
        mov ecx, esi
        call gwNodeDetachChild
        test eax, eax
        jnz L_4540ba
        mov edi, dword ptr [esi + 0x38]
        or ecx, 0xffffffff
        mov esi, dword ptr [edi + 0x1c]
        test esi, esi
        jle L_454080
        lea edx, [edi + 0x20]
    L_454070:
        cmp dword ptr [edx], ebx
        jz L_45407e
        inc eax
        add edx, 0x8
        cmp eax, esi
        jl L_454070
        jmp L_454080
    L_45407e:
        mov ecx, eax
    L_454080:
        test ecx, ecx
        jl L_4540a7
        dec esi
        cmp ecx, esi
        jge L_4540a4
        lea eax, [edi + ecx*0x8 + 0x20]
    L_45408d:
        mov edx, dword ptr [eax + 0x8]
        inc ecx
        mov dword ptr [eax], edx
        mov edx, dword ptr [eax + 0xc]
        mov dword ptr [eax + 0x4], edx
        mov edx, dword ptr [edi + 0x1c]
        add eax, 0x8
        dec edx
        cmp ecx, edx
        jl L_45408d
    L_4540a4:
        dec dword ptr [edi + 0x1c]
    L_4540a7:
        mov eax, dword ptr [edi + 0x14]
        mov ecx, dword ptr [edi + 0x1c]
        cmp eax, ecx
        jl L_4540b8
        mov dword ptr [edi + 0x14], 0x0
    L_4540b8:
        xor eax, eax
    L_4540ba:
        pop edi
        pop esi
        pop ebx
        ret
    }
}

// 0x004540c0 Seq_SetField0 - node ECX: null node -> report 'Null node pointer' (Seq.cpp 0x113) return 5; null class data [+0x38] -> report (0x114) return 5; else [data+0]=EDX, return 0
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Seq_SetField0(int, int)
{
    __asm {
        test ecx, ecx
        jnz L_4540d0
        push offset g_Data_004da000 + 0x39d4
        push 0x113
        jmp L_4540e1
    L_4540d0:
        mov ecx, dword ptr [ecx + 0x38]
        test ecx, ecx
        jnz L_4540f9
        push offset g_Data_004da000 + 0x39bc
        push 0x114
    L_4540e1:
        push offset g_Data_004da000 + 0x4df8
        push 0x400
        call Debug_ReportNoop
        add esp, 0x10
        mov eax, 0x5
        ret
    L_4540f9:
        mov dword ptr [ecx], edx
        xor eax, eax
        ret
    }
}

// 0x00454100 Seq_SetField4 - as Seq_SetField0 writing [data+4] (lines 0x133/0x134)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Seq_SetField4(int, int)
{
    __asm {
        test ecx, ecx
        jnz L_454110
        push offset g_Data_004da000 + 0x39d4
        push 0x133
        jmp L_454121
    L_454110:
        mov ecx, dword ptr [ecx + 0x38]
        test ecx, ecx
        jnz L_454139
        push offset g_Data_004da000 + 0x39bc
        push 0x134
    L_454121:
        push offset g_Data_004da000 + 0x4df8
        push 0x400
        call Debug_ReportNoop
        add esp, 0x10
        mov eax, 0x5
        ret
    L_454139:
        mov dword ptr [ecx + 0x4], edx
        xor eax, eax
        ret
    }
}

// 0x00454140 Seq_SetField8 - as Seq_SetField0 writing [data+8] (lines 0x153/0x154)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Seq_SetField8(int, int)
{
    __asm {
        test ecx, ecx
        jnz L_454150
        push offset g_Data_004da000 + 0x39d4
        push 0x153
        jmp L_454161
    L_454150:
        mov ecx, dword ptr [ecx + 0x38]
        test ecx, ecx
        jnz L_454179
        push offset g_Data_004da000 + 0x39bc
        push 0x154
    L_454161:
        push offset g_Data_004da000 + 0x4df8
        push 0x400
        call Debug_ReportNoop
        add esp, 0x10
        mov eax, 0x5
        ret
    L_454179:
        mov dword ptr [ecx + 0x8], edx
        xor eax, eax
        ret
    }
}

// 0x00454180 Seq_SetFieldC - as Seq_SetField0 writing [data+0xC] (lines 0x173/0x174)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Seq_SetFieldC(int, int)
{
    __asm {
        test ecx, ecx
        jnz L_454190
        push offset g_Data_004da000 + 0x39d4
        push 0x173
        jmp L_4541a1
    L_454190:
        mov ecx, dword ptr [ecx + 0x38]
        test ecx, ecx
        jnz L_4541b9
        push offset g_Data_004da000 + 0x39bc
        push 0x174
    L_4541a1:
        push offset g_Data_004da000 + 0x4df8
        push 0x400
        call Debug_ReportNoop
        add esp, 0x10
        mov eax, 0x5
        ret
    L_4541b9:
        mov dword ptr [ecx + 0xc], edx
        xor eax, eax
        ret
    }
}

// 0x004541c0 Seq_AdvanceKeyframes - ../../04_spec/systems/scene_update.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Seq_AdvanceKeyframes(int, int)
{
    __asm {
        push ecx
        push esi
        push edi
        xor edi, edi
        cmp ecx, edi
        jnz L_4541d5
        push offset g_Data_004da000 + 0x39d4
        push 0x193
        jmp L_4541e6
    L_4541d5:
        mov ecx, dword ptr [ecx + 0x38]
        cmp ecx, edi
        jnz L_454201
        push offset g_Data_004da000 + 0x39bc
        push 0x194
    L_4541e6:
        push offset g_Data_004da000 + 0x4df8
        push 0x400
        call Debug_ReportNoop
        add esp, 0x10
        mov eax, 0x5
        pop edi
        pop esi
        pop ecx
        ret
    L_454201:
        mov eax, dword ptr [g_Data_004da000 + 0x91424]
        mov dword ptr [esp + 0x8], eax
        mov eax, dword ptr [ecx + 0xc]
        cmp eax, edi
        jnz L_454297
        cmp dword ptr [ecx], edi
        jz L_454297
        fld dword ptr [esp + 0x8]
        fadd dword ptr [ecx + 0x18]
        mov edx, dword ptr [ecx + 0x14]
        fst dword ptr [ecx + 0x18]
        fcomp dword ptr [ecx + edx*0x8 + 0x24]
        fnstsw AX
        test AH, 0x41
        jnz L_454297
        mov esi, dword ptr [ecx + 0x1c]
    L_454234:
        fld dword ptr [ecx + 0x18]
        fsub dword ptr [ecx + edx*0x8 + 0x24]
        mov eax, dword ptr [ecx + 0x10]
        add edx, eax
        cmp edx, esi
        mov dword ptr [ecx + 0x14], edx
        fstp dword ptr [ecx + 0x18]
        jl L_454266
        cmp dword ptr [ecx + 0x8], edi
        jz L_454254
        mov dword ptr [ecx + 0x14], edi
        jmp L_45425f
    L_454254:
        lea edx, [esi - 0x1]
        neg eax
        mov dword ptr [ecx + 0x14], edx
        mov dword ptr [ecx + 0x10], eax
    L_45425f:
        cmp dword ptr [ecx + 0x4], edi
        jnz L_454286
        jmp L_454284
    L_454266:
        cmp edx, edi
        jge L_454286
        cmp dword ptr [ecx + 0x8], edi
        jz L_454277
        lea eax, [esi - 0x1]
        mov dword ptr [ecx + 0x14], eax
        jmp L_45427f
    L_454277:
        neg eax
        mov dword ptr [ecx + 0x14], edi
        mov dword ptr [ecx + 0x10], eax
    L_45427f:
        cmp dword ptr [ecx + 0x4], edi
        jnz L_454286
    L_454284:
        mov dword ptr [ecx], edi
    L_454286:
        mov edx, dword ptr [ecx + 0x14]
        fld dword ptr [ecx + 0x18]
        fcomp dword ptr [ecx + edx*0x8 + 0x24]
        fnstsw AX
        test AH, 0x41
        jz L_454234
    L_454297:
        pop edi
        xor eax, eax
        pop esi
        pop ecx
        ret
    }
}

// 0x004542a0 NodeType6_Create - node = 0x004478c0() (no null check); type [+0x34]=6; data calloc(1,0x50) unchecked: [0]=1, [1]=0, [2]=1000.0f, [3]=1000000.0f, [4..0x10]=0, [0x11]=1
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall NodeType6_Create(int, int)
{
    __asm {
        push esi
        call gwNodeAlloc
        mov esi, eax
        push 0x50
        push 0x1
        mov dword ptr [esi + 0x34], 0x6
        call dword ptr [g_Iat_calloc_004cc4ac]
        xor ecx, ecx
        add esp, 0x8
        mov dword ptr [esi + 0x38], eax
        mov dword ptr [eax], 0x1
        mov dword ptr [eax + 0x4], ecx
        mov dword ptr [eax + 0x8], 0x447a0000
        mov dword ptr [eax + 0xc], 0x49742400
        mov dword ptr [eax + 0x10], ecx
        mov dword ptr [eax + 0x14], ecx
        mov dword ptr [eax + 0x18], ecx
        mov dword ptr [eax + 0x1c], ecx
        mov dword ptr [eax + 0x20], ecx
        mov dword ptr [eax + 0x24], ecx
        mov dword ptr [eax + 0x28], ecx
        mov dword ptr [eax + 0x2c], ecx
        mov dword ptr [eax + 0x30], ecx
        mov dword ptr [eax + 0x34], ecx
        mov dword ptr [eax + 0x38], ecx
        mov dword ptr [eax + 0x3c], ecx
        mov dword ptr [eax + 0x40], ecx
        mov dword ptr [eax + 0x44], 0x1
        mov eax, esi
        pop esi
        ret
    }
}

// 0x00454320 Class6_DetachChild - ../../04_spec/systems/class_api.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Class6_DetachChild(int, int)
{
    __asm {
        call gwNodeDetachChild
        xor eax, eax
        ret
    }
}

// 0x00454330 Node_SetClassDataField0_NoCheck - [[node ECX+0x38]] = EDX; return 0 (no null checks)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Node_SetClassDataField0_NoCheck(int, int)
{
    __asm {
        mov eax, dword ptr [ecx + 0x38]
        mov dword ptr [eax], edx
        xor eax, eax
        ret
    }
}

// 0x00454340 Node_SetClassDataRangeCheck - bytes read: data=[ECX+0x38]; [data+0x48]=EDX; if EDX nonzero [data+0x4C] = float arg squared; return 0; ret 4 (no null check)
// Register/stack shape from the listing (ECX, EDX, 4 stack bytes).
__declspec(naked) int __fastcall Node_SetClassDataRangeCheck(int, int, int)
{
    __asm {
        mov eax, dword ptr [ecx + 0x38]
        test edx, edx
        mov dword ptr [eax + 0x48], edx
        jz L_454355
        fld dword ptr [esp + 0x4]
        fmul dword ptr [esp + 0x4]
        fstp dword ptr [eax + 0x4c]
    L_454355:
        xor eax, eax
        ret 0x4
    }
}

// 0x00454360 GameZ_ClearWorldPath - dword [0x00539ca8]=0 (empties the GameZ path string read by GameZ_LoadWorldFile); return 0
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall GameZ_ClearWorldPath(int, int)
{
    __asm {
        mov byte ptr [g_Data_004da000 + 0x5fca8], 0x0
        xor eax, eax
        ret
    }
}

// 0x00454370 ClsRecord_ToIndex - ptr ECX null -> -1; else (ptr - [0x00539c94]) / 0xC4
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ClsRecord_ToIndex(int, int)
{
    __asm {
        test ecx, ecx
        jnz L_454378
        or eax, 0xffffffff
        ret
    L_454378:
        mov edx, dword ptr [g_Data_004da000 + 0x5fc94]
        mov eax, 0x5397829d
        sub ecx, edx
        imul ecx
        mov eax, edx
        sar eax, 0x6
        mov ecx, eax
        shr ecx, 0x1f
        add eax, ecx
        ret
    }
}

// 0x004543a0 ClsRecord_ActiveIndex - bytes read: index = ClsRecord_ToIndex(ECX); -1 unless index >= 0 and record flags [+0xC0] bit 0x1000000 set
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ClsRecord_ActiveIndex(int, int)
{
    __asm {
        call ClsRecord_ToIndex
        test eax, eax
        jl L_4543c4
        mov edx, dword ptr [g_Data_004da000 + 0x5fc94]
        lea ecx, [eax + eax*0x2]
        shl ecx, 0x4
        add ecx, eax
        test dword ptr [edx + ecx*0x4 + 0xc0], 0x1000000
        jnz L_4543c7
    L_4543c4:
        or eax, 0xffffffff
    L_4543c7:
        ret
    }
}

}  // namespace recoil
