// SUBSYSTEM: zvideo
// Original file: GameZRecoil/zVideo/zvid_init.c (ledger orig_file).
// Instruction-level ports generated by tools/asm_port/port_batch.py from the Ghidra listings.
#include "GameZRecoil/zVideo/zvid_init.h"
#include "platform/image/original_data.h"
#include "platform/iat_user32.h"
#include "GameZRecoil/zVideo/zvid_buff.h"
#include "GameZRecoil/zVideo/zvid_dd.h"
#include "GameZRecoil/zVideo/zvid_ddd3d.h"
#include "GameZRecoil/zVideo/zvid_ddd3d_zvideo.h"
#include "unattributed/settings.h"
#include "unattributed/ui_widgets.h"
#include "unattributed/zvideo.h"

namespace recoil {

// 0x004a7b20 zVideo_SetD3DDeviceCreated - ../../04_spec/systems/render.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall zVideo_SetD3DDeviceCreated(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x158130]
        mov dword ptr [g_Data_004da000 + 0x158130], ecx
        ret
    }
}

// 0x004a7b30 zVideo_IsD3DDeviceCreated - ../../04_spec/systems/render.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall zVideo_IsD3DDeviceCreated(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x158130]
        ret
    }
}

// 0x004a7990 Render_ApplyResolutionPreset - ../../04_spec/systems/render.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Render_ApplyResolutionPreset(int, int)
{
    __asm {
        lea eax, [ecx - 0x2]
        cmp eax, 0x5
        ja L_4a7acd
        mov edx, 0x1
        cmp eax, 0
        je L_4a79a8
        cmp eax, 1
        je L_4a79e0
        cmp eax, 2
        je L_4a7a3d
        cmp eax, 3
        je L_4a7a18
        cmp eax, 4
        je L_4a7a62
        cmp eax, 5
        je L_4a7a87
        int 3  // unreachable: the bounds check above excludes other indices
    L_4a79a8:
        mov eax, 0x280
        mov dword ptr [g_Data_004da000 + 0x158128], edx
        mov dword ptr [g_Data_004da000 + 0x158240], eax
        mov dword ptr [g_Data_004da000 + 0x158220], eax
        mov eax, 0x190
        mov dword ptr [g_Data_004da000 + 0x158200], 0x140
        mov dword ptr [g_Data_004da000 + 0x158204], 0xc8
        mov dword ptr [g_Data_004da000 + 0x158244], eax
        jmp L_4a7ab4
    L_4a79e0:
        mov eax, 0x280
        mov dword ptr [g_Data_004da000 + 0x158128], edx
        mov dword ptr [g_Data_004da000 + 0x158240], eax
        mov dword ptr [g_Data_004da000 + 0x158220], eax
        mov eax, 0x1e0
        mov dword ptr [g_Data_004da000 + 0x158200], 0x140
        mov dword ptr [g_Data_004da000 + 0x158204], 0xf0
        mov dword ptr [g_Data_004da000 + 0x158244], eax
        jmp L_4a7ab4
    L_4a7a18:
        mov eax, 0x280
        mov dword ptr [g_Data_004da000 + 0x158128], 0x0
        mov dword ptr [g_Data_004da000 + 0x158240], eax
        mov dword ptr [g_Data_004da000 + 0x158200], eax
        mov dword ptr [g_Data_004da000 + 0x158220], eax
        mov eax, 0x1e0
        jmp L_4a7aaa
    L_4a7a3d:
        mov eax, 0x280
        mov dword ptr [g_Data_004da000 + 0x158128], 0x0
        mov dword ptr [g_Data_004da000 + 0x158240], eax
        mov dword ptr [g_Data_004da000 + 0x158200], eax
        mov dword ptr [g_Data_004da000 + 0x158220], eax
        mov eax, 0x190
        jmp L_4a7aaa
    L_4a7a62:
        mov eax, 0x320
        mov dword ptr [g_Data_004da000 + 0x158128], 0x0
        mov dword ptr [g_Data_004da000 + 0x158240], eax
        mov dword ptr [g_Data_004da000 + 0x158200], eax
        mov dword ptr [g_Data_004da000 + 0x158220], eax
        mov eax, 0x258
        jmp L_4a7aaa
    L_4a7a87:
        mov eax, 0x400
        mov dword ptr [g_Data_004da000 + 0x158128], 0x0
        mov dword ptr [g_Data_004da000 + 0x158240], eax
        mov dword ptr [g_Data_004da000 + 0x158200], eax
        mov dword ptr [g_Data_004da000 + 0x158220], eax
        mov eax, 0x300
    L_4a7aaa:
        mov dword ptr [g_Data_004da000 + 0x158244], eax
        mov dword ptr [g_Data_004da000 + 0x158204], eax
    L_4a7ab4:
        mov dword ptr [g_Data_004da000 + 0x158224], eax
        xor eax, eax
        cmp ecx, edx
        setle AL
        dec eax
        and eax, 0x8
        add eax, 0x8
        mov dword ptr [g_Data_004da000 + 0x158150], eax
        ret
    L_4a7acd:
        mov dword ptr [g_Data_004da000 + 0x15814c], 0x0
        ret
    }
}

// 0x004a7af0 zVideo_SetVideoMode - ../../04_spec/systems/render.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall zVideo_SetVideoMode(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x158154]
        push esi
        test eax, eax
        mov esi, ecx
        jnz L_4a7b03
        mov eax, 0x5a560000
        pop esi
        ret
    L_4a7b03:
        mov ecx, esi
        call Render_ApplyResolutionPreset
        mov ecx, esi
        call dword ptr [g_Data_004da000 + 0x1593bc]
        pop esi
        ret
    }
}

// 0x004a7700 zVideo_CacheClientRectScreen - ../../04_spec/systems/render.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall zVideo_CacheClientRectScreen(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x1581c8]
        push esi
        push offset g_Data_004da000 + 0x158f88
        push eax
        call dword ptr [g_Iat_GetClientRect_004cc670]
        mov ecx, dword ptr [g_Data_004da000 + 0x1581c8]
        mov esi, dword ptr [g_Iat_ClientToScreen_004cc6c8]
        push offset g_Data_004da000 + 0x158f88
        push ecx
        call esi
        mov edx, dword ptr [g_Data_004da000 + 0x1581c8]
        push offset g_Data_004da000 + 0x158f90
        push edx
        call esi
        xor eax, eax
        pop esi
        ret
    }
}

// 0x004a7740 zVideo_Close - ../../04_spec/systems/render.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall zVideo_Close(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x158154]
        test eax, eax
        jnz L_4a774f
        mov eax, 0x5a560000
        ret
    L_4a774f:
        mov dword ptr [g_Data_004da000 + 0x158154], 0x0
        call dword ptr [g_Data_004da000 + 0x1593b0]
        push 0x1
        call dword ptr [g_Iat_ShowCursor_004cc678]
        xor eax, eax
        ret
    }
}

// 0x004a75f0 zVideo_Open - ../../04_spec/systems/render.md
// Register/stack shape from the listing (ECX, EDX, 8 stack bytes).
__declspec(naked) int __fastcall zVideo_Open(int, int, int, int)
{
    __asm {
        mov eax, edx
        push esi
        mov edx, dword ptr [g_Data_004da000 + 0x158154]
        push edi
        test edx, edx
        jz L_4a7608
        mov eax, 0x5a560001
        pop edi
        pop esi
        ret 0x8
    L_4a7608:
        mov edx, dword ptr [esp + 0xc]
        mov dword ptr [g_Data_004da000 + 0x1581c8], ecx
        mov ecx, eax
        mov dword ptr [g_Data_004da000 + 0x91bd8], 0x0
        call Render_InstallDrawDispatchTable
        mov edi, dword ptr [esp + 0x10]
        mov ecx, edi
        call dword ptr [g_Data_004da000 + 0x1593ac]
        mov esi, eax
        test esi, esi
        jz L_4a7655
        push offset g_Data_004da000 + 0x90c8
        push 0x7a
        push offset g_Data_004da000 + 0x90a0
        push 0x800
        call Debug_ReportNoop
        add esp, 0x10
        mov eax, esi
        pop edi
        pop esi
        ret 0x8
    L_4a7655:
        push 0x0
        call dword ptr [g_Iat_ShowCursor_004cc678]
        mov ecx, edi
        mov dword ptr [g_Data_004da000 + 0x158154], 0x1
        call zVideo_SetVideoMode
        mov esi, eax
        test esi, esi
        jz L_4a769c
        push offset g_Data_004da000 + 0x9084
        push 0x86
        push offset g_Data_004da000 + 0x90a0
        push 0x800
        call Debug_ReportNoop
        add esp, 0x10
        call zVideo_Close
        mov eax, esi
        pop edi
        pop esi
        ret 0x8
    L_4a769c:
        mov eax, dword ptr [g_Data_004da000 + 0x158120]
        test eax, eax
        jz L_4a76e8
        push 0x0
        push 0x0
        push 0x0
        mov edx, offset g_Data_004da000 + 0x9338
        xor ecx, ecx
        call dword ptr [g_Data_004da000 + 0x91c08]
        mov dword ptr [g_Data_004da000 + 0x1593a8], eax
        mov dword ptr [g_Data_004da000 + 0x159638], 0x0
        mov eax, offset g_Data_004da000 + 0x159690
        mov ecx, 0xff000000
    L_4a76d1:
        mov dword ptr [eax + 0x20], ecx
        mov dword ptr [eax], ecx
        mov dword ptr [eax - 0x20], ecx
        mov dword ptr [eax - 0x40], ecx
        add eax, 0x80
        cmp eax, offset g_Data_004da000 + 0x159e90
        jl L_4a76d1
    L_4a76e8:
        call zVideo_CacheClientRectScreen
        xor eax, eax
        pop edi
        pop esi
        ret 0x8
    }
}

// 0x004a77a0 Render_InstallDrawDispatchTable - ../../04_spec/systems/render_d3d.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Render_InstallDrawDispatchTable(int, int)
{
    __asm {
        push esi
        mov esi, edx
        call zVideo_SetHardwareMode
        mov eax, dword ptr [g_Data_004da000 + 0x158120]
        mov dword ptr [g_Data_004da000 + 0x158124], esi
        cmp eax, 0x1
        mov dword ptr [g_Data_004da000 + 0x1593ac], offset DDraw_EnsureDeviceCreated
        mov dword ptr [g_Data_004da000 + 0x1593b0], offset DDraw_ReleaseDevice
        mov dword ptr [g_Data_004da000 + 0x1593b8], offset zVideo_SetPaletteEntries
        mov dword ptr [g_Data_004da000 + 0x1593bc], offset Render_ResetDisplayMode
        mov dword ptr [g_Data_004da000 + 0x1593b4], offset zVideo_FlipFrame
        jz L_4a77f4
        mov dword ptr [g_Data_004da000 + 0x1593b4], offset zVideo_BltPresent
    L_4a77f4:
        mov eax, dword ptr [g_Data_004da000 + 0x159e40]
        mov dword ptr [g_Data_004da000 + 0x1593c4], offset zVideo_LockSurfaceRecord
        test eax, eax
        mov dword ptr [g_Data_004da000 + 0x1593c0], offset zVideo_UnlockSurfaceRecordIfLocked
        mov dword ptr [g_Data_004da000 + 0x1593d0], offset zVideo_ClearDepthRect
        mov dword ptr [g_Data_004da000 + 0x1593cc], offset zVideo_ClearBackBufferColourAndDepthRects
        mov dword ptr [g_Data_004da000 + 0x1593c8], offset zVideo_ClearColourAndDepthRect
        mov dword ptr [g_Data_004da000 + 0x1593d4], offset zVideo_ApplyFogColour
        mov dword ptr [g_Data_004da000 + 0x91c30], offset Render_GetDriverSecondaryMemory
        mov dword ptr [g_Data_004da000 + 0x91c2c], offset Render_GetDriverVideoMemory
        mov dword ptr [g_Data_004da000 + 0x91bfc], offset zVideo_BltRecord0ToRecord1
        mov dword ptr [g_Data_004da000 + 0x91c00], offset zVideo_BltRecord1ToRecord0
        mov dword ptr [g_Data_004da000 + 0x91c04], offset zVideo_BlitImageToBackBufferEx
        mov dword ptr [g_Data_004da000 + 0x91c34], offset Render_DriverIs3DCapable
        mov dword ptr [g_Data_004da000 + 0x91c38], offset Texture_GetDC
        mov dword ptr [g_Data_004da000 + 0x91c3c], offset Texture_ReleaseDC
        mov dword ptr [g_Data_004da000 + 0x91c08], offset D3DTextureBinding_CreateFromImage
        mov dword ptr [g_Data_004da000 + 0x91c0c], offset D3DTextureBinding_GetSize
        mov dword ptr [g_Data_004da000 + 0x91c10], offset D3DTextureBinding_IsReady
        mov dword ptr [g_Data_004da000 + 0x91c14], offset D3DTextureBinding_ReleaseSurface
        mov dword ptr [g_Data_004da000 + 0x91c18], offset D3DTextureBinding_LoadFrom
        mov dword ptr [g_Data_004da000 + 0x91c1c], offset D3DTextureBinding_Free
        mov dword ptr [g_Data_004da000 + 0x91c20], offset Stub_Ret
        mov dword ptr [g_Data_004da000 + 0x91c24], offset Texture_CreateSurface
        mov dword ptr [g_Data_004da000 + 0x91c28], offset Texture_ReleaseSurface
        mov dword ptr [g_Data_004da000 + 0x91c40], offset Render_SetFogEnabled
        mov dword ptr [g_Data_004da000 + 0x91c44], offset Render_SetFogStart
        mov dword ptr [g_Data_004da000 + 0x91c48], offset Render_SetFogEnd
        mov dword ptr [g_Data_004da000 + 0x91c4c], offset Render_SetupFog
        mov dword ptr [g_Data_004da000 + 0x91c50], offset Render_QueuePolygon_Untextured
        mov dword ptr [g_Data_004da000 + 0x91c54], offset Render_QueuePolygon_UntexturedGouraud
        mov dword ptr [g_Data_004da000 + 0x91c58], offset Render_QueuePolygon_UntexturedLit
        mov dword ptr [g_Data_004da000 + 0x91c5c], offset Render_QueuePolygon_SingleTextured
        mov dword ptr [g_Data_004da000 + 0x91c60], offset Render_QueuePolygon_SingleTexturedLit
        mov dword ptr [g_Data_004da000 + 0x91c64], offset Render_QueuePolygon_SingleTexturedLitGradient
        mov dword ptr [g_Data_004da000 + 0x91c68], offset Render_DrawPolygonImmediate
        mov dword ptr [g_Data_004da000 + 0x91c6c], offset Render_FlushSortedDrawQueue
        mov dword ptr [g_Data_004da000 + 0x91c70], offset Render_FlushMainDrawQueue
        mov dword ptr [g_Data_004da000 + 0x91c74], offset Render_FlushQuadDrawQueue
        jz L_4a7983
        mov ecx, dword ptr [eax + 0xa4]
        test ecx, ecx
        jz L_4a7983
        mov dword ptr [eax + 0xa4], 0x0
    L_4a7983:
        pop esi
        ret
    }
}

}  // namespace recoil
