// SUBSYSTEM: input
// input members with no original-file attribution (ledger orig_file empty).
// Instruction-level ports generated by tools/asm_port/port_batch.py from the Ghidra listings.
#include "unattributed/input.h"
#include "platform/image/original_data.h"
#include "GameZRecoil/zInput/zin_kbd.h"
#include "platform/iat_msvcrt.h"
#include "unattributed/ui_widgets.h"
#include "unattributed/menus.h"
#include "GameZRecoil/zInput/zin_init.h"
#include "platform/iat_mfc42.h"
#include "platform/mfc42.h"
#include "platform/msvc_eh.h"
#include "unattributed/sound.h"
#include "GameZRecoil/zNetwork/znet_dplay.h"
#include "platform/dinput_formats.h"
#include "Battlesport/hud.h"
#include "Battlesport/hud_hud.h"
#include "unattributed/player.h"
#include "unattributed/vehicle.h"

namespace recoil {

// 0x0040c190 Array_FillN - ../../04_spec/systems/container.md
// Register/stack shape from the listing (ECX, EDX, 12 stack bytes).
__declspec(naked) int __fastcall Array_FillN(int, int, int, int, int)
{
    __asm {
        mov ecx, dword ptr [esp + 0x8]
        test ecx, ecx
        jbe L_40c1b0
        mov edx, dword ptr [esp + 0xc]
        mov eax, dword ptr [esp + 0x4]
        push esi
    L_40c1a1:
        test eax, eax
        jz L_40c1a9
        mov esi, dword ptr [edx]
        mov dword ptr [eax], esi
    L_40c1a9:
        add eax, 0x4
        dec ecx
        jnz L_40c1a1
        pop esi
    L_40c1b0:
        ret 0xc
    }
}

// 0x0042a480 CommandTable_Count - vector [0x004f3ae4,0x004f3ae8) of pointers; count (0 if null)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall CommandTable_Count(int, int)
{
    __asm {
        mov ecx, dword ptr [g_Data_004da000 + 0x19ae4]
        test ecx, ecx
        jnz L_42a48d
        xor eax, eax
        ret
    L_42a48d:
        mov eax, dword ptr [g_Data_004da000 + 0x19ae8]
        sub eax, ecx
        sar eax, 0x2
        ret
    }
}

// 0x0042a4a0 CommandTable_GetFirstField - returns *(table[ECX]) (first dword of entry)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall CommandTable_GetFirstField(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x19ae4]
        mov eax, dword ptr [eax + ecx*0x4]
        mov eax, dword ptr [eax]
        ret
    }
}

// 0x0042a4b0 CommandTable_EntrySubCount - entry=table[ECX]; count of pointer vector [entry+8,entry+0xC) (0 if null)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall CommandTable_EntrySubCount(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x19ae4]
        mov eax, dword ptr [eax + ecx*0x4]
        mov ecx, dword ptr [eax + 0x8]
        add eax, 0x4
        test ecx, ecx
        jnz L_42a4c5
        xor eax, eax
        ret
    L_42a4c5:
        mov eax, dword ptr [eax + 0x8]
        sub eax, ecx
        sar eax, 0x2
        ret
    }
}

// 0x0042a4d0 CommandTable_EntrySubItem - returns entry(ECX)->[+8][EDX]
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall CommandTable_EntrySubItem(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x19ae4]
        mov eax, dword ptr [eax + ecx*0x4]
        mov ecx, dword ptr [eax + 0x8]
        mov eax, dword ptr [ecx + edx*0x4]
        ret
    }
}

// 0x00471d10 Input_SetJoystickFlag2 - byte [0x00561cb8] |= 2
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_SetJoystickFlag2(int, int)
{
    __asm {
        or byte ptr [g_Data_004da000 + 0x87cb8], 0x2
        ret
    }
}

// 0x00471d80 Joystick_ReleaseCount - word [0x00561cbe] decremented if nonzero; returns it
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Joystick_ReleaseCount(int, int)
{
    __asm {
        mov AX, word ptr [g_Data_004da000 + 0x87cbe]
        test AX, AX
        jbe L_471d93
        dec AX
        mov word ptr [g_Data_004da000 + 0x87cbe], AX
    L_471d93:
        xor ecx, ecx
        mov CX, AX
        mov eax, ecx
        ret
    }
}

// 0x00471dd0 Joystick_GetAcquireCount - returns word [0x00561cbe]
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Joystick_GetAcquireCount(int, int)
{
    __asm {
        xor eax, eax
        mov AX, word ptr [g_Data_004da000 + 0x87cbe]
        ret
    }
}

// 0x004722b0 Joystick_IsPresent - returns [0x00565bcc]==1
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Joystick_IsPresent(int, int)
{
    __asm {
        mov ecx, dword ptr [g_Data_004da000 + 0x8bbcc]
        xor eax, eax
        cmp ecx, 0x1
        setz AL
        ret
    }
}

// 0x00472390 GetGlobalStruct_00565bd4 - Returns address 0x00565bd4.
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall GetGlobalStruct_00565bd4(int, int)
{
    __asm {
        mov eax, offset g_Data_004da000 + 0x8bbd4
        ret
    }
}

// 0x00472480 Input_Joystick_GetField565e18 - return [0x00565e18]
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_Joystick_GetField565e18(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x8be18]
        ret
    }
}

// 0x00472410 Joystick_ResetState - if [0x00565bcc]: zero bytes [0x00565d14+i] and [0x00565c04+i] for i 1..10; set 0xFFFF in dwords [0x00565cc4..] and [0x00565d04..0x00565d14)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Joystick_ResetState(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x8bbcc]
        xor ecx, ecx
        cmp eax, ecx
        jz L_47244e
        mov eax, 0x1
    L_472420:
        mov byte ptr [eax + g_Data_004da000 + 0x8bd14], CL
        mov byte ptr [eax + g_Data_004da000 + 0x8bc04], CL
        inc eax
        cmp eax, 0xb
        jc L_472420
        mov eax, offset g_Data_004da000 + 0x8bd04
        mov ecx, 0xffff
    L_47243c:
        mov dword ptr [eax + 0xfffffef0], ecx
        mov dword ptr [eax], ecx
        add eax, 0x4
        cmp eax, offset g_Data_004da000 + 0x8bd14
        jc L_47243c
    L_47244e:
        ret
    }
}

// 0x004723a0 Input_GetJoystickButtonEdgeState - cur [0x00565c03+ECX], prev [0x00565d13+ECX]: cur -> prev?2(held):1(pressed); !cur -> prev?4(released):0
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_GetJoystickButtonEdgeState(int, int)
{
    __asm {
        mov AL, byte ptr [ecx + g_Data_004da000 + 0x8bc03]
        test AL, AL
        jz L_4723b9
        mov DL, byte ptr [ecx + g_Data_004da000 + 0x8bd13]
        xor eax, eax
        test DL, DL
        setnz AL
        inc eax
        ret
    L_4723b9:
        mov AL, byte ptr [ecx + g_Data_004da000 + 0x8bd13]
        neg AL
        sbb eax, eax
        and eax, 0x4
        ret
    }
}

// 0x004716d0 InputMgr_GetPrimaryKeyBinding - wrapper: push ECX; ECX=[0x00565ea0]; call Input_GetPrimaryKeyBinding; ret
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall InputMgr_GetPrimaryKeyBinding(int, int)
{
    __asm {
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call Input_GetPrimaryKeyBinding
        ret
    }
}

// 0x004716e0 InputMgr_GetSecondaryKeyBinding - wrapper on [0x00565ea0] instance (same shape as 0x004716d0)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall InputMgr_GetSecondaryKeyBinding(int, int)
{
    __asm {
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call Input_GetSecondaryKeyBinding
        ret
    }
}

// 0x004716f0 InputMgr_GetJoystickButtonBinding - wrapper on [0x00565ea0] instance
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall InputMgr_GetJoystickButtonBinding(int, int)
{
    __asm {
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call Input_GetJoystickButtonBinding
        ret
    }
}

// 0x00471700 InputMgr_GetMouseButtonBinding - wrapper on [0x00565ea0] instance
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall InputMgr_GetMouseButtonBinding(int, int)
{
    __asm {
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call Input_GetMouseButtonBinding
        ret
    }
}

// 0x00471710 InputMgr_CommandForPrimaryKey - bytes: push ecx; ecx=[0x00565ea0]; call 0x00470ac0; ret (arg in ECX)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall InputMgr_CommandForPrimaryKey(int, int)
{
    __asm {
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call InputMap_CommandForPrimaryKey
        ret
    }
}

// 0x00471720 InputMgr_CommandForSecondaryKey - bytes: push ecx; ecx=[0x00565ea0]; call 0x00470ad0; ret
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall InputMgr_CommandForSecondaryKey(int, int)
{
    __asm {
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call InputMap_CommandForSecondaryKey
        ret
    }
}

// 0x00471730 InputMgr_CommandForJoystickButton - bytes: push ecx; ecx=[0x00565ea0]; call 0x00470b00; ret. Renamed from InputMgr_CommandForJoystickButton
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall InputMgr_CommandForJoystickButton(int, int)
{
    __asm {
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call InputMap_CommandForJoystickButton
        ret
    }
}

// 0x00471740 InputMgr_CommandForMouseButton - bytes: push ecx; ecx=[0x00565ea0]; call 0x00470b10; ret. Renamed from InputMgr_CommandForMouseButton
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall InputMgr_CommandForMouseButton(int, int)
{
    __asm {
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call InputMap_CommandForMouseButton
        ret
    }
}

// 0x00471750 InputMgr_SetPrimaryKeyBinding - bytes: push edx; push ecx; ecx=[0x00565ea0]; call 0x00470b20 (key ECX, command EDX); ret
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall InputMgr_SetPrimaryKeyBinding(int, int)
{
    __asm {
        push edx
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call InputMap_SetPrimaryKeyBinding
        ret
    }
}

// 0x00471760 InputMgr_SetSecondaryKeyBinding - bytes: push edx; push ecx; ecx=[0x00565ea0]; call 0x00470b80; ret
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall InputMgr_SetSecondaryKeyBinding(int, int)
{
    __asm {
        push edx
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call InputMap_SetSecondaryKeyBinding
        ret
    }
}

// 0x00471770 InputMgr_SetJoystickButtonBinding - bytes: push edx; push ecx; ecx=[0x00565ea0]; call 0x00470bf0; ret. Renamed from InputMgr_SetJoystickButtonBinding (it is a setter)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall InputMgr_SetJoystickButtonBinding(int, int)
{
    __asm {
        push edx
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call InputMap_SetJoystickButtonBinding
        ret
    }
}

// 0x004717e0 InputMgr_Call_00470f50 - push stack arg, EDX, ECX; ECX=[0x00565ea0]; call 0x00470f50; ret 4
// Register/stack shape from the listing (ECX, EDX, 4 stack bytes).
__declspec(naked) int __fastcall InputMgr_Call_00470f50(int, int, int)
{
    __asm {
        mov eax, dword ptr [esp + 0x4]
        push eax
        push edx
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call InputMap_CopyCommandName
        ret 0x4
    }
}

// 0x00471800 InputMgr_Call_00470f80 - wrapper on [0x00565ea0], args ECX,EDX,stack; ret 4
// Register/stack shape from the listing (ECX, EDX, 4 stack bytes).
__declspec(naked) int __fastcall InputMgr_Call_00470f80(int, int, int)
{
    __asm {
        mov eax, dword ptr [esp + 0x4]
        push eax
        push edx
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call Input_FormatKeyName
        ret 0x4
    }
}

// 0x00471820 InputMgr_Call_00471040 - wrapper on [0x00565ea0], args ECX,EDX,stack; ret 4
// Register/stack shape from the listing (ECX, EDX, 4 stack bytes).
__declspec(naked) int __fastcall InputMgr_Call_00471040(int, int, int)
{
    __asm {
        mov eax, dword ptr [esp + 0x4]
        push eax
        push edx
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call Input_CopyKeyName_5662bc
        ret 0x4
    }
}

// 0x00471840 InputMgr_Call_00471070 - wrapper on [0x00565ea0], args ECX,EDX,stack; ret 4
// Register/stack shape from the listing (ECX, EDX, 4 stack bytes).
__declspec(naked) int __fastcall InputMgr_Call_00471070(int, int, int)
{
    __asm {
        mov eax, dword ptr [esp + 0x4]
        push eax
        push edx
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call Input_CopyKeyName_5662fc
        ret 0x4
    }
}

// 0x00471d50 Joystick_AcquireCount - if [0x00561cb9]&1: on 0 -> Joystick_ResetState; increment word [0x00561cbe]; returns it
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Joystick_AcquireCount(int, int)
{
    __asm {
        test byte ptr [g_Data_004da000 + 0x87cb9], 0x1
        jz L_471d6f
        cmp word ptr [g_Data_004da000 + 0x87cbe], 0x0
        jnz L_471d68
        call Joystick_ResetState
    L_471d68:
        inc word ptr [g_Data_004da000 + 0x87cbe]
    L_471d6f:
        xor eax, eax
        mov AX, word ptr [g_Data_004da000 + 0x87cbe]
        ret
    }
}

// 0x00471fb0 Input_Joystick_Acquire - device [0x00565bd0] ? Acquire (vfunc+0x1c)==0 : false
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_Joystick_Acquire(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x8bbd0]
        test eax, eax
        jz L_471fc9
        mov ecx, dword ptr [eax]
        push eax
        call dword ptr [ecx + 0x1c]
        xor edx, edx
        test eax, eax
        setz DL
        mov eax, edx
        ret
    L_471fc9:
        xor eax, eax
        ret
    }
}

// 0x004721a0 Joystick_SetDeadzone - bytes read: DIPROPDWORD {size 0x14, header 0x10, dwObj ECX, dwHow 1 BYOFFSET, dwData EDX}; [0x00565bd0]->SetProperty (slot 0x18) DIPROP_DEADZONE (5); returns HRESULT (PLATFORM)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Joystick_SetDeadzone(int, int)
{
    __asm {
        sub esp, 0x14
        mov eax, dword ptr [g_Data_004da000 + 0x8bbd0]
        mov dword ptr [esp + 0x10], edx
        lea edx, [esp]
        mov dword ptr [esp], 0x14
        mov dword ptr [esp + 0x4], 0x10
        mov dword ptr [esp + 0x8], ecx
        mov dword ptr [esp + 0xc], 0x1
        mov ecx, dword ptr [eax]
        push edx
        push 0x5
        push eax
        call dword ptr [ecx + 0x18]
        add esp, 0x14
        ret
    }
}

// 0x004721e0 Joystick_SetAxisRange - bytes read: DIPROPRANGE {0x18, 0x10, dwObj ECX, BYOFFSET, lMin EDX, lMax stack arg}; SetProperty DIPROP_RANGE (4); ret 4; returns HRESULT
// Register/stack shape from the listing (ECX, EDX, 4 stack bytes).
__declspec(naked) int __fastcall Joystick_SetAxisRange(int, int, int)
{
    __asm {
        sub esp, 0x18
        mov eax, dword ptr [esp + 0x1c]
        mov dword ptr [esp + 0x10], edx
        mov dword ptr [esp + 0x14], eax
        mov eax, dword ptr [g_Data_004da000 + 0x8bbd0]
        lea edx, [esp]
        mov dword ptr [esp], 0x18
        mov dword ptr [esp + 0x4], 0x10
        mov dword ptr [esp + 0x8], ecx
        mov dword ptr [esp + 0xc], 0x1
        mov ecx, dword ptr [eax]
        push edx
        push 0x4
        push eax
        call dword ptr [ecx + 0x18]
        add esp, 0x18
        ret 0x4
    }
}

// 0x00472230 Joystick_GetAxisRange - bytes read: DIPROPRANGE header as SetAxisRange, obj ECX; GetProperty (slot 0x14) DIPROP_RANGE; writes lMin to [EDX], lMax to [stack arg]; result not checked before copying; ret 4
// Register/stack shape from the listing (ECX, EDX, 4 stack bytes).
__declspec(naked) int __fastcall Joystick_GetAxisRange(int, int, int)
{
    __asm {
        sub esp, 0x18
        mov eax, dword ptr [g_Data_004da000 + 0x8bbd0]
        push esi
        mov esi, edx
        mov dword ptr [esp + 0x4], 0x18
        lea edx, [esp + 0x4]
        mov dword ptr [esp + 0x8], 0x10
        mov dword ptr [esp + 0xc], ecx
        mov dword ptr [esp + 0x10], 0x1
        mov ecx, dword ptr [eax]
        push edx
        push 0x4
        push eax
        call dword ptr [ecx + 0x14]
        mov ecx, dword ptr [esp + 0x14]
        mov edx, dword ptr [esp + 0x20]
        mov dword ptr [esi], ecx
        mov ecx, dword ptr [esp + 0x18]
        mov dword ptr [edx], ecx
        pop esi
        add esp, 0x18
        ret 0x4
    }
}

// 0x00472280 Input_Joystick_ShutdownDevice - if joystick [0x00565bd0]: Unacquire, Release, clear; return 1
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_Joystick_ShutdownDevice(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x8bbd0]
        test eax, eax
        jz L_4722a4
        mov ecx, dword ptr [eax]
        push eax
        call dword ptr [ecx + 0x20]
        mov eax, dword ptr [g_Data_004da000 + 0x8bbd0]
        push eax
        mov edx, dword ptr [eax]
        call dword ptr [edx + 0x8]
        mov dword ptr [g_Data_004da000 + 0x8bbd0], 0x0
    L_4722a4:
        mov eax, 0x1
        ret
    }
}

// 0x00472450 Input_Joystick_AcquireOk - bytes: dev 0x00565bd0 null -> 0; hr=dev vtbl+0x48 (Poll/Acquire); return EDX if hr>=0 else 0; 3 callers
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_Joystick_AcquireOk(int, int)
{
    __asm {
        push ecx
        mov eax, dword ptr [g_Data_004da000 + 0x8bbd0]
        test eax, eax
        jnz L_47245c
        pop ecx
        ret
    L_47245c:
        push edi
        push esi
        mov esi, dword ptr [eax]
        lea edi, [esp + 0x8]
        push 0x0
        push edi
        push edx
        push ecx
        push eax
        call dword ptr [esi + 0x48]
        xor ecx, ecx
        test eax, eax
        mov eax, dword ptr [esp + 0x8]
        pop esi
        setl CL
        dec ecx
        pop edi
        and eax, ecx
        pop ecx
        ret
    }
}

// 0x00472490 DInput_ReportError - ECX HRESULT: 0 -> return 1; else maps DIERR_* codes to name strings (unknown -> 'Unknown Error'), sprintf into 256-byte local (no args), 0x00404e80(0x800); return 0
// Register/stack shape from the listing (ECX, EDX, 4 stack bytes).
__declspec(naked) int __fastcall DInput_ReportError(int, int, int)
{
    __asm {
        sub esp, 0x100
        cmp ecx, 0x80040110
        push esi
        mov esi, edx
        jg L_4724f6
        jz L_4724e7
        cmp ecx, 0x80004001
        jz L_4724dd
        cmp ecx, 0x80004002
        jz L_4724ce
        cmp ecx, 0x80004005
        jnz L_47260b
        lea eax, [esp + 0x4]
        push offset g_Data_004da000 + 0x6e34
        push eax
        jmp L_472630
    L_4724ce:
        lea ecx, [esp + 0x4]
        push offset g_Data_004da000 + 0x6e20
        push ecx
        jmp L_472630
    L_4724dd:
        push offset g_Data_004da000 + 0x6e0c
        jmp L_47262b
    L_4724e7:
        lea eax, [esp + 0x4]
        push offset g_Data_004da000 + 0x6df8
        push eax
        jmp L_472630
    L_4724f6:
        cmp ecx, 0x80070002
        jg L_472525
        jz L_47251b
        cmp ecx, 0x80040154
        jnz L_47260b
        lea ecx, [esp + 0x4]
        push offset g_Data_004da000 + 0x6de4
        push ecx
        jmp L_472630
    L_47251b:
        push offset g_Data_004da000 + 0x6dcc
        jmp L_47262b
    L_472525:
        cmp ecx, 0x8007000c
        jg L_472559
        jz L_47254a
        cmp ecx, 0x80070005
        jnz L_47260b
        lea eax, [esp + 0x4]
        push offset g_Data_004da000 + 0x6dbc
        push eax
        jmp L_472630
    L_47254a:
        lea ecx, [esp + 0x4]
        push offset g_Data_004da000 + 0x6da8
        push ecx
        jmp L_472630
    L_472559:
        cmp ecx, 0x80070015
        jg L_472588
        jz L_472579
        cmp ecx, 0x8007000e
        jnz L_47260b
        push offset g_Data_004da000 + 0x6d94
        jmp L_47262b
    L_472579:
        lea eax, [esp + 0x4]
        push offset g_Data_004da000 + 0x6d7c
        push eax
        jmp L_472630
    L_472588:
        cmp ecx, 0x80070057
        jg L_4725b0
        jz L_4725a9
        cmp ecx, 0x8007001e
        jnz L_47260b
        lea ecx, [esp + 0x4]
        push offset g_Data_004da000 + 0x6d6c
        push ecx
        jmp L_472630
    L_4725a9:
        push offset g_Data_004da000 + 0x6d58
        jmp L_47262b
    L_4725b0:
        cmp ecx, 0x800700aa
        jg L_4725da
        jz L_4725ce
        cmp ecx, 0x80070077
        jnz L_47260b
        lea eax, [esp + 0x4]
        push offset g_Data_004da000 + 0x6d44
        push eax
        jmp L_472630
    L_4725ce:
        lea ecx, [esp + 0x4]
        push offset g_Data_004da000 + 0x6d34
        push ecx
        jmp L_472630
    L_4725da:
        cmp ecx, 0x80070481
        jg L_4725ff
        jz L_4725f3
        cmp ecx, 0x8007047e
        jnz L_47260b
        push offset g_Data_004da000 + 0x6d18
        jmp L_47262b
    L_4725f3:
        lea eax, [esp + 0x4]
        push offset g_Data_004da000 + 0x6cf8
        push eax
        jmp L_472630
    L_4725ff:
        cmp ecx, 0x800704df
        jz L_472626
        test ecx, ecx
        jz L_472617
    L_47260b:
        lea ecx, [esp + 0x4]
        push offset g_Data_004da000 + 0x2aac
        push ecx
        jmp L_472630
    L_472617:
        mov eax, 0x1
        pop esi
        add esp, 0x100
        ret 0x4
    L_472626:
        push offset g_Data_004da000 + 0x6cdc
    L_47262b:
        lea edx, [esp + 0x8]
        push edx
    L_472630:
        call dword ptr [g_Iat_sprintf_004cc5c4]
        mov ecx, dword ptr [esp + 0x110]
        add esp, 0x8
        lea eax, [esp + 0x4]
        push eax
        push offset g_Data_004da000 + 0x6cc4
        push ecx
        push esi
        push 0x800
        call Debug_ReportNoop
        add esp, 0x14
        xor eax, eax
        pop esi
        add esp, 0x100
        ret 0x4
    }
}

// 0x00430070 ForceFeedback_CreateConstantEffect - DIEFFECT (size 0x34, flags 0x22, duration 10000, 1 axis, zero magnitude) -> 0x00472450
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ForceFeedback_CreateConstantEffect(int, int)
{
    __asm {
        sub esp, 0x48
        mov dword ptr [esp + 0xc], ecx
        or ecx, 0xffffffff
        mov dword ptr [esp + 0x1c], ecx
        mov dword ptr [esp + 0x28], ecx
        mov edx, 0x4
        lea ecx, [esp + 0x4]
        mov dword ptr [esp + 0x8], edx
        mov dword ptr [esp + 0x34], ecx
        mov dword ptr [esp + 0x40], edx
        lea ecx, [esp + 0xc]
        lea edx, [esp]
        xor eax, eax
        mov dword ptr [esp + 0x38], ecx
        mov dword ptr [esp + 0x44], edx
        lea edx, [esp + 0x14]
        mov ecx, offset g_RData_004cc000 + 0x6850
        mov dword ptr [esp + 0x4], eax
        mov dword ptr [esp + 0x10], eax
        mov dword ptr [esp], 0x2710
        mov dword ptr [esp + 0x14], 0x34
        mov dword ptr [esp + 0x18], 0x22
        mov dword ptr [esp + 0x20], eax
        mov dword ptr [esp + 0x24], eax
        mov dword ptr [esp + 0x2c], eax
        mov dword ptr [esp + 0x30], 0x2
        mov dword ptr [esp + 0x3c], eax
        call Input_Joystick_AcquireOk
        add esp, 0x48
        ret
    }
}

// 0x00471790 InputMgr_Call_00470cd0 - wrapper on [0x00565ea0], args ECX,EDX + 4 stack
// Register/stack shape from the listing (ECX, EDX, 16 stack bytes).
__declspec(naked) int __fastcall InputMgr_Call_00470cd0(int, int, int, int, int, int)
{
    __asm {
        mov eax, dword ptr [esp + 0x10]
        push esi
        mov esi, ecx
        push eax
        mov ecx, dword ptr [esp + 0x14]
        mov eax, dword ptr [esp + 0x10]
        push ecx
        mov ecx, dword ptr [esp + 0x10]
        push eax
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        push edx
        push esi
        call InputMap_SetCommand
        mov eax, esi
        pop esi
        ret 0x10
    }
}

// 0x004717d0 Input_QueryAction - Pushes action id (ECX) and calls Input_QueryActionState with ECX=[0x00565ea0] (input table).
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_QueryAction(int, int)
{
    __asm {
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call Input_QueryActionState
        ret
    }
}

// 0x00471fd0 Joystick_ApplyAxisRanges - ECX = 20-dword range block (null -> false). Per axis (min,max at +0/+4, +0x14/+0x18, then +0x28/+0x2C if [0x00565e14]>2, +0x3C/+0x40 if >3): 0x004721e0 set range, on failure 0x00472230 reads back; centre float = (min+max)*0.5 [0x004d2910], scale float = 2.0 [0x004d2914] / (max-min) (FSTP float, byte
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Joystick_ApplyAxisRanges(int, int)
{
    __asm {
        push ecx
        push esi
        mov esi, ecx
        test esi, esi
        jnz L_471fdd
        xor eax, eax
        pop esi
        pop ecx
        ret
    L_471fdd:
        mov eax, dword ptr [esi + 0x4]
        mov edx, dword ptr [esi]
        push edi
        lea edi, [esi + 0x4]
        push ebp
        push ebx
        push eax
        xor ecx, ecx
        call Joystick_SetAxisRange
        test eax, eax
        jge L_471ffe
        push edi
        mov edx, esi
        xor ecx, ecx
        call Joystick_GetAxisRange
    L_471ffe:
        mov eax, dword ptr [edi]
        mov ecx, dword ptr [esi]
        lea edx, [ecx + eax*0x1]
        sub eax, ecx
        mov dword ptr [esp + 0x10], edx
        mov edx, dword ptr [esi + 0x10]
        fild dword ptr [esp + 0x10]
        mov dword ptr [esp + 0x10], eax
        xor ecx, ecx
        fmul dword ptr [g_RData_004cc000 + 0x6910]
        fstp dword ptr [esi + 0xc]
        fild dword ptr [esp + 0x10]
        fdivr dword ptr [g_RData_004cc000 + 0x6914]
        fstp dword ptr [esi + 0x8]
        call Joystick_SetDeadzone
        mov edx, dword ptr [esi + 0x18]
        xor ecx, ecx
        test eax, eax
        lea edi, [esi + 0x18]
        lea ebx, [esi + 0x14]
        setge CL
        and ecx, 0x1
        push edx
        mov edx, dword ptr [ebx]
        mov ebp, ecx
        mov ecx, 0x4
        call Joystick_SetAxisRange
        test eax, eax
        jge L_472066
        push edi
        mov edx, ebx
        mov ecx, 0x4
        call Joystick_GetAxisRange
    L_472066:
        mov ebx, dword ptr [ebx]
        mov eax, dword ptr [edi]
        mov edx, dword ptr [esi + 0x24]
        lea ecx, [ebx + eax*0x1]
        sub eax, ebx
        mov dword ptr [esp + 0x10], ecx
        mov ecx, 0x4
        fild dword ptr [esp + 0x10]
        mov dword ptr [esp + 0x10], eax
        fmul dword ptr [g_RData_004cc000 + 0x6910]
        fstp dword ptr [esi + 0x20]
        fild dword ptr [esp + 0x10]
        fdivr dword ptr [g_RData_004cc000 + 0x6914]
        fstp dword ptr [esi + 0x1c]
        call Joystick_SetDeadzone
        xor edx, edx
        test eax, eax
        mov eax, dword ptr [g_Data_004da000 + 0x8be14]
        setge DL
        and ebp, edx
        cmp eax, 0x2
        jle L_47211a
        mov eax, dword ptr [esi + 0x2c]
        mov edx, dword ptr [esi + 0x28]
        lea edi, [esi + 0x2c]
        lea ebx, [esi + 0x28]
        push eax
        mov ecx, 0x8
        call Joystick_SetAxisRange
        test eax, eax
        jge L_4720d9
        push edi
        mov edx, ebx
        mov ecx, 0x8
        call Joystick_GetAxisRange
    L_4720d9:
        mov ecx, dword ptr [ebx]
        mov eax, dword ptr [edi]
        lea edx, [ecx + eax*0x1]
        sub eax, ecx
        mov dword ptr [esp + 0x10], edx
        mov edx, dword ptr [esi + 0x38]
        fild dword ptr [esp + 0x10]
        mov dword ptr [esp + 0x10], eax
        mov ecx, 0x8
        fmul dword ptr [g_RData_004cc000 + 0x6910]
        fstp dword ptr [esi + 0x34]
        fild dword ptr [esp + 0x10]
        fdivr dword ptr [g_RData_004cc000 + 0x6914]
        fstp dword ptr [esi + 0x30]
        call Joystick_SetDeadzone
        xor ecx, ecx
        test eax, eax
        setge CL
        and ebp, ecx
    L_47211a:
        cmp dword ptr [g_Data_004da000 + 0x8be14], 0x3
        jle L_47218b
        mov edx, dword ptr [esi + 0x40]
        lea edi, [esi + 0x40]
        lea ebx, [esi + 0x3c]
        push edx
        mov ecx, 0x14
        mov edx, dword ptr [ebx]
        call Joystick_SetAxisRange
        test eax, eax
        jge L_47214a
        push edi
        mov edx, ebx
        mov ecx, 0x14
        call Joystick_GetAxisRange
    L_47214a:
        mov eax, dword ptr [edi]
        mov ebx, dword ptr [ebx]
        mov edx, dword ptr [esi + 0x4c]
        lea ecx, [ebx + eax*0x1]
        sub eax, ebx
        mov dword ptr [esp + 0x10], ecx
        mov ecx, 0x14
        fild dword ptr [esp + 0x10]
        mov dword ptr [esp + 0x10], eax
        fmul dword ptr [g_RData_004cc000 + 0x6910]
        fstp dword ptr [esi + 0x48]
        fild dword ptr [esp + 0x10]
        fdivr dword ptr [g_RData_004cc000 + 0x6914]
        fstp dword ptr [esi + 0x44]
        call Joystick_SetDeadzone
        xor edx, edx
        test eax, eax
        setge DL
        and ebp, edx
    L_47218b:
        mov ecx, 0x14
        mov edi, offset g_Data_004da000 + 0x8be24
        rep movsd
        mov eax, ebp
        pop ebx
        pop ebp
        pop edi
        pop esi
        pop ecx
        ret
    }
}

// 0x0042e170 Joystick_EnableAndSetRanges - ECX!=0 and 0x004722b0 ok: if 0x00471dd0()==0 call 0x00471d50; set axis ranges [0x004f3350..0x004f339c] (+-1000 for three axes, -10000/10000, 2000, 3000, 1500, 2000); call 0x00471fd0; return 1. Else if 0x00471dd0() call 0x00471d80; return 0
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Joystick_EnableAndSetRanges(int, int)
{
    __asm {
        push esi
        xor esi, esi
        test ecx, ecx
        jz L_42e20b
        call Joystick_IsPresent
        test eax, eax
        jz L_42e20b
        call Joystick_GetAcquireCount
        test eax, eax
        jnz L_42e196
        call Joystick_AcquireCount
    L_42e196:
        mov eax, 0x3e8
        mov ecx, 0xfffffc18
        mov dword ptr [g_Data_004da000 + 0x19354], eax
        mov dword ptr [g_Data_004da000 + 0x1937c], eax
        mov dword ptr [g_Data_004da000 + 0x19390], eax
        mov dword ptr [g_Data_004da000 + 0x19350], ecx
        mov dword ptr [g_Data_004da000 + 0x19378], ecx
        mov dword ptr [g_Data_004da000 + 0x1938c], ecx
        mov eax, 0x7d0
        mov ecx, offset g_Data_004da000 + 0x19350
        mov dword ptr [g_Data_004da000 + 0x19364], 0xffffd8f0
        mov dword ptr [g_Data_004da000 + 0x19368], 0x2710
        mov dword ptr [g_Data_004da000 + 0x19360], eax
        mov dword ptr [g_Data_004da000 + 0x19374], 0xbb8
        mov dword ptr [g_Data_004da000 + 0x19388], 0x5dc
        mov dword ptr [g_Data_004da000 + 0x1939c], eax
        call Joystick_ApplyAxisRanges
        mov esi, 0x1
        mov eax, esi
        pop esi
        ret
    L_42e20b:
        call Joystick_GetAcquireCount
        test eax, eax
        jz L_42e219
        call Joystick_ReleaseCount
    L_42e219:
        mov eax, esi
        pop esi
        ret
    }
}

// 0x004722c0 Input_Joystick_Poll - if [0x00565bcc]==0 return 0; Poll (vtbl+0x64), GetDeviceState(0x110 bytes -> 0x00566310); zero axes 3 / 4 if axis count [0x00565e14]<3/<4; INPUTLOST -> 0x00471fb0 return 0; error -> 0; prev 0x00565ce4 = cur 0x00565bd4, cur = new (0x44 dwords); if CL: 0x00470db0; return 0x00472390()
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_Joystick_Poll(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x8bbcc]
        push ebx
        push esi
        push edi
        xor edi, edi
        mov BL, CL
        cmp eax, edi
        jnz L_4722d6
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_4722d6:
        mov esi, dword ptr [g_Data_004da000 + 0x8bbd0]
        push esi
        mov eax, dword ptr [esi]
        call dword ptr [eax + 0x64]
        mov ecx, dword ptr [esi]
        push offset g_Data_004da000 + 0x8c310
        push 0x110
        push esi
        call dword ptr [ecx + 0x24]
        mov ecx, dword ptr [g_Data_004da000 + 0x8be14]
        cmp ecx, 0x3
        jge L_472315
        mov dword ptr [g_Data_004da000 + 0x8c408], edi
        mov dword ptr [g_Data_004da000 + 0x8c3e8], edi
        mov dword ptr [g_Data_004da000 + 0x8c3c8], edi
        mov dword ptr [g_Data_004da000 + 0x8c318], edi
    L_472315:
        cmp ecx, 0x4
        jge L_472332
        mov dword ptr [g_Data_004da000 + 0x8c414], edi
        mov dword ptr [g_Data_004da000 + 0x8c3f4], edi
        mov dword ptr [g_Data_004da000 + 0x8c3d4], edi
        mov dword ptr [g_Data_004da000 + 0x8c324], edi
    L_472332:
        cmp eax, 0x8007001e
        jnz L_472344
        call Input_Joystick_Acquire
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_472344:
        cmp eax, edi
        jz L_47234e
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    L_47234e:
        mov ecx, 0x44
        mov esi, offset g_Data_004da000 + 0x8bbd4
        mov edi, offset g_Data_004da000 + 0x8bce4
        rep movsd
        mov ecx, 0x44
        mov esi, offset g_Data_004da000 + 0x8c310
        mov edi, offset g_Data_004da000 + 0x8bbd4
        test BL, BL
        rep movsd
        jz L_47237f
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call Input_Joystick_DispatchButtonHandlers
    L_47237f:
        call GetGlobalStruct_00565bd4
        pop edi
        pop esi
        pop ebx
        ret
    }
}

// 0x004723d0 Input_WaitJoystickButton - bytes: loop Input_Joystick_Poll; buttons 1.. Input_GetJoystickButtonEdgeState==1 -> return index; Joystick_ResetState; caller 0x0040b2e7
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_WaitJoystickButton(int, int)
{
    __asm {
        push ebx
        push esi
        push edi
        mov ebx, ecx
        xor edi, edi
    L_4723d7:
        mov CL, 0x1
        call Input_Joystick_Poll
        mov esi, 0x1
    L_4723e3:
        mov ecx, esi
        call Input_GetJoystickButtonEdgeState
        cmp eax, 0x1
        jz L_4723f7
        inc esi
        cmp esi, 0xb
        jl L_4723e3
        jmp L_4723f9
    L_4723f7:
        mov edi, esi
    L_4723f9:
        call Joystick_ResetState
        test edi, edi
        jnz L_472406
        test ebx, ebx
        jnz L_4723d7
    L_472406:
        mov eax, edi
        pop edi
        pop esi
        pop ebx
        ret
    }
}

// 0x0042a4e0 CommandSlot_Call_004a5bf0 - ECX=[0x004f3af0+ECX*4]; jmp 0x004a5bf0
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall CommandSlot_Call_004a5bf0(int, int)
{
    __asm {
        mov ecx, dword ptr [ecx*0x4 + g_Data_004da000 + 0x19af0]
        jmp Message_GetText
    }
}

// 0x0042a4f0 CommandSlot_Call_004a5bf0_Plus1 - ECX=[0x004f3af0+ECX*4]+1; jmp 0x004a5bf0
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall CommandSlot_Call_004a5bf0_Plus1(int, int)
{
    __asm {
        mov ecx, dword ptr [ecx*0x4 + g_Data_004da000 + 0x19af0]
        inc ecx
        jmp Message_GetText
    }
}

// 0x0042fa80 ForceFeedback_IsAvailable - Returns 1 when 0x004083c0() and 0x00472480() are both non-zero, else 0. (Name INFERRED from caller use in Vehicle_ResolveSurfaceHit: followed by 0x0042fb50 with the hit normal and a 0..1 strength.)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ForceFeedback_IsAvailable(int, int)
{
    __asm {
        call Setting_Get_004e5d60
        test eax, eax
        jz L_42fa98
        call Input_Joystick_GetField565e18
        test eax, eax
        jz L_42fa98
        mov eax, 0x1
        ret
    L_42fa98:
        xor eax, eax
        ret
    }
}

// 0x0042fac0 ForceFeedback_PlayConstant - (mag) ret 4: effect [ECX+4]: Stop (vfunc+0x20); params (13 dwords zeroed) magnitude=ftol(mag); SetParameters (vfunc+0x18, flags 4); Start (vfunc+0x1c,1,0)
// Register/stack shape from the listing (ECX, EDX, 4 stack bytes).
__declspec(naked) int __fastcall ForceFeedback_PlayConstant(int, int, int)
{
    __asm {
        sub esp, 0x34
        push esi
        mov esi, ecx
        mov edx, dword ptr [esi + 0x4]
        test edx, edx
        jz L_42fb46
        push edi
        mov ecx, 0xd
        xor eax, eax
        lea edi, [esp + 0x8]
        rep stosd
        mov eax, dword ptr [edx]
        push edx
        call dword ptr [eax + 0x20]
        fld dword ptr [esp + 0x40]
        fcom dword ptr [g_RData_004cc000 + 0x4bb8]
        fnstsw AX
        test AH, 0x41
        jnz L_42fafc
        fstp st(0)
        fld dword ptr [g_RData_004cc000 + 0x4bb8]
        jmp L_42fb11
    L_42fafc:
        fcom dword ptr [g_RData_004cc000 + 0x4bbc]
        fnstsw AX
        test AH, 0x1
        jz L_42fb11
        fstp st(0)
        fld dword ptr [g_RData_004cc000 + 0x4bbc]
    L_42fb11:
        fmul dword ptr [g_RData_004cc000 + 0x4bc0]
        mov dword ptr [esp + 0x8], 0x34
        call dword ptr [g_Iat__ftol_004cc5ac]
        mov dword ptr [esp + 0x18], eax
        mov eax, dword ptr [esi + 0x4]
        lea edx, [esp + 0x8]
        push 0x4
        mov ecx, dword ptr [eax]
        push edx
        push eax
        call dword ptr [ecx + 0x18]
        mov esi, dword ptr [esi + 0x4]
        push 0x0
        push 0x1
        push esi
        mov eax, dword ptr [esi]
        call dword ptr [eax + 0x1c]
        pop edi
    L_42fb46:
        pop esi
        add esp, 0x34
        ret 0x4
    }
}

// 0x0042fb50 ForceFeedback_PlayDirectional - If effect object +0xc exists: vtable+0x20 (stop); computes direction = atan2 of the arg vector (-x, -z) minus atan2 of the local player facing ([[0x004f3a88]+4]+0x520/+0x528) (two fpatan), converts to integer; fills a 0x34-byte parameter block (size 0x34, flags 0x20, 2 axes, direction, magnitude fro
// Register/stack shape from the listing (ECX, EDX, 8 stack bytes).
__declspec(naked) int __fastcall ForceFeedback_PlayDirectional(int, int, int, int)
{
    __asm {
        sub esp, 0x3c
        push esi
        mov esi, ecx
        mov eax, dword ptr [esi + 0xc]
        test eax, eax
        jz L_42fc80
        mov ecx, dword ptr [eax]
        push edi
        push eax
        call dword ptr [ecx + 0x20]
        mov ecx, dword ptr [esp + 0x48]
        mov edx, dword ptr [g_Data_004da000 + 0x19a88]
        fld dword ptr [ecx]
        mov eax, dword ptr [edx + 0x4]
        fld dword ptr [ecx + 0x8]
        fld dword ptr [eax + 0x520]
        fld dword ptr [eax + 0x528]
        fxch st(3)
        fchs
        fxch st(2)
        fchs
        fxch st(1)
        fchs
        fxch st(3)
        fchs
        fxch st(2)
        fxch st(1)
        fpatan
        fxch st(2)
        fxch st(1)
        fpatan
        fst dword ptr [esp + 0x48]
        fsubp st(1), st(0)
        fsubr dword ptr [g_RData_004cc000 + 0x4bc4]
        fcom dword ptr [g_RData_004cc000 + 0x4bc8]
        fnstsw AX
        test AH, 0x1
        jz L_42fbc3
        fsub dword ptr [g_RData_004cc000 + 0x4bc8]
        jmp L_42fbd6
    L_42fbc3:
        fcom dword ptr [g_RData_004cc000 + 0x4bcc]
        fnstsw AX
        test AH, 0x41
        jnz L_42fbd6
        fsub dword ptr [g_RData_004cc000 + 0x4bcc]
    L_42fbd6:
        fmul qword ptr [g_RData_004cc000 + 0x4bd0]
        call dword ptr [g_Iat__ftol_004cc5ac]
        fld dword ptr [esp + 0x4c]
        fcom dword ptr [g_RData_004cc000 + 0x4bb8]
        lea eax, [eax + eax*0x4]
        mov ecx, 0xd
        lea edi, [esp + 0x10]
        mov dword ptr [esp + 0xc], 0x0
        lea eax, [eax + eax*0x4]
        shl eax, 0x2
        mov dword ptr [esp + 0x8], eax
        xor eax, eax
        rep stosd
        fnstsw AX
        test AH, 0x41
        jnz L_42fc1e
        fstp st(0)
        fld dword ptr [g_RData_004cc000 + 0x4bb8]
        jmp L_42fc33
    L_42fc1e:
        fcom dword ptr [g_RData_004cc000 + 0x4bd8]
        fnstsw AX
        test AH, 0x1
        jz L_42fc33
        fstp st(0)
        fld dword ptr [g_RData_004cc000 + 0x4bd8]
    L_42fc33:
        fmul dword ptr [g_RData_004cc000 + 0x4bc0]
        mov dword ptr [esp + 0x10], 0x34
        call dword ptr [g_Iat__ftol_004cc5ac]
        lea ecx, [esp + 0x8]
        mov dword ptr [esp + 0x20], eax
        mov eax, dword ptr [esi + 0xc]
        mov dword ptr [esp + 0x34], ecx
        lea ecx, [esp + 0x10]
        mov dword ptr [esp + 0x14], 0x20
        mov dword ptr [esp + 0x2c], 0x2
        mov edx, dword ptr [eax]
        push 0x44
        push ecx
        push eax
        call dword ptr [edx + 0x18]
        mov eax, dword ptr [esi + 0xc]
        push 0x0
        push 0x1
        push eax
        mov edx, dword ptr [eax]
        call dword ptr [edx + 0x1c]
        pop edi
    L_42fc80:
        pop esi
        add esp, 0x3c
        ret 0x8
    }
}

// 0x0042fc90 ForceFeedback_PlayHitDirectional - (dir,mag) ret 8: effect [ECX+0x10]: Stop (vfunc+0x20); a_cam = atan2(-cam fwd x +0x520, -cam fwd z +0x528) of player; a_hit = fpatan(dir.x, dir.z); angle = pi - (a_hit - a_cam) wrapped: <-2pi +2pi? (if < -6.283185 subtract -2pi, if > 6.283185 subtract 2pi); direction = ftol(angle * 57.29577951308 [d
// Register/stack shape from the listing (ECX, EDX, 8 stack bytes).
__declspec(naked) int __fastcall ForceFeedback_PlayHitDirectional(int, int, int, int)
{
    __asm {
        sub esp, 0x3c
        push esi
        mov esi, ecx
        mov eax, dword ptr [esi + 0x10]
        test eax, eax
        jz L_42fdb4
        mov ecx, dword ptr [eax]
        push edi
        push eax
        call dword ptr [ecx + 0x20]
        mov edx, dword ptr [g_Data_004da000 + 0x19a88]
        mov eax, dword ptr [edx + 0x4]
        fld dword ptr [eax + 0x520]
        fld dword ptr [eax + 0x528]
        mov eax, dword ptr [esp + 0x48]
        fld dword ptr [eax]
        fld dword ptr [eax + 0x8]
        fxch st(3)
        fchs
        fxch st(2)
        fchs
        fxch st(3)
        fpatan
        fxch st(2)
        fpatan
        fst dword ptr [esp + 0x48]
        fsubp st(1), st(0)
        fsubr dword ptr [g_RData_004cc000 + 0x4bc4]
        fcom dword ptr [g_RData_004cc000 + 0x4bc8]
        fnstsw AX
        test AH, 0x1
        jz L_42fcf7
        fsub dword ptr [g_RData_004cc000 + 0x4bc8]
        jmp L_42fd0a
    L_42fcf7:
        fcom dword ptr [g_RData_004cc000 + 0x4bcc]
        fnstsw AX
        test AH, 0x41
        jnz L_42fd0a
        fsub dword ptr [g_RData_004cc000 + 0x4bcc]
    L_42fd0a:
        fmul qword ptr [g_RData_004cc000 + 0x4bd0]
        call dword ptr [g_Iat__ftol_004cc5ac]
        fld dword ptr [esp + 0x4c]
        fcom dword ptr [g_RData_004cc000 + 0x4bb8]
        lea eax, [eax + eax*0x4]
        mov ecx, 0xd
        lea edi, [esp + 0x10]
        mov dword ptr [esp + 0xc], 0x0
        lea eax, [eax + eax*0x4]
        shl eax, 0x2
        mov dword ptr [esp + 0x8], eax
        xor eax, eax
        rep stosd
        fnstsw AX
        test AH, 0x41
        jnz L_42fd52
        fstp st(0)
        fld dword ptr [g_RData_004cc000 + 0x4bb8]
        jmp L_42fd67
    L_42fd52:
        fcom dword ptr [g_RData_004cc000 + 0x4bbc]
        fnstsw AX
        test AH, 0x1
        jz L_42fd67
        fstp st(0)
        fld dword ptr [g_RData_004cc000 + 0x4bbc]
    L_42fd67:
        fmul dword ptr [g_RData_004cc000 + 0x4bc0]
        mov dword ptr [esp + 0x10], 0x34
        call dword ptr [g_Iat__ftol_004cc5ac]
        lea ecx, [esp + 0x8]
        mov dword ptr [esp + 0x20], eax
        mov eax, dword ptr [esi + 0x10]
        mov dword ptr [esp + 0x34], ecx
        lea ecx, [esp + 0x10]
        mov dword ptr [esp + 0x14], 0x20
        mov dword ptr [esp + 0x2c], 0x2
        mov edx, dword ptr [eax]
        push 0x44
        push ecx
        push eax
        call dword ptr [edx + 0x18]
        mov eax, dword ptr [esi + 0x10]
        push 0x0
        push 0x1
        push eax
        mov edx, dword ptr [eax]
        call dword ptr [edx + 0x1c]
        pop edi
    L_42fdb4:
        pop esi
        add esp, 0x3c
        ret 0x8
    }
}

// 0x0042fdc0 ForceFeedback_UpdateEffects - effect 1 [ECX+0x14]: direction 27000 if player +0x94/+0xcc >= 0 else 90; DIEFFECT (0x34 size, flags 0x20, 2 axes) SetParameters (vfunc+0x18, 0x44) and Start (vfunc+0x1c,1,0). effect 2 [ECX+0x18]: smoothed yaw [0x004f3ee8] (exp trick) vs player +0x3bc: direction 18000 if (yaw-smooth)*8>=0 else 0; sam
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ForceFeedback_UpdateEffects(int, int)
{
    __asm {
        push ebp
        mov ebp, esp
        sub esp, 0x44
        mov eax, dword ptr [g_Data_004da000 + 0x19a88]
        push ebx
        push esi
        mov esi, ecx
        push edi
        mov edi, dword ptr [eax + 0x4]
        mov ebx, dword ptr [esi + 0x14]
        xor eax, eax
        cmp ebx, eax
        mov dword ptr [ebp - 0x4], edi
        mov dword ptr [ebp - 0x10], eax
        mov dword ptr [ebp - 0xc], eax
        jz L_42fe90
        fld dword ptr [edi + 0x94]
        fdiv dword ptr [edi + 0xcc]
        fcom dword ptr [g_RData_004cc000 + 0x4bdc]
        fnstsw AX
        test AH, 0x1
        jz L_42fe0b
        mov eax, 0x5a
        fchs
        jmp L_42fe10
    L_42fe0b:
        mov eax, 0x6978
    L_42fe10:
        fcom dword ptr [g_RData_004cc000 + 0x4be0]
        mov dword ptr [ebp - 0x10], eax
        mov ecx, 0xd
        xor eax, eax
        lea edi, [ebp - 0x44]
        rep stosd
        fnstsw AX
        test AH, 0x41
        jnz L_42fe36
        fstp st(0)
        fld dword ptr [g_RData_004cc000 + 0x4be0]
        jmp L_42fe4b
    L_42fe36:
        fcom dword ptr [g_RData_004cc000 + 0x4bdc]
        fnstsw AX
        test AH, 0x1
        jz L_42fe4b
        fstp st(0)
        fld dword ptr [g_RData_004cc000 + 0x4bdc]
    L_42fe4b:
        fmul dword ptr [g_RData_004cc000 + 0x4bc0]
        mov dword ptr [ebp - 0x44], 0x34
        call dword ptr [g_Iat__ftol_004cc5ac]
        mov dword ptr [ebp - 0x34], eax
        lea ecx, [ebp - 0x10]
        lea eax, [ebp - 0x44]
        mov dword ptr [ebp - 0x40], 0x20
        mov dword ptr [ebp - 0x28], 0x2
        mov dword ptr [ebp - 0x20], ecx
        mov edx, dword ptr [ebx]
        push 0x44
        push eax
        push ebx
        call dword ptr [edx + 0x18]
        mov eax, dword ptr [esi + 0x14]
        push 0x0
        push 0x1
        push eax
        mov ecx, dword ptr [eax]
        call dword ptr [ecx + 0x1c]
        mov edi, dword ptr [ebp - 0x4]
    L_42fe90:
        mov eax, dword ptr [esi + 0x18]
        test eax, eax
        jz L_42ff8a
        fld dword ptr [g_Data_004da000 + 0x19ac4]
        fmul dword ptr [g_RData_004cc000 + 0x4be4]
        fmul dword ptr [g_RData_004cc000 + 0x4be8]
        call dword ptr [g_Iat__ftol_004cc5ac]
        mov dword ptr [ebp - 0x8], eax
        mov eax, dword ptr [ebp - 0x8]
        add eax, 0x3f800000
        mov dword ptr [ebp - 0x4], eax
        fld dword ptr [g_Data_004da000 + 0x19ee8]
        fmul dword ptr [ebp - 0x4]
        fld dword ptr [g_RData_004cc000 + 0x4bb8]
        fsub dword ptr [ebp - 0x4]
        fmul dword ptr [edi + 0x3bc]
        faddp st(1), st(0)
        fstp dword ptr [g_Data_004da000 + 0x19ee8]
        fld dword ptr [edi + 0x3bc]
        fsub dword ptr [g_Data_004da000 + 0x19ee8]
        fmul dword ptr [g_RData_004cc000 + 0x4bec]
        fcom dword ptr [g_RData_004cc000 + 0x4bdc]
        fnstsw AX
        test AH, 0x1
        jz L_42ff05
        xor eax, eax
        fchs
        jmp L_42ff0a
    L_42ff05:
        mov eax, 0x4650
    L_42ff0a:
        fcom dword ptr [g_RData_004cc000 + 0x4be0]
        mov dword ptr [ebp - 0x10], eax
        mov ecx, 0xd
        xor eax, eax
        lea edi, [ebp - 0x44]
        rep stosd
        fnstsw AX
        test AH, 0x41
        jnz L_42ff30
        fstp st(0)
        fld dword ptr [g_RData_004cc000 + 0x4be0]
        jmp L_42ff45
    L_42ff30:
        fcom dword ptr [g_RData_004cc000 + 0x4bdc]
        fnstsw AX
        test AH, 0x1
        jz L_42ff45
        fstp st(0)
        fld dword ptr [g_RData_004cc000 + 0x4bdc]
    L_42ff45:
        fmul dword ptr [g_RData_004cc000 + 0x4bc0]
        mov dword ptr [ebp - 0x44], 0x34
        call dword ptr [g_Iat__ftol_004cc5ac]
        lea edx, [ebp - 0x10]
        mov dword ptr [ebp - 0x34], eax
        mov eax, dword ptr [esi + 0x18]
        mov dword ptr [ebp - 0x20], edx
        lea edx, [ebp - 0x44]
        mov dword ptr [ebp - 0x40], 0x20
        mov dword ptr [ebp - 0x28], 0x2
        mov ecx, dword ptr [eax]
        push 0x44
        push edx
        push eax
        call dword ptr [ecx + 0x18]
        mov esi, dword ptr [esi + 0x18]
        push 0x0
        push 0x1
        push esi
        mov eax, dword ptr [esi]
        call dword ptr [eax + 0x1c]
    L_42ff8a:
        pop edi
        pop esi
        pop ebx
        mov esp, ebp
        pop ebp
        ret
    }
}

// 0x0042ffa0 ForceFeedback_CreatePeriodicEffect - (mag) ret 4: DIEFFECT (size 0x34, flags 0x22, duration 10000, gain 100000, 1 axis, magnitude ftol(arg)) -> create via 0x00472450
// Register/stack shape from the listing (ECX, EDX, 4 stack bytes).
__declspec(naked) int __fastcall ForceFeedback_CreatePeriodicEffect(int, int, int)
{
    __asm {
        sub esp, 0x44
        fld dword ptr [esp + 0x48]
        fcom dword ptr [g_RData_004cc000 + 0x4bb8]
        push esi
        xor esi, esi
        mov dword ptr [esp + 0x4], esi
        mov dword ptr [esp + 0x8], 0x4
        mov dword ptr [esp + 0xc], esi
        mov dword ptr [esp + 0x10], esi
        fnstsw AX
        test AH, 0x41
        jnz L_42ffd5
        fstp st(0)
        fld dword ptr [g_RData_004cc000 + 0x4bb8]
        jmp L_42ffea
    L_42ffd5:
        fcom dword ptr [g_RData_004cc000 + 0x4bdc]
        fnstsw AX
        test AH, 0x1
        jz L_42ffea
        fstp st(0)
        fld dword ptr [g_RData_004cc000 + 0x4bdc]
    L_42ffea:
        fmul dword ptr [g_RData_004cc000 + 0x4bc0]
        mov dword ptr [esp + 0x4c], 0x2710
        mov dword ptr [esp + 0x14], 0x34
        mov dword ptr [esp + 0x18], 0x22
        mov dword ptr [esp + 0x1c], 0x186a0
        mov dword ptr [esp + 0x20], esi
        call dword ptr [g_Iat__ftol_004cc5ac]
        lea ecx, [esp + 0xc]
        lea edx, [esp + 0x4c]
        mov dword ptr [esp + 0x24], eax
        lea eax, [esp + 0x4]
        mov dword ptr [esp + 0x38], ecx
        mov dword ptr [esp + 0x44], edx
        lea edx, [esp + 0x14]
        mov ecx, offset g_RData_004cc000 + 0x6850
        mov dword ptr [esp + 0x28], 0xffffffff
        mov dword ptr [esp + 0x2c], esi
        mov dword ptr [esp + 0x30], 0x2
        mov dword ptr [esp + 0x34], eax
        mov dword ptr [esp + 0x3c], esi
        mov dword ptr [esp + 0x40], 0x4
        call Input_Joystick_AcquireOk
        pop esi
        add esp, 0x44
        ret 0x4
    }
}

// 0x00430100 ForceFeedback_CreateRampEffect - (mag) ret 4: DIEFFECT (0x34, 0x22, 20000 / 10000 params, 2 axes, type size 0x10, magnitude ftol(arg)) -> 0x00472450
// Register/stack shape from the listing (ECX, EDX, 4 stack bytes).
__declspec(naked) int __fastcall ForceFeedback_CreateRampEffect(int, int, int)
{
    __asm {
        sub esp, 0x54
        fld dword ptr [esp + 0x58]
        fcom dword ptr [g_RData_004cc000 + 0x4bb8]
        push esi
        xor esi, esi
        mov dword ptr [esp + 0x4], esi
        mov dword ptr [esp + 0x8], 0x4
        mov dword ptr [esp + 0xc], esi
        mov dword ptr [esp + 0x10], esi
        fnstsw AX
        test AH, 0x41
        jnz L_430135
        fstp st(0)
        fld dword ptr [g_RData_004cc000 + 0x4bb8]
        jmp L_43014a
    L_430135:
        fcom dword ptr [g_RData_004cc000 + 0x4bdc]
        fnstsw AX
        test AH, 0x1
        jz L_43014a
        fstp st(0)
        fld dword ptr [g_RData_004cc000 + 0x4bdc]
    L_43014a:
        fmul dword ptr [g_RData_004cc000 + 0x4bc0]
        call dword ptr [g_Iat__ftol_004cc5ac]
        mov dword ptr [esp + 0x14], eax
        or eax, 0xffffffff
        lea ecx, [esp + 0xc]
        lea edx, [esp + 0x14]
        mov dword ptr [esp + 0x2c], eax
        mov dword ptr [esp + 0x38], eax
        lea eax, [esp + 0x4]
        mov dword ptr [esp + 0x48], ecx
        mov dword ptr [esp + 0x54], edx
        lea edx, [esp + 0x24]
        mov ecx, offset g_RData_004cc000 + 0x6880
        mov dword ptr [esp + 0x18], esi
        mov dword ptr [esp + 0x1c], esi
        mov dword ptr [esp + 0x20], 0x4e20
        mov dword ptr [esp + 0x24], 0x34
        mov dword ptr [esp + 0x28], 0x22
        mov dword ptr [esp + 0x30], esi
        mov dword ptr [esp + 0x34], 0x2710
        mov dword ptr [esp + 0x3c], esi
        mov dword ptr [esp + 0x40], 0x2
        mov dword ptr [esp + 0x44], eax
        mov dword ptr [esp + 0x4c], esi
        mov dword ptr [esp + 0x50], 0x10
        call Input_Joystick_AcquireOk
        pop esi
        add esp, 0x54
        ret 0x4
    }
}

// 0x0042f9f0 ForceFeedbackEffects_Create - Creates effect objects: [0] = 0x0042ffa0(0.25f), [1],[3],[4] = 0x0042ffa0(0.5f), [2] = 0x00430100(0.05f), [5] = 0x00430070(ECX=0x6978), [6] = 0x00430070(ECX=0x4650); starts [5] and [6] via vtable+0x1c(obj, 1, 0). Returns this. (Force-feedback naming INFERRED, as for 0x0042fa80.)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall ForceFeedbackEffects_Create(int, int)
{
    __asm {
        push esi
        mov esi, ecx
        push 0x3e800000
        call ForceFeedback_CreatePeriodicEffect
        push 0x3f000000
        mov dword ptr [esi], eax
        call ForceFeedback_CreatePeriodicEffect
        push 0x3f000000
        mov dword ptr [esi + 0x4], eax
        call ForceFeedback_CreatePeriodicEffect
        push 0x3f000000
        mov dword ptr [esi + 0xc], eax
        call ForceFeedback_CreatePeriodicEffect
        push 0x3d4ccccd
        mov dword ptr [esi + 0x10], eax
        call ForceFeedback_CreateRampEffect
        mov ecx, 0x6978
        mov dword ptr [esi + 0x8], eax
        call ForceFeedback_CreateConstantEffect
        mov ecx, 0x4650
        mov dword ptr [esi + 0x14], eax
        call ForceFeedback_CreateConstantEffect
        mov dword ptr [esi + 0x18], eax
        mov eax, dword ptr [esi + 0x14]
        test eax, eax
        jz L_42fa5e
        mov ecx, dword ptr [eax]
        push 0x0
        push 0x1
        push eax
        call dword ptr [ecx + 0x1c]
    L_42fa5e:
        mov eax, dword ptr [esi + 0x18]
        test eax, eax
        jz L_42fa6f
        mov edx, dword ptr [eax]
        push 0x0
        push 0x1
        push eax
        call dword ptr [edx + 0x1c]
    L_42fa6f:
        mov eax, esi
        pop esi
        ret
    }
}

// 0x00471cd0 Input_ReleaseKeyboardSuspend - if flag bit1 of [0x00561cb8]: Input_Keyboard_InitialPollAndClear; clear bit1
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_ReleaseKeyboardSuspend(int, int)
{
    __asm {
        test byte ptr [g_Data_004da000 + 0x87cb8], 0x2
        jz L_471cde
        call Input_Keyboard_InitialPollAndClear
    L_471cde:
        and byte ptr [g_Data_004da000 + 0x87cb8], 0xfd
        ret
    }
}

// 0x00471d20 Input_Keyboard_AcquireRef - if keyboard present (bit0 [0x00561cb8]): on first ref (count [0x00561cbc]==0) Input_Keyboard_InitialPollAndClear; count++; return count
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_Keyboard_AcquireRef(int, int)
{
    __asm {
        test byte ptr [g_Data_004da000 + 0x87cb8], 0x1
        jz L_471d3f
        cmp word ptr [g_Data_004da000 + 0x87cbc], 0x0
        jnz L_471d38
        call Input_Keyboard_InitialPollAndClear
    L_471d38:
        inc word ptr [g_Data_004da000 + 0x87cbc]
    L_471d3f:
        mov eax, dword ptr [g_Data_004da000 + 0x87cbc]
        and eax, 0xffff
        ret
    }
}

// 0x00471da0 Input_Mouse_AcquireRef - if mouse present ([0x00561cba]&1): on first ref 0x00470610; count [0x00561cc0]++; return count
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_Mouse_AcquireRef(int, int)
{
    __asm {
        test byte ptr [g_Data_004da000 + 0x87cba], 0x1
        jz L_471dbf
        cmp word ptr [g_Data_004da000 + 0x87cc0], 0x0
        jnz L_471db8
        call Mouse_ResetDeltas
    L_471db8:
        inc word ptr [g_Data_004da000 + 0x87cc0]
    L_471dbf:
        mov eax, dword ptr [g_Data_004da000 + 0x87cc0]
        and eax, 0xffff
        ret
    }
}

// 0x00471de0 Input_PollAllDevices - ../../04_spec/systems/menus.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_PollAllDevices(int, int)
{
    __asm {
        mov AL, byte ptr [g_Data_004da000 + 0x87cba]
        push ebx
        cmp AL, 0x1
        mov BL, CL
        jnz L_471dfb
        cmp word ptr [g_Data_004da000 + 0x87cc0], 0x0
        jbe L_471dfb
        call Input_Mouse_Poll
    L_471dfb:
        cmp byte ptr [g_Data_004da000 + 0x87cb9], 0x1
        jnz L_471e15
        cmp word ptr [g_Data_004da000 + 0x87cbe], 0x0
        jbe L_471e15
        mov CL, BL
        call Input_Joystick_Poll
    L_471e15:
        cmp byte ptr [g_Data_004da000 + 0x87cb8], 0x1
        jnz L_471e2f
        cmp word ptr [g_Data_004da000 + 0x87cbc], 0x0
        jbe L_471e2f
        mov CL, BL
        call Input_Keyboard_PollAndTranslate
    L_471e2f:
        pop ebx
        ret
    }
}

// 0x00470e80 Input_DispatchKeyHandler_00470e80 - ../../04_spec/systems/input.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_DispatchKeyHandler_00470e80(int, int)
{
    __asm {
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call InputMap_CommandForKey
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        mov edx, dword ptr [ecx + 0xc]
        mov edx, dword ptr [edx + eax*0x4]
        test edx, edx
        jz L_470ea0
        mov ecx, eax
        jmp edx
    L_470ea0:
        ret
    }
}

// 0x00471a10 AtexitStub_InputState_ClearLists_00471a10 - ../../04_spec/systems/input.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall AtexitStub_InputState_ClearLists_00471a10(int, int)
{
    __asm {
        mov ecx, offset g_Data_004da000 + 0x87cb0
        jmp InputState_ClearLists
    }
}

// 0x00471f60 Input_TryCreateDirectInputDevice_00471f60 - ../../04_spec/systems/input.md
// Register/stack shape from the listing (ECX, EDX, 8 stack bytes).
__declspec(naked) int __fastcall Input_TryCreateDirectInputDevice_00471f60(int, int, int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x87cb0]
        lea edx, [esp + 0x4]
        push 0x0
        push edx
        mov edx, dword ptr [esp + 0xc]
        mov ecx, dword ptr [eax]
        add edx, 0x4
        push edx
        push eax
        call dword ptr [ecx + 0xc]
        test eax, eax
        jnz L_471fa0
        mov eax, dword ptr [esp + 0x4]
        push offset g_Data_004da000 + 0x8bbd0
        push offset g_RData_004cc000 + 0x6740
        push eax
        mov ecx, dword ptr [eax]
        call dword ptr [ecx]
        mov eax, dword ptr [esp + 0x4]
        push eax
        mov edx, dword ptr [eax]
        call dword ptr [edx + 0x8]
        xor eax, eax
        ret 0x8
    L_471fa0:
        mov eax, 0x1
        ret 0x8
    }
}

// 0x004717c0 Registry_AddWithDefault - Calls 0x00470df0 with ECX=[0x00565ea0] and stack (ECX_in, EDX_in).
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Registry_AddWithDefault(int, int)
{
    __asm {
        push edx
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        call InputMap_SetCommandHandler
        ret
    }
}

// 0x004716c0 Bindings_Forward_004716c0 - ECX=[0x00565ea0]; tail jmp 0x004709d0
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Bindings_Forward_004716c0(int, int)
{
    __asm {
        mov ecx, dword ptr [g_Data_004da000 + 0x8bea0]
        jmp Bindings_ResetAll
    }
}

// 0x00414550 Input_FeedTypedCharToScreen_00414550 - ../../04_spec/systems/input.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_FeedTypedCharToScreen_00414550(int, int)
{
    __asm {
        call Input_Keyboard_ScancodeToAscii
        test eax, eax
        jz L_414585
        push esi
        push eax
        mov ecx, offset g_Data_004da000 + 0xc988
        call KeyDispatch_OnChar
        mov eax, dword ptr [g_Data_004da000 + 0xc844]
        mov ecx, offset g_Data_004da000 + 0xc988
        mov esi, dword ptr [eax]
        call TextBuffer_GetText
        mov ecx, dword ptr [g_Data_004da000 + 0xc844]
        push eax
        push ecx
        call dword ptr [esi + 0x74]
        add esp, 0x8
        pop esi
    L_414585:
        ret
    }
}

// 0x004719e0 StaticInitWrapper_004719e0 - ../../04_spec/systems/input.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall StaticInitWrapper_004719e0(int, int)
{
    __asm {
        call StaticInit_00561cb0
        jmp StaticInit_RegisterAtexit_00471a10
    }
}

// 0x00471c60 Input_IsBit1Clear_Byte00561cba_00471c60 - ../../04_spec/systems/input.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_IsBit1Clear_Byte00561cba_00471c60(int, int)
{
    __asm {
        mov AL, byte ptr [g_Data_004da000 + 0x87cba]
        not AL
        and eax, 0x2
        shr eax, 0x1
        ret
    }
}

// 0x00471c70 Input_IsBit1Clear_Byte00561cb9_00471c70 - ../../04_spec/systems/input.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_IsBit1Clear_Byte00561cb9_00471c70(int, int)
{
    __asm {
        mov AL, byte ptr [g_Data_004da000 + 0x87cb9]
        not AL
        and eax, 0x2
        shr eax, 0x1
        ret
    }
}

// 0x00471c80 Input_IsBit1Clear_Byte00561cb8_00471c80 - ../../04_spec/systems/input.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_IsBit1Clear_Byte00561cb8_00471c80(int, int)
{
    __asm {
        mov AL, byte ptr [g_Data_004da000 + 0x87cb8]
        not AL
        and eax, 0x2
        shr eax, 0x1
        ret
    }
}

// 0x00471c90 Input_ClearBit1Byte00561cba_ResetMouseDeltas_00471c90 - ../../04_spec/systems/input.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_ClearBit1Byte00561cba_ResetMouseDeltas_00471c90(int, int)
{
    __asm {
        test byte ptr [g_Data_004da000 + 0x87cba], 0x2
        jz L_471c9e
        call Mouse_ResetDeltas
    L_471c9e:
        and byte ptr [g_Data_004da000 + 0x87cba], 0xfd
        ret
    }
}

// 0x00471cb0 Input_ClearBit1Byte00561cb9_ResetJoystick_00471cb0 - ../../04_spec/systems/input.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_ClearBit1Byte00561cb9_ResetJoystick_00471cb0(int, int)
{
    __asm {
        test byte ptr [g_Data_004da000 + 0x87cb9], 0x2
        jz L_471cbe
        call Joystick_ResetState
    L_471cbe:
        and byte ptr [g_Data_004da000 + 0x87cb9], 0xfd
        ret
    }
}

// 0x00471cf0 Input_SetBit1_Byte00561cba_00471cf0 - ../../04_spec/systems/input.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_SetBit1_Byte00561cba_00471cf0(int, int)
{
    __asm {
        or byte ptr [g_Data_004da000 + 0x87cba], 0x2
        ret
    }
}

// 0x00471d00 Input_SetBit1_Byte00561cb9_00471d00 - ../../04_spec/systems/input.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_SetBit1_Byte00561cb9_00471d00(int, int)
{
    __asm {
        or byte ptr [g_Data_004da000 + 0x87cb9], 0x2
        ret
    }
}

// 0x00471ae0 Input_SetAllDeviceBit1AndAcquireMouse_00471ae0 - ../../04_spec/systems/input.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_SetAllDeviceBit1AndAcquireMouse_00471ae0(int, int)
{
    __asm {
        call Input_IsBit1Clear_Byte00561cb9_00471c70
        test eax, eax
        jz L_471aee
        call Input_SetBit1_Byte00561cb9_00471d00
    L_471aee:
        call Input_IsBit1Clear_Byte00561cba_00471c60
        test eax, eax
        jz L_471afc
        call Input_SetBit1_Byte00561cba_00471cf0
    L_471afc:
        call Input_IsBit1Clear_Byte00561cb8_00471c80
        test eax, eax
        jz L_471b0a
        call Input_SetJoystickFlag2
    L_471b0a:
        mov dword ptr [g_Data_004da000 + 0x87c74], 0x0
        jmp Input_Mouse_SetAcquired
    }
}

// 0x00429f80 CommandTable_Clear - deletes each entry of pointer vector [0x004f3ae4,0x004f3ae8) (0x0042a000 then operator delete), nulls slots, end=begin
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall CommandTable_Clear(int, int)
{
    __asm {
        push ecx
        mov ecx, dword ptr [g_Data_004da000 + 0x19ae4]
        mov eax, dword ptr [g_Data_004da000 + 0x19ae8]
        push ebx
        push ebp
        push esi
        mov ebx, eax
        mov esi, ecx
        push edi
        cmp esi, ebx
        jz L_429fcb
        mov ebp, ecx
        sub ebp, esi
    L_429f9c:
        mov edi, dword ptr [esi]
        test edi, edi
        jz L_429fb2
        mov ecx, edi
        call CommandTableEntry_Dtor
        push edi
        call dword ptr [g_Iat_MFC42_825_004cc2b8]
        add esp, 0x4
    L_429fb2:
        mov dword ptr [esi + ebp*0x1], 0x0
        add esi, 0x4
        cmp esi, ebx
        jnz L_429f9c
        mov eax, dword ptr [g_Data_004da000 + 0x19ae8]
        mov ecx, dword ptr [g_Data_004da000 + 0x19ae4]
    L_429fcb:
        mov edx, eax
        cmp eax, edx
        jz L_429fe4
    L_429fd1:
        mov esi, dword ptr [eax]
        add eax, 0x4
        mov dword ptr [ecx], esi
        add ecx, 0x4
        cmp eax, edx
        jnz L_429fd1
        mov eax, dword ptr [g_Data_004da000 + 0x19ae8]
    L_429fe4:
        pop edi
        pop esi
        pop ebp
        mov dword ptr [esp + 0x4], eax
        mov dword ptr [g_Data_004da000 + 0x19ae8], ecx
        pop ebx
        pop ecx
        ret
    }
}

// 0x0042a000 CommandTableEntry_Dtor - CString Empty; delete [+8]; zero +8/+0xC/+0x10; ~CString
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall CommandTableEntry_Dtor(int, int)
{
    __asm {
        push -0x1
        push offset EH_Handler_CommandTableEntry_Dtor
        mov eax, FS:[0x0]
        push eax
        mov dword ptr FS:[0x0], esp
        push ecx
        push esi
        mov esi, ecx
        mov dword ptr [esp + 0x4], esi
        mov dword ptr [esp + 0x10], 0x1
        call dword ptr [g_Iat_MFC42_2614_004cc3a8]
        mov eax, dword ptr [esi + 0x8]
        push eax
        mov dword ptr [esp + 0x8], eax
        call dword ptr [g_Iat_MFC42_825_004cc2b8]
        xor eax, eax
        add esp, 0x4
        mov ecx, esi
        mov dword ptr [esi + 0x8], eax
        mov dword ptr [esi + 0xc], eax
        mov dword ptr [esi + 0x10], eax
        mov dword ptr [esp + 0x10], 0xffffffff
        call dword ptr [g_Iat_MFC42_800_004cc2a0]
        mov ecx, dword ptr [esp + 0x8]
        pop esi
        mov dword ptr FS:[0x0], ecx
        add esp, 0x10
        ret
    }
}

// 0x004c9c90 EH_Unwind_CommandTableEntry_Dtor_0 - CString Empty; delete [+8]; zero +8/+0xC/+0x10; ~CString
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall EH_Unwind_CommandTableEntry_Dtor_0(int, int)
{
    __asm {
        mov ecx, dword ptr [ebp - 0x10]
        jmp dword ptr [g_Iat_MFC42_800_004cc2a0]
    }
}

// 0x004c9c98 EH_Unwind_CommandTableEntry_Dtor_1 - CString Empty; delete [+8]; zero +8/+0xC/+0x10; ~CString
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall EH_Unwind_CommandTableEntry_Dtor_1(int, int)
{
    __asm {
        mov ecx, dword ptr [ebp - 0x10]
        add ecx, 0x4
        jmp PtrVector_Free
    }
}

// 0x004c9cb0 EH_Unwind_CommandTable_AddEntry_0 - creates 0x14-byte entry (CString name = ECX, three zero fields +8/+0xC/+0x10; operator new unchecked for fields but null-guarded) and push_back into [0x004f3ae4..ae8, cap 0x004f3aec]; growth new cap = size + max(size,1); returns previous count (new index)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall EH_Unwind_CommandTable_AddEntry_0(int, int)
{
    __asm {
        mov eax, dword ptr [ebp - 0x10]
        push eax
        call dword ptr [g_Iat_MFC42_825_004cc2b8]
        pop ecx
        ret
    }
}

// 0x004c9cbb EH_Unwind_CommandTable_AddEntry_1 - creates 0x14-byte entry (CString name = ECX, three zero fields +8/+0xC/+0x10; operator new unchecked for fields but null-guarded) and push_back into [0x004f3ae4..ae8, cap 0x004f3aec]; growth new cap = size + max(size,1); returns previous count (new index)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall EH_Unwind_CommandTable_AddEntry_1(int, int)
{
    __asm {
        mov ecx, dword ptr [ebp - 0x10]
        jmp dword ptr [g_Iat_MFC42_800_004cc2a0]
    }
}

// 0x004c9cc3 EH_Unwind_CommandTable_AddEntry_2 - creates 0x14-byte entry (CString name = ECX, three zero fields +8/+0xC/+0x10; operator new unchecked for fields but null-guarded) and push_back into [0x004f3ae4..ae8, cap 0x004f3aec]; growth new cap = size + max(size,1); returns previous count (new index)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall EH_Unwind_CommandTable_AddEntry_2(int, int)
{
    __asm {
        mov ecx, dword ptr [ebp - 0x10]
        add ecx, 0x4
        jmp PtrVector_Free
    }
}

// 0x004c9ca3 EH_Handler_CommandTableEntry_Dtor - CString Empty; delete [+8]; zero +8/+0xC/+0x10; ~CString
// Generated by tools/gen_eh_frames.py from the exe bytes (b8 a0 5d 4d 00 e9 f3 c3 ff ff): MOV EAX,FuncInfo 0x004d5da0; JMP 0x004c60a0 (-> __CxxFrameHandler).
// FuncInfo CONFIRMED-BINARY: magic 0x19930520, 2 unwind states, unwind map 0x004d5dc0 (to-state, action) = ['(-1, 0x004c9c90)', '(0, 0x004c9c98)'], no try blocks;
// the port's table points at the port's funclets. Needs /SAFESEH:NO (CMakeLists.txt).
namespace {
const EhUnwindMapEntry g_EhUnwindMap_004d5dc0[2] = {{-1, reinterpret_cast<void*>(&EH_Unwind_CommandTableEntry_Dtor_0)}, {0, reinterpret_cast<void*>(&EH_Unwind_CommandTableEntry_Dtor_1)}};
const EhFuncInfo g_EhFuncInfo_004d5da0 = {0x19930520u, 2, g_EhUnwindMap_004d5dc0, 0, nullptr};
}  // namespace

__declspec(naked) int __fastcall EH_Handler_CommandTableEntry_Dtor(int, int)
{
    __asm {
        mov eax, offset g_EhFuncInfo_004d5da0
        jmp dword ptr [g_Iat___CxxFrameHandler_004cc5b0]
    }
}

// 0x004c9cce EH_Handler_CommandTable_AddEntry - creates 0x14-byte entry (CString name = ECX, three zero fields +8/+0xC/+0x10; operator new unchecked for fields but null-guarded) and push_back into [0x004f3ae4..ae8, cap 0x004f3aec]; growth new cap = size + max(size,1); returns previous count (new index)
// Generated by tools/gen_eh_frames.py from the exe bytes (b8 d0 5d 4d 00 e9 c8 c3 ff ff): MOV EAX,FuncInfo 0x004d5dd0; JMP 0x004c60a0 (-> __CxxFrameHandler).
// FuncInfo CONFIRMED-BINARY: magic 0x19930520, 3 unwind states, unwind map 0x004d5df0 (to-state, action) = ['(-1, 0x004c9cb0)', '(0, 0x004c9cbb)', '(1, 0x004c9cc3)'], no try blocks;
// the port's table points at the port's funclets. Needs /SAFESEH:NO (CMakeLists.txt).
namespace {
const EhUnwindMapEntry g_EhUnwindMap_004d5df0[3] = {{-1, reinterpret_cast<void*>(&EH_Unwind_CommandTable_AddEntry_0)}, {0, reinterpret_cast<void*>(&EH_Unwind_CommandTable_AddEntry_1)}, {1, reinterpret_cast<void*>(&EH_Unwind_CommandTable_AddEntry_2)}};
const EhFuncInfo g_EhFuncInfo_004d5dd0 = {0x19930520u, 3, g_EhUnwindMap_004d5df0, 0, nullptr};
}  // namespace

__declspec(naked) int __fastcall EH_Handler_CommandTable_AddEntry(int, int)
{
    __asm {
        mov eax, offset g_EhFuncInfo_004d5dd0
        jmp dword ptr [g_Iat___CxxFrameHandler_004cc5b0]
    }
}

// 0x0042a070 CommandTable_AddEntry - creates 0x14-byte entry (CString name = ECX, three zero fields +8/+0xC/+0x10; operator new unchecked for fields but null-guarded) and push_back into [0x004f3ae4..ae8, cap 0x004f3aec]; growth new cap = size + max(size,1); returns previous count (new index)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall CommandTable_AddEntry(int, int)
{
    __asm {
        mov eax, FS:[0x0]
        push -0x1
        push offset EH_Handler_CommandTable_AddEntry
        push eax
        mov dword ptr FS:[0x0], esp
        sub esp, 0x10
        push ebx
        push ebp
        push esi
        push edi
        mov edi, ecx
        xor ebx, ebx
        mov ecx, dword ptr [g_Data_004da000 + 0x19ae4]
        cmp ecx, ebx
        jnz L_42a0a0
        mov dword ptr [esp + 0x18], ebx
        jmp L_42a0ae
    L_42a0a0:
        mov eax, dword ptr [g_Data_004da000 + 0x19ae8]
        sub eax, ecx
        sar eax, 0x2
        mov dword ptr [esp + 0x18], eax
    L_42a0ae:
        push 0x14
        call dword ptr [g_Iat_MFC42_823_004cc2ac]
        mov esi, eax
        add esp, 0x4
        mov dword ptr [esp + 0x1c], esi
        cmp esi, ebx
        mov dword ptr [esp + 0x28], ebx
        jz L_42a0ec
        mov ecx, esi
        call dword ptr [g_Iat_MFC42_540_004cc3c0]
        mov AL, byte ptr [esp + 0x13]
        mov dword ptr [esi + 0x8], ebx
        mov byte ptr [esi + 0x4], AL
        mov dword ptr [esi + 0xc], ebx
        mov dword ptr [esi + 0x10], ebx
        push edi
        mov ecx, esi
        mov byte ptr [esp + 0x2c], 0x2
        call dword ptr [g_Iat_MFC42_860_004cc3d0]
        jmp L_42a0ee
    L_42a0ec:
        xor esi, esi
    L_42a0ee:
        mov eax, dword ptr [g_Data_004da000 + 0x19ae8]
        mov ecx, dword ptr [g_Data_004da000 + 0x19aec]
        sub ecx, eax
        mov dword ptr [esp + 0x14], esi
        sar ecx, 0x2
        cmp ecx, 0x1
        mov dword ptr [esp + 0x28], 0xffffffff
        mov esi, eax
        jnc L_42a1f7
        mov edx, dword ptr [g_Data_004da000 + 0x19ae4]
        cmp edx, ebx
        jnz L_42a123
        xor ecx, ecx
        jmp L_42a12a
    L_42a123:
        mov ecx, eax
        sub ecx, edx
        sar ecx, 0x2
    L_42a12a:
        cmp ecx, 0x1
        jbe L_42a140
        cmp edx, ebx
        jnz L_42a137
        xor ecx, ecx
        jmp L_42a145
    L_42a137:
        mov ecx, eax
        sub ecx, edx
        sar ecx, 0x2
        jmp L_42a145
    L_42a140:
        mov ecx, 0x1
    L_42a145:
        cmp edx, ebx
        jnz L_42a14d
        xor eax, eax
        jmp L_42a152
    L_42a14d:
        sub eax, edx
        sar eax, 0x2
    L_42a152:
        lea ebp, [eax + ecx*0x1]
        cmp ebp, ebx
        mov eax, ebp
        jge L_42a15d
        xor eax, eax
    L_42a15d:
        lea edx, [eax*0x4 + 0x0]
        push edx
        call dword ptr [g_Iat_MFC42_823_004cc2ac]
        add esp, 0x4
        mov edi, eax
        mov eax, dword ptr [g_Data_004da000 + 0x19ae4]
        mov ecx, offset g_Data_004da000 + 0x19ae0
        push edi
        push esi
        push eax
        call Array_CopyRange
        lea ecx, [esp + 0x14]
        mov ebx, eax
        push ecx
        push 0x1
        push ebx
        mov ecx, offset g_Data_004da000 + 0x19ae0
        call Array_FillN
        mov edx, dword ptr [g_Data_004da000 + 0x19ae8]
        add ebx, 0x4
        push ebx
        push edx
        push esi
        mov ecx, offset g_Data_004da000 + 0x19ae0
        call Array_CopyRange
        mov eax, dword ptr [g_Data_004da000 + 0x19ae8]
        mov ecx, dword ptr [g_Data_004da000 + 0x19ae4]
        push eax
        push ecx
        mov ecx, offset g_Data_004da000 + 0x19ae0
        call Stub_NoOp_TwoStackArgs
        mov eax, dword ptr [g_Data_004da000 + 0x19ae4]
        push eax
        call dword ptr [g_Iat_MFC42_825_004cc2b8]
        lea edx, [edi + ebp*0x4]
        add esp, 0x4
        mov ecx, offset g_Data_004da000 + 0x19ae0
        mov dword ptr [g_Data_004da000 + 0x19aec], edx
        call PtrVector_Size
        lea eax, [edi + eax*0x4 + 0x4]
        mov dword ptr [g_Data_004da000 + 0x19ae4], edi
        mov dword ptr [g_Data_004da000 + 0x19ae8], eax
        jmp L_42a29c
    L_42a1f7:
        mov ecx, eax
        sub ecx, esi
        sar ecx, 0x2
        cmp ecx, 0x1
        jnc L_42a252
        lea edx, [esi + 0x4]
        mov ecx, offset g_Data_004da000 + 0x19ae0
        push edx
        push eax
        push esi
        call Array_CopyRange
        lea eax, [esp + 0x14]
        mov edx, 0x1
        push eax
        mov eax, dword ptr [g_Data_004da000 + 0x19ae8]
        mov ecx, eax
        sub ecx, esi
        sar ecx, 0x2
        sub edx, ecx
        mov ecx, offset g_Data_004da000 + 0x19ae0
        push edx
        push eax
        call Array_FillN
        mov ecx, dword ptr [g_Data_004da000 + 0x19ae8]
        mov eax, esi
        cmp esi, ecx
        jz L_42a295
    L_42a243:
        mov edx, dword ptr [esp + 0x14]
        mov dword ptr [eax], edx
        add eax, 0x4
        cmp eax, ecx
        jnz L_42a243
        jmp L_42a295
    L_42a252:
        push eax
        push eax
        add eax, -0x4
        mov ecx, offset g_Data_004da000 + 0x19ae0
        push eax
        call Array_CopyRange
        mov eax, dword ptr [g_Data_004da000 + 0x19ae8]
        mov ecx, eax
        add eax, -0x4
        cmp esi, eax
        jz L_42a27f
    L_42a270:
        mov edx, dword ptr [eax - 0x4]
        sub eax, 0x4
        sub ecx, 0x4
        cmp eax, esi
        mov dword ptr [ecx], edx
        jnz L_42a270
    L_42a27f:
        lea ecx, [esi + 0x4]
        mov eax, esi
        cmp esi, ecx
        jz L_42a295
    L_42a288:
        mov edx, dword ptr [esp + 0x14]
        mov dword ptr [eax], edx
        add eax, 0x4
        cmp eax, ecx
        jnz L_42a288
    L_42a295:
        add dword ptr [g_Data_004da000 + 0x19ae8], 0x4
    L_42a29c:
        mov ecx, dword ptr [esp + 0x20]
        mov eax, dword ptr [esp + 0x18]
        pop edi
        pop esi
        pop ebp
        mov dword ptr FS:[0x0], ecx
        pop ebx
        add esp, 0x1c
        ret
    }
}

// 0x0042a2c0 CommandTableEntry_PushValue - entry=table[ECX]; push_back EDX into its dword vector [+8,+0xC, cap +0x10]; growth new cap = size + max(size,1); operator new unchecked
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall CommandTableEntry_PushValue(int, int)
{
    __asm {
        sub esp, 0xc
        mov eax, dword ptr [g_Data_004da000 + 0x19ae4]
        push ebx
        push ebp
        push esi
        mov esi, dword ptr [eax + ecx*0x4]
        mov ebx, 0x4
        add esi, ebx
        push edi
        mov dword ptr [esp + 0x10], edx
        mov eax, dword ptr [esi + 0x8]
        mov ecx, dword ptr [esi + 0xc]
        sub ecx, eax
        mov edi, eax
        sar ecx, 0x2
        cmp ecx, 0x1
        jnc L_42a3e3
        mov edx, dword ptr [esi + 0x4]
        test edx, edx
        jnz L_42a2fb
        xor ecx, ecx
        jmp L_42a302
    L_42a2fb:
        mov ecx, eax
        sub ecx, edx
        sar ecx, 0x2
    L_42a302:
        cmp ecx, 0x1
        jbe L_42a318
        test edx, edx
        jnz L_42a30f
        xor ecx, ecx
        jmp L_42a31d
    L_42a30f:
        mov ecx, eax
        sub ecx, edx
        sar ecx, 0x2
        jmp L_42a31d
    L_42a318:
        mov ecx, 0x1
    L_42a31d:
        test edx, edx
        jnz L_42a325
        xor eax, eax
        jmp L_42a32a
    L_42a325:
        sub eax, edx
        sar eax, 0x2
    L_42a32a:
        add eax, ecx
        test eax, eax
        mov dword ptr [esp + 0x18], eax
        jge L_42a336
        xor eax, eax
    L_42a336:
        lea edx, [eax*0x4 + 0x0]
        push edx
        call dword ptr [g_Iat_MFC42_823_004cc2ac]
        mov ebx, dword ptr [esi + 0x4]
        add esp, 0x4
        cmp ebx, edi
        mov dword ptr [esp + 0x14], eax
        mov ebp, eax
        jz L_42a366
    L_42a353:
        mov edx, ebx
        mov ecx, ebp
        call Value_AssignDword
        add ebx, 0x4
        add ebp, 0x4
        cmp ebx, edi
        jnz L_42a353
    L_42a366:
        lea eax, [esp + 0x10]
        mov ecx, esi
        push eax
        push 0x1
        push ebp
        call Array_FillN
        mov ecx, dword ptr [esi + 0x8]
        add ebp, 0x4
        push ebp
        push ecx
        push edi
        mov ecx, esi
        call Array_CopyRange
        mov edx, dword ptr [esi + 0x8]
        mov eax, dword ptr [esi + 0x4]
        push edx
        push eax
        mov ecx, esi
        call Stub_NoOp_TwoStackArgs
        mov eax, dword ptr [esi + 0x4]
        push eax
        call dword ptr [g_Iat_MFC42_825_004cc2b8]
        mov edx, dword ptr [esp + 0x18]
        mov ecx, dword ptr [esp + 0x1c]
        add esp, 0x4
        lea eax, [edx + ecx*0x4]
        mov dword ptr [esi + 0xc], eax
        mov eax, dword ptr [esi + 0x4]
        test eax, eax
        jnz L_42a3c9
        xor ecx, ecx
        mov dword ptr [esi + 0x4], edx
        lea ecx, [edx + ecx*0x4 + 0x4]
        mov dword ptr [esi + 0x8], ecx
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_42a3c9:
        mov ecx, dword ptr [esi + 0x8]
        mov dword ptr [esi + 0x4], edx
        sub ecx, eax
        sar ecx, 0x2
        lea ecx, [edx + ecx*0x4 + 0x4]
        mov dword ptr [esi + 0x8], ecx
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_42a3e3:
        mov edx, eax
        sub edx, edi
        sar edx, 0x2
        cmp edx, 0x1
        jnc L_42a439
        lea ecx, [edi + 0x4]
        push ecx
        push eax
        push edi
        mov ecx, esi
        call Array_CopyRange
        mov eax, dword ptr [esi + 0x8]
        lea edx, [esp + 0x10]
        mov ecx, eax
        push edx
        sub ecx, edi
        mov edx, 0x1
        sar ecx, 0x2
        sub edx, ecx
        mov ecx, esi
        push edx
        push eax
        call Array_FillN
        mov eax, dword ptr [esi + 0x8]
        cmp edi, eax
        jz L_42a46f
    L_42a422:
        mov ecx, dword ptr [esp + 0x10]
        mov dword ptr [edi], ecx
        add edi, ebx
        cmp edi, eax
        jnz L_42a422
        add dword ptr [esi + 0x8], ebx
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_42a439:
        push eax
        push eax
        add eax, -0x4
        mov ecx, esi
        push eax
        call Array_CopyRange
        mov ecx, dword ptr [esi + 0x8]
        lea eax, [ecx - 0x4]
        cmp edi, eax
        jz L_42a45c
    L_42a450:
        sub eax, ebx
        sub ecx, ebx
        cmp eax, edi
        mov edx, dword ptr [eax]
        mov dword ptr [ecx], edx
        jnz L_42a450
    L_42a45c:
        lea eax, [edi + 0x4]
        cmp edi, eax
        jz L_42a46f
    L_42a463:
        mov ecx, dword ptr [esp + 0x10]
        mov dword ptr [edi], ecx
        add edi, ebx
        cmp edi, eax
        jnz L_42a463
    L_42a46f:
        mov eax, dword ptr [esi + 0x8]
        pop edi
        add eax, ebx
        mov dword ptr [esi + 0x8], eax
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    }
}

// 0x0042a500 CommandSlot_Bind - calls 0x004a5bf0 and InputMgr_Call_00470cd0 with the 4 args, then 0x0042a2c0, stores EDX into [0x004f3af0+ECX*4]
// Register/stack shape from the listing (ECX, EDX, 16 stack bytes).
__declspec(naked) int __fastcall CommandSlot_Bind(int, int, int, int, int, int)
{
    __asm {
        mov eax, dword ptr [esp + 0x10]
        push esi
        push edi
        mov edi, ecx
        mov ecx, dword ptr [esp + 0x14]
        mov esi, edx
        mov edx, dword ptr [esp + 0x10]
        push eax
        mov eax, dword ptr [esp + 0x10]
        push ecx
        push edx
        push eax
        mov ecx, esi
        call Message_GetText
        mov edx, eax
        mov ecx, edi
        call InputMgr_Call_00470cd0
        mov ecx, dword ptr [g_Data_004da000 + 0x19ad8]
        mov edx, eax
        call CommandTableEntry_PushValue
        mov dword ptr [edi*0x4 + g_Data_004da000 + 0x19af0], esi
        pop edi
        pop esi
        ret 0x10
    }
}

// 0x00471e40 Input_Joystick_CreateDevice - no DirectInput [0x00561cb0] -> 0; EnumDevices(DIDEVTYPE_JOYSTICK 4, callback 0x00471f60, 0, DIEDFL_ATTACHEDONLY 1) (vfunc+0x10) -> [0x00565bd0]; none -> 0; SetDataFormat(c_dfDIJoystick 0x004c7ee0) (vfunc+0x2c); GetCapabilities (vfunc+0xc, size 0x2c) -> axis count [0x00565e14]; defaults [0x00565e18]=
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_Joystick_CreateDevice(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x87cb0]
        sub esp, 0x7c
        test eax, eax
        push esi
        push edi
        mov edi, ecx
        jnz L_471e56
        pop edi
        pop esi
        add esp, 0x7c
        ret
    L_471e56:
        push 0x1
        push 0x0
        mov dword ptr [g_Data_004da000 + 0x8bbd0], 0x0
        mov ecx, dword ptr [eax]
        push offset Input_TryCreateDirectInputDevice_00471f60
        push 0x4
        push eax
        call dword ptr [ecx + 0x10]
        mov esi, dword ptr [g_Data_004da000 + 0x8bbd0]
        test esi, esi
        jnz L_471e83
        xor eax, eax
        pop edi
        pop esi
        add esp, 0x7c
        ret
    L_471e83:
        mov dword ptr [esp + 0x8], 0x2c
        mov edx, dword ptr [esi]
        push offset c_dfDIJoystick2
        push esi
        call dword ptr [edx + 0x2c]
        mov eax, dword ptr [esi]
        lea ecx, [esp + 0x8]
        push ecx
        push esi
        call dword ptr [eax + 0xc]
        mov ecx, dword ptr [esp + 0xc]
        mov edx, dword ptr [esp + 0x14]
        mov eax, ecx
        mov dword ptr [g_Data_004da000 + 0x8be14], edx
        and eax, 0x100
        mov edx, ecx
        mov dword ptr [g_Data_004da000 + 0x8be18], eax
        and edx, 0x200
        and ecx, 0x400
        mov dword ptr [g_Data_004da000 + 0x8be1c], edx
        neg eax
        sbb eax, eax
        mov dword ptr [g_Data_004da000 + 0x8be20], ecx
        mov ecx, dword ptr [esi]
        and AL, 0xfc
        add eax, 0x9
        push eax
        push edi
        push esi
        call dword ptr [ecx + 0x34]
        mov ecx, 0x14
        xor eax, eax
        lea edi, [esp + 0x34]
        rep stosd
        mov ecx, 0xfffffc18
        mov eax, 0x3e8
        mov dword ptr [esp + 0x34], ecx
        mov dword ptr [esp + 0x48], ecx
        mov dword ptr [esp + 0x5c], ecx
        mov dword ptr [esp + 0x70], ecx
        lea ecx, [esp + 0x34]
        mov dword ptr [esp + 0x38], eax
        mov dword ptr [esp + 0x4c], eax
        mov dword ptr [esp + 0x60], eax
        mov dword ptr [esp + 0x74], eax
        mov dword ptr [esp + 0x44], eax
        mov dword ptr [esp + 0x58], eax
        mov dword ptr [esp + 0x6c], 0x0
        mov dword ptr [esp + 0x80], 0x9c4
        call Joystick_ApplyAxisRanges
        call Input_Joystick_Acquire
        mov dword ptr [g_Data_004da000 + 0x8bbcc], 0x1
        mov eax, 0x1
        pop edi
        pop esi
        add esp, 0x7c
        ret
    }
}

// 0x00471b20 Input_ResumeOnActivate - ../../04_spec/systems/input.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Input_ResumeOnActivate(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x87cb4]
        test eax, eax
        jz L_471b47
        call Input_ClearBit1Byte00561cb9_ResetJoystick_00471cb0
        call Input_ReleaseKeyboardSuspend
        call Input_ClearBit1Byte00561cba_ResetMouseDeltas_00471c90
        mov dword ptr [g_Data_004da000 + 0x87c74], 0x1
        jmp Input_Mouse_SetAcquired
    L_471b47:
        ret
    }
}

// 0x00426150 Game_DispatchCommand_00426150 - ../../04_spec/systems/input.md
// FIXED 2026-10-07 (port audit): the generated port began with inlined chunks of 0x00405ec0 / 0x00413640 (bad
// listing), so every call ran them instead of this dispatcher. The function now starts at 0x00426150;
// the chunks follow its code and are reached only by its tail jumps, as in the original.
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Game_DispatchCommand_00426150(int, int)
{
    __asm {
        lea eax, [ecx - 0x9]
        cmp eax, 0x24
        ja L_4262ce
        xor ecx, ecx
        cmp eax, 0
        jne Lsw_426164_0
        mov CL, 0
        jmp L_426172
    Lsw_426164_0:
        cmp eax, 1
        jne Lsw_426164_1
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_1:
        cmp eax, 2
        jne Lsw_426164_2
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_2:
        cmp eax, 3
        jne Lsw_426164_3
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_3:
        cmp eax, 4
        jne Lsw_426164_4
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_4:
        cmp eax, 5
        jne Lsw_426164_5
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_5:
        cmp eax, 6
        jne Lsw_426164_6
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_6:
        cmp eax, 7
        jne Lsw_426164_7
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_7:
        cmp eax, 8
        jne Lsw_426164_8
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_8:
        cmp eax, 9
        jne Lsw_426164_9
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_9:
        cmp eax, 10
        jne Lsw_426164_10
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_10:
        cmp eax, 11
        jne Lsw_426164_11
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_11:
        cmp eax, 12
        jne Lsw_426164_12
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_12:
        cmp eax, 13
        jne Lsw_426164_13
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_13:
        cmp eax, 14
        jne Lsw_426164_14
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_14:
        cmp eax, 15
        jne Lsw_426164_15
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_15:
        cmp eax, 16
        jne Lsw_426164_16
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_16:
        cmp eax, 17
        jne Lsw_426164_17
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_17:
        cmp eax, 18
        jne Lsw_426164_18
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_18:
        cmp eax, 19
        jne Lsw_426164_19
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_19:
        cmp eax, 20
        jne Lsw_426164_20
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_20:
        cmp eax, 21
        jne Lsw_426164_21
        mov CL, 1
        jmp L_42616b
    Lsw_426164_21:
        cmp eax, 22
        jne Lsw_426164_22
        mov CL, 2
        jmp L_426177
    Lsw_426164_22:
        cmp eax, 23
        jne Lsw_426164_23
        mov CL, 3
        jmp L_426199
    Lsw_426164_23:
        cmp eax, 24
        jne Lsw_426164_24
        mov CL, 4
        jmp L_426194
    Lsw_426164_24:
        cmp eax, 25
        jne Lsw_426164_25
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_25:
        cmp eax, 26
        jne Lsw_426164_26
        mov CL, 5
        jmp L_426181
    Lsw_426164_26:
        cmp eax, 27
        jne Lsw_426164_27
        mov CL, 6
        jmp L_4261e4
    Lsw_426164_27:
        cmp eax, 28
        jne Lsw_426164_28
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_28:
        cmp eax, 29
        jne Lsw_426164_29
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_29:
        cmp eax, 30
        jne Lsw_426164_30
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_30:
        cmp eax, 31
        jne Lsw_426164_31
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_31:
        cmp eax, 32
        jne Lsw_426164_32
        mov CL, 11
        jmp L_4262ce
    Lsw_426164_32:
        cmp eax, 33
        jne Lsw_426164_33
        mov CL, 7
        jmp L_42619e
    Lsw_426164_33:
        cmp eax, 34
        jne Lsw_426164_34
        mov CL, 8
        jmp L_4261a3
    Lsw_426164_34:
        cmp eax, 35
        jne Lsw_426164_35
        mov CL, 9
        jmp L_426223
    Lsw_426164_35:
        cmp eax, 36
        jne Lsw_426164_36
        mov CL, 10
        jmp L_426279
    Lsw_426164_36:
        int 3  // unreachable: the bounds check above excludes other indices
    L_42616b:
        xor ecx, ecx
        jmp Vehicle_SetCameraViewState
    L_426172:
        jmp L_405ec0
    L_426177:
        mov ecx, 0x2
        jmp Vehicle_SetCameraViewState
    L_426181:
        call Settings_GetNetworkFlag
        test eax, eax
        jnz L_42618f
        call ScreenHolder_Close_004e5ce8
    L_42618f:
        jmp Input_Keyboard_InitialPollAndClear
    L_426194:
        jmp Hud_ApplyTypeByMode_00413600
    L_426199:
        jmp L_413640
    L_42619e:
        jmp Net_SetupTableLoops_004143d0
    L_4261a3:
        call ControlFlags_GetBit0
        test eax, eax
        push 0x40a00000
        jz L_4261c9
        mov ecx, 0x24d
        call Message_GetText
        mov ecx, eax
        call Hud_ShowMessage
        xor ecx, ecx
        jmp ControlFlags_SetBit0
    L_4261c9:
        mov ecx, 0x24c
        call Message_GetText
        mov ecx, eax
        call Hud_ShowMessage
        mov ecx, 0x1
        jmp ControlFlags_SetBit0
    L_4261e4:
        mov eax, dword ptr [g_Data_004da000 + 0x19aa8]
        test eax, eax
        jz L_426205
        xor ecx, ecx
        mov dword ptr [g_Data_004da000 + 0x19aa8], 0x0
        call Hud_SetOverlayVisible
        xor ecx, ecx
        jmp Hud_ShowPanel_004e6db0
    L_426205:
        mov ecx, 0x1
        mov dword ptr [g_Data_004da000 + 0x19aa8], 0x1
        call Hud_SetOverlayVisible
        mov ecx, 0x1
        jmp Hud_ShowPanel_004e6db0
    L_426223:
        call Settings_GetNetworkFlag
        test eax, eax
        jz L_426249
        push 0x40000000
        mov ecx, 0x86
        call Message_GetText
        mov edx, offset g_Data_004da000 + 0xe40
        xor ecx, ecx
        push eax
        call Hud_ShowPopup
        ret
    L_426249:
        call Game_CanLoad
        test eax, eax
        jz L_42625c
        mov ecx, 0x2
        jmp LoadGameScreen_Open
    L_42625c:
        push 0x40000000
        mov ecx, 0x87
        call Message_GetText
        mov edx, offset g_Data_004da000 + 0xe40
        xor ecx, ecx
        push eax
        call Hud_ShowPopup
        ret
    L_426279:
        call Settings_GetNetworkFlag
        test eax, eax
        jz L_42629f
        push 0x40000000
        mov ecx, 0x85
        call Message_GetText
        mov edx, offset g_Data_004da000 + 0xe40
        xor ecx, ecx
        push eax
        call Hud_ShowPopup
        ret
    L_42629f:
        call Game_CanSave
        test eax, eax
        jz L_4262b2
        mov ecx, 0x1
        jmp SaveGameScreen_Open
    L_4262b2:
        push 0x40000000
        mov ecx, 0x82
        call Message_GetText
        mov edx, offset g_Data_004da000 + 0xe40
        xor ecx, ecx
        push eax
        call Hud_ShowPopup
    L_4262ce:
        ret
        // inlined original code reached only by tail jumps (0x00405ec0 is mid-function there; 0x00413640)
    L_405ec0:
        mov ecx, dword ptr [g_Data_004da000 + 0x19a88]
        call Vehicle_ResetLookOffset
        call ControlFlags_GetBit1
        mov ecx, eax
        neg ecx
        sbb ecx, ecx
        inc ecx
        jmp ControlFlags_SetBit1
    L_413640:
        mov eax, dword ptr [g_Data_004da000 + 0xbed4]
        test eax, eax
        jz L_413654
        call Inset_Disable
        mov eax, 0x1
        ret
    L_413654:
        call Inset_Enable
        mov eax, 0x1
        ret
    }
}

}  // namespace recoil
