// SUBSYSTEM: texture
// Original file: not attributed (ledger orig_file empty): texture manager, archives, images. Spec: 04_spec/systems/texture.md
// Instruction-level ports generated by tools/asm_port/port_batch.py from the Ghidra listings.
#include "unattributed/texture.h"
#include "platform/iat_msvcrt.h"
#include "platform/image/original_data.h"
#include "GameZRecoil/zImage/zimg_fonts.h"
#include "unattributed/render_frame.h"
#include "GameZRecoil/zUtil/zutl_zar.h"
#include "GameZRecoil/zVideo/zvid_buff.h"

namespace recoil {

// 0x0046d550 TextureManager_Reset - ../../04_spec/systems/render.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall TextureManager_Reset(int, int)
{
    __asm {
        push edi
        mov ecx, 0x9000
        xor eax, eax
        mov edi, offset g_Data_004da000 + 0x6379c
        mov dword ptr [g_Data_004da000 + 0x63798], 0x0
        rep stosd
        mov eax, dword ptr [g_Data_004da000 + 0x91be8]
        test eax, eax
        jz L_46d58d
        push 0x0
        push 0x0
        push 0x0
        mov edx, offset g_Data_004da000 + 0x66e0
        mov ecx, offset g_Data_004da000 + 0x6720
        call dword ptr [g_Data_004da000 + 0x91c08]
        mov dword ptr [g_Data_004da000 + 0x671c], eax
    L_46d58d:
        mov eax, 0x1
        pop edi
        ret
    }
}

// 0x0046d730 TextureArchive_CloseAllFiles - ../../04_spec/systems/texture.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall TextureArchive_CloseAllFiles(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x63768]
        push ebx
        xor ebx, ebx
        test eax, eax
        jle L_46d77d
        push edi
        push esi
        push ebp
        mov ebp, dword ptr [g_Iat_fclose_004cc5c0]
        xor edi, edi
    L_46d747:
        mov eax, dword ptr [g_Data_004da000 + 0x6376c]
        lea esi, [eax + edi*0x1 + 0x80]
        mov eax, dword ptr [eax + edi*0x1 + 0x80]
        test eax, eax
        jz L_46d76a
        push eax
        call ebp
        add esp, 0x4
        mov dword ptr [esi], 0x0
    L_46d76a:
        mov eax, dword ptr [g_Data_004da000 + 0x63768]
        inc ebx
        add edi, 0xa4
        cmp ebx, eax
        jl L_46d747
        pop ebp
        pop esi
        pop edi
    L_46d77d:
        pop ebx
        ret
    }
}

// 0x0046d780 TextureArchiveListB_FreeAll - ../../04_spec/systems/texture.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall TextureArchiveListB_FreeAll(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x63770]
        push ebx
        push ebp
        push esi
        push edi
        xor edi, edi
        xor ebp, ebp
        cmp eax, edi
        jle L_46d7e0
        xor ebx, ebx
    L_46d793:
        mov eax, dword ptr [g_Data_004da000 + 0x63774]
        lea esi, [eax + ebx*0x1]
        mov eax, dword ptr [eax + ebx*0x1 + 0x80]
        cmp eax, edi
        jz L_46d7b6
        push eax
        call dword ptr [g_Iat_fclose_004cc5c0]
        add esp, 0x4
        mov dword ptr [esi + 0x80], edi
    L_46d7b6:
        mov eax, dword ptr [esi + 0x9c]
        cmp eax, edi
        jz L_46d7d0
        push eax
        call dword ptr [g_Iat_free_004cc5b4]
        add esp, 0x4
        mov dword ptr [esi + 0x9c], edi
    L_46d7d0:
        mov eax, dword ptr [g_Data_004da000 + 0x63770]
        inc ebp
        add ebx, 0xa4
        cmp ebp, eax
        jl L_46d793
    L_46d7e0:
        mov eax, dword ptr [g_Data_004da000 + 0x63774]
        cmp eax, edi
        jz L_46d7f9
        push eax
        call dword ptr [g_Iat_free_004cc5b4]
        add esp, 0x4
        mov dword ptr [g_Data_004da000 + 0x63774], edi
    L_46d7f9:
        mov dword ptr [g_Data_004da000 + 0x63770], edi
        pop edi
        pop esi
        pop ebp
        pop ebx
        ret
    }
}

// 0x004902b0 Image_PrepareSoftwareSampling - ../../04_spec/systems/texture.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Image_PrepareSoftwareSampling(int, int)
{
    __asm {
        mov eax, ecx
        xor CL, CL
        mov byte ptr [eax + 0xb], CL
        mov byte ptr [eax + 0xa], CL
        movsx ecx, word ptr [eax + 0x4]
        cmp ecx, 0x1
        jle L_4902d2
    L_4902c3:
        mov DL, byte ptr [eax + 0xa]
        sar ecx, 0x1
        inc DL
        cmp ecx, 0x1
        mov byte ptr [eax + 0xa], DL
        jg L_4902c3
    L_4902d2:
        movsx ecx, word ptr [eax + 0x6]
        cmp ecx, 0x1
        jle L_4902ea
    L_4902db:
        mov DL, byte ptr [eax + 0xb]
        sar ecx, 0x1
        inc DL
        cmp ecx, 0x1
        mov byte ptr [eax + 0xb], DL
        jg L_4902db
    L_4902ea:
        xor ecx, ecx
        mov edx, 0x14
        mov CL, byte ptr [eax + 0xa]
        mov dword ptr [eax + 0x1c], 0x3f800000
        sub edx, ecx
        mov dword ptr [eax + 0x24], edx
        mov edx, 0x1
        shl edx, CL
        mov CL, byte ptr [eax + 0xb]
        dec edx
        mov dword ptr [eax + 0x28], edx
        mov edx, 0x1
        shl edx, CL
        shl edx, 0x14
        sub edx, 0x100000
        mov dword ptr [eax + 0x2c], edx
        ret
    }
}

// 0x0046d5b0 Texture_SetFlag_004e073c - bytes: [0x004e073c]=ECX
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Texture_SetFlag_004e073c(int, int)
{
    __asm {
        mov dword ptr [g_Data_004da000 + 0x673c], ecx
        ret
    }
}

// 0x0046d5c0 Texture_GetFlag_004e073c - bytes: return [0x004e073c]
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Texture_GetFlag_004e073c(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x673c]
        ret
    }
}

// 0x0046f210 Image_IsColumnTransparent - EDX=col: if col>=width (short +4) return 0; walk height (short +6) rows from +0x10 pixels (16-bit, stride width); return 1 iff all equal key colour [0x005617f4]
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Image_IsColumnTransparent(int, int)
{
    __asm {
        mov eax, dword ptr [ecx + 0x10]
        push esi
        push edi
        movsx edi, word ptr [ecx + 0x4]
        lea esi, [eax + edx*0x2]
        cmp edx, edi
        mov eax, 0x1
        jl L_46f22a
        xor eax, eax
        pop edi
        pop esi
        ret
    L_46f22a:
        movsx ecx, word ptr [ecx + 0x6]
        xor edx, edx
        push ebp
        test ecx, ecx
        push ebx
        jle L_46f254
        mov ebx, dword ptr [g_Data_004da000 + 0x877f4]
    L_46f23c:
        xor ebp, ebp
        mov BP, word ptr [esi]
        cmp ebp, ebx
        jnz L_46f252
        inc edx
        lea esi, [esi + edi*0x2]
        cmp edx, ecx
        jl L_46f23c
        pop ebx
        pop ebp
        pop edi
        pop esi
        ret
    L_46f252:
        xor eax, eax
    L_46f254:
        pop ebx
        pop ebp
        pop edi
        pop esi
        ret
    }
}

// 0x00479c60 Palette_SetName - [0x0057d9a0]=1; slot [0x0057d9a8 + [0x0057d9a4]*4] = ECX
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Palette_SetName(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0xa39a4]
        mov dword ptr [g_Data_004da000 + 0xa39a0], 0x1
        mov dword ptr [eax*0x4 + g_Data_004da000 + 0xa39a8], ecx
        ret
    }
}

// 0x0046d6b0 TextureArchiveListA_FreeAll - ../../04_spec/systems/texture.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall TextureArchiveListA_FreeAll(int, int)
{
    __asm {
        push ebx
        push ebp
        push esi
        push edi
        call TextureArchive_CloseAllFiles
        mov eax, dword ptr [g_Data_004da000 + 0x63768]
        mov ebp, dword ptr [g_Iat_free_004cc5b4]
        xor ebx, ebx
        test eax, eax
        jle L_46d6ff
        xor edi, edi
    L_46d6cc:
        mov eax, dword ptr [g_Data_004da000 + 0x6376c]
        lea esi, [eax + edi*0x1 + 0x9c]
        mov eax, dword ptr [eax + edi*0x1 + 0x9c]
        test eax, eax
        jz L_46d6ef
        push eax
        call ebp
        add esp, 0x4
        mov dword ptr [esi], 0x0
    L_46d6ef:
        mov eax, dword ptr [g_Data_004da000 + 0x63768]
        inc ebx
        add edi, 0xa4
        cmp ebx, eax
        jl L_46d6cc
    L_46d6ff:
        mov eax, dword ptr [g_Data_004da000 + 0x6376c]
        test eax, eax
        jz L_46d718
        push eax
        call ebp
        add esp, 0x4
        mov dword ptr [g_Data_004da000 + 0x6376c], 0x0
    L_46d718:
        pop edi
        pop esi
        pop ebp
        mov dword ptr [g_Data_004da000 + 0x63768], 0x0
        pop ebx
        ret
    }
}

// 0x0046d870 Image_ApplyAlphaMask - ../../04_spec/systems/texture.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Image_ApplyAlphaMask(int, int)
{
    __asm {
        push esi
        mov esi, ecx
        cmp word ptr [esi + 0xe], 0x0
        jnz L_46d8f4
        call Image_BytesPerPixel
        dec eax
        jz L_46d8d5
        dec eax
        jz L_46d8b0
        sub eax, 0x2
        jnz L_46d8f4
        mov edx, dword ptr [esi]
        mov ecx, dword ptr [esi + 0x10]
        xor eax, eax
        test edx, edx
        jle L_46d8f4
    L_46d895:
        mov edx, dword ptr [esi + 0x14]
        cmp byte ptr [eax + edx*0x1], 0x0
        jnz L_46d8a4
        mov dword ptr [ecx], 0x0
    L_46d8a4:
        mov edx, dword ptr [esi]
        inc eax
        add ecx, 0x4
        cmp eax, edx
        jl L_46d895
        pop esi
        ret
    L_46d8b0:
        mov edx, dword ptr [esi]
        mov ecx, dword ptr [esi + 0x10]
        xor eax, eax
        test edx, edx
        jle L_46d8f4
    L_46d8bb:
        mov edx, dword ptr [esi + 0x14]
        cmp byte ptr [eax + edx*0x1], 0x0
        jnz L_46d8c9
        mov word ptr [ecx], 0x0
    L_46d8c9:
        mov edx, dword ptr [esi]
        inc eax
        add ecx, 0x2
        cmp eax, edx
        jl L_46d8bb
        pop esi
        ret
    L_46d8d5:
        mov edx, dword ptr [esi]
        mov ecx, dword ptr [esi + 0x10]
        xor eax, eax
        test edx, edx
        jle L_46d8f4
    L_46d8e0:
        mov edx, dword ptr [esi + 0x14]
        cmp byte ptr [eax + edx*0x1], 0x0
        jnz L_46d8ec
        mov byte ptr [ecx], 0x0
    L_46d8ec:
        mov edx, dword ptr [esi]
        inc eax
        inc ecx
        cmp eax, edx
        jl L_46d8e0
    L_46d8f4:
        pop esi
        ret
    }
}

// 0x0046d5d0 TextureManager_FreeAllSlots - ../../04_spec/systems/texture.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall TextureManager_FreeAllSlots(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x63798]
        push ebx
        push esi
        push edi
        xor ebx, ebx
        xor edi, edi
        cmp eax, ebx
        jle L_46d621
        mov esi, offset g_Data_004da000 + 0x637a0
    L_46d5e5:
        mov eax, dword ptr [esi + 0x18]
        sub eax, ebx
        jz L_46d614
        dec eax
        jz L_46d5f4
        dec eax
        jz L_46d611
        jmp L_46d614
    L_46d5f4:
        mov ecx, dword ptr [esi - 0x4]
        cmp ecx, ebx
        jz L_46d603
        call Image_FreeUnlessDefault
        mov dword ptr [esi - 0x4], ebx
    L_46d603:
        mov ecx, dword ptr [esi]
        cmp ecx, ebx
        jz L_46d611
        call dword ptr [g_Data_004da000 + 0x91c1c]
        mov dword ptr [esi], ebx
    L_46d611:
        mov dword ptr [esi + 0x18], ebx
    L_46d614:
        mov eax, dword ptr [g_Data_004da000 + 0x63798]
        inc edi
        add esi, 0x24
        cmp edi, eax
        jl L_46d5e5
    L_46d621:
        mov dword ptr [g_Data_004da000 + 0x63798], ebx
        call dword ptr [g_Data_004da000 + 0x91c20]
        mov eax, dword ptr [g_Data_004da000 + 0x63778]
        mov edi, dword ptr [g_Iat_free_004cc5b4]
        xor esi, esi
        cmp eax, ebx
        jle L_46d65f
    L_46d63e:
        mov eax, dword ptr [g_Data_004da000 + 0x6377c]
        mov ecx, dword ptr [eax + esi*0x4]
        push ecx
        call edi
        mov edx, dword ptr [g_Data_004da000 + 0x6377c]
        add esp, 0x4
        mov dword ptr [edx + esi*0x4], ebx
        mov eax, dword ptr [g_Data_004da000 + 0x63778]
        inc esi
        cmp esi, eax
        jl L_46d63e
    L_46d65f:
        mov eax, dword ptr [g_Data_004da000 + 0x6377c]
        mov dword ptr [g_Data_004da000 + 0x63778], ebx
        cmp eax, ebx
        jz L_46d67a
        push eax
        call edi
        add esp, 0x4
        mov dword ptr [g_Data_004da000 + 0x6377c], ebx
    L_46d67a:
        mov eax, dword ptr [g_Data_004da000 + 0x63784]
        cmp eax, ebx
        jz L_46d68f
        push eax
        call edi
        add esp, 0x4
        mov dword ptr [g_Data_004da000 + 0x63784], ebx
    L_46d68f:
        mov dword ptr [g_Data_004da000 + 0x63780], ebx
        call TextureArchiveListA_FreeAll
        call TextureArchiveListB_FreeAll
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        ret
    }
}

// 0x0046d810 TextureManager_FindOrAddSlot - ../../04_spec/systems/texture.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall TextureManager_FindOrAddSlot(int, int)
{
    __asm {
        push esi
        push edi
        mov edi, ecx
        push 0x2e
        push edi
        call dword ptr [g_Iat_strrchr_004cc494]
        mov esi, eax
        add esp, 0x8
        test esi, esi
        jz L_46d829
        mov byte ptr [esi], 0x0
    L_46d829:
        mov ecx, edi
        call TextureManager_FindSlotByName
        test esi, esi
        jz L_46d837
        mov byte ptr [esi], 0x2e
    L_46d837:
        test eax, eax
        jnz L_46d863
        mov eax, dword ptr [g_Data_004da000 + 0x63798]
        lea ecx, [eax + eax*0x8]
        inc eax
        mov dword ptr [g_Data_004da000 + 0x63798], eax
        lea esi, [ecx*0x4 + g_Data_004da000 + 0x6379c]
        mov ecx, edi
        lea edx, [esi + 0x8]
        call TextureSlot_SetNameFromPath
        mov dword ptr [esi + 0x1c], 0x2
        mov eax, esi
    L_46d863:
        pop edi
        pop esi
        ret
    }
}

// 0x0046dae0 TextureArchive_Open - ../../04_spec/systems/texture.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall TextureArchive_Open(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x673c]
        sub esp, 0xc
        push ebx
        push ebp
        push esi
        xor esi, esi
        push edi
        cmp eax, esi
        mov edi, ecx
        jnz L_46dafe
        xor eax, eax
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_46dafe:
        push offset g_Data_004da000 + 0xf54
        mov edx, edi
        xor ecx, ecx
        call File_OpenOnSearchPath
        cmp eax, esi
        mov dword ptr [edi + 0x80], eax
        jnz L_46db20
        xor eax, eax
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_46db20:
        mov ebp, dword ptr [g_Iat_fread_004cc4e0]
        push eax
        push 0x1
        lea eax, [edi + 0x84]
        push 0x18
        push eax
        call ebp
        add esp, 0x10
        cmp eax, 0x1
        jz L_46db45
        mov ecx, dword ptr [edi + 0x80]
        push ecx
        jmp L_46db55
    L_46db45:
        cmp dword ptr [edi + 0x88], 0x1
        jz L_46db6e
        mov edx, dword ptr [edi + 0x80]
        push edx
    L_46db55:
        call dword ptr [g_Iat_fclose_004cc5c0]
        add esp, 0x4
        mov dword ptr [edi + 0x80], esi
        xor eax, eax
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_46db6e:
        mov eax, dword ptr [edi + 0x90]
        lea eax, [eax + eax*0x4]
        shl eax, 0x3
        push eax
        call dword ptr [g_Iat_malloc_004cc5dc]
        mov ecx, dword ptr [edi + 0x80]
        mov edx, dword ptr [edi + 0x90]
        add esp, 0x4
        mov dword ptr [edi + 0x9c], eax
        push ecx
        push edx
        push 0x28
        push eax
        call ebp
        mov ecx, dword ptr [edi + 0x90]
        add esp, 0x10
        cmp eax, ecx
        jz L_46dbcc
        mov eax, dword ptr [edi + 0x80]
        push eax
        call dword ptr [g_Iat_fclose_004cc5c0]
        mov ecx, dword ptr [edi + 0x9c]
        add esp, 0x4
        mov dword ptr [edi + 0x80], esi
        push ecx
        jmp L_46dcfe
    L_46dbcc:
        mov eax, dword ptr [edi + 0x8c]
        mov edx, dword ptr [g_Data_004da000 + 0x63778]
        cmp eax, esi
        mov dword ptr [edi + 0xa0], edx
        jle L_46dd17
        mov ebx, dword ptr [g_Data_004da000 + 0x63778]
        lea eax, [esp + 0x14]
        push eax
        lea edx, [esp + 0x14]
        lea ecx, [esp + 0x1c]
        call Pixfmt_GetFormat
        mov eax, dword ptr [g_Data_004da000 + 0x63778]
        mov ecx, dword ptr [edi + 0x8c]
        mov edx, dword ptr [g_Data_004da000 + 0x6377c]
        add eax, ecx
        mov dword ptr [g_Data_004da000 + 0x63778], eax
        lea ecx, [eax*0x4 + 0x0]
        push ecx
        push edx
        call dword ptr [g_Iat_realloc_004cc4ec]
        mov dword ptr [g_Data_004da000 + 0x6377c], eax
        mov eax, dword ptr [g_Data_004da000 + 0x63778]
        add esp, 0x8
        cmp ebx, eax
        jge L_46dd17
    L_46dc3a:
        push 0x200
        call dword ptr [g_Iat_malloc_004cc5dc]
        mov ecx, dword ptr [g_Data_004da000 + 0x6377c]
        add esp, 0x4
        mov dword ptr [ecx + ebx*0x4], eax
        mov edx, dword ptr [edi + 0x80]
        mov eax, dword ptr [g_Data_004da000 + 0x6377c]
        push edx
        push 0x100
        push 0x2
        mov ecx, dword ptr [eax + ebx*0x4]
        push ecx
        call ebp
        add esp, 0x10
        cmp eax, 0x100
        jnz L_46dce1
        cmp dword ptr [esp + 0x10], 0x5
        jnz L_46dca9
        xor edx, edx
    L_46dc7d:
        mov eax, dword ptr [g_Data_004da000 + 0x6377c]
        mov ecx, dword ptr [eax + ebx*0x4]
        xor eax, eax
        mov AX, word ptr [ecx + edx*0x1]
        lea esi, [ecx + edx*0x1]
        mov ecx, eax
        sar ecx, 0x1
        xor AL, CL
        add edx, 0x2
        and eax, 0x1f
        xor eax, ecx
        cmp edx, 0x200
        mov word ptr [esi], AX
        jl L_46dc7d
        xor esi, esi
    L_46dca9:
        mov eax, dword ptr [g_Data_004da000 + 0x6377c]
        mov edx, 0x100
        mov ecx, dword ptr [eax + ebx*0x4]
        call Image_BuildShadeLevels
        mov ecx, dword ptr [g_Data_004da000 + 0x6377c]
        inc ebx
        mov dword ptr [ecx + ebx*0x4 - 0x4], eax
        mov eax, dword ptr [g_Data_004da000 + 0x63778]
        cmp ebx, eax
        jl L_46dc3a
        mov eax, dword ptr [edi + 0x80]
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_46dce1:
        mov edx, dword ptr [edi + 0x80]
        push edx
        call dword ptr [g_Iat_fclose_004cc5c0]
        mov eax, dword ptr [edi + 0x9c]
        add esp, 0x4
        mov dword ptr [edi + 0x80], esi
        push eax
    L_46dcfe:
        call dword ptr [g_Iat_free_004cc5b4]
        add esp, 0x4
        mov dword ptr [edi + 0x9c], esi
        xor eax, eax
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    L_46dd17:
        mov eax, dword ptr [edi + 0x80]
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    }
}

// 0x0046da40 TextureArchiveListB_OpenImageZbd - ../../04_spec/systems/texture.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall TextureArchiveListB_OpenImageZbd(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x63770]
        push ebx
        push esi
        push edi
        test eax, eax
        jg L_46dad9
        inc eax
        lea ecx, [eax + eax*0x4]
        lea edx, [eax + ecx*0x8]
        mov eax, dword ptr [g_Data_004da000 + 0x63774]
        shl edx, 0x2
        push edx
        push eax
        call dword ptr [g_Iat_realloc_004cc4ec]
        mov ecx, dword ptr [g_Data_004da000 + 0x63770]
        mov dword ptr [g_Data_004da000 + 0x63774], eax
        add esp, 0x8
        lea edx, [ecx + ecx*0x4]
        lea ecx, [ecx + edx*0x8]
        lea ebx, [eax + ecx*0x4]
        mov ecx, 0x29
        xor eax, eax
        mov edi, ebx
        rep stosd
        mov edi, offset g_Data_004da000 + 0x67ec
        or ecx, 0xffffffff
        repne scasb
        not ecx
        sub edi, ecx
        mov edx, ecx
        mov esi, edi
        mov edi, ebx
        shr ecx, 0x2
        rep movsd
        mov ecx, edx
        and ecx, 0x3
        rep movsb
        mov ecx, ebx
        call TextureArchive_Open
        test eax, eax
        jnz L_46dad3
        push offset g_Data_004da000 + 0x67ec
        push offset g_Data_004da000 + 0x67e8
        push ebx
        call dword ptr [g_Iat_sprintf_004cc5c4]
        add esp, 0xc
        mov ecx, ebx
        call TextureArchive_Open
        test eax, eax
        jz L_46dad9
    L_46dad3:
        inc dword ptr [g_Data_004da000 + 0x63770]
    L_46dad9:
        pop edi
        pop esi
        pop ebx
        ret
    }
}

// 0x0046df50 TextureArchiveListA_OpenBySize - ../../04_spec/systems/texture.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall TextureArchiveListA_OpenBySize(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x63768]
        sub esp, 0x34
        test eax, eax
        push ebx
        push ebp
        push esi
        push edi
        jle L_46dfb0
        xor ebx, ebx
        test eax, eax
        jle L_46e234
        xor edi, edi
    L_46df6c:
        mov ecx, dword ptr [g_Data_004da000 + 0x6376c]
        lea esi, [ecx + edi*0x1]
        mov ecx, dword ptr [ecx + edi*0x1 + 0x80]
        test ecx, ecx
        jnz L_46df9d
        mov ecx, dword ptr [g_Data_004da000 + 0x63794]
        push offset g_Data_004da000 + 0xf54
        mov edx, esi
        call File_OpenOnSearchPath
        mov dword ptr [esi + 0x80], eax
        mov eax, dword ptr [g_Data_004da000 + 0x63768]
    L_46df9d:
        inc ebx
        add edi, 0xa4
        cmp ebx, eax
        jl L_46df6c
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0x34
        ret
    L_46dfb0:
        lea edx, [esp + 0x20]
        or ecx, 0xffffffff
        push edx
        lea edx, [esp + 0x18]
        mov dword ptr [esp + 0x1c], 0x0
        call dword ptr [g_Data_004da000 + 0x91c30]
        test eax, eax
        jz L_46e013
        mov eax, dword ptr [g_Data_004da000 + 0x91be8]
        test eax, eax
        jz L_46e013
        mov eax, dword ptr [esp + 0x14]
        mov ebx, dword ptr [g_Iat_sprintf_004cc5c4]
        shr eax, 0x14
        push offset g_Data_004da000 + 0x2b70
        mov dword ptr [esp + 0x18], eax
        mov dword ptr [esp + 0x14], eax
        push eax
        push offset g_Data_004da000 + 0x6844
        lea eax, [esp + 0x30]
        push offset g_Data_004da000 + 0x6838
        push eax
        call ebx
        add esp, 0x14
        mov dword ptr [esp + 0x18], 0x1
        jmp L_46e0f5
    L_46e013:
        mov ecx, dword ptr [g_Data_004da000 + 0x877f0]
        mov eax, dword ptr [ecx]
        dec eax
        cmp eax, 0x3
        ja L_46e0d3
        cmp eax, 0
        je L_46e02c
        cmp eax, 1
        je L_46e058
        cmp eax, 2
        je L_46e081
        cmp eax, 3
        je L_46e0aa
        int 3  // unreachable: the bounds check above excludes other indices
    L_46e02c:
        mov ebx, dword ptr [g_Iat_sprintf_004cc5c4]
        push offset g_Data_004da000 + 0x2b70
        push offset g_Data_004da000 + 0x6844
        lea edx, [esp + 0x2c]
        push offset g_Data_004da000 + 0x6830
        push edx
        call ebx
        add esp, 0x10
        mov dword ptr [esp + 0x10], 0x8
        jmp L_46e0f5
    L_46e058:
        mov ebx, dword ptr [g_Iat_sprintf_004cc5c4]
        push offset g_Data_004da000 + 0x2b70
        push offset g_Data_004da000 + 0x6844
        lea eax, [esp + 0x2c]
        push offset g_Data_004da000 + 0x6828
        push eax
        call ebx
        add esp, 0x10
        mov dword ptr [esp + 0x10], 0x6
        jmp L_46e0f5
    L_46e081:
        mov ebx, dword ptr [g_Iat_sprintf_004cc5c4]
        push offset g_Data_004da000 + 0x2b70
        push offset g_Data_004da000 + 0x6844
        lea ecx, [esp + 0x2c]
        push offset g_Data_004da000 + 0x6820
        push ecx
        call ebx
        add esp, 0x10
        mov dword ptr [esp + 0x10], 0x4
        jmp L_46e0f5
    L_46e0aa:
        mov ebx, dword ptr [g_Iat_sprintf_004cc5c4]
        push offset g_Data_004da000 + 0x2b70
        push offset g_Data_004da000 + 0x6844
        lea edx, [esp + 0x2c]
        push offset g_Data_004da000 + 0x6818
        push edx
        call ebx
        add esp, 0x10
        mov dword ptr [esp + 0x10], 0x2
        jmp L_46e0f5
    L_46e0d3:
        mov ebx, dword ptr [g_Iat_sprintf_004cc5c4]
        push offset g_Data_004da000 + 0x6808
        lea eax, [esp + 0x28]
        push offset g_Data_004da000 + 0x97c
        push eax
        mov dword ptr [esp + 0x1c], 0x8
        call ebx
        add esp, 0xc
    L_46e0f5:
        mov ecx, dword ptr [g_Data_004da000 + 0x63768]
        lea eax, [ecx + 0x1]
        mov ecx, dword ptr [g_Data_004da000 + 0x6376c]
        lea edx, [eax + eax*0x4]
        lea eax, [eax + edx*0x8]
        shl eax, 0x2
        push eax
        push ecx
        call dword ptr [g_Iat_realloc_004cc4ec]
        mov ecx, dword ptr [g_Data_004da000 + 0x63768]
        mov dword ptr [g_Data_004da000 + 0x6376c], eax
        add esp, 0x8
        lea edx, [ecx + ecx*0x4]
        lea ecx, [ecx + edx*0x8]
        lea ebp, [eax + ecx*0x4]
        mov ecx, 0x29
        xor eax, eax
        mov edi, ebp
        rep stosd
        lea edi, [esp + 0x24]
        or ecx, 0xffffffff
        repne scasb
        not ecx
        sub edi, ecx
        mov dword ptr [esp + 0x1c], ebp
        mov edx, ecx
        mov esi, edi
        mov edi, ebp
        shr ecx, 0x2
        rep movsd
        mov ecx, edx
        and ecx, 0x3
        rep movsb
        mov ecx, ebp
        call TextureArchive_Open
        mov eax, dword ptr [ebp + 0x80]
        test eax, eax
        jnz L_46e22e
        mov ebp, dword ptr [esp + 0x10]
        cmp ebp, -0x1
        jl L_46e220
    L_46e17c:
        test ebp, ebp
        jle L_46e1b5
        mov eax, dword ptr [esp + 0x18]
        push offset g_Data_004da000 + 0x2b70
        test eax, eax
        push ebp
        push offset g_Data_004da000 + 0x6844
        jz L_46e1a4
        lea eax, [esp + 0x30]
        push offset g_Data_004da000 + 0x6838
        push eax
        call ebx
        add esp, 0x14
        jmp L_46e1e6
    L_46e1a4:
        lea ecx, [esp + 0x30]
        push offset g_Data_004da000 + 0x6800
        push ecx
        call ebx
        add esp, 0x14
        jmp L_46e1e6
    L_46e1b5:
        jnz L_46e1cd
        push offset g_Data_004da000 + 0x6808
        lea edx, [esp + 0x28]
        push offset g_Data_004da000 + 0x97c
        push edx
        call ebx
        add esp, 0xc
        jmp L_46e1e6
    L_46e1cd:
        push offset g_Data_004da000 + 0x2b70
        push offset g_Data_004da000 + 0x6844
        lea eax, [esp + 0x2c]
        push offset g_Data_004da000 + 0x67f8
        push eax
        call ebx
        add esp, 0x10
    L_46e1e6:
        lea edi, [esp + 0x24]
        or ecx, 0xffffffff
        xor eax, eax
        repne scasb
        mov eax, dword ptr [esp + 0x1c]
        not ecx
        sub edi, ecx
        mov edx, ecx
        mov esi, edi
        mov edi, eax
        shr ecx, 0x2
        rep movsd
        mov ecx, edx
        and ecx, 0x3
        rep movsb
        mov ecx, eax
        call TextureArchive_Open
        test eax, eax
        jnz L_46e220
        dec ebp
        cmp ebp, -0x1
        jge L_46e17c
    L_46e220:
        mov ebp, dword ptr [esp + 0x1c]
        mov eax, dword ptr [ebp + 0x80]
        test eax, eax
        jz L_46e234
    L_46e22e:
        inc dword ptr [g_Data_004da000 + 0x63768]
    L_46e234:
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0x34
        ret
    }
}

// 0x0046d940 Image_LoadFromArchive - ../../04_spec/systems/texture.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Image_LoadFromArchive(int, int)
{
    __asm {
        sub esp, 0xc
        mov eax, dword ptr [g_Data_004da000 + 0x63770]
        push ebx
        xor ebx, ebx
        push ebp
        push esi
        cmp eax, ebx
        push edi
        mov dword ptr [esp + 0x18], ecx
        jnz L_46d95b
        call TextureArchiveListB_OpenImageZbd
    L_46d95b:
        mov eax, dword ptr [g_Data_004da000 + 0x63770]
        mov dword ptr [esp + 0x14], ebx
        cmp eax, ebx
        jle L_46da28
        mov dword ptr [esp + 0x10], ebx
    L_46d970:
        test ebx, ebx
        jnz L_46da28
        mov eax, dword ptr [g_Data_004da000 + 0x63774]
        mov ecx, dword ptr [esp + 0x10]
        lea esi, [eax + ecx*0x1]
        mov eax, dword ptr [eax + ecx*0x1 + 0x80]
        test eax, eax
        jz L_46da03
        mov eax, dword ptr [esi + 0x90]
        mov edi, dword ptr [esi + 0x9c]
        xor ebp, ebp
        test eax, eax
        jle L_46da03
    L_46d9a1:
        test ebx, ebx
        jnz L_46da03
        mov edx, dword ptr [esp + 0x18]
        push edx
        push edi
        call dword ptr [g_Iat__stricmp_004cc4c8]
        add esp, 0x8
        test eax, eax
        jnz L_46d9f5
        mov ecx, dword ptr [esi + 0x80]
        push eax
        mov eax, dword ptr [edi + 0x20]
        push eax
        push ecx
        call dword ptr [g_Iat_fseek_004cc490]
        mov ecx, dword ptr [esi + 0x80]
        add esp, 0xc
        call Image_CreateProcedural
        mov ebx, eax
        mov eax, dword ptr [edi + 0x24]
        cmp eax, -0x1
        jz L_46d9f5
        mov edx, dword ptr [esi + 0xa0]
        add edx, eax
        mov eax, dword ptr [g_Data_004da000 + 0x6377c]
        mov ecx, dword ptr [eax + edx*0x4]
        mov dword ptr [ebx + 0x18], ecx
    L_46d9f5:
        mov eax, dword ptr [esi + 0x90]
        inc ebp
        add edi, 0x28
        cmp ebp, eax
        jl L_46d9a1
    L_46da03:
        mov eax, dword ptr [esp + 0x14]
        mov edx, dword ptr [esp + 0x10]
        mov ecx, dword ptr [g_Data_004da000 + 0x63770]
        inc eax
        add edx, 0xa4
        cmp eax, ecx
        mov dword ptr [esp + 0x14], eax
        mov dword ptr [esp + 0x10], edx
        jl L_46d970
    L_46da28:
        pop edi
        pop esi
        mov eax, ebx
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    }
}

// 0x0046dd30 Image_LoadFromArchiveListA - ../../04_spec/systems/texture.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Image_LoadFromArchiveListA(int, int)
{
    __asm {
        sub esp, 0xc
        mov eax, dword ptr [g_Data_004da000 + 0x63768]
        push ebx
        push ebp
        push esi
        xor esi, esi
        push edi
        cmp eax, esi
        mov dword ptr [esp + 0x18], ecx
        mov dword ptr [esp + 0x14], esi
        jle L_46de43
        mov dword ptr [esp + 0x10], esi
    L_46dd52:
        test esi, esi
        jnz L_46de43
        mov eax, dword ptr [g_Data_004da000 + 0x6376c]
        mov ecx, dword ptr [esp + 0x10]
        lea edi, [eax + ecx*0x1]
        mov eax, dword ptr [eax + ecx*0x1 + 0x80]
        test eax, eax
        jz L_46de1e
        mov eax, dword ptr [edi + 0x90]
        mov ebp, dword ptr [edi + 0x9c]
        xor ebx, ebx
        test eax, eax
        jle L_46de1e
    L_46dd8b:
        test esi, esi
        jnz L_46de1e
        mov edx, dword ptr [esp + 0x18]
        push edx
        push ebp
        call dword ptr [g_Iat__stricmp_004cc4c8]
        add esp, 0x8
        test eax, eax
        jnz L_46de0c
        mov ecx, dword ptr [edi + 0x80]
        push eax
        mov eax, dword ptr [ebp + 0x20]
        push eax
        push ecx
        call dword ptr [g_Iat_fseek_004cc490]
        mov ecx, dword ptr [edi + 0x80]
        add esp, 0xc
        call Image_CreateProcedural
        mov esi, eax
        mov eax, dword ptr [ebp + 0x24]
        cmp eax, -0x1
        jz L_46de0c
        mov eax, dword ptr [esi + 0x18]
        test eax, eax
        jz L_46ddf0
        push eax
        call dword ptr [g_Iat_free_004cc5b4]
        mov AL, byte ptr [esi + 0x9]
        add esp, 0x4
        and AL, 0x7f
        mov dword ptr [esi + 0x18], 0x0
        mov byte ptr [esi + 0x9], AL
    L_46ddf0:
        mov word ptr [esi + 0xe], 0x100
        mov edx, dword ptr [edi + 0xa0]
        mov eax, dword ptr [ebp + 0x24]
        add edx, eax
        mov eax, dword ptr [g_Data_004da000 + 0x6377c]
        mov ecx, dword ptr [eax + edx*0x4]
        mov dword ptr [esi + 0x18], ecx
    L_46de0c:
        mov eax, dword ptr [edi + 0x90]
        inc ebx
        add ebp, 0x28
        cmp ebx, eax
        jl L_46dd8b
    L_46de1e:
        mov eax, dword ptr [esp + 0x14]
        mov edx, dword ptr [esp + 0x10]
        mov ecx, dword ptr [g_Data_004da000 + 0x63768]
        inc eax
        add edx, 0xa4
        cmp eax, ecx
        mov dword ptr [esp + 0x14], eax
        mov dword ptr [esp + 0x10], edx
        jl L_46dd52
    L_46de43:
        mov eax, esi
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0xc
        ret
    }
}

// 0x0046d900 Image_Load - ../../04_spec/systems/texture.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Image_Load(int, int)
{
    __asm {
        push esi
        push edi
        mov edi, ecx
        call Image_LoadFromArchiveListA
        mov esi, eax
        test esi, esi
        jnz L_46d91c
        mov ecx, edi
        call Image_LoadFromArchive
        mov esi, eax
        test esi, esi
        jz L_46d930
    L_46d91c:
        test byte ptr [esi + 0x9], 0x2
        jz L_46d930
        mov eax, dword ptr [esi + 0x14]
        test eax, eax
        jz L_46d930
        mov ecx, esi
        call Image_ApplyAlphaMask
    L_46d930:
        mov eax, esi
        pop edi
        pop esi
        ret
    }
}

// 0x0046de50 TextureManager_LoadPending - ../../04_spec/systems/render.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall TextureManager_LoadPending(int, int)
{
    __asm {
        push ebx
        call TextureArchiveListA_OpenBySize
        mov eax, dword ptr [g_Data_004da000 + 0x63798]
        xor ebx, ebx
        test eax, eax
        jle L_46df46
        push edi
        push esi
        push ebp
        mov esi, offset g_Data_004da000 + 0x637a4
        mov ebp, 0x2
    L_46de72:
        mov eax, dword ptr [esi + 0x14]
        cmp eax, ebp
        jz L_46de82
        cmp eax, 0x3
        jnz L_46df32
    L_46de82:
        mov ecx, esi
        call Image_Load
        lea edi, [esi - 0x8]
        mov dword ptr [esi + 0x18], 0x0
        test eax, eax
        mov dword ptr [edi], eax
        jnz L_46deb3
        mov eax, dword ptr [g_Data_004da000 + 0x63788]
        test eax, eax
        jz L_46dea8
        mov ecx, esi
        call eax
        mov dword ptr [edi], eax
    L_46dea8:
        cmp dword ptr [edi], 0x0
        jnz L_46deb3
        mov dword ptr [edi], offset g_Data_004da000 + 0x66e0
    L_46deb3:
        mov ecx, edi
        call TextureSlot_LoadMipChain
        mov eax, dword ptr [g_Data_004da000 + 0x91be8]
        test eax, eax
        jz L_46df24
        mov ecx, edi
        call Texture_IsSoftwareOnly
        test eax, eax
        jnz L_46df24
        cmp dword ptr [esi + 0x14], 0x3
        jnz L_46dee4
        mov eax, dword ptr [edi]
        mov ecx, dword ptr [esi - 0x4]
        push eax
        xor edx, edx
        call dword ptr [g_Data_004da000 + 0x91c18]
        jmp L_46df2b
    L_46dee4:
        mov eax, dword ptr [esi - 0x4]
        test eax, eax
        jnz L_46df2b
        mov edi, dword ptr [edi]
        xor eax, eax
        mov AX, word ptr [edi + 0xc]
        mov DL, byte ptr [edi + 0x9]
        mov ecx, eax
        and eax, 0x1
        shr ecx, 0x1
        and ecx, 0x1
        and edx, ebp
        push ecx
        push eax
        push edx
        mov edx, edi
        mov ecx, esi
        call dword ptr [g_Data_004da000 + 0x91c08]
        mov dword ptr [esi - 0x4], eax
        mov eax, dword ptr [g_Data_004da000 + 0x91be8]
        cmp eax, ebp
        jz L_46df2b
        mov ecx, edi
        call Image_FreeOwnedBuffers
        jmp L_46df2b
    L_46df24:
        mov ecx, dword ptr [edi]
        call Image_PrepareSoftwareSampling
    L_46df2b:
        mov dword ptr [esi + 0x14], 0x1
    L_46df32:
        mov eax, dword ptr [g_Data_004da000 + 0x63798]
        inc ebx
        add esi, 0x24
        cmp ebx, eax
        jl L_46de72
        pop ebp
        pop esi
        pop edi
    L_46df46:
        call TextureArchive_CloseAllFiles
        xor eax, eax
        pop ebx
        ret
    }
}

}  // namespace recoil
