// SUBSYSTEM: zeffect
// zeffect members with no original-file attribution (ledger orig_file empty).
// Instruction-level ports generated by tools/asm_port/port_batch.py from the Ghidra listings.
#include "unattributed/zeffect.h"
#include "platform/image/original_data.h"
#include "GameZRecoil/zFMV/fmv_main.h"
#include "GameZRecoil/zVideo/zvid_dd.h"
#include "platform/iat_winmm.h"
#include "GameZRecoil/zClass/Object3d.h"
#include "GameZRecoil/zClass/Seq.h"
#include "GameZRecoil/zEffect/zeff_anim_init.h"
#include "platform/iat_msvcrt.h"
#include "unattributed/savegame.h"
#include "unattributed/sysinfo.h"
#include "unattributed/zclass_nodes.h"
#include "GameZRecoil/zClass/Class.h"
#include "GameZRecoil/zReader/zreader.h"
#include "GameZRecoil/zClass/Light.h"
#include "GameZRecoil/zClass/Sound.h"
#include "GameZRecoil/zClass/cls_world.h"
#include "GameZRecoil/zDEClient/zdec_crater.h"
#include "GameZRecoil/zEffect/zeff_anim_run.h"
#include "GameZRecoil/zEffect/zeff_init.h"
#include "unattributed/render_frame.h"
#include "unattributed/ui_widgets.h"

namespace recoil {

// 0x00460480 EffectList_EntryAt - [0x0053a2d8] + index ECX * 0x50 (no bounds check)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall EffectList_EntryAt(int, int)
{
    __asm {
        lea eax, [ecx + ecx*0x4]
        mov ecx, dword ptr [g_Data_004da000 + 0x602d8]
        shl eax, 0x4
        add eax, ecx
        ret
    }
}

// 0x00462540 EffectCmd_SetVec1C - copies four dwords from the argument to [ECX+0x1C..0x28]; flags [ECX] |= 0x40000
// Register/stack shape from the listing (ECX, EDX, 4 stack bytes).
__declspec(naked) int __fastcall EffectCmd_SetVec1C(int, int, int)
{
    __asm {
        mov edx, dword ptr [esp + 0x4]
        push esi
        lea eax, [ecx + 0x1c]
        mov esi, dword ptr [edx]
        mov dword ptr [eax], esi
        mov esi, dword ptr [edx + 0x4]
        mov dword ptr [eax + 0x4], esi
        mov esi, dword ptr [edx + 0x8]
        mov dword ptr [eax + 0x8], esi
        pop esi
        mov edx, dword ptr [edx + 0xc]
        mov dword ptr [eax + 0xc], edx
        mov eax, dword ptr [ecx]
        or eax, 0x40000
        mov dword ptr [ecx], eax
        ret 0x4
    }
}

// 0x0049aa40 LensFlare_SetTexture - ECX index 0..3: [0x0056b250+i*4]=EDX; enabled [0x0056b248] = all four set
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall LensFlare_SetTexture(int, int)
{
    __asm {
        test ecx, ecx
        jl L_49aa50
        cmp ecx, 0x4
        jge L_49aa50
        mov dword ptr [ecx*0x4 + g_Data_004da000 + 0x91250], edx
    L_49aa50:
        mov ecx, dword ptr [g_Data_004da000 + 0x91250]
        test ecx, ecx
        jz L_49aa82
        mov ecx, dword ptr [g_Data_004da000 + 0x91254]
        test ecx, ecx
        jz L_49aa82
        mov ecx, dword ptr [g_Data_004da000 + 0x91258]
        test ecx, ecx
        jz L_49aa82
        mov ecx, dword ptr [g_Data_004da000 + 0x9125c]
        mov dword ptr [g_Data_004da000 + 0x91248], 0x1
        test ecx, ecx
        jnz L_49aa8c
    L_49aa82:
        mov dword ptr [g_Data_004da000 + 0x91248], 0x0
    L_49aa8c:
        ret
    }
}

// 0x00462280 Effect_FindTemplateByName - ../../04_spec/structs/weapon_two_struct_split.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Effect_FindTemplateByName(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x9ba44]
        push ebx
        push ebp
        xor ebp, ebp
        push esi
        push edi
        test eax, eax
        jle L_4622e4
        mov eax, dword ptr [g_Data_004da000 + 0x9ba50]
        lea edi, [eax + 0x8]
    L_462297:
        mov esi, dword ptr [edi]
        mov edx, ecx
    L_46229b:
        mov AL, byte ptr [edx]
        mov BL, AL
        cmp AL, byte ptr [esi]
        jnz L_4622bf
        test BL, BL
        jz L_4622bb
        mov AL, byte ptr [edx + 0x1]
        mov BL, AL
        cmp AL, byte ptr [esi + 0x1]
        jnz L_4622bf
        add edx, 0x2
        add esi, 0x2
        test BL, BL
        jnz L_46229b
    L_4622bb:
        xor edx, edx
        jmp L_4622c4
    L_4622bf:
        sbb edx, edx
        sbb edx, -0x1
    L_4622c4:
        test edx, edx
        jz L_4622dd
        mov eax, dword ptr [g_Data_004da000 + 0x9ba44]
        inc ebp
        add edi, 0x48
        cmp ebp, eax
        jl L_462297
        or eax, 0xffffffff
        pop edi
        pop esi
        pop ebp
        pop ebx
        ret
    L_4622dd:
        mov eax, ebp
        pop edi
        pop esi
        pop ebp
        pop ebx
        ret
    L_4622e4:
        pop edi
        pop esi
        pop ebp
        or eax, 0xffffffff
        pop ebx
        ret
    }
}

// 0x004a5b20 CallOptionalHook_0056b568 - If function pointer [0x0056b568] non-null, calls it with ECX pushed as the one cdecl arg and returns its result; else returns 0.
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall CallOptionalHook_0056b568(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x91568]
        test eax, eax
        jz L_4a5b30
        push ecx
        call eax
        add esp, 0x4
        ret
    L_4a5b30:
        xor eax, eax
        ret
    }
}

// 0x00462370 MciVideo_OpenAndPlay - ECX=video desc. 0x004a7d70 then MCI_OPEN (0x803, flags 0x2202) type string MPEGVideo [0x004dfb1c], device id stored ECX+4; MCI_WINDOW 0x841 flags 0x10002; if desc bit 0x40000 MCI_PUT 0x842 0x50002 rect from [7..10]; if bit 0x20000 MCI_PUT 0x30002 rect [3..6]; MCI_SET 0x811 0x302 time format 0x1b; MC
// Register/stack shape from the listing (ECX, EDX, 12 stack bytes).
__declspec(naked) int __fastcall MciVideo_OpenAndPlay(int, int, int, int, int)
{
    __asm {
        sub esp, 0x58
        push esi
        push edi
        mov esi, ecx
        call Render_FlipToGDISurface
        mov eax, dword ptr [esi + 0x2c]
        mov edi, dword ptr [g_Iat_mciSendCommandA_004cc6e8]
        lea ecx, [esp + 0x44]
        mov dword ptr [esp + 0x4c], offset g_Data_004da000 + 0x5b1c
        push ecx
        push 0x2202
        push 0x803
        push 0x0
        mov dword ptr [esp + 0x60], eax
        call edi
        test eax, eax
        jz L_4623b0
        push eax
        mov ecx, esi
        call Mci_ReportError
    L_4623b0:
        mov eax, dword ptr [esp + 0x48]
        mov edx, dword ptr [esi + 0x8]
        lea ecx, [esp + 0x20]
        mov word ptr [esi + 0x4], AX
        push ecx
        push 0x10002
        and eax, 0xffff
        push 0x841
        push eax
        mov dword ptr [esp + 0x34], edx
        call edi
        test eax, eax
        jnz L_4624de
        test dword ptr [esi], 0x40000
        jz L_462426
        mov eax, dword ptr [esi + 0x1c]
        mov edx, dword ptr [esi + 0x24]
        mov ecx, dword ptr [esi + 0x28]
        mov dword ptr [esp + 0x34], eax
        sub edx, eax
        mov eax, dword ptr [esi + 0x20]
        mov dword ptr [esp + 0x3c], edx
        mov dword ptr [esp + 0x38], eax
        sub ecx, eax
        lea edx, [esp + 0x30]
        xor eax, eax
        push edx
        mov AX, word ptr [esi + 0x4]
        push 0x50002
        push 0x842
        push eax
        mov dword ptr [esp + 0x50], ecx
        call edi
        test eax, eax
        jnz L_4624de
    L_462426:
        test dword ptr [esi], 0x20000
        jz L_46246a
        mov eax, dword ptr [esi + 0xc]
        mov ecx, dword ptr [esi + 0x14]
        mov edx, dword ptr [esi + 0x18]
        mov dword ptr [esp + 0x34], eax
        sub ecx, eax
        mov eax, dword ptr [esi + 0x10]
        mov dword ptr [esp + 0x38], eax
        sub edx, eax
        mov dword ptr [esp + 0x3c], ecx
        lea eax, [esp + 0x30]
        xor ecx, ecx
        push eax
        mov CX, word ptr [esi + 0x4]
        push 0x30002
        push 0x842
        push ecx
        mov dword ptr [esp + 0x50], edx
        call edi
        test eax, eax
        jnz L_4624de
    L_46246a:
        mov edx, dword ptr [esi + 0x8]
        lea eax, [esp + 0x14]
        xor ecx, ecx
        push eax
        mov CX, word ptr [esi + 0x4]
        push 0x302
        push 0x811
        push ecx
        mov dword ptr [esp + 0x28], 0x1b
        mov dword ptr [esp + 0x2c], edx
        call edi
        test eax, eax
        jnz L_4624de
        mov ecx, dword ptr [esp + 0x64]
        mov edx, dword ptr [esi + 0x8]
        mov dword ptr [esp + 0xc], ecx
        mov ecx, dword ptr [esp + 0x68]
        test ecx, ecx
        mov eax, 0x6
        mov dword ptr [esp + 0x8], edx
        jl L_4624ba
        mov dword ptr [esp + 0x10], ecx
        mov eax, 0xe
    L_4624ba:
        cmp dword ptr [esp + 0x6c], 0x1
        jnz L_4624c6
        or eax, 0x10000
    L_4624c6:
        lea edx, [esp + 0x8]
        push edx
        push eax
        xor eax, eax
        push 0x806
        mov AX, word ptr [esi + 0x4]
        push eax
        call edi
        test eax, eax
        jz L_4624e6
    L_4624de:
        push eax
        mov ecx, esi
        call Mci_ReportError
    L_4624e6:
        pop edi
        pop esi
        add esp, 0x58
        ret 0xc
    }
}

// 0x00460490 Anim_SaveActivationRecords_00460490 - ../../04_spec/systems/zeffect.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Anim_SaveActivationRecords_00460490(int, int)
{
    __asm {
        mov eax, 0x4484
        call Crt_ChkStk
        mov dword ptr [esp + 0x14], ecx
        mov eax, 0x1
        mov ecx, dword ptr [g_Data_004da000 + 0x602e0]
        push ebx
        push ebp
        xor ebp, ebp
        push esi
        push edi
        test ecx, ecx
        mov dword ptr [esp + 0x20], ebp
        jle L_4606c5
        xor esi, esi
        mov dword ptr [esp + 0x14], esi
        jmp L_4604c7
    L_4604c3:
        mov esi, dword ptr [esp + 0x14]
    L_4604c7:
        test eax, eax
        jz L_4606c5
        mov eax, dword ptr [g_Data_004da000 + 0x602d8]
        lea ecx, [eax + esi*0x1 + 0x8]
        call Anim_FindByName
        mov ecx, dword ptr [g_Data_004da000 + 0x602d8]
        mov ebx, eax
        lea edi, [esp + 0x3c]
        mov dword ptr [esp + 0x18], ebx
        lea eax, [ecx + esi*0x1]
        mov ecx, 0x14
        mov esi, eax
        rep movsd
        xor esi, esi
        cmp ebx, esi
        jz L_460656
        mov ecx, dword ptr [eax + 0x28]
        call ClsRecord_FromIndex
        mov DL, byte ptr [ebx + 0x98]
        mov ecx, ebx
        mov byte ptr [esp + 0x90], DL
        mov edx, eax
        call AnimInstance_BindNode
        cmp dword ptr [ebx + 0x110], esi
        jz L_46065e
        mov AL, byte ptr [ebx + 0x105]
        mov dword ptr [esp + 0x1c], esi
        mov byte ptr [esp + 0x91], AL
        mov AL, byte ptr [ebx + 0x105]
        test AL, AL
        jbe L_460666
        mov dword ptr [esp + 0x10], esi
        lea ebp, [esp + 0x9c]
        jmp L_46055d
    L_460559:
        mov ebx, dword ptr [esp + 0x18]
    L_46055d:
        mov ecx, dword ptr [ebx + 0x110]
        mov edx, dword ptr [esp + 0x10]
        mov ebx, dword ptr [edx + ecx*0x1 + 0x24]
        test ebx, ebx
        jz L_46061e
        cmp dword ptr [ebx + 0x34], 0x5
        jnz L_46061e
        mov esi, dword ptr [ebx + 0x38]
        mov ecx, ebx
        call ClsRecord_ActiveIndex
        mov dword ptr [ebp - 0x8], eax
        mov eax, dword ptr [ebx + 0x24]
        shr eax, 0x2
        and eax, 0x1
        mov dword ptr [ebp - 0x4], eax
        mov eax, dword ptr [esi]
        shr eax, 0x4
        and eax, 0x1
        mov dword ptr [ebp], eax
        jz L_4605b8
        mov ecx, ebx
        call Object3D_GetLocalMatrix
        lea edi, [ebp + 0x4]
        mov ecx, 0xc
        mov esi, eax
        rep movsd
        jmp L_4605ee
    L_4605b8:
        lea ecx, [ebp + 0xc]
        lea edx, [ebp + 0x8]
        push ecx
        push edx
        lea edx, [ebp + 0x4]
        mov ecx, ebx
        call Object3D_GetPosition
        lea eax, [ebp + 0x18]
        lea ecx, [ebp + 0x14]
        push eax
        push ecx
        lea edx, [ebp + 0x10]
        mov ecx, ebx
        call Object3D_GetRotation
        lea edx, [ebp + 0x24]
        lea eax, [ebp + 0x20]
        push edx
        push eax
        lea edx, [ebp + 0x1c]
        mov ecx, ebx
        call Object3D_GetScale
    L_4605ee:
        mov eax, dword ptr [ebx + 0x3c]
        test eax, eax
        jz L_460614
        mov edx, dword ptr [eax + 0x4]
        mov ecx, dword ptr [ebp + 0x34]
        shr edx, 0x3
        and ecx, 0xfffffffe
        and edx, 0x1
        or ecx, edx
        mov dword ptr [ebp + 0x34], ecx
        mov eax, dword ptr [ebx + 0x3c]
        mov ecx, dword ptr [eax + 0x20]
        mov dword ptr [ebp + 0x38], ecx
        jmp L_460625
    L_460614:
        mov eax, dword ptr [ebp + 0x34]
        and AL, 0xfe
        mov dword ptr [ebp + 0x34], eax
        jmp L_460625
    L_46061e:
        mov dword ptr [ebp - 0x8], 0xffffffff
    L_460625:
        mov ecx, dword ptr [esp + 0x18]
        mov eax, dword ptr [esp + 0x1c]
        mov esi, dword ptr [esp + 0x10]
        xor edx, edx
        mov DL, byte ptr [ecx + 0x105]
        inc eax
        add esi, 0x60
        add ebp, 0x44
        cmp eax, edx
        mov dword ptr [esp + 0x1c], eax
        mov dword ptr [esp + 0x10], esi
        jl L_460559
        mov ebp, dword ptr [esp + 0x20]
        jmp L_460666
    L_460656:
        mov byte ptr [esp + 0x90], 0x0
    L_46065e:
        mov byte ptr [esp + 0x91], 0x0
    L_460666:
        push ebp
        lea edx, [esp + 0x2c]
        push offset g_Data_004da000 + 0x59bc
        push edx
        call dword ptr [g_Iat_sprintf_004cc5c4]
        mov eax, dword ptr [esp + 0x9d]
        add esp, 0xc
        and eax, 0xff
        mov ecx, eax
        shl ecx, 0x4
        add ecx, eax
        lea eax, [esp + 0x3c]
        lea edx, [ecx*0x4 + 0x58]
        mov ecx, dword ptr [esp + 0x24]
        push edx
        push eax
        lea edx, [esp + 0x30]
        call SaveGame_WriteRecord
        mov ecx, dword ptr [g_Data_004da000 + 0x602e0]
        inc ebp
        mov edx, dword ptr [esp + 0x14]
        mov dword ptr [esp + 0x20], ebp
        add edx, 0x50
        cmp ebp, ecx
        mov dword ptr [esp + 0x14], edx
        jl L_4604c3
    L_4606c5:
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0x4484
        ret
    }
}

// 0x004621b0 Effect_UpdateScalePulse_004621b0 - ../../04_spec/systems/zeffect.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Effect_UpdateScalePulse_004621b0(int, int)
{
    __asm {
        push ecx
        push esi
        mov esi, ecx
        test byte ptr [esi + 0x24], 0x4
        jz L_462274
        mov edx, dword ptr [esi + 0x40]
        fld dword ptr [g_Data_004da000 + 0x91424]
        fadd dword ptr [edx + 0x34]
        fcom dword ptr [edx + 0x14]
        fst dword ptr [edx + 0x34]
        fnstsw AX
        test AH, 0x1
        jz L_4621fb
        fstp st(0)
        fld dword ptr [edx + 0x18]
        fmul dword ptr [g_Data_004da000 + 0x91424]
        fadd dword ptr [edx + 0x38]
        fst dword ptr [esp + 0x4]
        mov eax, dword ptr [esp + 0x4]
        fstp dword ptr [edx + 0x38]
        push eax
        push eax
        push eax
        call Object3D_SetScale
        pop esi
        pop ecx
        ret
    L_4621fb:
        fcomp dword ptr [edx + 0x30]
        fnstsw AX
        test AH, 0x1
        jz L_46223c
        fld dword ptr [edx + 0x24]
        fmul dword ptr [g_Data_004da000 + 0x91424]
        fsubr dword ptr [edx + 0x38]
        fcom qword ptr [g_RData_004cc000 + 0x6518]
        fstp dword ptr [edx + 0x38]
        fnstsw AX
        test AH, 0x1
        jz L_462228
        mov dword ptr [edx + 0x38], 0x3c23d70a
    L_462228:
        mov eax, dword ptr [edx + 0x38]
        mov ecx, esi
        push eax
        push eax
        push eax
        mov dword ptr [esp + 0x10], eax
        call Object3D_SetScale
        pop esi
        pop ecx
        ret
    L_46223c:
        mov dword ptr [esi + 0x40], 0x0
        mov ecx, dword ptr [g_Data_004da000 + 0x9ba4c]
        call Container_ListAppend
        xor edx, edx
        mov ecx, esi
        call gwNodeSetActionCallback
        xor edx, edx
        mov ecx, esi
        call gwNodeSetActive
        mov eax, dword ptr [esi + 0x54]
        test eax, eax
        jz L_462274
        mov ecx, dword ptr [g_Data_004da000 + 0x9ba54]
        mov edx, esi
        call gwNodeDetachChildByClass
    L_462274:
        pop esi
        pop ecx
        ret
    }
}

// 0x00458bb0 Effect_TickLifetime_00458bb0 - ../../04_spec/systems/zeffect.md
// Register/stack shape from the listing (ECX, EDX, 8 stack bytes).
__declspec(naked) int __fastcall Effect_TickLifetime_00458bb0(int, int, int, int)
{
    __asm {
        mov eax, dword ptr [edx + 0x54]
        test AH, 0x2
        jnz L_458bfc
        mov AL, byte ptr [ecx + 0x99]
        test AL, AL
        jz L_458bc6
        cmp AL, 0x2
        jnz L_458bfc
    L_458bc6:
        fld dword ptr [ecx + 0xb0]
        fsub dword ptr [esp + 0x8]
        fcom dword ptr [g_RData_004cc000 + 0x6460]
        fstp dword ptr [ecx + 0xb0]
        fnstsw AX
        test AH, 0x41
        jz L_458bfc
        push 0x0
        push 0x0
        push 0x0
        push 0x0
        push 0x0
        push 0x0
        push 0x0
        push 0x0
        push 0x0
        xor edx, edx
        call AnimInstance_SetTransformVelocity
    L_458bfc:
        xor eax, eax
        ret 0x8
    }
}

// 0x0045d010 Anim_UpdateInstance_0045d010 - ../../04_spec/systems/zeffect.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Anim_UpdateInstance_0045d010(int, int)
{
    __asm {
        push ecx
        push ebx
        push ebp
        push esi
        push edi
        test ecx, ecx
        mov dword ptr [esp + 0x10], 0x1
        jz L_45d231
        mov esi, dword ptr [ecx + 0x40]
        test esi, esi
        jz L_45d231
        mov eax, dword ptr [esi + 0x94]
        mov ecx, eax
        and ecx, 0x2
        jnz L_45d045
        test AL, 0xc
        jz L_45d181
    L_45d045:
        mov AL, byte ptr [esi + 0x9b]
        test AL, AL
        jbe L_45d05d
        dec AL
        mov byte ptr [esi + 0x9b], AL
        pop edi
        pop esi
        pop ebp
        pop ebx
        pop ecx
        ret
    L_45d05d:
        test ecx, ecx
        jz L_45d0b2
        mov eax, dword ptr [g_Data_004da000 + 0x9bdc0]
        test eax, eax
        jz L_45d231
        mov ecx, dword ptr [esi + 0x64]
        call Anim_SquaredDistanceToEventAnchor
        fcom dword ptr [esi + 0x9c]
        fnstsw AX
        test AH, 0x1
        jnz L_45d0a0
        fcomp dword ptr [esi + 0xa0]
        fnstsw AX
        test AH, 0x1
        jnz L_45d0b2
        mov AL, byte ptr [g_Data_004da000 + 0x5fea8]
        mov byte ptr [esi + 0x9b], AL
        jmp L_45d134
    L_45d0a0:
        mov AL, byte ptr [g_Data_004da000 + 0x5fea8]
        fstp st(0)
        mov byte ptr [esi + 0x9b], AL
        jmp L_45d134
    L_45d0b2:
        test byte ptr [esi + 0x94], 0x8
        jz L_45d112
        mov eax, dword ptr [g_Data_004da000 + 0x9bdc4]
        test eax, eax
        jz L_45d231
        mov edx, dword ptr [g_Data_004da000 + 0x9bdd4]
        xor ecx, ecx
        mov dword ptr [g_Data_004da000 + 0xa3a28], edx
        mov eax, dword ptr [esi + 0x64]
        mov CL, byte ptr [eax + 0x30]
        call Render_IsNodeTypeEnabledForRender
        test eax, eax
        jnz L_45d112
        mov CL, byte ptr [g_Data_004da000 + 0x5fea8]
        mov byte ptr [esi + 0x9b], CL
        mov AL, byte ptr [g_Data_004da000 + 0x5fea8]
        inc AL
        cmp AL, 0xa
        mov byte ptr [g_Data_004da000 + 0x5fea8], AL
        jbe L_45d231
        mov byte ptr [g_Data_004da000 + 0x5fea8], 0x1
        pop edi
        pop esi
        pop ebp
        pop ebx
        pop ecx
        ret
    L_45d112:
        test byte ptr [esi + 0x94], 0x4
        jz L_45d181
        mov ecx, dword ptr [esi + 0x64]
        mov eax, dword ptr [ecx + 0x24]
        test eax, 0x80000000
        jnz L_45d179
        mov DL, byte ptr [g_Data_004da000 + 0x5fea8]
        mov byte ptr [esi + 0x9b], DL
    L_45d134:
        mov DL, byte ptr [g_Data_004da000 + 0x5fea8]
        xor eax, eax
        inc DL
        mov byte ptr [g_Data_004da000 + 0x5fea8], DL
        mov AL, byte ptr [esi + 0x9a]
        mov ecx, dword ptr [g_Data_004da000 + 0x5fea8]
        lea eax, [eax + eax*0x4]
        and ecx, 0xff
        shl eax, 0x1
        cdq
        and edx, 0x3
        add eax, edx
        sar eax, 0x2
        cmp ecx, eax
        jle L_45d231
        mov byte ptr [g_Data_004da000 + 0x5fea8], 0x1
        pop edi
        pop esi
        pop ebp
        pop ebx
        pop ecx
        ret
    L_45d179:
        and eax, 0x7fffffff
        mov dword ptr [ecx + 0x24], eax
    L_45d181:
        fld dword ptr [g_Data_004da000 + 0x91424]
        fadd dword ptr [esi + 0xa8]
        mov AL, byte ptr [esi + 0x104]
        mov edi, dword ptr [esi + 0xc0]
        xor ebp, ebp
        test AL, AL
        fstp dword ptr [esi + 0xa8]
        jbe L_45d212
        mov BL, 0x5
    L_45d1a7:
        mov edx, dword ptr [g_Data_004da000 + 0x91424]
        mov dword ptr [g_Data_004da000 + 0x9bdd8], edx
        mov AL, byte ptr [edi + 0x20]
        test AL, AL
        jz L_45d1be
        cmp AL, 0x1
        jnz L_45d202
    L_45d1be:
        mov edx, edi
        mov ecx, esi
        call AnimInstance_RunSequence
        test eax, eax
        jz L_45d1ef
        push edi
        push esi
        push offset g_Data_004da000 + 0x56ec
        push 0x180f
        push offset g_Data_004da000 + 0x5674
        push 0x400
        mov byte ptr [esi + 0x98], BL
        call Debug_ReportNoop
        add esp, 0x18
    L_45d1ef:
        mov AL, byte ptr [edi + 0x20]
        test AL, AL
        jz L_45d1fa
        cmp AL, 0x1
        jnz L_45d202
    L_45d1fa:
        mov dword ptr [esp + 0x10], 0x0
    L_45d202:
        xor eax, eax
        inc ebp
        mov AL, byte ptr [esi + 0x104]
        add edi, 0x40
        cmp ebp, eax
        jl L_45d1a7
    L_45d212:
        mov eax, dword ptr [esp + 0x10]
        test eax, eax
        jz L_45d231
        mov eax, dword ptr [esi + 0x6c]
        test eax, eax
        jz L_45d22a
        mov edx, dword ptr [esi + 0x70]
        push 0x0
        mov ecx, esi
        call eax
    L_45d22a:
        mov ecx, esi
        call Effect_StopOrFade
    L_45d231:
        pop edi
        pop esi
        pop ebp
        pop ebx
        pop ecx
        ret
    }
}

// 0x0045d4c0 Anim_UpdateSingleChannel_0045d4c0 - ../../04_spec/systems/zeffect.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Anim_UpdateSingleChannel_0045d4c0(int, int)
{
    __asm {
        push ebx
        push esi
        test ecx, ecx
        push edi
        mov ebx, 0x1
        jnz L_45d4d3
        or eax, 0xffffffff
        pop edi
        pop esi
        pop ebx
        ret
    L_45d4d3:
        mov esi, dword ptr [ecx + 0x40]
        test esi, esi
        jnz L_45d4e1
        or eax, 0xffffffff
        pop edi
        pop esi
        pop ebx
        ret
    L_45d4e1:
        fld dword ptr [g_Data_004da000 + 0x91424]
        fadd dword ptr [esi + 0xa8]
        mov eax, dword ptr [esi + 0xfc]
        test eax, eax
        fstp dword ptr [esi + 0xa8]
        jz L_45d557
        mov eax, dword ptr [g_Data_004da000 + 0x91424]
        lea edi, [esi + 0xc4]
        mov dword ptr [g_Data_004da000 + 0x9bdd8], eax
        mov AL, byte ptr [edi + 0x20]
        test AL, AL
        jz L_45d518
        cmp AL, 0x1
        jnz L_45d557
    L_45d518:
        mov edx, edi
        mov ecx, esi
        call AnimInstance_RunSequence
        test eax, eax
        jz L_45d54a
        push edi
        push esi
        push offset g_Data_004da000 + 0x56ec
        push 0x196d
        push offset g_Data_004da000 + 0x5674
        push 0x400
        mov byte ptr [esi + 0x98], 0x5
        call Debug_ReportNoop
        add esp, 0x18
    L_45d54a:
        mov AL, byte ptr [edi + 0x20]
        test AL, AL
        jz L_45d555
        cmp AL, 0x1
        jnz L_45d557
    L_45d555:
        xor ebx, ebx
    L_45d557:
        test ebx, ebx
        jz L_45d562
        mov ecx, esi
        call AnimInstance_Stop
    L_45d562:
        pop edi
        pop esi
        xor eax, eax
        pop ebx
        ret
    }
}

// 0x00460060 EffectList_ResetAndFree - bytes read: call 0x00460330 then tail-jump EffectList_FreeIfLoaded (ECX passed through)
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall EffectList_ResetAndFree(int, int)
{
    __asm {
        call EffectConfig_Release
        jmp EffectList_FreeIfLoaded
    }
}

// 0x00461040 Anim_LoadActivationRecord_00461040 - ../../04_spec/systems/zeffect.md
// Register/stack shape from the listing (ECX, EDX, 12 stack bytes).
__declspec(naked) int __fastcall Anim_LoadActivationRecord_00461040(int, int, int, int, int)
{
    __asm {
        sub esp, 0xb0
        mov edx, dword ptr [esp + 0xb8]
        mov ecx, dword ptr [esp + 0xb4]
        push ebp
        call SaveSystem_WriteToTempFile
        xor ebp, ebp
        mov dword ptr [esp + 0x4], eax
        cmp eax, ebp
        jz L_461426
        push edi
        push esi
        push ebx
        push eax
        push 0x1
        lea eax, [esp + 0x5c]
        push 0x68
        push eax
        call dword ptr [g_Iat_fread_004cc4e0]
        mov eax, dword ptr [esp + 0x64]
        add esp, 0x10
        lea ecx, [eax + eax*0x8]
        lea edx, [eax + ecx*0x2]
        mov ecx, dword ptr [g_Data_004da000 + 0x9bdac]
        lea eax, [eax + edx*0x4]
        lea edi, [ecx + eax*0x4]
        mov ecx, dword ptr [esp + 0x7c]
        call ClsRecord_FromIndex
        cmp dword ptr [esp + 0x58], ebp
        jz L_4610fa
        mov ecx, dword ptr [edi + 0x130]
        cmp ecx, ebp
        jz L_4610be
    L_4610ad:
        cmp dword ptr [edi + 0x40], eax
        jz L_4610be
        mov edi, ecx
        mov ecx, dword ptr [edi + 0x130]
        cmp ecx, ebp
        jnz L_4610ad
    L_4610be:
        cmp dword ptr [edi + 0x40], eax
        jz L_4610fa
        mov ecx, dword ptr [edi + 0x130]
        mov DL, 0x2
        cmp ecx, ebp
        jz L_4610e3
    L_4610cf:
        cmp byte ptr [edi + 0x98], DL
        jnz L_4610e3
        mov edi, ecx
        mov ecx, dword ptr [edi + 0x130]
        cmp ecx, ebp
        jnz L_4610cf
    L_4610e3:
        cmp byte ptr [edi + 0x98], DL
        jnz L_4610fa
        mov edx, eax
        mov ecx, edi
        call AnimInstance_Clone
        mov dword ptr [edi + 0x130], eax
    L_4610fa:
        mov ecx, dword ptr [edi + 0x94]
        or CH, 0x40
        mov dword ptr [edi + 0x94], ecx
        mov ecx, dword ptr [esp + 0x80]
        call ClsRecord_FromIndex
        mov dword ptr [edi + 0x74], eax
        mov eax, dword ptr [esp + 0x84]
        lea edx, [edi + 0x78]
        mov dword ptr [edi + 0x78], eax
        mov ecx, dword ptr [esp + 0x88]
        mov dword ptr [edx + 0x4], ecx
        mov eax, dword ptr [esp + 0x8c]
        mov dword ptr [edx + 0x8], eax
        mov ecx, dword ptr [esp + 0x90]
        call ClsRecord_FromIndex
        mov dword ptr [edi + 0x84], eax
        mov edx, dword ptr [esp + 0x94]
        lea ecx, [edi + 0x88]
        mov dword ptr [esp + 0x14], ebp
        mov dword ptr [ecx], edx
        mov eax, dword ptr [esp + 0x98]
        mov dword ptr [ecx + 0x4], eax
        mov edx, dword ptr [esp + 0x9c]
        mov dword ptr [ecx + 0x8], edx
        mov AL, byte ptr [esp + 0xa0]
        mov byte ptr [edi + 0x98], AL
        mov ecx, dword ptr [esp + 0xa4]
        mov dword ptr [edi + 0xa8], ecx
        mov edx, dword ptr [esp + 0xa8]
        mov dword ptr [edi + 0xb0], edx
        mov ecx, dword ptr [esp + 0xac]
        lea eax, [edi + 0xb4]
        mov dword ptr [edi + 0xb4], ecx
        mov edx, dword ptr [esp + 0xb0]
        mov dword ptr [eax + 0x4], edx
        mov ecx, dword ptr [esp + 0xb4]
        mov dword ptr [eax + 0x8], ecx
        mov DL, byte ptr [esp + 0xb8]
        mov AL, DL
        mov byte ptr [edi + 0x104], DL
        test AL, AL
        jbe L_461269
        mov ebx, dword ptr [g_Iat_malloc_004cc5dc]
    L_4611dd:
        mov eax, dword ptr [edi + 0xc0]
        mov eax, dword ptr [ebp + eax*0x1 + 0x38]
        test eax, eax
        jz L_461203
        push eax
        call dword ptr [g_Iat_free_004cc5b4]
        mov ecx, dword ptr [edi + 0xc0]
        add esp, 0x4
        mov dword ptr [ebp + ecx*0x1 + 0x38], 0x0
    L_461203:
        mov edx, dword ptr [esp + 0x10]
        mov ecx, dword ptr [edi + 0xc0]
        mov esi, ebp
        push edx
        add esi, ecx
        push 0x1
        push 0x40
        push esi
        call dword ptr [g_Iat_fread_004cc4e0]
        mov eax, dword ptr [esi + 0x3c]
        add esp, 0x10
        test eax, eax
        jle L_46124d
        push eax
        call ebx
        mov ecx, dword ptr [esi + 0x34]
        mov edx, dword ptr [esi + 0x3c]
        add ecx, eax
        add esp, 0x4
        mov dword ptr [esi + 0x34], ecx
        mov ecx, dword ptr [esp + 0x10]
        push ecx
        push 0x1
        push edx
        push eax
        mov dword ptr [esi + 0x38], eax
        call dword ptr [g_Iat_fread_004cc4e0]
        add esp, 0x10
    L_46124d:
        mov eax, dword ptr [esp + 0x14]
        xor ecx, ecx
        mov CL, byte ptr [edi + 0x104]
        inc eax
        add ebp, 0x40
        cmp eax, ecx
        mov dword ptr [esp + 0x14], eax
        jl L_4611dd
    L_461269:
        mov AL, byte ptr [esp + 0xb9]
        xor ebx, ebx
        test AL, AL
        jbe L_461334
    L_46127a:
        mov edx, dword ptr [esp + 0x10]
        lea eax, [esp + 0x18]
        push edx
        push 0x1
        push 0x38
        push eax
        call dword ptr [g_Iat_fread_004cc4e0]
        mov eax, dword ptr [esp + 0x4c]
        add esp, 0x10
        test eax, eax
        jz L_46131e
        lea edx, [esp + 0x18]
        mov ecx, edi
        call AnimNode_AddLightEntry
        test eax, eax
        jl L_46131e
        lea ecx, [eax + eax*0x4]
        lea edx, [eax + ecx*0x2]
        mov eax, dword ptr [edi + 0x118]
        mov esi, dword ptr [eax + edx*0x4 + 0x24]
        lea ebp, [eax + edx*0x4]
        mov eax, dword ptr [eax + edx*0x4 + 0x28]
        test eax, eax
        jnz L_46131e
        test esi, esi
        jz L_46131e
        mov edx, 0x1
        mov ecx, esi
        call gwNodeSetActive
        mov ecx, dword ptr [esp + 0x4c]
        test ecx, ecx
        jl L_4612f4
        mov eax, dword ptr [esi + 0x54]
        test eax, eax
        jnz L_4612f4
        call ClsRecord_FromIndex
        mov edx, esi
        mov ecx, eax
        call gwNodeAttachChildByClass
    L_4612f4:
        mov ecx, dword ptr [esp + 0x48]
        mov edx, dword ptr [esp + 0x44]
        mov eax, dword ptr [esp + 0x40]
        push ecx
        push edx
        push eax
        mov ecx, esi
        call Light_SetVec14
        mov ecx, dword ptr [g_Data_004da000 + 0x9bdb8]
        mov edx, esi
        call World_AddLight
        mov dword ptr [ebp + 0x28], 0x1
    L_46131e:
        mov ecx, dword ptr [esp + 0xb9]
        inc ebx
        and ecx, 0xff
        cmp ebx, ecx
        jl L_46127a
    L_461334:
        mov AL, byte ptr [esp + 0xba]
        xor ebx, ebx
        test AL, AL
        jbe L_461407
    L_461345:
        mov edx, dword ptr [esp + 0x10]
        lea eax, [esp + 0x18]
        push edx
        push 0x1
        push 0x3c
        push eax
        call dword ptr [g_Iat_fread_004cc4e0]
        mov eax, dword ptr [esp + 0x4c]
        add esp, 0x10
        test eax, eax
        jz L_4613f1
        lea edx, [esp + 0x18]
        mov ecx, edi
        call AnimNode_AddSoundEntry
        test eax, eax
        jl L_4613f1
        lea ecx, [eax + eax*0x4]
        lea edx, [eax + ecx*0x2]
        mov eax, dword ptr [edi + 0x11c]
        mov esi, dword ptr [eax + edx*0x4 + 0x24]
        lea ebp, [eax + edx*0x4]
        mov eax, dword ptr [eax + edx*0x4 + 0x28]
        test eax, eax
        jnz L_4613f1
        test esi, esi
        jz L_4613f1
        mov edx, 0x1
        mov ecx, esi
        call gwNodeSetActive
        mov ecx, dword ptr [esp + 0x50]
        test ecx, ecx
        jl L_4613bf
        mov eax, dword ptr [esi + 0x54]
        test eax, eax
        jnz L_4613bf
        call ClsRecord_FromIndex
        mov edx, esi
        mov ecx, eax
        call gwNodeAttachChildByClass
    L_4613bf:
        mov eax, dword ptr [esp + 0x40]
        test eax, eax
        jz L_4613dd
        mov ecx, dword ptr [esp + 0x4c]
        mov edx, dword ptr [esp + 0x48]
        mov eax, dword ptr [esp + 0x44]
        push ecx
        push edx
        push eax
        mov ecx, esi
        call Sound_SetVec30
    L_4613dd:
        mov ecx, dword ptr [g_Data_004da000 + 0x9bdb8]
        mov edx, esi
        call World_AddSound
        mov dword ptr [ebp + 0x28], 0x1
    L_4613f1:
        mov ecx, dword ptr [esp + 0xba]
        inc ebx
        and ecx, 0xff
        cmp ebx, ecx
        jl L_461345
    L_461407:
        mov edx, dword ptr [edi + 0x68]
        mov dword ptr [edx + 0x40], edi
        mov ecx, dword ptr [edi + 0x68]
        mov edx, offset Anim_UpdateInstance_0045d010
        call gwNodeSetActionCallbackFirst
        mov ecx, dword ptr [esp + 0x10]
        call SaveSystem_RemoveTempFiles
        pop ebx
        pop esi
        pop edi
    L_461426:
        pop ebp
        add esp, 0xb0
        ret 0xc
    }
}

// 0x00461670 Anim_RestoreNodesFromRecord_00461670 - ../../04_spec/systems/zeffect.md
// Register/stack shape from the listing (ECX, EDX, 12 stack bytes).
__declspec(naked) int __fastcall Anim_RestoreNodesFromRecord_00461670(int, int, int, int, int)
{
    __asm {
        push ebx
        push ebp
        mov ebp, dword ptr [esp + 0xc]
        push esi
        push edi
        mov eax, dword ptr [ebp + 0x50]
        lea ecx, [eax + eax*0x8]
        lea edx, [eax + ecx*0x2]
        mov ecx, dword ptr [g_Data_004da000 + 0x9bdac]
        lea eax, [eax + edx*0x4]
        lea esi, [ecx + eax*0x4]
        test esi, esi
        jz L_4617f3
        mov eax, dword ptr [esi + 0x94]
        mov edi, 0x4000
        test edi, eax
        jnz L_4617f3
        cmp byte ptr [ebp + 0x54], 0x1
        jnz L_4616ea
        mov AL, byte ptr [esi + 0x98]
        cmp AL, 0x1
        jz L_4616ea
        cmp AL, 0x4
        jnz L_4616c3
        mov byte ptr [esi + 0x98], 0x3
    L_4616c3:
        mov edx, dword ptr [esi + 0x40]
        mov ecx, esi
        call Wrap_0045d570_Arg1
        push esi
        push offset g_Data_004da000 + 0x5ad8
        push 0x419
        push offset g_Data_004da000 + 0x5a58
        push 0x100
        call Debug_ReportNoop
        add esp, 0x14
    L_4616ea:
        mov BL, 0x2
    L_4616ec:
        test dword ptr [esi + 0x94], edi
        jnz L_461723
        cmp byte ptr [esi + 0x98], BL
        jnz L_461723
        mov edx, dword ptr [esi + 0x40]
        mov ecx, esi
        call Wrap_0045d570_Arg1
        push esi
        push offset g_Data_004da000 + 0x5ad8
        push 0x41f
        push offset g_Data_004da000 + 0x5a58
        push 0x100
        call Debug_ReportNoop
        add esp, 0x14
    L_461723:
        mov esi, dword ptr [esi + 0x130]
        test esi, esi
        jnz L_4616ec
        mov AL, byte ptr [ebp + 0x55]
        xor ebx, ebx
        test AL, AL
        jbe L_4617f3
        lea esi, [ebp + 0x5c]
        mov ebp, 0x5
    L_461742:
        mov ecx, dword ptr [esi - 0x4]
        call ClsRecord_FromIndex
        mov edi, eax
        test edi, edi
        jz L_4617de
        cmp dword ptr [edi + 0x34], ebp
        jnz L_4617de
        mov edx, dword ptr [esi]
        push edx
        push edi
        push offset g_Data_004da000 + 0x59cc
        push 0x426
        push offset g_Data_004da000 + 0x5a58
        push 0x100
        call Debug_ReportNoop
        mov ecx, dword ptr [esi]
        add esp, 0x18
        xor edx, edx
        test ecx, ecx
        setnz DL
        mov ecx, edi
        call gwNodeSetActive
        cmp dword ptr [esi], 0x0
        jz L_4617de
        mov eax, dword ptr [esi + 0x4]
        test eax, eax
        jz L_4617a5
        lea edx, [esi + 0x8]
        mov ecx, edi
        call Object3D_SetLocalMatrix
        jmp L_4617de
    L_4617a5:
        mov eax, dword ptr [esi + 0x10]
        mov ecx, dword ptr [esi + 0xc]
        mov edx, dword ptr [esi + 0x8]
        push eax
        push ecx
        push edx
        mov ecx, edi
        call Object3D_SetPosition
        mov eax, dword ptr [esi + 0x1c]
        mov ecx, dword ptr [esi + 0x18]
        mov edx, dword ptr [esi + 0x14]
        push eax
        push ecx
        push edx
        mov ecx, edi
        call Object3D_SetRotation
        mov eax, dword ptr [esi + 0x28]
        mov ecx, dword ptr [esi + 0x24]
        mov edx, dword ptr [esi + 0x20]
        push eax
        push ecx
        push edx
        mov ecx, edi
        call Object3D_SetScale
    L_4617de:
        mov ecx, dword ptr [esp + 0x14]
        xor eax, eax
        inc ebx
        add esi, 0x44
        mov AL, byte ptr [ecx + 0x55]
        cmp ebx, eax
        jl L_461742
    L_4617f3:
        pop edi
        pop esi
        pop ebp
        pop ebx
        ret 0xc
    }
}

}  // namespace recoil
