// SUBSYSTEM: sound
// Original file: GameZRecoil/zSound/zsnd_cd.cpp (ledger orig_file).
// Instruction-level ports generated by tools/asm_port/port_batch.py from the Ghidra listings.
#include "GameZRecoil/zSound/zsnd_cd.h"
#include "platform/image/original_data.h"
#include "GameZRecoil/zSound/zsnd_create.h"
#include "platform/iat_winmm.h"
#include "platform/iat_msvcrt.h"
#include "platform/mfc42.h"
#include "GameZRecoil/zSound/zsnd_parm.h"
#include "platform/msvc_eh.h"

namespace recoil {

// 0x004a2490 SoundCD_ResetTrackState - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall SoundCD_ResetTrackState(int, int)
{
    __asm {
        mov eax, 0x1
        xor ecx, ecx
        xor edx, edx
        mov dword ptr [g_Data_004da000 + 0x91340], eax
        mov dword ptr [g_Data_004da000 + 0x91344], ecx
        mov dword ptr [g_Data_004da000 + 0x91348], edx
        mov dword ptr [g_Data_004da000 + 0x9134c], eax
        mov dword ptr [g_Data_004da000 + 0x91350], ecx
        mov dword ptr [g_Data_004da000 + 0x91354], edx
        mov dword ptr [g_Data_004da000 + 0x91358], eax
        mov dword ptr [g_Data_004da000 + 0x9135c], ecx
        mov dword ptr [g_Data_004da000 + 0x91360], edx
        ret
    }
}

// 0x004a27d0 SoundCD_HasVolumeControl - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall SoundCD_HasVolumeControl(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x91324]
        test AL, 0x2
        jnz L_4a27dc
        xor eax, eax
        ret
    L_4a27dc:
        cmp dword ptr [g_Data_004da000 + 0x9132c], -0x1
        jnz L_4a27e8
        xor eax, eax
        ret
    L_4a27e8:
        and eax, 0x1
        ret
    }
}

// 0x004a2930 SoundCD_GetTrackCount - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall SoundCD_GetTrackCount(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x91324]
        mov ecx, dword ptr [g_Data_004da000 + 0x91334]
        and AL, 0x2
        neg AL
        sbb eax, eax
        and eax, ecx
        ret
    }
}

// 0x004a2e70 Sound_GetSpeedOfSound - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Sound_GetSpeedOfSound(int, int)
{
    __asm {
        fld dword ptr [g_Data_004da000 + 0x8420]
        ret
    }
}

// 0x004a2e80 Sound_SetSpeedOfSound - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 4 stack bytes).
__declspec(naked) int __fastcall Sound_SetSpeedOfSound(int, int, int)
{
    __asm {
        fld dword ptr [g_RData_004cc000 + 0x6efc]
        fdiv dword ptr [esp + 0x4]
        mov eax, dword ptr [esp + 0x4]
        mov dword ptr [g_Data_004da000 + 0x8420], eax
        fstp dword ptr [g_Data_004da000 + 0x8424]
        ret 0x4
    }
}

// 0x004a2950 Sound_SetListenerFromMatrix - ../../04_spec/systems/scene_render.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall Sound_SetListenerFromMatrix(int, int)
{
    __asm {
        mov eax, dword ptr [g_Data_004da000 + 0x912ac]
        push ebx
        push esi
        sub eax, 0x0
        push edi
        mov ebx, edx
        mov esi, ecx
        jz L_4a29ec
        dec eax
        jnz L_4a2a19
        mov eax, dword ptr [g_Data_004da000 + 0x912b4]
        test eax, eax
        jnz L_4a297c
        or eax, 0xffffffff
        pop edi
        pop esi
        pop ebx
        ret
    L_4a297c:
        test esi, esi
        jz L_4a29c9
        mov edx, dword ptr [esi + 0x2c]
        mov ecx, dword ptr [eax]
        push edx
        mov edx, dword ptr [esi + 0x28]
        push edx
        mov edx, dword ptr [esi + 0x24]
        push edx
        push eax
        call dword ptr [ecx + 0xc]
        mov edx, dword ptr [esi + 0x14]
        mov eax, dword ptr [g_Data_004da000 + 0x912b4]
        fld dword ptr [esi + 0x20]
        mov ecx, dword ptr [eax]
        push edx
        mov edx, dword ptr [esi + 0x10]
        push edx
        mov edx, dword ptr [esi + 0xc]
        push edx
        push ecx
        fchs
        fstp dword ptr [esp]
        fld dword ptr [esi + 0x1c]
        push ecx
        fchs
        fstp dword ptr [esp]
        fld dword ptr [esi + 0x18]
        push ecx
        fchs
        fstp dword ptr [esp]
        push eax
        call dword ptr [ecx + 0x2c]
        mov eax, dword ptr [g_Data_004da000 + 0x912b4]
    L_4a29c9:
        test ebx, ebx
        jz L_4a2a19
        mov edx, dword ptr [ebx + 0x8]
        mov ecx, dword ptr [eax]
        push edx
        mov edx, dword ptr [ebx + 0x4]
        push edx
        mov edx, dword ptr [ebx]
        push edx
        push eax
        call dword ptr [ecx + 0x3c]
        mov eax, 0x1
        mov dword ptr [g_Data_004da000 + 0x9136c], eax
        pop edi
        pop esi
        pop ebx
        ret
    L_4a29ec:
        test esi, esi
        jz L_4a29fc
        mov ecx, 0xc
        mov edi, offset g_Data_004da000 + 0x91370
        rep movsd
    L_4a29fc:
        test ebx, ebx
        jz L_4a2a19
        mov eax, dword ptr [ebx]
        mov dword ptr [g_Data_004da000 + 0x913a0], eax
        mov ecx, dword ptr [ebx + 0x4]
        mov dword ptr [g_Data_004da000 + 0x913a4], ecx
        mov edx, dword ptr [ebx + 0x8]
        mov dword ptr [g_Data_004da000 + 0x913a8], edx
    L_4a2a19:
        mov eax, 0x1
        pop edi
        pop esi
        mov dword ptr [g_Data_004da000 + 0x9136c], eax
        pop ebx
        ret
    }
}

// 0x004a2600 SoundCD_Play - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall SoundCD_Play(int, int)
{
    __asm {
        mov AL, byte ptr [g_Data_004da000 + 0x91324]
        sub esp, 0xc
        test AL, 0x2
        push esi
        mov esi, ecx
        jnz L_4a2616
        xor eax, eax
        pop esi
        add esp, 0xc
        ret
    L_4a2616:
        mov eax, dword ptr [g_Data_004da000 + 0x9134c]
        mov edx, dword ptr [g_Data_004da000 + 0x91334]
        cmp esi, 0x2
        jz L_4a262e
        cmp esi, 0x5
        lea ecx, [edx + 0x1]
        jnz L_4a2631
    L_4a262e:
        lea ecx, [eax + 0x1]
    L_4a2631:
        and eax, 0xff
        mov dword ptr [g_Data_004da000 + 0x91358], ecx
        mov dword ptr [esp + 0x8], eax
        mov eax, ecx
        and eax, 0xff
        cmp ecx, edx
        mov dword ptr [esp + 0xc], eax
        mov eax, dword ptr [g_Data_004da000 + 0x912a8]
        mov dword ptr [esp + 0x4], eax
        mov eax, 0x5
        ja L_4a2662
        mov eax, 0xd
    L_4a2662:
        mov edx, dword ptr [g_Data_004da000 + 0x91328]
        lea ecx, [esp + 0x4]
        push ecx
        push eax
        and edx, 0xffff
        push 0x806
        push edx
        call dword ptr [g_Iat_mciSendCommandA_004cc6e8]
        test eax, eax
        jz L_4a269a
        push 0xf1
        mov edx, offset g_Data_004da000 + 0x83f0
        mov ecx, eax
        call SoundCD_ReportMCIError
        pop esi
        add esp, 0xc
        ret
    L_4a269a:
        mov dword ptr [g_Data_004da000 + 0x9131c], esi
        mov eax, 0x1
        pop esi
        add esp, 0xc
        ret
    }
}

// 0x004a26f0 SoundCD_Stop - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall SoundCD_Stop(int, int)
{
    __asm {
        push ecx
        test byte ptr [g_Data_004da000 + 0x91324], 0x2
        jnz L_4a26fe
        xor eax, eax
        pop ecx
        ret
    L_4a26fe:
        mov ecx, dword ptr [g_Data_004da000 + 0x91328]
        lea eax, [esp]
        push eax
        push 0x2
        and ecx, 0xffff
        push 0x808
        push ecx
        call dword ptr [g_Iat_mciSendCommandA_004cc6e8]
        test eax, eax
        jz L_4a2734
        push 0x10e
        mov edx, offset g_Data_004da000 + 0x83f0
        mov ecx, eax
        call SoundCD_ReportMCIError
        pop ecx
        ret
    L_4a2734:
        mov dword ptr [g_Data_004da000 + 0x9131c], 0x0
        call SoundCD_ResetTrackState
        mov eax, 0x1
        pop ecx
        ret
    }
}

// 0x004a2750 SoundCD_PlayTrack - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall SoundCD_PlayTrack(int, int)
{
    __asm {
        mov AL, byte ptr [g_Data_004da000 + 0x91324]
        sub esp, 0x8
        test AL, 0x2
        push esi
        mov esi, ecx
        jnz L_4a2766
        xor eax, eax
        pop esi
        add esp, 0x8
        ret
    L_4a2766:
        mov edx, dword ptr [g_Data_004da000 + 0x91328]
        lea ecx, [esp + 0x4]
        mov eax, esi
        push ecx
        push 0xa
        and edx, 0xffff
        and eax, 0xff
        push 0x807
        push edx
        mov dword ptr [esp + 0x18], eax
        call dword ptr [g_Iat_mciSendCommandA_004cc6e8]
        test eax, eax
        jz L_4a27aa
        push 0x16e
        mov edx, offset g_Data_004da000 + 0x83f0
        mov ecx, eax
        call SoundCD_ReportMCIError
        pop esi
        add esp, 0x8
        ret
    L_4a27aa:
        call SoundCD_ResetTrackState
        mov dword ptr [g_Data_004da000 + 0x9134c], esi
        mov dword ptr [g_Data_004da000 + 0x91358], esi
        mov dword ptr [g_Data_004da000 + 0x91340], esi
        mov eax, 0x1
        pop esi
        add esp, 0x8
        ret
    }
}

// 0x004a27f0 SoundCD_GetVolume - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall SoundCD_GetVolume(int, int)
{
    __asm {
        push ecx
        mov AL, byte ptr [g_Data_004da000 + 0x91324]
        push ebx
        push esi
        push edi
        test AL, 0x2
        mov esi, edx
        mov edi, ecx
        jnz L_4a2808
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        pop ecx
        ret
    L_4a2808:
        call SoundCD_HasVolumeControl
        mov ecx, dword ptr [g_Data_004da000 + 0x9132c]
        mov ebx, eax
        lea eax, [esp + 0xc]
        push eax
        push ecx
        call dword ptr [g_Iat_auxGetVolume_004cc6e0]
        test eax, eax
        jz L_4a283b
        push 0x194
        mov edx, offset g_Data_004da000 + 0x83f0
        mov ecx, eax
        call SoundCD_ReportMCIError
        pop edi
        pop esi
        pop ebx
        pop ecx
        ret
    L_4a283b:
        mov eax, dword ptr [esp + 0xc]
        test ebx, ebx
        mov word ptr [g_Data_004da000 + 0x91330], AX
        jz L_4a2862
        mov word ptr [edi], AX
        shr eax, 0x10
        mov word ptr [g_Data_004da000 + 0x91332], AX
        mov word ptr [esi], AX
        mov eax, 0x1
        pop edi
        pop esi
        pop ebx
        pop ecx
        ret
    L_4a2862:
        mov word ptr [g_Data_004da000 + 0x91332], AX
        mov word ptr [esi], AX
        mov DX, word ptr [g_Data_004da000 + 0x91332]
        mov eax, 0x1
        mov word ptr [edi], DX
        pop edi
        pop esi
        pop ebx
        pop ecx
        ret
    }
}

// 0x004a2880 SoundCD_SetVolume - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall SoundCD_SetVolume(int, int)
{
    __asm {
        sub esp, 0x8
        mov AL, byte ptr [g_Data_004da000 + 0x91324]
        push esi
        push edi
        mov SI, DX
        mov DI, CX
        mov word ptr [esp + 0xc], SI
        test AL, 0x2
        mov word ptr [esp + 0x8], DI
        jnz L_4a28a6
        xor eax, eax
        pop edi
        pop esi
        add esp, 0x8
        ret
    L_4a28a6:
        call SoundCD_HasVolumeControl
        test eax, eax
        jz L_4a28c9
        mov eax, dword ptr [esp + 0xc]
        mov ecx, dword ptr [esp + 0x8]
        and eax, 0xffff
        and ecx, 0xffff
        shl eax, 0x10
        or eax, ecx
        jmp L_4a28e8
    L_4a28c9:
        mov eax, dword ptr [esp + 0x8]
        mov edx, dword ptr [esp + 0xc]
        and eax, 0xffff
        and edx, 0xffff
        add eax, edx
        cdq
        sub eax, edx
        sar eax, 0x1
        and eax, 0xffff
    L_4a28e8:
        push eax
        mov eax, dword ptr [g_Data_004da000 + 0x9132c]
        push eax
        call dword ptr [g_Iat_auxSetVolume_004cc6e4]
        test eax, eax
        jz L_4a2910
        push 0x1b2
        mov edx, offset g_Data_004da000 + 0x83f0
        mov ecx, eax
        call SoundCD_ReportMCIError
        pop edi
        pop esi
        add esp, 0x8
        ret
    L_4a2910:
        mov word ptr [g_Data_004da000 + 0x91330], DI
        mov word ptr [g_Data_004da000 + 0x91332], SI
        pop edi
        mov eax, 0x1
        pop esi
        add esp, 0x8
        ret
    }
}

// 0x004a24d0 SoundCD_Shutdown - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall SoundCD_Shutdown(int, int)
{
    __asm {
        push ecx
        push ebx
        push ebp
        push esi
        push edi
        call SoundCD_Stop
        xor ebp, ebp
        cmp word ptr [g_Data_004da000 + 0x91328], BP
        jz L_4a250f
        mov ecx, dword ptr [g_Data_004da000 + 0x91328]
        lea eax, [esp + 0x10]
        push eax
        push 0x2
        and ecx, 0xffff
        push 0x804
        push ecx
        mov dword ptr [esp + 0x20], ebp
        call dword ptr [g_Iat_mciSendCommandA_004cc6e8]
        mov word ptr [g_Data_004da000 + 0x91328], BP
    L_4a250f:
        mov edi, dword ptr [g_Data_004da000 + 0x91324]
        mov eax, dword ptr [g_Data_004da000 + 0x913e4]
        and edi, 0xfffffffd
        xor edx, edx
        mov dword ptr [g_Data_004da000 + 0x91324], edi
        mov ebx, dword ptr [eax]
        mov edi, ebx
        mov dword ptr [esp + 0x10], eax
        cmp edi, eax
        setz DL
        neg DL
        sbb edx, edx
        inc edx
        test DL, DL
        jz L_4a257d
    L_4a253b:
        mov esi, dword ptr [edi + 0x8]
        cmp esi, ebp
        jz L_4a255d
        mov eax, dword ptr [esi]
        cmp eax, ebp
        jz L_4a2554
        push eax
        call dword ptr [g_Iat_free_004cc5b4]
        add esp, 0x4
        mov dword ptr [esi], ebp
    L_4a2554:
        push esi
        call dword ptr [g_Iat_MFC42_825_004cc2b8]
        add esp, 0x4
    L_4a255d:
        mov ecx, dword ptr [esp + 0x10]
        mov dword ptr [ebx + 0x8], ebp
        mov edi, dword ptr [edi]
        xor eax, eax
        cmp edi, ecx
        mov ebx, dword ptr [ebx]
        setz AL
        neg AL
        sbb eax, eax
        inc eax
        test AL, AL
        jnz L_4a253b
        mov eax, dword ptr [g_Data_004da000 + 0x913e4]
    L_4a257d:
        mov esi, dword ptr [eax]
        xor ecx, ecx
        cmp esi, eax
        mov edi, eax
        setz CL
        neg CL
        sbb ecx, ecx
        inc ecx
        test CL, CL
        jz L_4a25c8
    L_4a2591:
        mov eax, esi
        mov esi, dword ptr [esi]
        push eax
        mov edx, dword ptr [eax + 0x4]
        mov ecx, dword ptr [eax]
        mov dword ptr [edx], ecx
        mov edx, dword ptr [eax]
        mov ecx, dword ptr [eax + 0x4]
        mov dword ptr [edx + 0x4], ecx
        call dword ptr [g_Iat_MFC42_825_004cc2b8]
        mov eax, dword ptr [g_Data_004da000 + 0x913e8]
        add esp, 0x4
        dec eax
        xor edx, edx
        cmp esi, edi
        mov dword ptr [g_Data_004da000 + 0x913e8], eax
        setz DL
        neg DL
        sbb edx, edx
        inc edx
        test DL, DL
        jnz L_4a2591
    L_4a25c8:
        pop edi
        pop esi
        pop ebp
        mov eax, 0x1
        pop ebx
        pop ecx
        ret
    }
}

// 0x004a25e0 SoundCD_PlayIfPrepared - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall SoundCD_PlayIfPrepared(int, int)
{
    __asm {
        push esi
        push edi
        mov edi, edx
        xor esi, esi
        call SoundCD_PlayTrack
        test eax, eax
        jz L_4a25f8
        mov ecx, edi
        call SoundCD_Play
        mov esi, eax
    L_4a25f8:
        mov eax, esi
        pop edi
        pop esi
        ret
    }
}

// 0x004a26b0 SoundCD_OnMciNotify - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall SoundCD_OnMciNotify(int, int)
{
    __asm {
        test byte ptr [g_Data_004da000 + 0x91324], 0x2
        jz L_4a26e5
        cmp dword ptr [g_Data_004da000 + 0x9131c], 0x5
        jnz L_4a26e5
        mov eax, dword ptr [g_Data_004da000 + 0x91328]
        and eax, 0xffff
        cmp edx, eax
        jnz L_4a26e5
        cmp ecx, 0x1
        jnz L_4a26e5
        mov ecx, dword ptr [g_Data_004da000 + 0x9134c]
        mov edx, 0x5
        jmp SoundCD_PlayIfPrepared
    L_4a26e5:
        ret
    }
}

// 0x004a2a70 Sound_Set3DParams_A3D - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 8 stack bytes).
__declspec(naked) int __fastcall Sound_Set3DParams_A3D(int, int, int, int)
{
    __asm {
        push esi
        mov esi, ecx
        push edi
        mov eax, dword ptr [esi + 0x4]
        test eax, eax
        jz L_4a2a83
        or eax, 0xffffffff
        pop edi
        pop esi
        ret 0x8
    L_4a2a83:
        test edx, edx
        jz L_4a2a94
        mov eax, dword ptr [esi + 0x2c]
        test byte ptr [eax + 0xc], 0x4
        jz L_4a2b32
    L_4a2a94:
        mov eax, dword ptr [esi + 0x8]
        test eax, eax
        jnz L_4a2aa3
        or eax, 0xffffffff
        pop edi
        pop esi
        ret 0x8
    L_4a2aa3:
        test edx, edx
        jz L_4a2ab8
        mov edi, dword ptr [edx + 0x8]
        mov ecx, dword ptr [eax]
        push edi
        mov edi, dword ptr [edx + 0x4]
        mov edx, dword ptr [edx]
        push edi
        push edx
        push eax
        call dword ptr [ecx + 0x50]
    L_4a2ab8:
        mov eax, dword ptr [esp + 0xc]
        test eax, eax
        jz L_4a2ad7
        mov edi, dword ptr [eax + 0x8]
        mov ecx, dword ptr [esi + 0x8]
        push edi
        mov edi, dword ptr [eax + 0x4]
        mov eax, dword ptr [eax]
        mov edx, dword ptr [ecx]
        push edi
        push eax
        push ecx
        call dword ptr [edx + 0x80]
    L_4a2ad7:
        call Sound_IsMuted
        test eax, eax
        jz L_4a2af0
        mov eax, dword ptr [esi + 0x8]
        push 0x0
        push eax
        mov ecx, dword ptr [eax]
        call dword ptr [ecx + 0xa0]
        jmp L_4a2b0c
    L_4a2af0:
        mov edx, dword ptr [esi + 0x8]
        mov eax, dword ptr [esi + 0x24]
        push eax
        mov edi, dword ptr [edx]
        call Sound_LoadFloatArg
        push ecx
        mov ecx, dword ptr [esi + 0x8]
        fstp dword ptr [esp]
        push ecx
        call dword ptr [edi + 0xa0]
    L_4a2b0c:
        mov eax, dword ptr [esp + 0x10]
        test eax, eax
        jz L_4a2b1c
        fld qword ptr [g_RData_004cc000 + 0x6ee8]
        jmp L_4a2b22
    L_4a2b1c:
        fld qword ptr [g_RData_004cc000 + 0x6ef0]
    L_4a2b22:
        mov esi, dword ptr [esi + 0x8]
        push ecx
        mov edx, dword ptr [esi]
        fstp dword ptr [esp]
        push esi
        call dword ptr [edx + 0xb0]
    L_4a2b32:
        pop edi
        mov eax, 0x1
        pop esi
        ret 0x8
    }
}

// 0x004a2b40 Sound_Set3DParams_DirectSound - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 8 stack bytes).
__declspec(naked) int __fastcall Sound_Set3DParams_DirectSound(int, int, int, int)
{
    __asm {
        push ebp
        mov ebp, esp
        sub esp, 0x2c
        push ebx
        push esi
        mov esi, ecx
        push edi
        mov eax, dword ptr [esi + 0x4]
        test eax, eax
        jz L_4a2b5e
        or eax, 0xffffffff
        pop edi
        pop esi
        pop ebx
        mov esp, ebp
        pop ebp
        ret 0x8
    L_4a2b5e:
        test edx, edx
        jz L_4a2b6f
        mov eax, dword ptr [esi + 0x2c]
        test byte ptr [eax + 0xc], 0x4
        jz L_4a2e5d
    L_4a2b6f:
        mov eax, dword ptr [esi + 0x8]
        test eax, eax
        jnz L_4a2b82
        or eax, 0xffffffff
        pop edi
        pop esi
        pop ebx
        mov esp, ebp
        pop ebp
        ret 0x8
    L_4a2b82:
        mov eax, dword ptr [g_Data_004da000 + 0x9136c]
        test eax, eax
        jz L_4a2df2
        mov eax, dword ptr [esi + 0x28]
        test eax, eax
        jnz L_4a2b9e
        test edx, edx
        jz L_4a2df2
    L_4a2b9e:
        mov eax, dword ptr [esi + 0x2c]
        mov dword ptr [ebp - 0xc], eax
        cmp dword ptr [eax], 0x0
        jz L_4a2bb5
        or eax, 0xffffffff
        pop edi
        pop esi
        pop ebx
        mov esp, ebp
        pop ebp
        ret 0x8
    L_4a2bb5:
        test edx, edx
        jz L_4a2bd4
        mov dword ptr [esi + 0x28], 0x1
        mov eax, dword ptr [edx]
        lea ecx, [esi + 0xc]
        mov dword ptr [esi + 0xc], eax
        mov eax, dword ptr [edx + 0x4]
        mov dword ptr [ecx + 0x4], eax
        mov edx, dword ptr [edx + 0x8]
        mov dword ptr [ecx + 0x8], edx
    L_4a2bd4:
        mov eax, dword ptr [ebp + 0x8]
        test eax, eax
        jz L_4a2bef
        mov edx, dword ptr [eax]
        lea ecx, [esi + 0x18]
        mov dword ptr [esi + 0x18], edx
        mov edx, dword ptr [eax + 0x4]
        mov dword ptr [ecx + 0x4], edx
        mov eax, dword ptr [eax + 0x8]
        mov dword ptr [ecx + 0x8], eax
    L_4a2bef:
        call Sound_IsMuted
        test eax, eax
        mov edi, 0xffffd8f0
        jnz L_4a2c00
        mov edi, dword ptr [esi + 0x24]
    L_4a2c00:
        lea ecx, [ebp - 0x20]
        lea edx, [esi + 0xc]
        mov dword ptr [ebp + 0x8], ecx
        mov dword ptr [ebp - 0x8], offset g_Data_004da000 + 0x91394
        mov dword ptr [ebp - 0x4], edx
        mov ebx, dword ptr [ebp - 0x4]
        mov ecx, dword ptr [ebp - 0x8]
        mov edx, dword ptr [ebp + 0x8]
        fld dword ptr [ebx]
        fsub dword ptr [ecx]
        fld dword ptr [ebx + 0x4]
        fsub dword ptr [ecx + 0x4]
        fld dword ptr [ebx + 0x8]
        fsub dword ptr [ecx + 0x8]
        fxch st(2)
        fstp dword ptr [edx]
        fstp dword ptr [edx + 0x4]
        fstp dword ptr [edx + 0x8]
        lea eax, [ebp - 0x20]
        mov dword ptr [ebp + 0x8], eax
        mov ecx, dword ptr [ebp + 0x8]
        fld dword ptr [ecx]
        fmul dword ptr [ecx]
        fld dword ptr [ecx + 0x4]
        fmul dword ptr [ecx + 0x4]
        fld dword ptr [ecx + 0x8]
        fmul dword ptr [ecx + 0x8]
        fxch st(1)
        faddp st(2), st(0)
        faddp st(1), st(0)
        fstp dword ptr [ebp - 0x8]
        fld dword ptr [ebp - 0x8]
        fcomp dword ptr [g_RData_004cc000 + 0x6ef8]
        mov ecx, dword ptr [ebp - 0x8]
        mov dword ptr [ebp + 0x8], ecx
        fnstsw AX
        test AH, 0x40
        jz L_4a2c8c
        mov ecx, dword ptr [ebp - 0xc]
        mov dword ptr [ebp - 0x8], 0x0
        fld dword ptr [g_RData_004cc000 + 0x6efc]
        mov edx, dword ptr [ecx + 0x14]
        mov dword ptr [ebp + 0x8], edx
        fdiv dword ptr [ebp + 0x8]
        fstp dword ptr [ebp - 0x4]
        jmp L_4a2ce9
    L_4a2c8c:
        mov eax, dword ptr [ebp + 0x8]
        sar eax, 0x1
        add eax, 0x1fc00000
        mov dword ptr [ebp - 0x8], eax
        fld dword ptr [g_RData_004cc000 + 0x6efc]
        fdiv dword ptr [ebp - 0x8]
        mov eax, dword ptr [ebp - 0x8]
        lea ecx, [ebp - 0x20]
        mov dword ptr [ebp + 0x8], eax
        mov dword ptr [ebp - 0x8], ecx
        fstp dword ptr [ebp - 0x4]
        mov ecx, dword ptr [ebp - 0x8]
        mov edx, offset g_Data_004da000 + 0x91370
        fld dword ptr [ecx]
        fmul dword ptr [edx]
        fld dword ptr [ecx + 0x4]
        fmul dword ptr [edx + 0x4]
        fld dword ptr [ecx + 0x8]
        fmul dword ptr [edx + 0x8]
        fxch st(1)
        faddp st(2), st(0)
        faddp st(1), st(0)
        fstp dword ptr [ebp - 0x10]
        fld dword ptr [ebp - 0x10]
        fmul dword ptr [ebp - 0x4]
        fmul dword ptr [g_RData_004cc000 + 0x6f00]
        call dword ptr [g_Iat__ftol_004cc5ac]
        mov ecx, dword ptr [ebp - 0xc]
        mov dword ptr [ebp - 0x8], eax
    L_4a2ce9:
        fld dword ptr [ebp + 0x8]
        fcomp dword ptr [ecx + 0x18]
        fnstsw AX
        test AH, 0x41
        jnz L_4a2d0f
        mov esi, dword ptr [esi + 0x8]
        push 0xffffd8f0
        push esi
        mov edx, dword ptr [esi]
        call dword ptr [edx + 0x3c]
        xor eax, eax
        pop edi
        pop esi
        pop ebx
        mov esp, ebp
        pop ebp
        ret 0x8
    L_4a2d0f:
        fld dword ptr [ebp + 0x8]
        fcomp dword ptr [ecx + 0x14]
        fnstsw AX
        test AH, 0x1
        jnz L_4a2d42
        fld dword ptr [ebp + 0x8]
        fdiv dword ptr [ecx + 0x14]
        fsub dword ptr [g_RData_004cc000 + 0x6efc]
        fmul dword ptr [g_RData_004cc000 + 0x6f04]
        call dword ptr [g_Iat__ftol_004cc5ac]
        add edi, eax
        cmp edi, 0xffffd8f0
        jge L_4a2d42
        mov edi, 0xffffd8f0
    L_4a2d42:
        mov eax, dword ptr [ebp + 0xc]
        test eax, eax
        jz L_4a2e0a
        lea eax, [ebp - 0x2c]
        lea ecx, [esi + 0x18]
        mov dword ptr [ebp + 0xc], eax
        mov dword ptr [ebp - 0x10], ecx
        mov ebx, dword ptr [ebp - 0x10]
        mov ecx, offset g_Data_004da000 + 0x913a0
        mov edx, dword ptr [ebp + 0xc]
        fld dword ptr [ebx]
        fsub dword ptr [ecx]
        fld dword ptr [ebx + 0x4]
        fsub dword ptr [ecx + 0x4]
        fld dword ptr [ebx + 0x8]
        fsub dword ptr [ecx + 0x8]
        fxch st(2)
        fstp dword ptr [edx]
        fstp dword ptr [edx + 0x4]
        fstp dword ptr [edx + 0x8]
        lea edx, [ebp - 0x20]
        lea eax, [ebp - 0x2c]
        mov dword ptr [ebp + 0xc], edx
        mov dword ptr [ebp - 0x10], eax
        mov ecx, dword ptr [ebp - 0x10]
        mov edx, dword ptr [ebp + 0xc]
        fld dword ptr [ecx]
        fmul dword ptr [edx]
        fld dword ptr [ecx + 0x4]
        fmul dword ptr [edx + 0x4]
        fld dword ptr [ecx + 0x8]
        fmul dword ptr [edx + 0x8]
        fxch st(1)
        faddp st(2), st(0)
        faddp st(1), st(0)
        fstp dword ptr [ebp - 0xc]
        fld dword ptr [ebp - 0xc]
        fmul dword ptr [ebp - 0x4]
        mov eax, dword ptr [esi + 0x8]
        lea edx, [ebp + 0x8]
        push edx
        push eax
        fmul dword ptr [g_Data_004da000 + 0x8424]
        mov ecx, dword ptr [eax]
        fsubr dword ptr [g_RData_004cc000 + 0x6efc]
        fstp dword ptr [ebp + 0xc]
        call dword ptr [ecx + 0x20]
        mov eax, dword ptr [ebp + 0x8]
        mov dword ptr [ebp - 0x10], 0x0
        mov dword ptr [ebp - 0x14], eax
        fild qword ptr [ebp - 0x14]
        fmul dword ptr [ebp + 0xc]
        call dword ptr [g_Iat__ftol_004cc5ac]
        mov ecx, dword ptr [esi + 0x8]
        mov dword ptr [ebp + 0x8], eax
        push eax
        push ecx
        mov edx, dword ptr [ecx]
        call dword ptr [edx + 0x44]
        jmp L_4a2e0a
    L_4a2df2:
        call Sound_IsMuted
        test eax, eax
        mov edi, 0xffffd8f0
        jnz L_4a2e03
        mov edi, dword ptr [esi + 0x24]
    L_4a2e03:
        mov dword ptr [ebp - 0x8], 0x0
    L_4a2e0a:
        mov eax, dword ptr [esi + 0x8]
        mov edx, dword ptr [ebp - 0x8]
        push edx
        push eax
        mov ecx, dword ptr [eax]
        call dword ptr [ecx + 0x40]
        test eax, eax
        jz L_4a2e35
        push 0x160
        mov edx, offset g_Data_004da000 + 0x8428
        mov ecx, eax
        call Sound_ReportDirectSoundError
        pop edi
        pop esi
        pop ebx
        mov esp, ebp
        pop ebp
        ret 0x8
    L_4a2e35:
        mov esi, dword ptr [esi + 0x8]
        push edi
        push esi
        mov eax, dword ptr [esi]
        call dword ptr [eax + 0x3c]
        test eax, eax
        jz L_4a2e5d
        push 0x164
        mov edx, offset g_Data_004da000 + 0x8428
        mov ecx, eax
        call Sound_ReportDirectSoundError
        pop edi
        pop esi
        pop ebx
        mov esp, ebp
        pop ebp
        ret 0x8
    L_4a2e5d:
        pop edi
        pop esi
        mov eax, 0x1
        pop ebx
        mov esp, ebp
        pop ebp
        ret 0x8
    }
}

// 0x004a2a30 Sound_Set3DParams_Dispatch - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 8 stack bytes).
__declspec(naked) int __fastcall Sound_Set3DParams_Dispatch(int, int, int, int)
{
    __asm {
        push esi
        mov esi, dword ptr [g_Data_004da000 + 0x912ac]
        xor eax, eax
        sub esi, eax
        jz L_4a2a53
        dec esi
        jnz L_4a2a62
        mov eax, dword ptr [esp + 0xc]
        push eax
        mov eax, dword ptr [esp + 0xc]
        push eax
        call Sound_Set3DParams_A3D
        pop esi
        ret 0x8
    L_4a2a53:
        mov eax, dword ptr [esp + 0xc]
        push eax
        mov eax, dword ptr [esp + 0xc]
        push eax
        call Sound_Set3DParams_DirectSound
    L_4a2a62:
        pop esi
        ret 0x8
    }
}

// 0x004a20d0 SoundCD_OpenDevice - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall SoundCD_OpenDevice(int, int)
{
    __asm {
        push -0x1
        push offset EH_Handler_SoundCD_OpenDevice
        mov eax, FS:[0x0]
        push eax
        mov dword ptr FS:[0x0], esp
        sub esp, 0x68
        mov eax, dword ptr [g_Data_004da000 + 0x91324]
        push ebx
        shr eax, 0x1
        push ebp
        push esi
        test AL, 0x1
        push edi
        mov dword ptr [esp + 0x14], ecx
        jnz L_4a246f
        xor ecx, ecx
        mov esi, dword ptr [g_Iat_mciSendCommandA_004cc6e8]
        mov dword ptr [esp + 0x34], ecx
        lea edx, [esp + 0x34]
        mov dword ptr [esp + 0x38], ecx
        push edx
        mov dword ptr [esp + 0x40], ecx
        push 0x2000
        mov dword ptr [esp + 0x48], ecx
        push 0x803
        push ecx
        mov dword ptr [esp + 0x54], ecx
        mov dword ptr [esp + 0x4c], offset g_Data_004da000 + 0x8418
        call esi
        test eax, eax
        jz L_4a215a
        push 0x43
        mov edx, offset g_Data_004da000 + 0x83f0
        mov ecx, eax
        call SoundCD_ReportMCIError
        mov ecx, dword ptr [esp + 0x78]
        mov dword ptr FS:[0x0], ecx
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0x74
        ret
    L_4a215a:
        mov eax, dword ptr [esp + 0x38]
        xor ecx, ecx
        mov dword ptr [esp + 0x24], ecx
        lea edx, [esp + 0x24]
        mov word ptr [g_Data_004da000 + 0x91328], AX
        mov dword ptr [esp + 0x28], ecx
        push edx
        push 0x102
        and eax, 0xffff
        mov dword ptr [esp + 0x34], ecx
        push 0x814
        push eax
        mov dword ptr [esp + 0x40], ecx
        mov dword ptr [esp + 0x3c], 0x5
        call esi
        test eax, eax
        jz L_4a21ba
        push 0x4d
        mov edx, offset g_Data_004da000 + 0x83f0
        mov ecx, eax
        call SoundCD_ReportMCIError
        mov ecx, dword ptr [esp + 0x78]
        mov dword ptr FS:[0x0], ecx
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0x74
        ret
    L_4a21ba:
        mov eax, dword ptr [esp + 0x28]
        test eax, eax
        jnz L_4a21dc
        call SoundCD_Shutdown
        xor eax, eax
        mov ecx, dword ptr [esp + 0x78]
        mov dword ptr FS:[0x0], ecx
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0x74
        ret
    L_4a21dc:
        mov edx, dword ptr [g_Data_004da000 + 0x91328]
        xor eax, eax
        lea ecx, [esp + 0x18]
        mov dword ptr [esp + 0x18], eax
        push ecx
        push 0x402
        and edx, 0xffff
        mov dword ptr [esp + 0x24], eax
        push 0x80d
        push edx
        mov dword ptr [esp + 0x30], eax
        mov dword ptr [esp + 0x2c], 0xa
        call esi
        test eax, eax
        jz L_4a2235
        push 0x5d
        mov edx, offset g_Data_004da000 + 0x83f0
        mov ecx, eax
        call SoundCD_ReportMCIError
        mov ecx, dword ptr [esp + 0x78]
        mov dword ptr FS:[0x0], ecx
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0x74
        ret
    L_4a2235:
        mov edx, dword ptr [g_Data_004da000 + 0x91328]
        xor eax, eax
        mov dword ptr [esp + 0x24], eax
        lea ecx, [esp + 0x24]
        mov dword ptr [esp + 0x28], eax
        push ecx
        push 0x102
        and edx, 0xffff
        mov dword ptr [esp + 0x34], eax
        push 0x814
        push edx
        mov dword ptr [esp + 0x40], eax
        mov dword ptr [esp + 0x3c], 0x3
        call esi
        test eax, eax
        jz L_4a2292
        push 0x66
        mov edx, offset g_Data_004da000 + 0x83f0
        mov ecx, eax
        call SoundCD_ReportMCIError
        mov ecx, dword ptr [esp + 0x78]
        mov dword ptr FS:[0x0], ecx
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0x74
        ret
    L_4a2292:
        mov edx, dword ptr [g_Data_004da000 + 0x91328]
        mov eax, dword ptr [esp + 0x28]
        lea ecx, [esp + 0x24]
        and edx, 0xffff
        push ecx
        push 0x102
        push 0x814
        push edx
        mov dword ptr [g_Data_004da000 + 0x91334], eax
        mov dword ptr [esp + 0x3c], 0x1
        mov dword ptr [esp + 0x40], 0x0
        call esi
        test eax, eax
        jz L_4a22ee
        push 0x70
        mov edx, offset g_Data_004da000 + 0x83f0
        mov ecx, eax
        call SoundCD_ReportMCIError
        mov ecx, dword ptr [esp + 0x78]
        mov dword ptr FS:[0x0], ecx
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0x74
        ret
    L_4a22ee:
        call dword ptr [g_Iat_auxGetNumDevs_004cc6dc]
        mov ebx, eax
        xor esi, esi
        test ebx, ebx
        jle L_4a2348
        mov ebp, dword ptr [g_Iat_auxGetDevCapsA_004cc6d4]
    L_4a2302:
        mov ecx, 0xc
        xor eax, eax
        lea edi, [esp + 0x48]
        push 0x30
        rep stosd
        lea eax, [esp + 0x4c]
        push eax
        push esi
        call ebp
        test eax, eax
        jnz L_4a2331
        mov ecx, 0x1
        cmp word ptr [esp + 0x70], CX
        jnz L_4a2331
        mov AL, byte ptr [esp + 0x74]
        test CL, AL
        jnz L_4a2338
    L_4a2331:
        inc esi
        cmp esi, ebx
        jl L_4a2302
        jmp L_4a2348
    L_4a2338:
        test AL, 0x2
        jz L_4a2342
        or dword ptr [g_Data_004da000 + 0x91324], ecx
    L_4a2342:
        mov dword ptr [g_Data_004da000 + 0x9132c], esi
    L_4a2348:
        mov eax, dword ptr [g_Data_004da000 + 0x9132c]
        cmp eax, -0x1
        jz L_4a2378
        lea ecx, [esp + 0x10]
        push ecx
        push eax
        call dword ptr [g_Iat_auxGetVolume_004cc6e0]
        test eax, eax
        jnz L_4a2378
        mov eax, dword ptr [esp + 0x10]
        mov edx, eax
        mov word ptr [g_Data_004da000 + 0x91332], AX
        shr edx, 0x10
        mov word ptr [g_Data_004da000 + 0x91330], DX
    L_4a2378:
        mov eax, dword ptr [esp + 0x28]
        xor ecx, ecx
        mov CL, AH
        shr eax, 0x10
        and ecx, 0xff
        and eax, 0xff
        mov dword ptr [g_Data_004da000 + 0x91338], ecx
        mov dword ptr [g_Data_004da000 + 0x9133c], eax
        call SoundCD_ResetTrackState
        mov edx, dword ptr [g_Data_004da000 + 0x91324]
        mov eax, dword ptr [esp + 0x14]
        or edx, 0x2
        test eax, eax
        mov dword ptr [g_Data_004da000 + 0x91324], edx
        jz L_4a246f
        mov eax, dword ptr [eax + 0x4]
        mov ebx, 0x1
        cmp dword ptr [eax + 0x4], ebx
        jle L_4a246f
    L_4a23ca:
        mov edi, dword ptr [eax + ebx*0x8 + 0x4]
        push 0x8
        call dword ptr [g_Iat_MFC42_823_004cc2ac]
        mov esi, eax
        add esp, 0x4
        mov dword ptr [esp + 0x10], esi
        xor eax, eax
        cmp esi, eax
        mov dword ptr [esp + 0x80], eax
        jz L_4a2406
        mov eax, dword ptr [edi + 0xc]
        mov edx, dword ptr [edi + 0x14]
        push eax
        mov dword ptr [esi + 0x4], edx
        call dword ptr [g_Iat__strdup_004cc5e4]
        add esp, 0x4
        mov dword ptr [esi], eax
        mov dword ptr [esp + 0x10], esi
        jmp L_4a240a
    L_4a2406:
        mov dword ptr [esp + 0x10], eax
    L_4a240a:
        mov edi, dword ptr [g_Data_004da000 + 0x913e4]
        push 0xc
        mov dword ptr [esp + 0x84], 0xffffffff
        mov esi, dword ptr [edi + 0x4]
        lea ebp, [edi + 0x4]
        call dword ptr [g_Iat_MFC42_823_004cc2ac]
        add esp, 0x4
        test edi, edi
        jnz L_4a2431
        mov edi, eax
    L_4a2431:
        test esi, esi
        mov dword ptr [eax], edi
        jnz L_4a2439
        mov esi, eax
    L_4a2439:
        mov dword ptr [eax + 0x4], esi
        mov dword ptr [ebp], eax
        mov ecx, dword ptr [eax + 0x4]
        mov dword ptr [ecx], eax
        add eax, 0x8
        test eax, eax
        jz L_4a2451
        mov edx, dword ptr [esp + 0x10]
        mov dword ptr [eax], edx
    L_4a2451:
        mov esi, dword ptr [g_Data_004da000 + 0x913e8]
        mov eax, dword ptr [esp + 0x14]
        inc esi
        inc ebx
        mov dword ptr [g_Data_004da000 + 0x913e8], esi
        mov eax, dword ptr [eax + 0x4]
        cmp ebx, dword ptr [eax + 0x4]
        jl L_4a23ca
    L_4a246f:
        mov ecx, dword ptr [esp + 0x78]
        pop edi
        pop esi
        pop ebp
        mov eax, 0x1
        mov dword ptr FS:[0x0], ecx
        pop ebx
        add esp, 0x74
        ret
    }
}

// 0x004cb1c0 EH_Unwind_SoundCD_OpenDevice_0 - ../../04_spec/systems/sound.md
// Register/stack shape from the listing (ECX, EDX, 0 stack bytes).
__declspec(naked) int __fastcall EH_Unwind_SoundCD_OpenDevice_0(int, int)
{
    __asm {
        mov eax, dword ptr [ebp - 0x74]
        push eax
        call dword ptr [g_Iat_MFC42_825_004cc2b8]
        pop ecx
        ret
    }
}

// 0x004cb1cb EH_Handler_SoundCD_OpenDevice - ../../04_spec/systems/sound.md
// Generated by tools/gen_eh_frames.py from the exe bytes (b8 a8 73 4d 00 e9 cb ae ff ff): MOV EAX,FuncInfo 0x004d73a8; JMP 0x004c60a0 (-> __CxxFrameHandler).
// FuncInfo CONFIRMED-BINARY: magic 0x19930520, 1 unwind states, unwind map 0x004d73c8 (to-state, action) = ['(-1, 0x004cb1c0)'], no try blocks;
// the port's table points at the port's funclets. Needs /SAFESEH:NO (CMakeLists.txt).
namespace {
const EhUnwindMapEntry g_EhUnwindMap_004d73c8[1] = {{-1, reinterpret_cast<void*>(&EH_Unwind_SoundCD_OpenDevice_0)}};
const EhFuncInfo g_EhFuncInfo_004d73a8 = {0x19930520u, 1, g_EhUnwindMap_004d73c8, 0, nullptr};
}  // namespace

__declspec(naked) int __fastcall EH_Handler_SoundCD_OpenDevice(int, int)
{
    __asm {
        mov eax, offset g_EhFuncInfo_004d73a8
        jmp dword ptr [g_Iat___CxxFrameHandler_004cc5b0]
    }
}

}  // namespace recoil
