// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "unattributed/vehicle.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept; };
std::vector<Entry> entries()
{
    return {
        {0x0041bab0, reinterpret_cast<void*>(&recoil::Vehicle_UpdateFireRequests), 0, "Vehicle_UpdateFireRequests", {0x004f3760}, {}},
        {0x00426350, reinterpret_cast<void*>(&recoil::Sign_Float), 1, "Sign_Float", {}, {}},
        {0x004283f0, reinterpret_cast<void*>(&recoil::Vehicle_CockpitThrottle), 0, "Vehicle_CockpitThrottle", {0x004f3ac4}, {}},
        {0x004290f0, reinterpret_cast<void*>(&recoil::Terrain_FindGroundHeight), 5, "Terrain_FindGroundHeight", {}, {}},
        {0x00429240, reinterpret_cast<void*>(&recoil::Vehicle_ApplyBodyWobble), 1, "Vehicle_ApplyBodyWobble", {0x0056b428}, {}},
        {0x00429430, reinterpret_cast<void*>(&recoil::Vehicle_ApplyKnockback), 2, "Vehicle_ApplyKnockback", {}, {0x004e0e84, 0x004e0e88}},
        {0x004294d0, reinterpret_cast<void*>(&recoil::Vehicle_ExtractAxesFromMatrix), 0, "Vehicle_ExtractAxesFromMatrix", {}, {}},
        {0x00429f20, reinterpret_cast<void*>(&recoil::VehicleGlobals_StaticInit), 0, "VehicleGlobals_StaticInit", {0x004f3ae0, 0x004f3ae4, 0x004f3ae8, 0x004f3aec}, {}},
        {0x0042b810, reinterpret_cast<void*>(&recoil::Vehicle_SyncPlayerTransformFromObject), 0, "Vehicle_SyncPlayerTransformFromObject", {0x004f3a88}, {}},
        {0x0042b8c0, reinterpret_cast<void*>(&recoil::Vehicle_ComputeGroundContactHeight), 0, "Vehicle_ComputeGroundContactHeight", {}, {}},
    };
}
}  // namespace

TEST(native_fuzz_vehicle1_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = true;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
