// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "GameZRecoil/zFMV/fmv_script.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept, dict; };
std::vector<Entry> entries()
{
    return {
        {0x004625e0, reinterpret_cast<void*>(&recoil::Seq_Ctor), 3, "Seq_Ctor", {0x004f3eec}, {0x004dd484, 0x004dfb64, 0x004dfb94, 0x004dfba0, 0x004dfba8, 0x004dfbb0, 0x004dfbb8, 0x004dfbc0, 0x004dfbc8, 0x004dfbd0, 0x004dfbd8, 0x004dfbe0, 0x004dfbec, 0x004dfbf8, 0x004dfc04, 0x004dfc10, 0x004dfc1c, 0x004dfc44, 0x0053a708, 0x0053a70c, 0x0053a710, 0x0053a714, 0x0053a718, 0x0053a71c, 0x0053a720, 0x0053a724, 0x0053a728, 0x0053a72c, 0x0053a730, 0x0053a734}, {}},
        {0x004626b0, reinterpret_cast<void*>(&recoil::Seq_Load), 2, "Seq_Load", {0x004dfb64, 0x004dfb94, 0x004dfba0, 0x004dfba8, 0x004dfbb0, 0x004dfbb8, 0x004dfbc0, 0x004dfbc8, 0x004dfbd0, 0x004dfbd8, 0x004dfbe0, 0x004dfbec, 0x004dfbf8, 0x004dfc04, 0x004dfc10, 0x004dfc1c, 0x004dfc44}, {0x004dd484, 0x0053a708, 0x0053a70c, 0x0053a710, 0x0053a714, 0x0053a718, 0x0053a71c, 0x0053a720, 0x0053a724, 0x0053a728, 0x0053a72c, 0x0053a730, 0x0053a734}, {}},
        {0x00462e90, reinterpret_cast<void*>(&recoil::SeqItem_PlaySound), 2, "SeqItem_PlaySound", {}, {}, {}},
        {0x00462f50, reinterpret_cast<void*>(&recoil::Seq_Play), 1, "Seq_Play", {}, {0x004dfc70}, {}},
        {0x00462f90, reinterpret_cast<void*>(&recoil::Seq_Begin), 2, "Seq_Begin", {0x004dfc70}, {}, {}},
        {0x00463000, reinterpret_cast<void*>(&recoil::Seq_Tick), 2, "Seq_Tick", {}, {}, {}},
        {0x004630a0, reinterpret_cast<void*>(&recoil::Seq_BeginAtNow), 0, "Seq_BeginAtNow", {}, {0x004dfc70}, {}},
        {0x004630e0, reinterpret_cast<void*>(&recoil::Seq_TickAtNow), 0, "Seq_TickAtNow", {}, {}, {}},
    };
}
}  // namespace

TEST(native_fuzz_auto_avi5_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        af::dictionary() = e.dict;  // empty for a plain arena test
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        af::dictionary().clear();
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
