// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "unattributed/render_frame.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept; };
std::vector<Entry> entries()
{
    return {
        {0x0044d320, reinterpret_cast<void*>(&recoil::Camera_UpdateFollowNodes), 0, "Camera_UpdateFollowNodes", {0x005398fc}, {}},
        {0x004762f0, reinterpret_cast<void*>(&recoil::RenderState_ApplyColour), 0, "RenderState_ApplyColour", {0x0057d938}, {}},
        {0x00479660, reinterpret_cast<void*>(&recoil::Decal_StampOntoTexture), 0, "Decal_StampOntoTexture", {0x0056bc0c, 0x0056bc10, 0x0056bc18, 0x0057d9a4, 0x0057d9a8, 0x0057d9b4, 0x0057d9b8, 0x0057de38}, {}},
        {0x0048d7a0, reinterpret_cast<void*>(&recoil::Backend_ScreenTintOverlay), 0, "Backend_ScreenTintOverlay", {0x0056b198, 0x0056b19c, 0x0056b1b0, 0x0056b1c4, 0x0056b1d4, 0x0056b1d8, 0x0056b1dc, 0x0056b1e0, 0x0056b1e4, 0x0057de38, 0x0062e9dc, 0x0062e9e0, 0x0062e9e4, 0x0062e9e8, 0x0062e9ec, 0x0062e9f0, 0x0062e9f8, 0x00632110}, {}},
        {0x0048fd80, reinterpret_cast<void*>(&recoil::zRndrInit), 0, "zRndrInit", {0x004da834, 0x004da888, 0x0056bbe8, 0x0057dac0, 0x0057dac4, 0x0057dac8, 0x0057dacc, 0x0057dae0, 0x0057dae4, 0x0057dae8, 0x0057daec, 0x0057daf0, 0x0057daf4, 0x0057daf8, 0x0057dafc, 0x0057de58, 0x0057de5c, 0x0057de60, 0x0057de64, 0x0057de68, 0x0057de6c, 0x0057de70, 0x0057de7c, 0x005cb270, 0x0062e9dc, 0x0062ea00, 0x00631ccc, 0x00631dd0, 0x00631e70, 0x00631fb0, 0x00632050, 0x00632054, 0x00632058, 0x0063205c, 0x00632060, 0x00632064, 0x00632068, 0x0063206c, 0x00632070, 0x00632074, 0x00632078, 0x0063207c, 0x00632080, 0x00632084, 0x00632088, 0x0063208c, 0x00632090, 0x00632094, 0x00632098, 0x0063209c, 0x006320a0, 0x006320ac, 0x0063210c, 0x00632110}, {0x0057db04, 0x0057db08, 0x0057db0c}},
        {0x00498cb0, reinterpret_cast<void*>(&recoil::SW_PlotPoint16), 1, "SW_PlotPoint16", {0x0057de38, 0x0062e9dc, 0x0062e9f0, 0x0062e9f8, 0x00632050, 0x00632054, 0x00632058, 0x0063205c}, {}},
        {0x0049a8c0, reinterpret_cast<void*>(&recoil::PointQueue_FlushAll), 1, "PointQueue_FlushAll", {0x0062e9dc, 0x0062ea00, 0x0062ea04}, {0x0057de38, 0x0062e9f0, 0x0062e9f8, 0x00632050, 0x00632054, 0x00632058, 0x0063205c}},
        {0x0049a920, reinterpret_cast<void*>(&recoil::Backend_CompactAndCollectItems), 0, "Backend_CompactAndCollectItems", {0x0062ea00, 0x0062ea04, 0x0062ef04, 0x00631ccc, 0x00631cd0}, {}},
    };
}
}  // namespace

TEST(native_fuzz_auto_render_frame1_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
