// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "GameZRecoil/zClass/cls_util.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept, dict; };
std::vector<Entry> entries()
{
    return {
        {0x00452500, reinterpret_cast<void*>(&recoil::gwNode_CloneWithFlag), 1, "gwNode_CloneWithFlag", {0x004dd9d4, 0x004de4cc, 0x004de4d0, 0x00539c9c}, {0x004de538, 0x004de58c, 0x004de5ec, 0x004de658, 0x004de68c, 0x004de6d8, 0x004de730, 0x004de78c, 0x004de7e4, 0x004de840, 0x004de898, 0x004de8f0, 0x004de950, 0x004de9b0, 0x004dea14, 0x004dea6c, 0x004deac8, 0x004deae8, 0x004deb14, 0x004deb48, 0x004deb7c, 0x004debb8, 0x004debf4, 0x004dec30, 0x004dec60, 0x00539ca0}, {}},
        {0x00452560, reinterpret_cast<void*>(&recoil::Node_FindWithSearchParams), 2, "Node_FindWithSearchParams", {0x004dd9d4, 0x004de4cc, 0x004de4d0, 0x00539c9c, 0x00539ca0}, {0x004de538, 0x004de58c, 0x004de5ec, 0x004de658, 0x004de68c, 0x004de6d8, 0x004de730, 0x004de78c, 0x004de7e4, 0x004de840, 0x004de898, 0x004de8f0, 0x004de950, 0x004de9b0, 0x004dea14, 0x004dea6c, 0x004deac8, 0x004deae8, 0x004deb14, 0x004deb48, 0x004deb7c, 0x004debb8, 0x004debf4, 0x004dec30, 0x004dec60}, {}},
    };
}
}  // namespace

TEST(native_fuzz_auto_zclass_nodes14_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        af::dictionary() = e.dict;  // empty for a plain arena test
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        af::dictionary().clear();
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
