// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "GameZRecoil/zInput/zin_kbd.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept; };
std::vector<Entry> entries()
{
    return {
        {0x004706c0, reinterpret_cast<void*>(&recoil::InputMap_CopyCtor), 1, "InputMap_CopyCtor", {}, {0x00561cd8, 0x00565bc8}},
        {0x00470820, reinterpret_cast<void*>(&recoil::InputMap_RebuildReverseTables), 0, "InputMap_RebuildReverseTables", {}, {0x00561cd8, 0x00565bc8}},
        {0x004708f0, reinterpret_cast<void*>(&recoil::Bindings_Alloc), 1, "Bindings_Alloc", {0x004e0904}, {0x00561cd8, 0x00565bc8}},
        {0x004709d0, reinterpret_cast<void*>(&recoil::Bindings_ResetAll), 0, "Bindings_ResetAll", {}, {0x00561cd8, 0x00565bc8}},
        {0x00470df0, reinterpret_cast<void*>(&recoil::InputMap_SetCommandHandler), 2, "InputMap_SetCommandHandler", {}, {0x00561cd8}},
        {0x00471660, reinterpret_cast<void*>(&recoil::Input_DestroyBindings), 0, "Input_DestroyBindings", {0x00565ea0}, {}},
    };
}
}  // namespace

TEST(native_fuzz_auto_input7_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
