// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "unattributed/rasteriser.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept; };
std::vector<Entry> entries()
{
    return {
        {0x0049b4c0, reinterpret_cast<void*>(&recoil::BlendState_SelectPresetF10), 0, "BlendState_SelectPresetF10", {0x00631f10, 0x00631f14, 0x00631f18, 0x00631fb0, 0x00631fb4, 0x00631fb8}, {}},
        {0x0049b530, reinterpret_cast<void*>(&recoil::BlendState_SelectPresetDD0), 0, "BlendState_SelectPresetDD0", {0x00631dd0, 0x00631dd4, 0x00631dd8, 0x00631fb0, 0x00631fb4, 0x00631fb8}, {}},
        {0x0049b710, reinterpret_cast<void*>(&recoil::BlendState_SelectPresetE70), 0, "BlendState_SelectPresetE70", {0x00631e70, 0x00631e74, 0x00631e78, 0x00631fb0, 0x00631fb4, 0x00631fb8}, {}},
        {0x0049b780, reinterpret_cast<void*>(&recoil::BlendState_BlendPixel), 0, "BlendState_BlendPixel", {0x0057de40, 0x0057de44, 0x0057de48, 0x00631fbc, 0x00631fc0, 0x00631fc4}, {}},
        {0x0049c020, reinterpret_cast<void*>(&recoil::Fill_Tex8ShadeKeyedBlend565_Broken), 2, "Fill_Tex8ShadeKeyedBlend565_Broken", {0x004e21f4, 0x004e21f8, 0x0056b260, 0x0056b264, 0x0056b268, 0x0056b26c, 0x0056b270, 0x0057da48}, {}},
        {0x0049c150, reinterpret_cast<void*>(&recoil::Fill_Tex16KeyedBlend_Broken), 2, "Fill_Tex16KeyedBlend_Broken", {0x004e21f4, 0x004e21f8, 0x0056b260, 0x0056b268, 0x0056b26c, 0x0056b270, 0x0057da48}, {}},
        {0x0049c230, reinterpret_cast<void*>(&recoil::Fill_Tex8ShadeKeyedBlend_555Slot_Broken), 2, "Fill_Tex8ShadeKeyedBlend_555Slot_Broken", {0x004e21f4, 0x004e21f8, 0x0056b260, 0x0056b264, 0x0056b268, 0x0056b26c, 0x0056b270, 0x0057da48}, {}},
        {0x0049c360, reinterpret_cast<void*>(&recoil::Fill_Tex16AlphaMap565), 2, "Fill_Tex16AlphaMap565", {0x004e21f4, 0x004e21f8, 0x0056b260, 0x0056b268, 0x0056b26c, 0x0056b270, 0x0056b27c}, {}},
        {0x0049c560, reinterpret_cast<void*>(&recoil::Fill_Tex16AlphaMap555), 2, "Fill_Tex16AlphaMap555", {0x004e21f4, 0x004e21f8, 0x0056b260, 0x0056b268, 0x0056b26c, 0x0056b270, 0x0056b27c}, {}},
        {0x0049c760, reinterpret_cast<void*>(&recoil::Fill_Tex16Blend565_LeftToRight), 2, "Fill_Tex16Blend565_LeftToRight", {0x004e21f4, 0x004e21f8, 0x0056b260, 0x0056b268, 0x0056b26c, 0x0056b270, 0x0057da48}, {}},
    };
}
}  // namespace

TEST(native_fuzz_rasteriser3_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = true;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
