// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "unattributed/app.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept, dict; };
std::vector<Entry> entries()
{
    return {
        {0x00442632, reinterpret_cast<void*>(&recoil::EH_Catch_RefCounted_Create_0), 0, "EH_Catch_RefCounted_Create_0", {}, {}, {}},
        {0x00442638, reinterpret_cast<void*>(&recoil::EH_Cont_RefCounted_Create_0), 0, "EH_Cont_RefCounted_Create_0", {}, {}, {}},
        {0x00442790, reinterpret_cast<void*>(&recoil::RefCounted_Release), 1, "RefCounted_Release", {}, {0x004f53e4}, {}},
        {0x004427f0, reinterpret_cast<void*>(&recoil::RefCounted_Dtor), 0, "RefCounted_Dtor", {0x004f53e4}, {}, {}},
        {0x00442bc0, reinterpret_cast<void*>(&recoil::Engine_ShutdownSubsystems), 0, "Engine_ShutdownSubsystems", {}, {}, {}},
        {0x00442d00, reinterpret_cast<void*>(&recoil::RecoilApp_Run), 0, "RecoilApp_Run", {}, {}, {}},
        {0x0044300b, reinterpret_cast<void*>(&recoil::AppRun_CatchMemoryException), 0, "AppRun_CatchMemoryException", {0x004dd890, 0x004dd8cc}, {}, {}},
        {0x00443032, reinterpret_cast<void*>(&recoil::AppRun_CatchFileException), 0, "AppRun_CatchFileException", {0x004dd64c, 0x004dd658, 0x004dd678, 0x004dd68c, 0x004dd6cc, 0x004dd708, 0x004dd724, 0x004dd758, 0x004dd780, 0x004dd7b4, 0x004dd7e8, 0x004dd808, 0x004dd83c, 0x004dd860, 0x004dd880, 0x004e5ce0}, {}, {}},
    };
}
}  // namespace

TEST(native_fuzz_auto_app20_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        af::dictionary() = e.dict;  // empty for a plain arena test
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        af::dictionary().clear();
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
