// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "unattributed/rasteriser.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept, dict; };
std::vector<Entry> entries()
{
    return {
        {0x0048f560, reinterpret_cast<void*>(&recoil::Raster_BlitImageColorKey), 3, "Raster_BlitImageColorKey", {0x0057de38, 0x00632050, 0x00632054, 0x00632058, 0x0063205c}, {}, {0x0000001e, 0x0000001f, 0x00000020, 0x00000027, 0x00000028, 0x00000029, 0x000000fb, 0x000000fc, 0x000000fd, 0x000000fe, 0x000000ff, 0x00000100, 0x000003df, 0x000003e0, 0x000003e1, 0x000007df, 0x000007e0, 0x000007e1, 0x000007ff, 0x00000800, 0x00000801, 0x00007bff, 0x00007c00, 0x00007c01, 0x0000f7ff, 0x0000f800, 0x0000f801, 0xfffff7ff, 0xfffff800, 0xfffff801, 0xfffffbff, 0xfffffc00, 0xfffffc01, 0xffffffdf, 0xffffffe0, 0xffffffe1}},
        {0x00491dd0, reinterpret_cast<void*>(&recoil::Span_TestVisible), 0, "Span_TestVisible", {0x0057dae0, 0x0057dae4, 0x0057db08}, {0x0057db04, 0x0057db0c}, {0x7f800000, 0x7fc00000, 0x80000000, 0xff800000, 0x00000027, 0x00000028, 0x00000029, 0x00000040, 0x00000041, 0x00000042}},
        {0x004998a0, reinterpret_cast<void*>(&recoil::Fill_BlendConst565), 1, "Fill_BlendConst565", {0x0056b270}, {}, {0x0000001e, 0x0000001f, 0x00000020, 0x000000df, 0x000000e0, 0x000000e1, 0x000000fb, 0x000000fc, 0x000000fd, 0x000007df, 0x000007e0, 0x000007e1, 0x0000f7ff, 0x0000f800, 0x0000f801, 0xfffff7ff, 0xfffff800, 0xfffff801}},
        {0x0049b4c0, reinterpret_cast<void*>(&recoil::BlendState_SelectPresetF10), 0, "BlendState_SelectPresetF10", {0x00631f10, 0x00631f14, 0x00631f18, 0x00631fb0, 0x00631fb4, 0x00631fb8}, {}, {0x7f800000, 0x7fc00000, 0x80000000, 0xff800000, 0x00000027, 0x00000028, 0x00000029}},
        {0x0049b530, reinterpret_cast<void*>(&recoil::BlendState_SelectPresetDD0), 0, "BlendState_SelectPresetDD0", {0x00631dd0, 0x00631dd4, 0x00631dd8, 0x00631fb0, 0x00631fb4, 0x00631fb8}, {}, {0x7f800000, 0x7fc00000, 0x80000000, 0xff800000, 0x00000027, 0x00000028, 0x00000029}},
        {0x0049b710, reinterpret_cast<void*>(&recoil::BlendState_SelectPresetE70), 0, "BlendState_SelectPresetE70", {0x00631e70, 0x00631e74, 0x00631e78, 0x00631fb0, 0x00631fb4, 0x00631fb8}, {}, {0x7f800000, 0x7fc00000, 0x80000000, 0xff800000, 0x00000027, 0x00000028, 0x00000029}},
        {0x0049d950, reinterpret_cast<void*>(&recoil::Fill_Tex8ShadeAlphaLevelBlend555), 2, "Fill_Tex8ShadeAlphaLevelBlend555", {0x004e21f4, 0x004e21f8, 0x0056b260, 0x0056b264, 0x0056b268, 0x0056b26c, 0x0056b270, 0x0056b27c, 0x0057da48}, {}, {0x00000013, 0x00000014, 0x00000015, 0x0000001b, 0x0000001c, 0x0000001d, 0x0000001e, 0x0000001f, 0x00000020, 0x000000fb, 0x000000fc, 0x000000fd, 0x000003df, 0x000003e0, 0x000003e1, 0x00007bff, 0x00007c00, 0x00007c01, 0xfffffbff, 0xfffffc00, 0xfffffc01, 0xffffffdf, 0xffffffe0, 0xffffffe1}},
    };
}
}  // namespace

TEST(native_fuzz_dict_rasteriser1_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        af::dictionary() = e.dict;  // empty for a plain arena test
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        af::dictionary().clear();
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
