// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "GameZRecoil/zModel/gmod_init.h"
#include "GameZRecoil/zModel/gmod_matl.h"
#include "GameZRecoil/zModel/gmod_const.h"
#include "GameZRecoil/zReader/zreader.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept; };
std::vector<Entry> entries()
{
    return {
        {0x00475f60, reinterpret_cast<void*>(&recoil::Model_ForEachLoaded_004820f0), 0, "Model_ForEachLoaded_004820f0", {0x00576200, 0x00576204, 0x00576208}, {0x0057620c}},
        {0x00480d80, reinterpret_cast<void*>(&recoil::Material_FreeAllUsed), 0, "Material_FreeAllUsed", {0x004e1164, 0x00566a1c, 0x00566a24}, {0x004e1160, 0x00566a20}},
        {0x00483ad0, reinterpret_cast<void*>(&recoil::Model_ComputeBoundsCentreRadius), 0, "Model_ComputeBoundsCentreRadius", {}, {0x0057d97c}},
        {0x00484250, reinterpret_cast<void*>(&recoil::ModelInstance_Call481050), 0, "ModelInstance_Call481050", {0x004e13a0, 0x004e17b0, 0x00575de0}, {0x004e0718, 0x005669f0}},
        {0x0048c800, reinterpret_cast<void*>(&recoil::Container_GrowFreeList), 0, "Container_GrowFreeList", {0x0056ae74}, {0x0056ae70, 0x0056ae78}},
        {0x0048cae0, reinterpret_cast<void*>(&recoil::Container_FreeNode), 0, "Container_FreeNode", {}, {0x0056ae70, 0x0056ae78}},
        {0x0048ce60, reinterpret_cast<void*>(&recoil::ConfigTree_FreeNode), 0, "ConfigTree_FreeNode", {}, {}},
        {0x0048cec0, reinterpret_cast<void*>(&recoil::ConfigTree_FindChildByName), 1, "ConfigTree_FindChildByName", {}, {}},
    };
}
}  // namespace

TEST(native_fuzz_tier3a_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
