// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "GameZRecoil/zImage/zimg_texture.h"
#include "GameZRecoil/zModel/gmod_init.h"
#include "unattributed/asset_io_misc.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals; };
std::vector<Entry> entries()
{
    return {
        {0x0046d4c0, reinterpret_cast<void*>(&recoil::zImage_GetTable_004e0718), 0, "zImage_GetTable_004e0718", {0x004e0718}},
        {0x00475ff0, reinterpret_cast<void*>(&recoil::ModelCache_SetArraySize), 0, "ModelCache_SetArraySize", {0x004e0f28, 0x004e0f50, 0x00576200}},
        {0x00407190, reinterpret_cast<void*>(&recoil::NameTable_LookupValue), 0, "NameTable_LookupValue", {0x004da3e0, 0x004da3e4, 0x004da4b8}},
        {0x004815a0, reinterpret_cast<void*>(&recoil::Model_FromIndex), 0, "Model_FromIndex", {0x00576204}},
        {0x004a62f0, reinterpret_cast<void*>(&recoil::Zar_GrowTocBuffer), 1, "Zar_GrowTocBuffer", {}},
        {0x004a6330, reinterpret_cast<void*>(&recoil::ZarIndex_Free), 0, "ZarIndex_Free", {}},
    };
}
}  // namespace

TEST(native_fuzz_asset_misc_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
