// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "unattributed/render_frame.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept, dict; };
std::vector<Entry> entries()
{
    return {
        {0x00476400, reinterpret_cast<void*>(&recoil::Render_IsNodeTypeEnabledForRender), 0, "Render_IsNodeTypeEnabledForRender", {0x004dd90c, 0x0057da28}, {}, {0x000000fe, 0x000000ff, 0x00000100}},
        {0x00490430, reinterpret_cast<void*>(&recoil::zRndr_SetPerspectiveSubdivFixed), 0, "zRndr_SetPerspectiveSubdivFixed", {0x0057de58, 0x0057de5c, 0x0057de60, 0x0057de64, 0x0057de6c, 0x00632060}, {}, {0x00000000, 0xfffffffe, 0xffffffff}},
        {0x004904d0, reinterpret_cast<void*>(&recoil::zRndr_SetPerspectiveInverseZTolerance), 1, "zRndr_SetPerspectiveInverseZTolerance", {0x0057db04, 0x0057db08, 0x0057db0c}, {}, {0x7f800000, 0x7fc00000, 0x80000000, 0xff800000, 0x0000003f, 0x00000040, 0x00000041}},
        {0x0049a830, reinterpret_cast<void*>(&recoil::Queue_AppendPoint), 1, "Queue_AppendPoint", {0x0057dac0, 0x0057dac4, 0x0062ea00, 0x0062ea04, 0x0062ea10, 0x0062ea14}, {}, {0x00000289, 0x0000028a, 0x0000028b}},
    };
}
}  // namespace

TEST(native_fuzz_dict_render_frame1_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        af::dictionary() = e.dict;  // empty for a plain arena test
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        af::dictionary().clear();
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
