// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "GameZRecoil/zGeometry/zgeo_model.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept; };
std::vector<Entry> entries()
{
    return {
        {0x0046ae40, reinterpret_cast<void*>(&recoil::ClipGroupList_Release), 0, "ClipGroupList_Release", {}, {}},
        {0x0046af40, reinterpret_cast<void*>(&recoil::ClipGroup_BuildModelNode), 1, "ClipGroup_BuildModelNode", {}, {}},
        {0x0046b1f0, reinterpret_cast<void*>(&recoil::AreaPartition_ClipObjects), 2, "AreaPartition_ClipObjects", {0x004e034c, 0x004e040c}, {0x004e03b0, 0x004e03e0, 0x004e0458, 0x004e048c, 0x0053a73c}},
        {0x0046b550, reinterpret_cast<void*>(&recoil::ClipObject_Dispatch), 1, "ClipObject_Dispatch", {}, {0x004e034c, 0x004e03b0, 0x004e03e0, 0x004e0458, 0x004e048c, 0x0053a73c}},
        {0x0046b6d0, reinterpret_cast<void*>(&recoil::ClipModel_SplitByRegion), 1, "ClipModel_SplitByRegion", {0x004e034c, 0x004e03b0, 0x004e03e0, 0x004e0458}, {0x004e048c, 0x0053a73c}},
        {0x0046ba90, reinterpret_cast<void*>(&recoil::Geometry_AddChildPolygon), 3, "Geometry_AddChildPolygon", {0x004e034c, 0x004e048c}, {0x0053a73c}},
        {0x0046bb30, reinterpret_cast<void*>(&recoil::ClipPolygon_EmitToModel), 1, "ClipPolygon_EmitToModel", {}, {}},
    };
}
}  // namespace

TEST(native_fuzz_auto_geometry1_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
