// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "GameZRecoil/zInput/zin_kbd.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept; };
std::vector<Entry> entries()
{
    return {
        {0x0046f450, reinterpret_cast<void*>(&recoil::Input_Keyboard_InitialPollAndClear), 0, "Input_Keyboard_InitialPollAndClear", {0x004e08cc, 0x00561cc4, 0x00561cc8, 0x00561ccc, 0x00561cd0, 0x00561cd4, 0x00565bc4}, {0x004dcaac, 0x004e0cc4, 0x004e0cdc, 0x004e0cf8, 0x004e0d18, 0x004e0d34, 0x004e0d44, 0x004e0d58, 0x004e0d6c, 0x004e0d7c, 0x004e0d94, 0x004e0da8, 0x004e0dbc, 0x004e0dcc, 0x004e0de4, 0x004e0df8, 0x004e0e0c, 0x004e0e20, 0x004e0e34}},
        {0x0046f690, reinterpret_cast<void*>(&recoil::Input_Keyboard_PollAndTranslate), 0, "Input_Keyboard_PollAndTranslate", {0x004e08cc, 0x00561cc8, 0x00561ccc, 0x00561cd0, 0x00561cd4, 0x00561cd8, 0x00565bc4, 0x00565bc8}, {0x004dcaac, 0x004e0cc4, 0x004e0cdc, 0x004e0cf8, 0x004e0d18, 0x004e0d34, 0x004e0d44, 0x004e0d58, 0x004e0d6c, 0x004e0d7c, 0x004e0d94, 0x004e0da8, 0x004e0dbc, 0x004e0dcc, 0x004e0de4, 0x004e0df8, 0x004e0e0c, 0x004e0e20, 0x004e0e34, 0x00561848, 0x00561850, 0x00561854, 0x00561858, 0x0056185c, 0x00561860, 0x00561864, 0x00561868, 0x0056186c, 0x00561870, 0x00561874, 0x00561878, 0x0056187c, 0x00561880, 0x00561884, 0x00561888, 0x0056188c, 0x00561890, 0x00561894, 0x00561898, 0x0056189c, 0x005618a0, 0x005618a4, 0x005618a8, 0x005618ac, 0x005618b0, 0x005618b4, 0x005618b8, 0x005618c0, 0x005618c4, 0x005618c8, 0x005618cc, 0x005618d0, 0x005618d4, 0x005618d8, 0x005618dc, 0x005618e0, 0x005618e4, 0x005618e8, 0x005618ec, 0x005618f4, 0x005618f8, 0x005618fc, 0x00561900, 0x00561904, 0x00561908, 0x0056190c, 0x00561910, 0x00561914, 0x00561918, 0x0056191c, 0x00561924, 0x0056192c, 0x00561964, 0x00561968, 0x0056196c, 0x00561970, 0x00561974, 0x00561978, 0x0056197c, 0x00561980, 0x00561984, 0x00561988, 0x0056198c, 0x00561990, 0x00561994, 0x00561a7c, 0x00561a88, 0x00561a8c, 0x00561a90, 0x00561a94, 0x00561ab8, 0x00561b14, 0x00561b1c, 0x00561b74, 0x00561b7c, 0x00561b94, 0x00561c48}},
        {0x0046fba0, reinterpret_cast<void*>(&recoil::Input_Keyboard_ScancodeToAscii), 0, "Input_Keyboard_ScancodeToAscii", {0x00561848, 0x00561c48}, {0x00561850, 0x00561854, 0x00561858, 0x0056185c, 0x00561860, 0x00561864, 0x00561868, 0x0056186c, 0x00561870, 0x00561874, 0x00561878, 0x0056187c, 0x00561880, 0x00561884, 0x00561888, 0x0056188c, 0x00561890, 0x00561894, 0x00561898, 0x0056189c, 0x005618a0, 0x005618a4, 0x005618a8, 0x005618ac, 0x005618b0, 0x005618b4, 0x005618b8, 0x005618c0, 0x005618c4, 0x005618c8, 0x005618cc, 0x005618d0, 0x005618d4, 0x005618d8, 0x005618dc, 0x005618e0, 0x005618e4, 0x005618e8, 0x005618ec, 0x005618f4, 0x005618f8, 0x005618fc, 0x00561900, 0x00561904, 0x00561908, 0x0056190c, 0x00561910, 0x00561914, 0x00561918, 0x0056191c, 0x00561924, 0x0056192c, 0x00561964, 0x00561968, 0x0056196c, 0x00561970, 0x00561974, 0x00561978, 0x0056197c, 0x00561980, 0x00561984, 0x00561988, 0x0056198c, 0x00561990, 0x00561994, 0x00561a7c, 0x00561a88, 0x00561a8c, 0x00561a90, 0x00561a94, 0x00561ab8, 0x00561b14, 0x00561b1c, 0x00561b74, 0x00561b7c, 0x00561b94}},
        {0x00470020, reinterpret_cast<void*>(&recoil::Input_Mouse_SetCursorToCenter), 0, "Input_Mouse_SetCursorToCenter", {0x00561c80, 0x00561c84, 0x00561cb4}, {}},
        {0x00470060, reinterpret_cast<void*>(&recoil::Input_Mouse_UpdateFromClientRect), 0, "Input_Mouse_UpdateFromClientRect", {0x00561c78, 0x00561c7c, 0x00561cb4}, {0x00561c50, 0x00561c68, 0x00561c6c, 0x00561c70}},
        {0x004700a0, reinterpret_cast<void*>(&recoil::Input_Mouse_SetNormalizedPos), 2, "Input_Mouse_SetNormalizedPos", {0x00561c50, 0x00561c70, 0x00561c80, 0x00561c84, 0x00561c88, 0x00561c8c}, {0x00561cb4}},
        {0x00470150, reinterpret_cast<void*>(&recoil::Input_Mouse_RecenterCursor), 0, "Input_Mouse_RecenterCursor", {0x00561c50, 0x00561c70, 0x00561c80, 0x00561c84, 0x00561c88, 0x00561c8c}, {0x00561cb4}},
        {0x00470180, reinterpret_cast<void*>(&recoil::Input_Mouse_Recenter), 0, "Input_Mouse_Recenter", {0x00561c70, 0x00561c80}, {0x00561c84, 0x00561cb4}},
    };
}
}  // namespace

TEST(native_fuzz_auto_input2_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
