// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "unattributed/znetwork.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept, dict; };
std::vector<Entry> entries()
{
    return {
        {0x00441250, reinterpret_cast<void*>(&recoil::Slot_ReturnZero_Retc_00441250), 3, "Slot_ReturnZero_Retc_00441250", {}, {}, {}},
        {0x00441260, reinterpret_cast<void*>(&recoil::ZoneSink_LogTimeMessage_302a_00441260), 3, "ZoneSink_LogTimeMessage_302a_00441260", {0x00538568}, {0x0053898c, 0x00538990}, {}},
        {0x004412c0, reinterpret_cast<void*>(&recoil::ZoneSink_LogMessage_302b_or_302c_004412c0), 4, "ZoneSink_LogMessage_302b_or_302c_004412c0", {0x00538568}, {0x0053898c, 0x00538990}, {}},
        {0x00441350, reinterpret_cast<void*>(&recoil::ZoneDlg_RefreshPlayerListEntry_00441350), 5, "ZoneDlg_RefreshPlayerListEntry_00441350", {0x004dd460, 0x004dd464, 0x00538568}, {}, {}},
        {0x00441480, reinterpret_cast<void*>(&recoil::ZoneSink_OnPlayerKicked_00441480), 5, "ZoneSink_OnPlayerKicked_00441480", {0x004f53c8, 0x004f547c, 0x00538568, 0x00538574, 0x00538578, 0x00538584}, {0x0053898c, 0x00538990}, {}},
        {0x00441600, reinterpret_cast<void*>(&recoil::CritSecHolder_Init), 0, "CritSecHolder_Init", {}, {}, {}},
        {0x00441620, reinterpret_cast<void*>(&recoil::ZoneSink_Release), 1, "ZoneSink_Release", {}, {0x004f53e4}, {}},
        {0x00441660, reinterpret_cast<void*>(&recoil::ZNet_Forward_0042db50_00441660), 3, "ZNet_Forward_0042db50_00441660", {}, {}, {}},
    };
}
}  // namespace

TEST(native_fuzz_auto_znetwork15_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        af::dictionary() = e.dict;  // empty for a plain arena test
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        af::dictionary().clear();
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
