// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "unattributed/app.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept, dict; };
std::vector<Entry> entries()
{
    return {
        {0x00441cb0, reinterpret_cast<void*>(&recoil::ComboDialog_RunModal), 0, "ComboDialog_RunModal", {0x00538568}, {}, {}},
        {0x00442180, reinterpret_cast<void*>(&recoil::RecoilApp_SetString4b8), 1, "RecoilApp_SetString4b8", {}, {}, {}},
        {0x004421d0, reinterpret_cast<void*>(&recoil::RecoilApp_SetString4bc), 1, "RecoilApp_SetString4bc", {}, {}, {}},
        {0x004422a0, reinterpret_cast<void*>(&recoil::StatusDialog_CreateComObject), 0, "StatusDialog_CreateComObject", {0x0053929c, 0x005392a0, 0x005392ac}, {0x004f53e4}, {}},
        {0x004422f0, reinterpret_cast<void*>(&recoil::StatusDialog_Refresh), 0, "StatusDialog_Refresh", {0x005392a0, 0x005392ac}, {}, {}},
        {0x00442320, reinterpret_cast<void*>(&recoil::WolPatch_DialogProc_00442320), 4, "WolPatch_DialogProc_00442320", {0x004dd468, 0x004dd484, 0x004f5240, 0x004f52c0, 0x00539198, 0x005392a0, 0x005392a4, 0x005392a8}, {0x004f53e4, 0x0053929c, 0x005392ac}, {}},
        {0x00442530, reinterpret_cast<void*>(&recoil::App_PromptForEachListItem), 0, "App_PromptForEachListItem", {0x004f3eec, 0x004f3ef8, 0x004f5240, 0x004f52c0}, {}, {}},
        {0x004425c0, reinterpret_cast<void*>(&recoil::RefCounted_Create), 0, "RefCounted_Create", {0x004f53e4}, {}, {}},
    };
}
}  // namespace

TEST(native_fuzz_auto_app19_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        af::dictionary() = e.dict;  // empty for a plain arena test
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        af::dictionary().clear();
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
