// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "GameZRecoil/zClass/Camera.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept; };
std::vector<Entry> entries()
{
    return {
        {0x0044a0f0, reinterpret_cast<void*>(&recoil::Camera_SetPosition), 3, "Camera_SetPosition", {0x004dd9bc, 0x004dd9d4, 0x004ddd44, 0x004ddd68}, {}},
        {0x0044a1a0, reinterpret_cast<void*>(&recoil::Camera_TranslatePosition), 3, "Camera_TranslatePosition", {0x004dd9bc, 0x004dd9d4, 0x004ddd44, 0x004ddd68}, {}},
        {0x0044a2f0, reinterpret_cast<void*>(&recoil::Camera_SetNearFar), 2, "Camera_SetNearFar", {0x004dd9bc, 0x004dd9d4, 0x004ddd44, 0x004ddd68}, {}},
        {0x0044a380, reinterpret_cast<void*>(&recoil::Camera_GetNearFar), 1, "Camera_GetNearFar", {0x004dd9bc, 0x004dd9d4, 0x004ddd44, 0x004ddd68}, {}},
        {0x0044a7f0, reinterpret_cast<void*>(&recoil::Camera_GetD0), 0, "Camera_GetD0", {0x004dd9bc, 0x004dd9d4, 0x004ddd44, 0x004ddd68}, {}},
        {0x0044a870, reinterpret_cast<void*>(&recoil::Camera_SetD0AndInverseSquare), 1, "Camera_SetD0AndInverseSquare", {0x004dd9bc, 0x004dd9d4, 0x004ddd44, 0x004ddd68}, {}},
        {0x0044a910, reinterpret_cast<void*>(&recoil::Camera_SetData08), 0, "Camera_SetData08", {0x004dd9bc, 0x004dd9d4, 0x004ddd44, 0x004ddd68}, {}},
        {0x0044a980, reinterpret_cast<void*>(&recoil::Camera_SetData0C), 0, "Camera_SetData0C", {0x004dd9bc, 0x004dd9d4, 0x004ddd44, 0x004ddd68}, {}},
    };
}
}  // namespace

TEST(native_fuzz_auto_camera4_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
