// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "unattributed/menus.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept; };
std::vector<Entry> entries()
{
    return {
        {0x004159b0, reinterpret_cast<void*>(&recoil::Screen_Enter_004edc48), 0, "Screen_Enter_004edc48", {0x004edc48, 0x004f3ca8}, {}},
        {0x004159e0, reinterpret_cast<void*>(&recoil::Screen_RunModalLoop), 0, "Screen_RunModalLoop", {}, {}},
        {0x00415a80, reinterpret_cast<void*>(&recoil::ScalarDeletingDtor_00415a80), 1, "ScalarDeletingDtor_00415a80", {}, {}},
        {0x0041ad20, reinterpret_cast<void*>(&recoil::MPNewGameScreen_Destroy), 0, "MPNewGameScreen_Destroy", {0x004da3d8}, {}},
        {0x0041ad80, reinterpret_cast<void*>(&recoil::Screen_Enter_004f32a0_WithArg), 0, "Screen_Enter_004f32a0_WithArg", {0x004f32a0, 0x004f32a8, 0x004f3ca8}, {}},
        {0x0041c500, reinterpret_cast<void*>(&recoil::NewGamePanel_OnStart), 0, "NewGamePanel_OnStart", {0x004f3ca8, 0x004f3e80}, {0x004f3a88}},
        {0x0041c6c0, reinterpret_cast<void*>(&recoil::Screen_Enter_004f32c8), 0, "Screen_Enter_004f32c8", {0x004f32c8, 0x004f3ca8}, {}},
        {0x00434ee0, reinterpret_cast<void*>(&recoil::SaveLoadDialog_FillList), 0, "SaveLoadDialog_FillList", {0x004da97c}, {0x004dd078}},
    };
}
}  // namespace

TEST(native_fuzz_auto_menus6_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
