// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "unattributed/input.h"
#include "GameZRecoil/zInput/zin_kbd.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept; };
std::vector<Entry> entries()
{
    return {
        {0x0040c190, reinterpret_cast<void*>(&recoil::Array_FillN), 3, "Array_FillN", {}, {}},
        {0x0042a480, reinterpret_cast<void*>(&recoil::CommandTable_Count), 0, "CommandTable_Count", {0x004f3ae4, 0x004f3ae8}, {}},
        {0x0042a4a0, reinterpret_cast<void*>(&recoil::CommandTable_GetFirstField), 0, "CommandTable_GetFirstField", {0x004f3ae4}, {}},
        {0x0042a4b0, reinterpret_cast<void*>(&recoil::CommandTable_EntrySubCount), 0, "CommandTable_EntrySubCount", {0x004f3ae4}, {}},
        {0x0042a4d0, reinterpret_cast<void*>(&recoil::CommandTable_EntrySubItem), 0, "CommandTable_EntrySubItem", {0x004f3ae4}, {}},
        {0x00470190, reinterpret_cast<void*>(&recoil::Input_GetMouseAvailable), 0, "Input_GetMouseAvailable", {0x00565e74}, {}},
        {0x004701a0, reinterpret_cast<void*>(&recoil::Input_Mouse_SetScreenSize), 0, "Input_Mouse_SetScreenSize", {0x00561c50, 0x00561c68, 0x00561c6c, 0x00561c70, 0x00561c78, 0x00561c7c}, {}},
        {0x004703a0, reinterpret_cast<void*>(&recoil::Input_GetMouseButtonEdgeTable), 0, "Input_GetMouseButtonEdgeTable", {0x00561c80}, {}},
        {0x00470670, reinterpret_cast<void*>(&recoil::Input_SetMouseMode_Exchange), 0, "Input_SetMouseMode_Exchange", {0x004e08fc}, {}},
        {0x00470a10, reinterpret_cast<void*>(&recoil::Binding_Pack), 2, "Binding_Pack", {}, {}},
        {0x004705f0, reinterpret_cast<void*>(&recoil::CopyStruct_00561c80), 0, "CopyStruct_00561c80", {0x004e0900, 0x00561c80}, {}},
    };
}
}  // namespace

TEST(native_fuzz_input1_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = true;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
