// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "unattributed/vehicle.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept; };
std::vector<Entry> entries()
{
    return {
        {0x00426330, reinterpret_cast<void*>(&recoil::Vehicle_ResetLookOffset), 0, "Vehicle_ResetLookOffset", {}, {}},
        {0x00428c20, reinterpret_cast<void*>(&recoil::Vehicle_SubVerticalSpeed), 0, "Vehicle_SubVerticalSpeed", {0x004f3ac4, 0x0056b428}, {}},
        {0x0042aa50, reinterpret_cast<void*>(&recoil::Vehicle_DrawDebugInfo), 1, "Vehicle_DrawDebugInfo", {0x004dc9a8, 0x004dc9bc, 0x004dc9d4, 0x004dc9f0, 0x004dca0c, 0x004dca18, 0x004dca40, 0x004dca48, 0x004dca4c, 0x004dca50, 0x004dca58, 0x004dca60, 0x004dca68, 0x004f3764}, {}},
        {0x0042c2e0, reinterpret_cast<void*>(&recoil::Vehicle_TrackVerticalVelocity), 0, "Vehicle_TrackVerticalVelocity", {0x004f3aac, 0x004f3ac4, 0x004f3c8c}, {0x004f3338, 0x004f3bf8}},
        {0x0042d320, reinterpret_cast<void*>(&recoil::Vehicle_ThirdContactSnap), 0, "Vehicle_ThirdContactSnap", {0x004f3ac4, 0x004f3bc8, 0x004f3bf8, 0x004f3bfc, 0x004f3c20}, {}},
        {0x0042da40, reinterpret_cast<void*>(&recoil::Vehicle_AlignToUpNormal), 0, "Vehicle_AlignToUpNormal", {}, {}},
        {0x00439990, reinterpret_cast<void*>(&recoil::Vehicle_ClearFireState), 0, "Vehicle_ClearFireState", {}, {}},
        {0x00439b70, reinterpret_cast<void*>(&recoil::Vehicle_StopAlarmSounds), 0, "Vehicle_StopAlarmSounds", {0x004f3748, 0x004f374c, 0x004f3750}, {}},
    };
}
}  // namespace

TEST(native_fuzz_auto_vehicle1_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
