// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "GameZRecoil/zDEClient/zdec_init.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept, dict; };
std::vector<Entry> entries()
{
    return {
        {0x004558f0, reinterpret_cast<void*>(&recoil::DEClient_Init), 0, "DEClient_Init", {0x004df3c4, 0x004df3c8, 0x004df3d4, 0x004df3f4, 0x004df400, 0x004df410, 0x004df420, 0x004df430, 0x004df438, 0x004df440, 0x004df448, 0x004df450, 0x004df458, 0x004df47c, 0x004df48c, 0x004df4b8, 0x00539ce0, 0x00539ce4, 0x00539ce8, 0x00539cec, 0x00539cf4, 0x00539cf8, 0x00539cfc, 0x00539d10, 0x00539d14, 0x00539d18, 0x00539d1c, 0x00539d24, 0x00539d28, 0x00539d34, 0x00539d38, 0x00539d44, 0x00539d48, 0x00539d4c, 0x00539de0}, {0x00539e18, 0x00539e1c}, {}},
        {0x00455e40, reinterpret_cast<void*>(&recoil::DEClient_Shutdown), 0, "DEClient_Shutdown", {0x00539ce4, 0x00539d10, 0x00539d1c}, {0x00539df4, 0x00539df8, 0x00539e00, 0x00539e04, 0x00539e10}, {}},
    };
}
}  // namespace

TEST(native_fuzz_auto_declient11_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        af::dictionary() = e.dict;  // empty for a plain arena test
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        af::dictionary().clear();
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
