// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "unattributed/scene_update.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept; };
std::vector<Entry> entries()
{
    return {
        {0x0044ea70, reinterpret_cast<void*>(&recoil::NodeList_RunAll), 0, "NodeList_RunAll", {0x004ddee0, 0x004ddef8}, {0x004dded8, 0x00539c00, 0x00539c54, 0x00539c60}},
        {0x0044eb00, reinterpret_cast<void*>(&recoil::NodeTree_UpdatePending), 0, "NodeTree_UpdatePending", {}, {}},
        {0x0044eb50, reinterpret_cast<void*>(&recoil::NodeTree_UpdateWithAncestors), 0, "NodeTree_UpdateWithAncestors", {0x004dded8}, {}},
        {0x0044eba0, reinterpret_cast<void*>(&recoil::NodeList_UpdateAllPending), 0, "NodeList_UpdateAllPending", {0x00539c00}, {0x004dded8}},
        {0x0044ebe0, reinterpret_cast<void*>(&recoil::NodeList_RunList11), 0, "NodeList_RunList11", {0x004dded8, 0x00539c54}, {}},
        {0x0044ec30, reinterpret_cast<void*>(&recoil::NodeList_RunList12), 0, "NodeList_RunList12", {0x004dded8, 0x00539c60}, {}},
        {0x0044ec80, reinterpret_cast<void*>(&recoil::NodeList_RunClientLists), 0, "NodeList_RunClientLists", {}, {0x004dded8, 0x00539c00, 0x00539c54, 0x00539c60}},
    };
}
}  // namespace

TEST(native_fuzz_auto_scene_update1_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
