// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "Battlesport/hud.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept; };
std::vector<Entry> entries()
{
    return {
        {0x00411760, reinterpret_cast<void*>(&recoil::Hud_SetRadarVisible), 0, "Hud_SetRadarVisible", {0x004e66f8, 0x004e66fc, 0x004e6734, 0x004e6740, 0x004e6758, 0x004e683c, 0x004e6840}, {}},
        {0x004117f0, reinterpret_cast<void*>(&recoil::Hud_RadarOpenAnimate), 0, "Hud_RadarOpenAnimate", {0x004e6734, 0x004e6740, 0x004e6758, 0x004e6834, 0x004e683c, 0x004e6840, 0x0056b42c}, {}},
        {0x00411ac0, reinterpret_cast<void*>(&recoil::Hud_PopupTick), 0, "Hud_PopupTick", {0x004e6560, 0x004e6564, 0x004e6568, 0x004e656c, 0x004e6570, 0x004e6578, 0x004e657c, 0x004e65b8, 0x004e6638, 0x004e6674, 0x004e66f4, 0x004e6844, 0x004e6848, 0x004e6888, 0x004e6894, 0x004e68a0, 0x004e6980, 0x004e6ab0, 0x004e6bb0, 0x004ed718, 0x0056b42c, 0x0057da2c}, {0x004e62f0, 0x004e6730, 0x004e673c, 0x004e6748, 0x004e6754, 0x004e6984}},
        {0x00411f10, reinterpret_cast<void*>(&recoil::Hud_SetHealthBar), 1, "Hud_SetHealthBar", {0x004dacbc, 0x004e6dac}, {}},
        {0x004124b0, reinterpret_cast<void*>(&recoil::Hud_UpdateTargetHealthBar), 0, "Hud_UpdateTargetHealthBar", {0x004e5ed4, 0x004e6564, 0x004e6af0, 0x004e6c6c, 0x004e6ca4, 0x004e6cb0, 0x004e6cc8, 0x004e6da4}, {}},
        {0x00412650, reinterpret_cast<void*>(&recoil::HudPlayerSlot_SetTimerText), 1, "HudPlayerSlot_SetTimerText", {0x004dacbc, 0x004dae08, 0x004ea9e8, 0x004ead6c}, {}},
        {0x00412820, reinterpret_cast<void*>(&recoil::HudPlayerSlot_SetActiveTimer), 1, "HudPlayerSlot_SetActiveTimer", {0x004dacbc, 0x004dae08, 0x004ea9e0, 0x004ea9e4, 0x004ea9e8, 0x004ead6c, 0x004eae34, 0x004eaef0, 0x004eaf04, 0x004eaf08, 0x004eaf0c, 0x004eaf10, 0x004eaf14, 0x004eb1b8, 0x004eb1c4}, {}},
        {0x00412db0, reinterpret_cast<void*>(&recoil::Hud_ApplyViewportRect), 0, "Hud_ApplyViewportRect", {0x004f0db4}, {}},
    };
}
}  // namespace

TEST(native_fuzz_auto_hud1_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
