// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "unattributed/menus.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept, dict; };
std::vector<Entry> entries()
{
    return {
        {0x00407ec0, reinterpret_cast<void*>(&recoil::ControlFlags_SetBit3AndCamera), 0, "ControlFlags_SetBit3AndCamera", {0x004e5d3c}, {}, {}},
        {0x00408050, reinterpret_cast<void*>(&recoil::Settings_ApplyMuteSound), 0, "Settings_ApplyMuteSound", {0x004e5d40}, {}, {}},
        {0x004081a0, reinterpret_cast<void*>(&recoil::Settings_ApplyGfxFlags), 0, "Settings_ApplyGfxFlags", {0x004da8cc, 0x004e5d08, 0x004e5d0c, 0x004e5dcc}, {}, {}},
        {0x00408d20, reinterpret_cast<void*>(&recoil::StaticInitWrapper_00408d20), 0, "StaticInitWrapper_00408d20", {}, {0x004e5dd0}, {}},
        {0x00408d40, reinterpret_cast<void*>(&recoil::StaticInit_RegisterAtexit_00408d50), 0, "StaticInit_RegisterAtexit_00408d50", {}, {}, {}},
        {0x00408d50, reinterpret_cast<void*>(&recoil::AtexitStub_ControlsHost_Dtor_00408d50), 0, "AtexitStub_ControlsHost_Dtor_00408d50", {0x004e5dd0}, {}, {}},
        {0x00408d70, reinterpret_cast<void*>(&recoil::ControlsHost_ScalarDeletingDtor), 1, "ControlsHost_ScalarDeletingDtor", {}, {}, {}},
        {0x00408d90, reinterpret_cast<void*>(&recoil::ControlsHost_Dtor), 0, "ControlsHost_Dtor", {}, {}, {}},
    };
}
}  // namespace

TEST(native_fuzz_auto_menus20_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        af::dictionary() = e.dict;  // empty for a plain arena test
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        af::dictionary().clear();
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
