// Arena-fuzz native L1 for a ported batch (tests/arena_fuzz.h). Generated by tools/asm_port/gen_fuzz_test.py.
#include "test.h"
#include "arena_fuzz.h"
#include "platform/image/original_data.h"
#include "unattributed/vehicle.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>

namespace {
struct Entry { std::uint32_t va; void* port; int nstack; const char* name; std::vector<std::uint32_t> globals, kept, dict; };
std::vector<Entry> entries()
{
    return {
        {0x00405c90, reinterpret_cast<void*>(&recoil::Vehicle_SetCameraViewState), 0, "Vehicle_SetCameraViewState", {0x004e5cc4, 0x004f3650, 0x004f36a8, 0x004f36bc, 0x004f3ab0, 0x0057da28}, {0x004f36c0}, {}},
        {0x004266b0, reinterpret_cast<void*>(&recoil::Vehicle_DispatchMovementPhysics), 0, "Vehicle_DispatchMovementPhysics", {0x004f36b4, 0x004f3a88}, {0x004db5ec, 0x004dc3a4, 0x004dc988, 0x004dc98c, 0x004dc990, 0x004dc9a4, 0x004dca70, 0x004dca7c, 0x004e5cc4, 0x004f3140, 0x004f3338, 0x004f3650, 0x004f3698, 0x004f36a8, 0x004f36b8, 0x004f36bc, 0x004f36c0, 0x004f36c4, 0x004f36c8, 0x004f36cc, 0x004f36d0, 0x004f36d4, 0x004f3734, 0x004f373c, 0x004f3740, 0x004f3748, 0x004f374c, 0x004f3750, 0x004f3754, 0x004f3768, 0x004f376c, 0x004f3778, 0x004f3aac, 0x004f3ab0, 0x004f3ab8, 0x004f3abc, 0x004f3ac0, 0x004f3ac4, 0x004f3ac8, 0x004f3bbc, 0x004f3bc0, 0x004f3bc8, 0x004f3bd0, 0x004f3bf8, 0x004f3bfc, 0x004f3c00, 0x004f3c20, 0x004f3c24, 0x004f3c2c, 0x004f3c38, 0x004f3c44, 0x004f3c50, 0x004f3c5c, 0x004f3c68, 0x004f3c6c, 0x004f3c70, 0x004f3c8c, 0x0056b424, 0x0056b428, 0x0057da28, 0x00779a80, 0x00779a88}, {}},
        {0x00426770, reinterpret_cast<void*>(&recoil::Vehicle_UpdatePhysicsFrame), 0, "Vehicle_UpdatePhysicsFrame", {0x004f3a88, 0x004f3aac, 0x004f3ac4}, {0x004e5cc4, 0x004f3140, 0x004f3338, 0x004f3650, 0x004f3698, 0x004f36a8, 0x004f36b4, 0x004f36b8, 0x004f36bc, 0x004f36c0, 0x004f36c4, 0x004f36c8, 0x004f36cc, 0x004f36d0, 0x004f36d4, 0x004f3734, 0x004f373c, 0x004f3740, 0x004f3748, 0x004f374c, 0x004f3750, 0x004f3754, 0x004f3768, 0x004f376c, 0x004f3778, 0x004f3ab0, 0x004f3ab8, 0x004f3abc, 0x004f3ac0, 0x004f3ac8, 0x004f3bbc, 0x004f3bc0, 0x004f3bc8, 0x004f3bd0, 0x004f3bf8, 0x004f3bfc, 0x004f3c00, 0x004f3c20, 0x004f3c24, 0x004f3c2c, 0x004f3c38, 0x004f3c44, 0x004f3c50, 0x004f3c5c, 0x004f3c68, 0x004f3c6c, 0x004f3c70, 0x004f3c8c, 0x0056b424, 0x0056b428, 0x0057da28, 0x00779a80, 0x00779a88}, {}},
        {0x00427140, reinterpret_cast<void*>(&recoil::Vehicle_UpdateHoverModePhysics), 0, "Vehicle_UpdateHoverModePhysics", {0x004f3a88, 0x004f3ac4}, {0x004e5cc4, 0x004f3338, 0x004f3650, 0x004f36a8, 0x004f36b8, 0x004f36bc, 0x004f36c0, 0x004f3aac, 0x004f3ab0, 0x004f3abc, 0x0056b424, 0x0056b428, 0x0057da28}, {}},
        {0x00427440, reinterpret_cast<void*>(&recoil::Vehicle_HoverSuspension), 0, "Vehicle_HoverSuspension", {0x004f3338, 0x004f3ac4, 0x0056b424, 0x0056b428}, {0x004f36b8, 0x004f3a88, 0x004f3ab0, 0x0057da28}, {}},
        {0x004279f0, reinterpret_cast<void*>(&recoil::Vehicle_UpdateAmphibModePhysics), 0, "Vehicle_UpdateAmphibModePhysics", {0x004f3a88, 0x004f3aac, 0x004f3ac4}, {0x004dc988, 0x004dc98c, 0x004dc990, 0x004dc9a4, 0x004e5cc4, 0x004f3650, 0x004f36a8, 0x004f36b8, 0x004f36bc, 0x004f36c0, 0x004f36c4, 0x004f36c8, 0x004f36cc, 0x004f3768, 0x004f3778, 0x004f3ab0, 0x004f3abc, 0x004f3bbc, 0x004f3bc0, 0x0056b424, 0x0056b428, 0x0057da28}, {}},
        {0x00427ec0, reinterpret_cast<void*>(&recoil::Vehicle_AmphibGroundSnap), 0, "Vehicle_AmphibGroundSnap", {0x004dc988, 0x004dc98c, 0x004dc990, 0x004dc9a4, 0x004f3a88, 0x004f3aac, 0x0056b424, 0x0056b428}, {0x004f36b8, 0x004f36c4, 0x004f36c8, 0x004f36cc, 0x004f3768, 0x004f3778, 0x004f3ab0, 0x004f3ac4, 0x004f3bbc, 0x004f3bc0, 0x0057da28}, {}},
        {0x00428120, reinterpret_cast<void*>(&recoil::Vehicle_UpdateBasicModePhysics), 0, "Vehicle_UpdateBasicModePhysics", {0x004f3ac4}, {0x004f36b8, 0x004f3a88, 0x004f3aac, 0x004f3ab0, 0x004f3abc, 0x0057da28}, {}},
    };
}
}  // namespace

TEST(native_fuzz_auto_vehicle6_match_original)
{
    if (!rt::map_original()) { CHECK(false); return; }
    af::real_floats() = false;  // ordinary float values in half the scalar words
    int failed = 0;
    const char* only = std::getenv("RECOIL_ONLY");  // diagnostics: run one function by name
    int shard = 0, shards = 1;  // RECOIL_SHARD=i/n: this process runs entries i, i+n, ... (tools/run_tests.py)
    if (const char* s = std::getenv("RECOIL_SHARD")) std::sscanf(s, "%d/%d", &shard, &shards);
    int index = 0;
    for (const Entry& e : entries()) {
        if (index++ % shards != shard) continue;
        if (only && std::strcmp(only, e.name) != 0) continue;
        std::printf("  run  %s\n", e.name); std::fflush(stdout);  // names the function if a crash escapes
        std::vector<af::GlobalRange> gr;
        for (std::uint32_t g : e.globals) gr.push_back({g, recoil::ImageData_Address(g), 4});
        for (std::uint32_t g : e.kept) gr.push_back({g, recoil::ImageData_Address(g), 4, true});  // callee-only: pristine each call
        af::dictionary() = e.dict;  // empty for a plain arena test
        const af::Result r = af::run(e.va, e.port, e.nstack, 1000, e.va, gr);
        af::dictionary().clear();
        std::printf("  %-40s calls %5d abnormal %5d %s%s\n", e.name, r.calls, r.abnormal, r.bad ? "DIFF " : "ok", r.first.c_str());
        if (r.bad || r.calls - r.abnormal < 50) ++failed;  // at least 50 calls that ended normally (and compared data)
    }
    CHECK_EQ(failed, 0);
}
