// SUBSYSTEM: poly_shade
// Original file: GameZRecoil/zRender/zrndr_draw.c (ledger orig_file).
// Instruction-level ports generated by tools/asm_port/port_batch.py from the Ghidra listings.
#include "GameZRecoil/zRender/zrndr_draw.h"
#include "platform/image/original_data.h"
#include "unattributed/rasteriser.h"
#include "unattributed/ui_widgets.h"
#include "GameZRecoil/zImage/zimg_fonts.h"
#include "platform/iat_msvcrt.h"

namespace recoil {

// 0x00499a20 Queue_FlatPolygon_SW - ../../04_spec/systems/poly_shade.md
// Register/stack shape from the listing (ECX, EDX, 16 stack bytes).
__declspec(naked) int __fastcall Queue_FlatPolygon_SW(int, int, int, int, int, int)
{
    __asm {
        mov eax, dword ptr [esp + 0x10]
        push ebx
        push ebp
        push esi
        test eax, eax
        push edi
        mov esi, ecx
        jz L_499ae8
        mov ecx, dword ptr [g_Data_004da000 + 0xf1270]
        cmp ecx, 0x15e
        jl L_499a50
        push ecx
        push offset g_Data_004da000 + 0x81c0
        push 0x9c
        jmp L_499b25
    L_499a50:
        mov ebx, dword ptr [esp + 0x1c]
        lea eax, [ecx + ecx*0x2]
        shl eax, 0x5
        add eax, ecx
        inc ecx
        mov dword ptr [g_Data_004da000 + 0xf1270], ecx
        lea ecx, [ebx + ebx*0x2]
        lea eax, [eax + eax*0x2]
        shl ecx, 0x2
        lea eax, [eax*0x4 + g_Data_004da000 + 0xf1274]
        mov ebp, ecx
        shr ecx, 0x2
        lea edi, [eax + 0x4]
        mov dword ptr [eax], 0x0
        rep movsd
        fild dword ptr [esp + 0x18]
        mov ecx, ebp
        and ecx, 0x3
        rep movsb
        lea edi, [eax + 0x328]
        mov ecx, 0x9
        mov esi, edx
        rep movsd
        fstp dword ptr [eax + 0x34c]
        mov ecx, dword ptr [esp + 0x14]
        mov dword ptr [eax + 0x370], 0x0
        mov dword ptr [eax + 0x354], ebx
        mov dword ptr [eax + 0x350], ecx
        mov edx, dword ptr [g_Data_004da000 + 0xa3ac8]
        mov dword ptr [eax + 0x478], edx
        mov ecx, dword ptr [g_Data_004da000 + 0xa3ac0]
        mov dword ptr [eax + 0x480], ecx
        mov edx, dword ptr [g_Data_004da000 + 0xa3ac4]
        mov dword ptr [eax + 0x484], edx
        pop edi
        pop esi
        pop ebp
        pop ebx
        ret 0x10
    L_499ae8:
        mov ebx, dword ptr [esp + 0x18]
        cmp ebx, 0xff
        jl L_499b0c
        mov eax, dword ptr [esp + 0x14]
        mov ecx, dword ptr [esp + 0x1c]
        push eax
        push ecx
        mov ecx, esi
        call Raster_FillFlatPoly
        pop edi
        pop esi
        pop ebp
        pop ebx
        ret 0x10
    L_499b0c:
        mov edi, dword ptr [g_Data_004da000 + 0xa3e7c]
        cmp edi, 0x15e
        jl L_499b3e
        push edi
        push offset g_Data_004da000 + 0x8194
        push 0xb9
    L_499b25:
        push offset g_Data_004da000 + 0x8168
        push 0x400
        call Debug_ReportNoop
        add esp, 0x14
        pop edi
        pop esi
        pop ebp
        pop ebx
        ret 0x10
    L_499b3e:
        mov eax, dword ptr [esp + 0x1c]
        lea edi, [edi + edi*0x4]
        fld dword ptr [g_Data_004da000 + 0xa3ac0]
        lea ecx, [eax + eax*0x2]
        lea edi, [edi + edi*0x8]
        shl ecx, 0x2
        lea edi, [edi + edi*0x4]
        mov ebp, ecx
        shr ecx, 0x2
        lea edi, [edi*0x4 + g_Data_004da000 + 0xa3e88]
        rep movsd
        mov ecx, ebp
        and ecx, 0x3
        rep movsb
        mov ecx, dword ptr [g_Data_004da000 + 0xa3e7c]
        mov esi, edx
        lea ecx, [ecx + ecx*0x4]
        lea ecx, [ecx + ecx*0x8]
        lea ecx, [ecx + ecx*0x4]
        lea edi, [ecx*0x4 + g_Data_004da000 + 0xa41ac]
        mov ecx, 0x9
        rep movsd
        mov ecx, dword ptr [g_Data_004da000 + 0xa3e7c]
        pop edi
        pop esi
        pop ebp
        lea ecx, [ecx + ecx*0x4]
        lea ecx, [ecx + ecx*0x8]
        lea edx, [ecx + ecx*0x4]
        mov dword ptr [edx*0x4 + g_Data_004da000 + 0xa3e80], 0x0
        mov ecx, dword ptr [g_Data_004da000 + 0xa3e7c]
        lea ecx, [ecx + ecx*0x4]
        lea ecx, [ecx + ecx*0x8]
        lea ecx, [ecx + ecx*0x4]
        mov dword ptr [ecx*0x4 + g_Data_004da000 + 0xa3e84], eax
        mov eax, dword ptr [g_Data_004da000 + 0xa3e7c]
        lea eax, [eax + eax*0x4]
        lea eax, [eax + eax*0x8]
        lea edx, [eax + eax*0x4]
        mov eax, dword ptr [esp + 0x8]
        mov dword ptr [edx*0x4 + g_Data_004da000 + 0xa41fc], eax
        mov eax, dword ptr [g_Data_004da000 + 0xa3e7c]
        lea eax, [eax + eax*0x4]
        lea eax, [eax + eax*0x8]
        lea ecx, [eax + eax*0x4]
        mov dword ptr [ecx*0x4 + g_Data_004da000 + 0xa41f8], ebx
        mov eax, dword ptr [g_Data_004da000 + 0xa3e7c]
        pop ebx
        lea eax, [eax + eax*0x4]
        lea eax, [eax + eax*0x8]
        lea edx, [eax + eax*0x4]
        mov eax, dword ptr [g_Data_004da000 + 0xa3ac8]
        mov dword ptr [edx*0x4 + g_Data_004da000 + 0xa41e8], eax
        mov eax, dword ptr [g_Data_004da000 + 0xa3e7c]
        lea eax, [eax + eax*0x4]
        lea eax, [eax + eax*0x8]
        lea ecx, [eax + eax*0x4]
        fstp dword ptr [ecx*0x4 + g_Data_004da000 + 0xa41f0]
        mov eax, dword ptr [g_Data_004da000 + 0xa3e7c]
        fld dword ptr [g_Data_004da000 + 0xa3ac4]
        lea eax, [eax + eax*0x4]
        lea eax, [eax + eax*0x8]
        lea edx, [eax + eax*0x4]
        fstp dword ptr [edx*0x4 + g_Data_004da000 + 0xa41f4]
        inc dword ptr [g_Data_004da000 + 0xa3e7c]
        ret 0x10
    }
}

// 0x00499ec0 Queue_TexturedPolygon_SW - ../../04_spec/systems/poly_shade.md
// Register/stack shape from the listing (ECX, EDX, 32 stack bytes).
__declspec(naked) int __fastcall Queue_TexturedPolygon_SW(int, int, int, int, int, int, int, int, int, int)
{
    __asm {
        sub esp, 0x40c
        push ebx
        mov ebx, dword ptr [esp + 0x428]
        push ebp
        push esi
        push edi
        xor edi, edi
        cmp ebx, edi
        mov dword ptr [esp + 0x18], edx
        mov esi, ecx
        mov dword ptr [esp + 0x10], edi
        jz L_499ee9
        mov eax, dword ptr [ebx]
        mov dword ptr [esp + 0x14], eax
        jmp L_499eed
    L_499ee9:
        mov dword ptr [esp + 0x14], edi
    L_499eed:
        mov ebp, dword ptr [g_Data_004da000 + 0x81fc]
        cmp ebp, -0x1
        jnz L_499f6e
        cmp dword ptr [esp + 0x438], edi
        jnz L_499f6e
        mov ecx, dword ptr [ebx]
        cmp word ptr [ecx + 0xe], DI
        jle L_499f6e
        mov ecx, offset g_Data_004da000 + 0x157fb0
        call Tex_CallWithDefaultRecord
        mov ebp, eax
        test ebp, ebp
        jl L_499f6e
        mov edx, dword ptr [esp + 0x428]
        fld dword ptr [edx]
        fmul dword ptr [g_RData_004cc000 + 0x6e40]
        call dword ptr [g_Iat__ftol_004cc5ac]
        cmp eax, 0x1f
        jle L_499f39
        mov eax, 0x1f
        jmp L_499f3f
    L_499f39:
        test eax, eax
        jge L_499f3f
        xor eax, eax
    L_499f3f:
        mov ecx, dword ptr [esp + 0x14]
        shl ebp, 0x5
        mov DL, byte ptr [ecx + 0x9]
        add ebp, eax
        xor eax, eax
        test DL, DL
        setz AL
        test AL, 0x2
        jz L_499f6e
        mov eax, dword ptr [esp + 0x43c]
        test eax, eax
        jz L_49a27b
        mov edi, 0x1
        mov dword ptr [esp + 0x10], edi
    L_499f6e:
        mov eax, dword ptr [esp + 0x43c]
        test eax, eax
        jz L_49a0a8
        mov ecx, dword ptr [g_Data_004da000 + 0xf1270]
        cmp ecx, 0x15e
        jl L_499f9b
        push ecx
        push offset g_Data_004da000 + 0x81c0
        push 0x19e
        jmp L_49a1b5
    L_499f9b:
        lea eax, [ecx + ecx*0x2]
        mov edx, dword ptr [esp + 0x430]
        shl eax, 0x5
        add eax, ecx
        inc ecx
        neg edi
        lea eax, [eax + eax*0x2]
        mov dword ptr [g_Data_004da000 + 0xf1270], ecx
        sbb edi, edi
        lea eax, [eax*0x4 + g_Data_004da000 + 0xf1274]
        add edi, 0x2
        fild dword ptr [esp + 0x42c]
        mov dword ptr [eax], edi
        mov dword ptr [eax + 0x354], edx
        mov dword ptr [eax + 0x370], ebx
        mov ecx, dword ptr [g_Data_004da000 + 0xa3ac0]
        mov dword ptr [eax + 0x480], ecx
        mov ecx, dword ptr [g_Data_004da000 + 0xa3ac4]
        mov dword ptr [eax + 0x484], ecx
        mov ecx, dword ptr [g_Data_004da000 + 0xa3ac8]
        mov dword ptr [eax + 0x478], ecx
        lea ecx, [edx + edx*0x2]
        fstp dword ptr [eax + 0x34c]
        shl ecx, 0x2
        mov ebx, ecx
        lea edi, [eax + 0x4]
        shr ecx, 0x2
        rep movsd
        mov ecx, ebx
        and ecx, 0x3
        rep movsb
        mov esi, dword ptr [esp + 0x420]
        lea edi, [eax + 0x328]
        mov ecx, 0x9
        rep movsd
        mov esi, dword ptr [esp + 0x424]
        lea edi, [eax + 0x358]
        mov ecx, 0x6
        rep movsd
        mov ecx, dword ptr [esp + 0x10]
        test ecx, ecx
        jnz L_49a059
        mov esi, dword ptr [esp + 0x428]
        mov ecx, edx
        lea edi, [eax + 0x374]
        rep movsd
    L_49a059:
        mov esi, dword ptr [esp + 0x18]
        test esi, esi
        jz L_49a08b
        lea edi, [eax + 0x304]
        mov ecx, 0x9
        rep movsd
        mov dword ptr [eax + 0x47c], 0x1
        mov dword ptr [eax + 0x488], ebp
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0x40c
        ret 0x20
    L_49a08b:
        mov dword ptr [eax + 0x47c], 0x0
        mov dword ptr [eax + 0x488], ebp
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0x40c
        ret 0x20
    L_49a0a8:
        mov edi, dword ptr [esp + 0x428]
        mov edx, esi
        mov eax, dword ptr [edx]
        mov dword ptr [esp + 0x11c], eax
        mov eax, dword ptr [edi]
        mov ecx, dword ptr [edx + 0x4]
        mov dword ptr [esp + 0x1c], eax
        mov dword ptr [esp + 0x120], ecx
        mov ecx, dword ptr [esp + 0x14]
        mov edx, dword ptr [edx + 0x8]
        mov dword ptr [esp + 0x124], edx
        mov AL, byte ptr [ecx + 0x9]
        test AL, 0x2
        jnz L_49a19e
        mov edx, dword ptr [esp + 0x430]
        xor ebx, ebx
        lea eax, [edx - 0x2]
        test eax, eax
        mov dword ptr [esp + 0x10], eax
        jle L_49a26e
        add edi, 0x8
        add esi, 0x18
    L_49a101:
        lea eax, [esi - 0xc]
        push ebp
        push ebx
        push 0x3
        mov ecx, dword ptr [eax]
        mov dword ptr [esp + 0x134], ecx
        mov ecx, esi
        mov edx, dword ptr [eax + 0x4]
        mov dword ptr [esp + 0x138], edx
        mov edx, dword ptr [ecx]
        mov eax, dword ptr [eax + 0x8]
        mov dword ptr [esp + 0x140], edx
        mov edx, dword ptr [edi - 0x4]
        mov dword ptr [esp + 0x13c], eax
        mov eax, dword ptr [ecx + 0x4]
        mov dword ptr [esp + 0x2c], edx
        mov edx, dword ptr [esp + 0x430]
        mov dword ptr [esp + 0x144], eax
        mov ecx, dword ptr [ecx + 0x8]
        mov eax, dword ptr [edi]
        mov dword ptr [esp + 0x148], ecx
        lea ecx, [esp + 0x28]
        mov dword ptr [esp + 0x30], eax
        mov eax, dword ptr [esp + 0x42c]
        push ecx
        mov ecx, dword ptr [esp + 0x28]
        push edx
        push eax
        push ecx
        mov ecx, dword ptr [esp + 0x450]
        lea edx, [esp + 0x138]
        call Raster_FillShadedTexturedFan
        inc ebx
        add esi, 0xc
        mov eax, dword ptr [esp + 0x10]
        add edi, 0x4
        cmp ebx, eax
        jl L_49a101
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0x40c
        ret 0x20
    L_49a19e:
        mov eax, dword ptr [g_Data_004da000 + 0xa3e7c]
        cmp eax, 0x15e
        jl L_49a1d4
        push eax
        push offset g_Data_004da000 + 0x8194
        push 0x1e1
    L_49a1b5:
        push offset g_Data_004da000 + 0x8168
        push 0x400
        call Debug_ReportNoop
        add esp, 0x14
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0x40c
        ret 0x20
    L_49a1d4:
        lea eax, [eax + eax*0x4]
        mov ecx, dword ptr [esp + 0x430]
        lea eax, [eax + eax*0x8]
        lea edx, [eax + eax*0x4]
        lea eax, [edx*0x4 + g_Data_004da000 + 0xa3e80]
        mov dword ptr [eax + 0x4], ecx
        mov dword ptr [eax], ebx
        mov edx, dword ptr [g_Data_004da000 + 0xa3ac0]
        lea ecx, [ecx + ecx*0x2]
        mov dword ptr [eax + 0x370], edx
        mov edx, dword ptr [g_Data_004da000 + 0xa3ac4]
        mov dword ptr [eax + 0x374], edx
        mov edx, dword ptr [g_Data_004da000 + 0xa3ac8]
        shl ecx, 0x2
        mov dword ptr [eax + 0x368], edx
        mov edx, ecx
        lea edi, [eax + 0x8]
        mov dword ptr [eax + 0x378], 0xff
        shr ecx, 0x2
        rep movsd
        mov ecx, edx
        and ecx, 0x3
        rep movsb
        mov esi, dword ptr [esp + 0x420]
        lea edi, [eax + 0x32c]
        mov ecx, 0x9
        rep movsd
        mov esi, dword ptr [esp + 0x424]
        lea edi, [eax + 0x350]
        mov ecx, 0x6
        rep movsd
        mov dword ptr [eax + 0x380], ebp
        mov eax, dword ptr [g_Data_004da000 + 0xa3e7c]
        inc eax
        mov dword ptr [g_Data_004da000 + 0xa3e7c], eax
    L_49a26e:
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0x40c
        ret 0x20
    L_49a27b:
        mov edx, dword ptr [esp + 0x430]
        mov eax, dword ptr [esp + 0x424]
        mov ecx, dword ptr [esp + 0x420]
        push ebp
        push edx
        mov edx, dword ptr [esp + 0x20]
        push eax
        push ecx
        push edx
        mov edx, esi
        mov ecx, ebx
        call Raster_FillTexturedPolySubdiv
        pop edi
        pop esi
        pop ebp
        pop ebx
        add esp, 0x40c
        ret 0x20
    }
}

// 0x00499c40 Queue_TexturedPolygonSubdiv_SW - ../../04_spec/systems/poly_shade.md
// Register/stack shape from the listing (ECX, EDX, 24 stack bytes).
__declspec(naked) int __fastcall Queue_TexturedPolygonSubdiv_SW(int, int, int, int, int, int, int, int)
{
    __asm {
        mov eax, dword ptr [esp + 0x18]
        push ebx
        push ebp
        mov ebp, edx
        xor edx, edx
        push esi
        cmp eax, edx
        push edi
        mov esi, ecx
        jz L_499d57
        mov ecx, dword ptr [g_Data_004da000 + 0xf1270]
        cmp ecx, 0x15e
        jl L_499c74
        push ecx
        push offset g_Data_004da000 + 0x81c0
        push 0xfa
        jmp L_499db4
    L_499c74:
        lea eax, [ecx + ecx*0x2]
        mov edi, dword ptr [esp + 0x20]
        shl eax, 0x5
        add eax, ecx
        inc ecx
        mov dword ptr [g_Data_004da000 + 0xf1270], ecx
        mov ecx, dword ptr [esp + 0x1c]
        lea eax, [eax + eax*0x2]
        lea eax, [eax*0x4 + g_Data_004da000 + 0xf1274]
        mov dword ptr [eax], 0x1
        mov dword ptr [eax + 0x354], ecx
        mov dword ptr [eax + 0x370], edi
        mov edi, dword ptr [g_Data_004da000 + 0xa3ac0]
        mov dword ptr [eax + 0x480], edi
        mov edi, dword ptr [g_Data_004da000 + 0xa3ac4]
        mov dword ptr [eax + 0x484], edi
        mov edi, dword ptr [g_Data_004da000 + 0xa3ac8]
        lea ecx, [ecx + ecx*0x2]
        mov dword ptr [eax + 0x478], edi
        mov edi, dword ptr [esp + 0x24]
        shl ecx, 0x2
        mov ebx, ecx
        mov dword ptr [eax + 0x34c], edi
        lea edi, [eax + 0x4]
        shr ecx, 0x2
        rep movsd
        mov ecx, ebx
        and ecx, 0x3
        cmp ebp, edx
        rep movsb
        mov esi, dword ptr [esp + 0x14]
        lea edi, [eax + 0x328]
        mov ecx, 0x9
        rep movsd
        mov esi, dword ptr [esp + 0x18]
        lea edi, [eax + 0x358]
        mov ecx, 0x6
        rep movsd
        jz L_499d3e
        lea edi, [eax + 0x304]
        mov ecx, 0x9
        mov esi, ebp
        rep movsd
        mov dword ptr [eax + 0x47c], 0x1
        mov ecx, dword ptr [g_Data_004da000 + 0x81fc]
        mov dword ptr [eax + 0x488], ecx
        pop edi
        pop esi
        pop ebp
        pop ebx
        ret 0x18
    L_499d3e:
        mov dword ptr [eax + 0x47c], edx
        mov ecx, dword ptr [g_Data_004da000 + 0x81fc]
        mov dword ptr [eax + 0x488], ecx
        pop edi
        pop esi
        pop ebp
        pop ebx
        ret 0x18
    L_499d57:
        mov ecx, dword ptr [esp + 0x20]
        cmp ecx, edx
        jz L_499d61
        mov edx, dword ptr [ecx]
    L_499d61:
        test byte ptr [edx + 0x9], 0x2
        jnz L_499d9d
        fld dword ptr [esp + 0x24]
        fcomp dword ptr [g_RData_004cc000 + 0x6e48]
        fnstsw AX
        test AH, 0x1
        jnz L_499d9d
        mov edx, dword ptr [g_Data_004da000 + 0x81fc]
        mov eax, dword ptr [esp + 0x1c]
        push edx
        mov edx, dword ptr [esp + 0x1c]
        push eax
        mov eax, dword ptr [esp + 0x1c]
        push edx
        push eax
        push ebp
        mov edx, esi
        call Raster_FillTexturedPolySubdiv
        pop edi
        pop esi
        pop ebp
        pop ebx
        ret 0x18
    L_499d9d:
        mov eax, dword ptr [g_Data_004da000 + 0xa3e7c]
        cmp eax, 0x15e
        jl L_499dcd
        push eax
        push offset g_Data_004da000 + 0x8194
        push 0x126
    L_499db4:
        push offset g_Data_004da000 + 0x8168
        push 0x400
        call Debug_ReportNoop
        add esp, 0x14
        pop edi
        pop esi
        pop ebp
        pop ebx
        ret 0x18
    L_499dcd:
        lea eax, [eax + eax*0x4]
        mov edi, dword ptr [esp + 0x1c]
        lea eax, [eax + eax*0x8]
        lea eax, [eax + eax*0x4]
        lea ebx, [eax*0x4 + g_Data_004da000 + 0xa3e80]
        mov dword ptr [ebx + 0x4], edi
        mov dword ptr [ebx], ecx
        mov ecx, dword ptr [g_Data_004da000 + 0xa3ac0]
        mov dword ptr [ebx + 0x370], ecx
        mov eax, dword ptr [g_Data_004da000 + 0xa3ac4]
        mov dword ptr [ebx + 0x374], eax
        mov ecx, dword ptr [g_Data_004da000 + 0xa3ac8]
        mov dword ptr [ebx + 0x368], ecx
        mov AL, byte ptr [edx + 0x9]
        test AL, 0x2
        jz L_499e1c
        mov edx, dword ptr [esp + 0x24]
        mov dword ptr [ebx + 0x378], edx
        jmp L_499e31
    L_499e1c:
        fld dword ptr [esp + 0x24]
        fmul dword ptr [g_RData_004cc000 + 0x6e4c]
        call dword ptr [g_Iat__ftol_004cc5ac]
        mov dword ptr [ebx + 0x378], eax
    L_499e31:
        lea ecx, [edi + edi*0x2]
        lea edi, [ebx + 0x8]
        shl ecx, 0x2
        mov eax, ecx
        shr ecx, 0x2
        rep movsd
        mov ecx, eax
        and ecx, 0x3
        rep movsb
        mov esi, dword ptr [esp + 0x14]
        lea edi, [ebx + 0x32c]
        mov ecx, 0x9
        rep movsd
        mov esi, dword ptr [esp + 0x18]
        lea edi, [ebx + 0x350]
        mov ecx, 0x6
        test ebp, ebp
        rep movsd
        jz L_499e89
        lea edi, [ebx + 0x308]
        mov ecx, 0x9
        mov esi, ebp
        rep movsd
        mov dword ptr [ebx + 0x36c], 0x1
        jmp L_499e93
    L_499e89:
        mov dword ptr [ebx + 0x36c], 0x0
    L_499e93:
        mov ecx, dword ptr [g_Data_004da000 + 0x81fc]
        pop edi
        mov dword ptr [ebx + 0x380], ecx
        mov eax, dword ptr [g_Data_004da000 + 0xa3e7c]
        inc eax
        pop esi
        pop ebp
        mov dword ptr [g_Data_004da000 + 0xa3e7c], eax
        pop ebx
        ret 0x18
    }
}

}  // namespace recoil
