// SUBSYSTEM: platform
// Import slots for every AVIFIL32.dll import of Recoil.exe (import table), bound to the system avifil32.dll.
// Generated by tools/asm_port/gen_iat_slots.py - do not edit by hand. PLATFORM.
#pragma once

namespace recoil {

extern void* g_Iat_AVIStreamRelease_004cc01c;  // AVIStreamRelease
extern void* g_Iat_AVIFileInit_004cc020;  // AVIFileInit
extern void* g_Iat_AVIStreamInfoA_004cc024;  // AVIStreamInfoA
extern void* g_Iat_AVIStreamLength_004cc028;  // AVIStreamLength
extern void* g_Iat_AVIStreamReadFormat_004cc02c;  // AVIStreamReadFormat
extern void* g_Iat_AVIStreamOpenFromFileA_004cc030;  // AVIStreamOpenFromFileA
extern void* g_Iat_AVIStreamRead_004cc034;  // AVIStreamRead
extern void* g_Iat_AVIFileExit_004cc038;  // AVIFileExit

}  // namespace recoil
