// SUBSYSTEM: platform
// Import slots for every MSVFW32.dll import of Recoil.exe (import table), bound to the system msvfw32.dll.
// Generated by tools/asm_port/gen_iat_slots.py - do not edit by hand. PLATFORM.
#pragma once

namespace recoil {

extern void* g_Iat_ICDecompress_004cc5ec;  // ICDecompress
extern void* g_Iat_ICLocate_004cc5f0;  // ICLocate
extern void* g_Iat_ICSendMessage_004cc5f4;  // ICSendMessage
extern void* g_Iat_ICClose_004cc5f8;  // ICClose

}  // namespace recoil
