// SUBSYSTEM: platform
// Generated by tools/asm_port/gen_iat_slots.py - do not edit by hand. PLATFORM.
#include "platform/iat_shell32.h"

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

namespace recoil {
namespace {
void* crt(const char* name) { return reinterpret_cast<void*>(GetProcAddress(LoadLibraryA("shell32.dll"), name)); }
}  // namespace

void* g_Iat_FindExecutableA_004cc600 = crt("FindExecutableA");
void* g_Iat_ShellExecuteA_004cc604 = crt("ShellExecuteA");

}  // namespace recoil
