// SUBSYSTEM: platform
// Import slots for every DSOUND.dll import of Recoil.exe (import table), bound to the system dsound.dll.
// Generated by tools/asm_port/gen_iat_slots.py - do not edit by hand. PLATFORM.
#pragma once

namespace recoil {

extern void* g_Iat_DSOUND_1_004cc05c;  // ordinal 1

}  // namespace recoil
