// SUBSYSTEM: platform
// Import slots for every ole32.dll import of Recoil.exe (import table), bound to the system ole32.dll.
// Generated by tools/asm_port/gen_iat_slots.py - do not edit by hand. PLATFORM.
#pragma once

namespace recoil {

extern void* g_Iat_CoCreateInstance_004cc708;  // CoCreateInstance
extern void* g_Iat_CoInitialize_004cc70c;  // CoInitialize
extern void* g_Iat_CoUninitialize_004cc710;  // CoUninitialize

}  // namespace recoil
