"""gen_spec_ref.py - write 04_spec/reference/<subsystem>.md from the ledger.

One entry per subsystem member: address, name, status, verification, the ledger's
byte-read description, and direct callers/callees by name. The output is GENERATED:
it restates the ledger, adds no new facts, and is overwritten on every run. The
hand-written narrative specs live in 04_spec/systems/ and are never touched here.

usage: python 03_re/scripts/gen_spec_ref.py [subsystem ...]   (default: all)
"""
import collections
import csv
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
LEDGER = os.path.join(ROOT, "03_re", "ledger", "functions.csv")
SUBSYS = os.path.join(ROOT, "03_re", "ledger", "subsystems.csv")
REGISTRY = os.path.join(ROOT, "03_re", "ledger", "subsystem_registry.csv")
CALLGRAPH = os.path.join(ROOT, "03_re", "ledger", "_callgraph.tsv")
OUT = os.path.join(ROOT, "04_spec", "reference")


def norm(a):
    return a.lower().replace("0x", "")


def main():
    fn = {norm(r["address"]): r for r in csv.DictReader(open(LEDGER, encoding="utf-8"))}
    reg = {r["subsystem"]: r for r in csv.DictReader(open(REGISTRY, encoding="utf-8"))}
    mem = collections.defaultdict(list)
    owner = collections.defaultdict(list)
    for m in csv.DictReader(open(SUBSYS, encoding="utf-8")):
        a = norm(m["address"])
        if a in fn and fn[a]["class"] == "ENGINE" and m["subsystem"] in reg:
            if a not in mem[m["subsystem"]]:
                mem[m["subsystem"]].append(a)
                owner[a].append(m["subsystem"])
    cal, cee = collections.defaultdict(set), collections.defaultdict(set)
    for line in open(CALLGRAPH, encoding="utf-8").read().splitlines()[1:]:
        a, _, b = line.partition("\t")
        a, b = a.strip().lower(), b.strip().lower()
        cee[a].add(b)
        cal[b].add(a)

    def label(a):
        r = fn.get(a)
        if not r:
            return "0x" + a
        n = r["ghidra_name"]
        tag = "" if a in mem_of else " [%s]" % "/".join(owner.get(a, ["lib"]))
        return "`%s`%s" % (n if not n.startswith("FUN_") else "0x" + a, tag)

    os.makedirs(OUT, exist_ok=True)
    want = sys.argv[1:] or sorted(reg)
    for s in want:
        mem_of = set(mem.get(s, ()))
        out = ["# %s - function reference (GENERATED)" % s, "",
               "> Generated by `03_re/scripts/gen_spec_ref.py` from `03_re/ledger/functions.csv`.",
               "> It restates the ledger's byte-read notes and adds nothing; do not edit by hand.",
               "> This is **not** a narrative spec. Narrative specs live in `04_spec/systems/`.",
               "> Callers/callees are direct call edges only; `[other]` marks another subsystem.", "",
               "Registry: membership **%s** - %s" % (reg[s]["membership"],
                                                    reg[s].get("description", "")), "",
               "Members: %d" % len(mem_of), ""]
        for a in sorted(mem_of):
            r = fn[a]
            ref = r["spec_ref"].strip()
            desc = ref if ref and not ref.endswith(".md") else ""
            method = r["notes"].strip()
            if not desc:
                desc, method = method, ""
            out.append("## `0x%s` %s" % (a, r["ghidra_name"]))
            meta = "status %s" % r["status"]
            if r["verification"].strip():
                meta += " - verification %s" % r["verification"].strip()
            if ref.endswith(".md"):
                meta += " - see `%s`" % ref
            out.append("*%s*" % meta)
            out.append("")
            out.append(desc or "_(no description in ledger)_")
            if method and method != desc:
                out.append("")
                out.append("Method: " + method)
            cs = sorted(cal.get(a, ()))
            ce = sorted(cee.get(a, ()))
            if cs:
                out.append("")
                out.append("Callers (%d): %s%s" % (len(cs), ", ".join(label(x) for x in cs[:10]),
                                                   " ..." if len(cs) > 10 else ""))
            if ce:
                out.append("")
                out.append("Callees (%d): %s%s" % (len(ce), ", ".join(label(x) for x in ce[:12]),
                                                   " ..." if len(ce) > 12 else ""))
            out.append("")
        open(os.path.join(OUT, s + ".md"), "w", encoding="utf-8").write("\n".join(out))
        print("%-14s %4d members" % (s, len(mem_of)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
